### PR TITLE
fix: ironwood

### PR DESCRIPTION
**Pull request by qasimgulzar**
1. Removed broken repositories 
2. Updated boto version

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @qasimgulzar! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @qasimgulzar! Just checking in to see if you plan on pursuing this pull request? If so, you'll need to submit a CLA form as mentioned above.

**Comment by mphilbrick211** [comment]
Hi @qasimgulzar - I am closing this pull request for now. If you'd like to pursue in the future, we can reopen. Thanks!

**Comment by qasimgulzar** [comment]
@mphilbrick211 I have submitted CLA could you please reopen this PR?

**Comment by mphilbrick211** [comment]
Hi @qasimgulzar! Thanks for submitting your CLA form. If you re-run the checks the CLA check should turn green.

Also, when you get a moment, could you please add a description of your change(s) to the top of the pull request? Thanks!

**Comment by qasimgulzar** [comment]
@mphilbrick211 could you please help reviewing this PR?

**Comment by mphilbrick211** [comment]
> @mphilbrick211 could you please help reviewing this PR?

Hi @qasimgulzar! Yes, I will look into this for you.

**Comment by pomegranited** [comment]
Hi @qasimgulzar @mphilbrick211 I didn't think we were maintaining Ironwood anymore, since we're at Quince now?

**Comment by pomegranited** [comment]
Closing this PR as Ironwood is unmaintained.

**Comment by openedx-webhooks** [comment]
@qasimgulzar Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/configuration&entry.867055334=https://github.com/openedx/configuration/pull/6872&entry.1484655318=https://github.com/qasimgulzar&entry.752974735=2023-01-29+06:06&entry.1917517419=2024-04-05+00:47&entry.2133058324=No) so we can improve your experience in the future.

**Comment by openedx-webhooks** [comment]
@qasimgulzar Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/configuration&entry.867055334=https://github.com/openedx/configuration/pull/6872&entry.1484655318=https://github.com/qasimgulzar&entry.752974735=2023-01-29+06:06&entry.1917517419=2024-04-05+00:47&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
