### PR TITLE
fix: add Elasticsearch variable overrides

### PR DESCRIPTION
**Pull request by Agrendalath**
Elasticsearch variables have been renamed for `discovery` and `edx_notes_api` services after the Koa release. This replaces the old names with the new ones.

## Reviewers

- [x] @kaustavb12
- [ ] CC / edX reviewer[s] TBD

## Follow-up

- [ ] Cherry-pick to `open-release/lilac.master` and `open-release/maple.master` once we merge this.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Agrendalath! I've created [OSPR-6356](https://openedx.atlassian.net/browse/OSPR-6356) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by kaustavb12 — APPROVED** [review]
:+1:

- [x] I tested this: I have verified that the corresponding variables have been changed in the course-discovery and edx-notes-api repos for lilac
- [x] I read through the code
- [x] Includes documentation

**Comment by Agrendalath** [comment]
@nizarmah, would you be able to add this to the OSPR list?

It could be a good candidate for the CC review.

**Comment by natabene** [comment]
@Agrendalath Thank you for your contribution. @pomegranited Are you interested in reviewing this?

**Comment by pomegranited** [comment]
@natabene  Yep! I'll review this next sprint (starts Tues 11 Jan).

**Comment by nizarmah** [comment]
Yes @Agrendalath! I was going to ask @pomegranited as well, thank you so much @natabene!

**Review by pomegranited — APPROVED** [review]
:+1:

- [x] I tested this by deploying an [Ocim appserver](https://manage.opencraft.com/instance/32850/edx-appserver/21988/) using this branch, with Notes and Discovery services enabled. I checked that the configured ES hostnames made it through to the Notes and Discovery .yml files.
- [x] I read through the code, and checked the updated variable names against [course_discovery.settings.production](https://github.com/openedx/course-discovery/blob/master/course_discovery/settings/production.py#L69) and [notesserver.settings.common](https://github.com/openedx/edx-notes-api/blob/master/notesserver/settings/common.py#L22). 
- [x] Includes documentation
- [x] Commit structure follows [OEP-0051](https://github.com/edx/open-edx-proposals/pull/189) 
- [x] <strike>I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.</strike> N/A

**Comment by nadeemshahzad** [comment]
@Agrendalath Looks good to me.

**Review by nadeemshahzad — APPROVED** [review]

**Comment by Agrendalath** [comment]
Thanks for reviewing this, @pomegranited and @nadeemshahzad. Given that this is already approved, and won't likely need any changes, I've opened #6659 and #6660 to backport it to Lilac and Maple. Would you mind reviewing these too (and merging them, if possible)?

**Comment by natabene** [comment]
So who can merge this?

**Comment by Agrendalath** [comment]
@natabene, @pomegranited is going to merge this one on Monday.

**Comment by openedx-webhooks** [comment]
@Agrendalath 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/configuration&entry.867055334=https://github.com/openedx/configuration/pull/6646&entry.1484655318=https://github.com/Agrendalath&entry.752974735=2021-12-30+21:07&entry.1917517419=2022-01-16+23:06&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
