### PR TITLE
Mvo/update firefox

### PR DESCRIPTION
**Pull request by minhtuev**

### CODE REVIEW

**Comment by minhtuev** [comment]
@hkim823  @jzoldak

**Comment by hkim823** [comment]
This looks good to me :+1:

**Comment by clytwynec** [comment]
I just tried provisioning a brand new instance devstack with the most recent commit from this PR and it failed...

```
TASK: [browsers | download browser debian packages from S3] ******************* 
changed: [localhost] => (item={'url': 'https://s3.amazonaws.com/vagrant.testeng.edx.org/google-chrome-stable_30.0.1599.114-1_amd64.deb', 'name': 'google-chrome-stable_30.0.1599.114-1_amd64.deb'})
failed: [localhost] => (item={'url': 'https://s3.amazonaws.com/vagrant.testeng.edx.org/firefox_28.0%2Bbuild2-0ubuntu2_amd64.deb', 'name': 'firefox_28.0+build2-0ubuntu2_amd64.deb'}) => {"dest": "/tmp/firefox_28.0+build2-0ubuntu2_amd64.deb", "failed": true, "item": {"name": "firefox_28.0+build2-0ubuntu2_amd64.deb", "url": "https://s3.amazonaws.com/vagrant.testeng.edx.org/firefox_28.0%2Bbuild2-0ubuntu2_amd64.deb"}, "response": "HTTP Error 403: Forbidden", "state": "absent", "status_code": 403, "url": "https://s3.amazonaws.com/vagrant.testeng.edx.org/firefox_28.0%2Bbuild2-0ubuntu2_amd64.deb"}
msg: Request failed
```

Apparently I grabbed the oldest hash instead of the newest one...

**Comment by clytwynec** [comment]
So, after a bit of research, it seems we need to use one of versions 17, 24, 27, or 28 of firefox for v2.42.1 of selenium.  The tests that use ActionChains are failing with the new version of selenium with both firefox 25 (the current version) and with firefox 31.  I tested with firefox 28.0 and selenium 2.42.1, and those errors don't happen.  I'm looking a bit more into this to see if one of these Firefox versions will work with both the old and new versions of selenium to make the transition smoother though.

**Comment by minhtuev** [comment]
thanks! ok let me know if we need to update the PR to firefox 28.

**Comment by clytwynec** [comment]
So far, It looks like we should go with version 28.0.  When this is updated, I'll create a new AMI and test it out again.

**Comment by muhammad-ammar** [comment]
@clytwynec As per [changelog](http://selenium.googlecode.com/git/py/CHANGES) v2.42.1 should work fine with FF v29. 
A month ago I have tested the FF v29 with Selenuim v2.42.1 and it was working fine.

**Comment by minhtuev** [comment]
@muhammad-ammar : maybe we have newer commits that do not work with FF v29 more.

**Comment by muhammad-ammar** [comment]
@minhtuev yeah may be...i am not sure about this.

**Pull request merged**
