### PR TITLE
Removing SEGMENT_KEY from configuration for ecommerce application

### PR DESCRIPTION
**Pull request by mikedikan**
Configuration Pull Request
---
@edx/ecommerce & @edx/devops (https://openedx.atlassian.net/browse/DEVOPS-5416)

Make sure that the following steps are done before merging

  - [x] @devops team member has commented with :+1:
  - [x] are you adding any new default values that need to be overridden when this goes live?  
    - [x] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [x] Add an entry to the CHANGELOG.

### CODE REVIEW

**Review by clintonb — APPROVED** [review]

**Review by jibsheet — APPROVED** [review]
Should make a Changelog entry - link to the PR where it was removed from ecommerce.

**Comment by mikedikan** [comment]
sorry @jibsheet - Changelog entry?  Meaning in the commit comment?

**Comment by clintonb** [comment]
https://github.com/edx/configuration/blob/master/CHANGELOG.md

**Comment by mikedikan** [comment]
thanks @clintonb

**Review by rlucioni — APPROVED** [review]

**Review by jibsheet — APPROVED** [review]

**Pull request merged**
