### PR TITLE
Add new Django requirement file to install.

### PR DESCRIPTION
**Pull request by doctoryes**
A new django.txt requirement file was added in the edx-platform work here:
https://github.com/edx/edx-platform/pull/16022
That requirements file needs to be added to the edxapp build as well - this PR does that.

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

### CODE REVIEW

**Review by bmedx — APPROVED** [review]
Will this also fix the devstack issues?

**Review by feanil — APPROVED** [review]

**Comment by macdiesel** [comment]
It should with the next image that builds successfully and is shipped to docker.io.

**Comment by doctoryes** [comment]
@bmedx As the Docker devstack build also uses the edxapp playbook, it should.
@macdiesel What will I need to do to kick a new Docker devstack build?

**Comment by macdiesel** [comment]
It will build automatically with the next commit to edx-platform.

**Comment by doctoryes** [comment]
Gonna go ahead with the merge before testing completes as this issue is affecting multiple folks.

**Comment by clintonb** [comment]
Why is there now one file that only contains Django?

**Comment by doctoryes** [comment]
@clintonb The Django requirement was removed from base.txt and put in a separate file to accommodate tox testing, which tests against different Django versions.

**Pull request merged**
