### PR TITLE
update port forward for comments service and add 9200 for elasticsearch

### PR DESCRIPTION
**Pull request by jimabramson**
devstack needs comments service running on 18080, so updated the port forward to make it directly accessible from the host.  in addition, made elasticsearch accessible from the host as well.

I know there are several other Vagrantfiles where these directives exist, let me know which of these would need the same changes applied and I'll add.

### CODE REVIEW

**Comment by e0d** [comment]
:+1:

**Comment by hkim823** [comment]
isn't 4567 used as the api port for forums?

**Comment by e0d** [comment]
4567 is the sinatra webbrick port, we are now running under unicorn and have the service fronted  by nginx.

**Comment by jimabramson** [comment]
if making edxapp look for forums on 4567 in devstack is a thing that makes sense, we could do that instead (would be a little more user-friendly too).  not sure how to implement that though.

**Comment by jimabramson** [comment]
should the Vagrantfile under vagrant/base/devstack get the same changes?
any of the fullstack ones?

**Comment by hkim823** [comment]
i'd make the same changes to the devstack file in base, they should match what's in release

probably can leave fullstack be

**Comment by jimabramson** [comment]
re-pushed with port forwards synced to base devstack Vagrantfile as well.
also planning to fix port forward instructions on [the devstack wiki](https://github.com/edx/configuration/wiki/edX-Developer-Stack#forum-workflow) so they align with this change.

**Comment by hkim823** [comment]
:+1:

**Pull request merged**
