### PR TITLE
Update dockerfiles Syntax

### PR DESCRIPTION
**Pull request by mostafahussein**
The current syntax in Dockerfile recommends to use
```
LABEL maintainer="foo"
```
Instead of
```
MAINTAINER foo
```
As the `MAINTAINER` keyword deprecated

---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mostafahussein! I've created [OSPR-3313](https://openedx.atlassian.net/browse/OSPR-3313) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@mostafahussein Thank you for the contribution! Once our legal team reviews your agreement and confirms you are all set,  we will review your PR.

**Comment by natabene** [comment]
@mostafahussein Thank you for joining the Open edX community! We have added your user to our records and can now review your code going forward. Please let me know once test is green.

**Comment by mostafahussein** [comment]
@natabene Is there a keyword for triggering the CI again ? Also note that the issues in the CI is not related to the modifications I made

**Comment by natabene** [comment]
@jmbowman How can I re-trigger Travis CI here?

**Comment by mostafahussein** [comment]
@natabene @jmbowman , I have triggered and checked the CI logs again and these issues are not related to what I have modified, What should we do in this case ?

**Comment by jmbowman** [comment]
A different set of tests run depending on which files were modified, and you're apparently the first person to change some of these in a while.  This error message from the Travis log seems pretty clear on how to fix at least one of the issues:

> ERROR:__main__:The following Dockerfiles are not described in the parsefiles_config.yml file: set(['graphite', 'elasticsearch-devstack']). Please see the following documentation on how to add Dockerfile ranks to the configuration file: https://github.com/edx/configuration/blob/master/util/README.rst

If you don't want to tackle that yourself, we can write up a ticket to fix it but I'm not sure off hand how long it will take us to get around to working on it.

**Comment by mostafahussein** [comment]
@jmbowman  Yea sure I was working on a solution for this error in specific indeed but i didn't know should i add it on a separate PR so we can merge it first or within this PR wont be a problem ?

**Comment by jmbowman** [comment]
It would probably be a little cleaner to do it in a separate PR, but I have no opposition to adding it in this one as long as the changes needed aren't too extensive.

**Comment by edx-webhook** [comment]
Thanks for the pull request, @mostafahussein! I've created [OSPR-3478](https://openedx.atlassian.net/browse/OSPR-3478) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@mostafahussein Have you had a chance to address @jmbowman 's feedback?

**Comment by feanil** [comment]
The test failures are because Travis is timing out because there are not enough shards to run all the tests. Given the change I believe it's safe to merge.

**Comment by openedx-webhooks** [comment]
@mostafahussein 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/5080&entry.1484655318=https://github.com/mostafahussein&entry.752974735=2019-04-16+15:28&entry.1917517419=2019-06-11+19:38&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
