### PR TITLE
(WIP) -- WL-300: Remove all usages of USE_CUSTOM_THEME and THEME_NAME

### PR DESCRIPTION
**Pull request by saleem-latif**
@mattdrayer , @fredsmith -- FYI

### CODE REVIEW

**Comment by mattdrayer** [comment]
@edx/devops -- need a hand with this one

**Comment by fredsmith** [comment]
There should be a changelog entry for this, as it's a significant change.  

As a note, we're using this code block to check out the edx-microsite repo.  Is that completely replaced by comprehensive theming?

**Comment by saleem-latif** [comment]
@fredsmith I was under the impression that this code is used only by Stanford Theming (related to `USE_CUSTOM_THEME` setting) that is why I am removing this. But if it is being used by `edx-microsites` than I suppose we would not have to remove this.
Can you take a look at https://github.com/edx/edx-platform/pull/12995 and let us know if they require configuration changes as done in this PR if not than I think we can close this PR?
@mattdrayer -- FYI

**Comment by fredsmith** [comment]
@saleem-latif I don't know how assets are built from microsites, but that's a concern i have with your other PR.  We certainly shouldn't merge this PR until we have a new way of deploying the microsites repo.

I would suggest we close this PR.

**Comment by saleem-latif** [comment]
It seems we do need these changes, so closing this PR for now. 
@fredsmith , @mattdrayer -- FYI

**Pull request closed without merging**
