### PR TITLE
SE-2989 Update labxchange-xblocks hash to include case study updates

### PR DESCRIPTION
**Pull request by samuelallan72**
See https://github.com/open-craft/labxchange-xblocks/pull/10 - this adds customizable sections and attachments to the labxchange case study xblock.

**Dependencies**: None

**Merge deadline**: None

**Testing instructions**:

1. verify that the updated hash/revision of the labxchange-xblocks dependency is valid and matches the commit that merged https://github.com/open-craft/labxchange-xblocks/pull/10
1. provision the platform with this configuration
2. verify that labxchange-xblocks is installed successfully in the environment.

**Reviewers**
- [x] @s0b0lev
- [x] edX reviewer[s] (@pomegranited )

**Settings**
```yaml
```

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @swalladge! I've created [OSPR-4887](https://openedx.atlassian.net/browse/OSPR-4887) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@swalladge Thank you for your contribution.  Please let me know once it is ready for edX review.

**Comment by s0b0lev** [comment]
@swalladge LGTM +1

- [x] I tested this: checked manually. (Instance provision is in progress)
- [x] I read through the code

**Comment by samuelallan72** [comment]
@natabene this is ready for edX review. :smile:

**Review by pomegranited — APPROVED** [review]
@swalladge  :+1: 

FYI @edx/devops @feanil 

- [x] I tested this by installing the updated XBlock hash, using the exact path used here.
- [x] I read through the code
- [x] <strike>I checked for accessibility issues</strike> N/A
- [x] <strike>Includes documentation</strike> N/A
- [x] <strike>I made sure any change in configuration variables is reflected in the corresponding
    client's `configuration-secure` repository.</strike> N/A

**Comment by pomegranited** [comment]
@feanil  Pinging you here since this is a mod to `edxapp`, though quite a straightforward one.

My plan here is to wait 2 business days for DevOps to comment before merging this OSPR -- is this ok with you?

**Comment by pomegranited** [comment]
Merging this as cc-reviewer since it's been 2 business days since [approving](https://github.com/edx/configuration/pull/5922#pullrequestreview-468269721) and pinging @edx/devops .

**Comment by openedx-webhooks** [comment]
@swalladge 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/5922&entry.1484655318=https://github.com/swalladge&entry.752974735=2020-08-10+05:09&entry.1917517419=2020-08-20+07:35&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by samuelallan72** [comment]
@ormsbee, we created this PR to update labxchange-xblocks on edX stage and prod, but we're not sure now if this is how plugins are managed on edX. Could you please clarify if the default `EDXAPP_PRIVATE_REQUIREMENTS` are installed in edX stage and/or prod? If so, is there a way of knowing when it has been deployed? If not, what should the process be for requesting an update to labxchange-xblocks (and other plugins) on edX stage and prod?

**Pull request merged**
