### PR TITLE
Add NAT hole to reach mongohq.

### PR DESCRIPTION
**Pull request by feanil**

### CODE REVIEW

**Comment by jarv** [comment]
We will probably also want port 15672 open for the web interface.

**Comment by jarv** [comment]
Will we be able to reach these guys on 15672 from the bastion?

**Comment by feanil** [comment]
Not with the current set of rules.  Do you want that before this gets merged in or as a seperate PR.

**Comment by jarv** [comment]
Let's make it part of this pull, unless it's tricky otherwise feel free to merge

**Pull request merged**
