### PR TITLE
Unpin virtualenv to latest version

### PR DESCRIPTION
**Pull request by mzulqarnain1**
Reverts edx/configuration#6141 which reverted #6137, which reverted #6135, which reverted #6131

Don't merge, Testing in progress

### CODE REVIEW

**Comment by iamsobanjaved** [comment]
I have tested and verified that `Instructor Tasks` are running successfully on the sandbox created with this change

**Sandbox:** https://venvunpintesting.sandbox.edx.org/
**Flower:** http://100.26.141.67:5555/

image

**Comment by mzulqarnain1** [comment]
FYI, @jmbowman and @kdmccormick

**Comment by jmbowman** [comment]
Is there anything different here than the last time we merged?  If not, we may want to hold off until we make some progress on figuring out how to log the actual cause of task registration failures, since the problem has been intermittent even between different workers in the same deployment.

**Comment by jmbowman** [comment]
The unregistered celery tasks issue was resolved in https://github.com/edx/edx-platform/pull/25840 , so we should be clear to try merging this again.

**Review by UsamaSadiq — APPROVED** [review]

**Comment by jmbowman** [comment]
@nedbat Do you want to backport this to Koa, in case there's another broken pip or setuptools release before Lilac comes out?

**Pull request merged**
