### PR TITLE
grafana role: fetch from packages.grafana.com

### PR DESCRIPTION
**Pull request by jsdnhk**
reason: original PackageCloud apt sources are disabled, using packages.grafana.com from official instead

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @jsdnhk! I've created [OSPR-3751](https://openedx.atlassian.net/browse/OSPR-3751) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@jsdnhk Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions. Thanks

**Comment by jsdnhk** [comment]
just sent the form to the mail, and please refer to it, thank you!

**Comment by natabene** [comment]
@jsdnhk Thank you for joining the Open edX community! We have added your user to our records and can now review your code going forward.

**Comment by natabene** [comment]
@edx/devops This is ready for your review when you have a chance.

**Comment by jsdnhk** [comment]
excuse me but any responses?

**Review by fredsmith — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@jsdnhk 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/5290&entry.1484655318=https://github.com/jsdnhk&entry.752974735=2019-07-17+02:20&entry.1917517419=2019-08-01+14:29&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by fredsmith** [comment]
@jsdnhk Thanks for your contribution, sorry it took so long to check out.

**Pull request merged**
