### PR TITLE
use YAML syntax

### PR DESCRIPTION
**Pull request by arbabnazar**
@e0d  kindly review. Thanks

CC: @edx/devops

### CODE REVIEW

**Comment by arbabnazar** [comment]
@mulby please review. Thanks

**Comment by mulby** [comment]
Looks reasonable to me. Can you confirm that you can still provision the analytics devstack base image?

https://github.com/edx/configuration/tree/master/vagrant/base/analyticstack

**Comment by e0d** [comment]
:+1: after we build the vagrant box.

@bradenmacdonald does someone from your side what to have a look?

**Comment by e0d** [comment]
@arbabnazar still syntax issues.

**Comment by arbabnazar** [comment]
@e0d I have reverted the change, so this is the issue with the previous config. Will try to fixed that

**Comment by bradenmacdonald** [comment]
@e0d We'd like to review, and I'll see if someone's available. But since we've got a few people on holidays and lots of deadlines at the moment, it may take a while - don't wait for us to merge.

**Comment by arbabnazar** [comment]
@e0d all error fixed.

@mulby can you please test it as I don't have an idea of analytics stuff much and want to merge it before my leaving.

Thanks,

**Comment by arbabnazar** [comment]
@e0d @mulby please review error has been fixed. Thanks

**Comment by e0d** [comment]
I'm :+1:

**Pull request merged**
