### PR TITLE
WIP: Changes to devstack for Xenial compatibility

### PR DESCRIPTION
**Pull request by gsong**
* Switch base box from `ubuntu/xenial64` to `boxcutter/ubuntu1604`
* Update to Firefox 45 which comes from the official package repo (verified to be compatible with Selenium 2.53.1)
* Install latest stable Chrome using Google's PPA (verified to be compatible with Selenium 2.53.1)
* Upgrade chromedriver from 2.6 to 2.25 (current release, verified to be compatible with Selenium 2.53.1)
* Manage `xvfb` via systemd rather than upstart

Address #3487.

/cc @nedbat @benpatterson @jibsheet

Make sure that the following steps are done before merging

  - [x] Verify successful [Vagrant box build](https://openedx.atlassian.net/wiki/display/COMM/Process+to+Create+an+Open+edX+Release#ProcesstoCreateanOpenedXRelease-MakeVagrantboxes) (@gsong)
  - [ ] Verify successful `paver test` (@gsong)
  - [ ] @devops team member has commented with :+1:

### CODE REVIEW

**Comment by benpatterson** [comment]
@gsong Glancing here, but I'm assuming we don't want to spend cycles re-testing this on a packer build?

**Comment by gsong** [comment]
@benpatterson I don't think so. This is just a rebase of the same work onto current-ish `master`.

**Comment by benpatterson** [comment]
@gsong cool

**Comment by gsong** [comment]
@edx/testeng Still couple errors for the `paver test` suite:

<details>
<summary>lms failure</summary>

```
ERROR: test_provider_login_can_handle_unicode_email_inactive_account (openedx.core.djangoapps.e
xternal_auth.tests.test_openid_provider.OpenIdProviderTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/external_auth/tests/test_openid_pr
ovider.py", line 360, in test_provider_login_can_handle_unicode_email_inactive_account
    self.client.login(username=user.username, password='test')
  File "/edx/app/edxapp/edx-platform/openedx/core/djangoapps/safe_sessions/testing.py", line 41
, in login_with_safe_session
    if not patched_client_login(self, **credentials):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/test/client.py",l
ine 593, in login
    user = authenticate(**credentials)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/contrib/auth/__in
it__.py", line 74, in authenticate
    user = backend.authenticate(**credentials)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/ratelimitbackend/backend
s.py", line 38, in authenticate
    stacklevel=2)
  File "/usr/lib/python2.7/logging/__init__.py", line 1724, in _showwarning
    s = warnings.formatwarning(message, category, filename, lineno, line)
  File "/edx/app/edxapp/venvs/edxapp/lib/python2.7/warnings.py", line 50, in formatwarning
    s =  "%s: %s: %s\n" % (lineno, category.__name__, message)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 70-73: ordinal not in ran
ge(128)
```
</details>

and

<details>
<summary>common/lib/capa failure</summary>

```
ERROR: test_802x (capa.safe_exec.tests.test_safe_exec.TestRealProblems)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/common/lib/capa/capa/safe_exec/tests/test_safe_exec.py", l
ine 302, in test_802x
    safe_exec(code, g)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/dogapi/stats/dog_stats_a
pi.py", line 184, in wrapped
    result = func(*args, **kwargs)
  File "/edx/app/edxapp/edx-platform/common/lib/capa/capa/safe_exec/safe_exec.py", line 155, in
 safe_exec
    raise e
SafeExecException: Couldn't execute jailed code: stdout: '', stderr: 'OpenBLAS blas_thread_init
: pthread_create: Resource temporarily unavailable\nOpenBLAS blas_thread_init: RLIMIT_NPROC 0 c
urrent, 0 max\nTraceback (most recent call last):\n  File "jailed_code", line 15, in <module>\n
    exec code in g_dict\n  File "<string>", line 62, in <module>\n  File "/edx/app/edxapp/venvs
/edxapp-sandbox/local/lib/python2.7/site-packages/numpy/__init__.py", line 137, in <module>\n
import add_newdocs\n  File "/edx/app/edxapp/venvs/edxapp-sandbox/local/lib/python2.7/site-packa
ges/numpy/add_newdocs.py", line 9, in <module>\n    from numpy.lib import add_newdoc\n  File"/e
dx/app/edxapp/venvs/edxapp-sandbox/local/lib/python2.7/site-packages/numpy/lib/__init__.py", li
ne 4, in <module>\n    from type_check import *\n  File "/edx/app/edxapp/venvs/edxapp-sandbox/l
ocal/lib/python2.7/site-packages/numpy/lib/type_check.py", line 8, in <module>\n    import nump
y.core.numeric as _nx\n  File "/edx/app/edxapp/venvs/edxapp-sandbox/local/lib/python2.7/site-pa
ckages/numpy/core/__init__.py", line 11, in <module>\n    from numeric import *\n  File "/edx/a
pp/edxapp/venvs/edxapp-sandbox/local/lib/python2.7/site-packages/numpy/core/numeric.py", line 8
17, in <module>\n    from _dotblas import dot, vdot, inner, alterdot, restoredot\nKeyboardInter
rupt\n' with status code: 1
```
</details>

[paver_test.txt.zip](https://github.com/edx/configuration/files/653249/paver_test.txt.zip)

**Comment by nedbat** [comment]
@gsong these two failures are reproducible?

**Comment by gsong** [comment]
@nedbat Based on [previous results](https://github.com/edx/configuration/pull/3525#issuecomment-265496859), reproducible.

**Comment by benpatterson** [comment]
Hmm the second failure would be related to apparmor install or
configuration, I think.

**Comment by benpatterson** [comment]
I don't know much about the first error. Perhaps Nimisha knows. (Sorry...
On my phone and don't recall her github handle.)

**Comment by gsong** [comment]
@nasthagiri Can you check out the LMS test failure in <https://github.com/edx/configuration/pull/3557#issuecomment-267174761> when you get a chance? Thanks.

**Comment by gsong** [comment]
I’m closing this PR as we won’t be merging this branch directly into `master`. It’s been supplanted by <https://github.com/edx/configuration/tree/ned/xenial>.

**Pull request closed without merging**
