### PR TITLE
Update to ansible 2.x

### PR DESCRIPTION
**Pull request by feanil**
Just trying to figure out what's still failing.

### CODE REVIEW

**Comment by arbabnazar** [comment]
@feanil are you able to fix the `ERROR! A recursion loop was detected with the roles`. Whenever I try to run any role, got this error although the exact same role is working with 1.9.x. I am not able to find the root cause. Thanks

**Comment by feanil** [comment]
@MichaelRoytman found that loop while doing some other work.  @MichaelRoytman have you PRed up the change that removes the dependency cycle?

**Comment by arbabnazar** [comment]
Thanks @feanil, once the @MichaelRoytman will update the changes, I'll work on the Warning messages to fix them for Ansible 2.x

**Comment by smaeda-ks** [comment]
Intersting!
I am looking forward to it.

FYI
combine(New in version 2.0) is useful.
http://docs.ansible.com/ansible/playbooks_filters.html#combining-hashes-dictionaries

**Comment by feanil** [comment]
@smaeda-ks nice,  that looks handy.

@edx/devops I just pushed up changes that get most of the tests passing.  I'll be doing further testing from our ansible checklist this week.

I cut out the jinja testing which was using some functions internal to Ansible that have both moved around and changed behavior.  If we are going to continue to have the docker build I think we should rely on them to test templates in the right context.

**Comment by arbabnazar** [comment]
@feanil today I found that we need to modified our callback plugins as well due to change in 2.x API. I think we are not ready to move to the 2.x. Thanks

**Comment by feanil** [comment]
@arbabnazar good to know, there are warnings in the output for the syntax check which mentions those I think.

**Comment by arbabnazar** [comment]
unfortunately it gives error instead of warnings in this case during my testing, we have created the story for it on which I'll start work. I am working on one of the story to remove all those warnings.

**Comment by feanil** [comment]
Sounds good.  In that case perhaps I should remove the requirements change from this PR? I think the rest of it is backwards compatible and can be merged if people are okay with my decision about what to do about the Jinja tests.

**Comment by feanil** [comment]
@bradenmacdonald @antoviaque FYI, we've got a few of us working on landing this for our hackathon.

**Comment by feanil** [comment]
## What we have tested so far
- All Docker builds that travis can run, tested locally because travis times out before running all of them. All Pass
- Building a Mongo Cluster
- Building an Elasticsearch Cluster
- Building a RabbitMQ Cluster
- Building baked-secure config for edx-platform, no differences
## Things Left to Test
- [x] Building Sandboxes
- [ ] Building Sandboxes from Scratch
- [x] Building Devstack basebox from scratch
- [ ] Building release Devstack using the new basebox and this branch
- [ ] Building release Devstack with the old basebox and  this branch
- [x] Building AMIs
- [x] Building AMI from scratch (edxapp 16.04)
- [x] Building AMI from scratch (edxapp 12.04)
- [ ] Building all app AMIs from scratch
- [x] Deploy edxapp AMI and make sure we didn't break the course-lifecycle
- [x] Deploying Using the Pipeline
- [x] Test Eng Packer Builds

**Comment by macdiesel** [comment]
👍

**Comment by antoviaque** [comment]
@feanil Cool, kudos for the work on this! : )

**Pull request merged**
