### PR TITLE
Allow config of Celery worker prefetch optimization (default|fair)

### PR DESCRIPTION
**Pull request by bryanlandia**
The default value of 'default' is to maintain the current behavior.  'fair' turns off task prefetching so that tasks are only sent to available processes.  Apparently there is a small performance decrease but it is useful to use 'fair' in case tasks are getting prefetched by worker processes that have long-running tasks—they won't execute until the long-running task is done, even using concurrency set above 1. 

see: https://celery.readthedocs.io/en/latest/userguide/optimizing.html#prefork-pool-prefetch-settings

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [x] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @bryanlandia! I've created [OSPR-3998](https://openedx.atlassian.net/browse/OSPR-3998) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@bryanlandia Thank you for your contribution. @fredsmith Can you give this a look?

**Comment by fredsmith** [comment]
This is not really a change to the configuration code as much as the defaults for the edxapp workers. the ansible changes are fine with me. We should bring in @nasthagiri to approve this.

@nasthagiri this won't affect edx.org, as we override this entire data structure.  if we want to take advantage of this scheduling, we should make a similar change to our internal overrides.

**Comment by nasthagiri** [comment]
@fredsmith If I understand correctly, this PR does not change the default for `edxapp` workers. Therefore, we can go ahead and merge this PR.

Regarding updating edX's own internal config, we would want to observe and monitor its impact in production before turning it on.  I have created an [Arch ticket](https://openedx.atlassian.net/browse/BOM-1128) to investigate this in the future.

@bryanlandia Do you have information/link to explain what you mean by `Apparently there is a small performance decrease`?  Thanks for the PR!

**Comment by bryanlandia** [comment]
Thanks @nasthagiri 

re: 

> Do you have information/link to explain what you mean by Apparently there is a small performance decrease

I don't have any actual benchmarking/performance test results to support this, just going off of the Celery Docs statement at  https://celery.readthedocs.io/en/latest/userguide/optimizing.html#prefork-pool-prefetch-settings

> The prefork pool will asynchronously send as many tasks to the processes as it can and this means that the processes are, in effect, prefetching tasks.   This benefits performance but it also means that tasks may be stuck waiting for long running tasks to complete:...

My understanding is that the difference is that there will likely be fewer separate read operations from the prefork pipe buffer by the worker when using default prefork behavior.  So if you changed to `fair` optimization, you might see a higher number of read operations on edX.org's VMs where there is a very large amount of tasks being run.  I probably wouldn't want to change the prefork strategy on a system if the disk where the pipe buffer was written (I don't think in a cloud computing setup this would be on physical memory) wasn't SSD or where there could be network restrictions/distance in accessing that disk.

**Comment by bryanlandia** [comment]
I can rebase to resolve conflicts once a decision is otherwise done re: merging

**Review by nasthagiri — APPROVED** [review]
@bryanlandia I am approving this PR since it doesn't change the current behavior of edx.org but does allow us to do so in the future.  Thanks for your PR!

**Comment by openedx-webhooks** [comment]
@bryanlandia 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/5590&entry.1484655318=https://github.com/bryanlandia&entry.752974735=2019-12-27+01:51&entry.1917517419=2020-01-09+17:51&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
