### PR TITLE
Adding the necessary variables to configure OAuth2 Client

### PR DESCRIPTION
**Pull request by Alec4r**
These changes fix the next two issues:

- The login isn't working because some variables wasn't defined, so always the login redirect to http://127.0.0.1:8000, these variables were hardcoded in the file analytics_dashboard/settings/base.py

- In the file /edx/etc/insights.yml the variabels are defined with the prefix "INSIGHTS_" and that isn't working because We are expecting the variables without the prefix.

**reviewers:**
@morenol

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Alec4r! I've created [OSPR-4922](https://openedx.atlassian.net/browse/OSPR-4922) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

Please let us know once your PR is ready for our review and all tests are green.

**Review by morenol — APPROVED** [review]
This looks good to me, I think that we should add this to Juniper once this gets merged to master. 

CC (@nedbat)

**Comment by nedbat** [comment]
Ping me again when this merges.

**Comment by natabene** [comment]
@Alec4r Thank you for your contribution! I will line this up for our review.

**Review by fredsmith — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@Alec4r 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/5967&entry.1484655318=https://github.com/Alec4r&entry.752974735=2020-08-26+16:27&entry.1917517419=2020-09-17+13:27&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by morenol** [comment]
Hi @nedbat, could we cherry-pick this into juniper.master?

**Comment by nedbat** [comment]
Yikes! Somehow I missed this comment. Would it still be useful to have this in Juniper?

**Comment by morenol** [comment]
I think that it could be useful for the Juniper installations, but since that release is not longer supported we can just keep it without this change.

**Pull request merged**
