### PR TITLE
Custom requirements installation fix on vanillas

### PR DESCRIPTION
**Pull request by defance**
There is a heavy bug that makes installation fail on vanillas when using `custom_requirements_file`.

I supposes this mistake was made by just copying-paste some snippets.

The main idea: on vanilla versions there is no `inst.stat.md5`-file and it is created much latter. So overall process fails on calclulating `when`-condition. 

There are some other tasks that are successfully executed on these cases (like `install post-requirements`). So I suppose that this is the condition supposed to be when installing custom requirements. :)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @defance! I've created [OSPR-303](https://openedx.atlassian.net/browse/OSPR-303) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams. 

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ('this must be merged by XX date', and why that is)
- partner information ('this is a course on edx.org')
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the Github pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

We can't start reviewing your pull request until you've added yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS) file. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst) file for more information.

**Comment by sarina** [comment]
@defance - this makes sense. I'm assigning this to the Ops team for review. They will review as soon as they can, but it may take a bit as we are approaching the Christmas season and we have lots of people on holiday.

Please be sure to add yourself to the `AUTHORS` file in this repo (you have to do this for each new repo you contribute to).

**Comment by e0d** [comment]
@defance Look like this branch needs a rebase.

**Comment by defance** [comment]
@e0d I rebased this branch. Conflict was in AUTHORS file. That's why I prefer not to edit documentation related files till the latest moment.

**Comment by sarina** [comment]
@defance totally fair, feel free to say something like, "I'll add myself to AUTHORS before this gets merged", or submit a separate PR to add yourself to AUTHORS that we can quickly merge. Either is okay.

**Comment by openedx-webhooks** [comment]
Hello @defance: We are unable to continue with review of your submission at this time. Please see the associated JIRA ticket for more explanation.

**Pull request closed without merging**
