### PR TITLE
Removed all references to the Programs Service

### PR DESCRIPTION
**Pull request by clintonb**
ECOM-7207

### CODE REVIEW

**Comment by clintonb** [comment]
@edx/devops please review and advise on the removal of the role and templates.

FYI @edx/ecommerce

**Review by rlucioni — APPROVED** [review]
Do we intend to remove the `programs` role?

**Comment by clintonb** [comment]
@rlucioni eventually. I'm awaiting comment from @edx/devops before taking that step. I'm not sure how that will affect OpenEdX users who make use of this repo.

**Comment by jibsheet** [comment]
I don't know if folks who follow master run programs, or if they're expected to stay on ficus.
@nedbat @gsong thoughts?

I'm all for removing it in master and leaving it on the named release branches, but not sure who that would impact (I expect this requires polling edx-code).

**Comment by gsong** [comment]
From my perspective it's fine to remove from `master` since we have a release branch for Ficus.

**Comment by clintonb** [comment]
RIP `programs`

**Comment by clintonb** [comment]
@edx/devops @edx/ecommerce please review

**Review by schenedx — APPROVED** [review]
👍

**Review by rlucioni — APPROVED** [review]

**Review by feanil — APPROVED** [review]

**Pull request merged**
