### PR TITLE
allow pulling ansible from a private github repo

### PR DESCRIPTION
**Pull request by trungpham**
edx_ansible_source_repo: 'ssh://git@github.com/private-repo/configuration.git'
EDX_ANSIBLE_USE_GIT_IDENTITY: True
EDX_ANSIBLE_LOCAL_GIT_IDENTITY: '/path/to/ansible_deploy_key'

### CODE REVIEW

**Comment by feanil** [comment]
This looks pretty good, but the credentials should be removed once the checkout is complete.(https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/tasks/deploy.yml#L57-L59)

and also the two all caps vars should have a default value in 'defaults/main.yml'(https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml#L134-L136).

Also have you signed the edX CLA(https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)

**Comment by trungpham** [comment]
I added the two default variables and removed the ssh private key after checking out the code.

**Comment by yarko** [comment]
@trungpham - thanks for this, it is instructional for me.   In general, for Open edX development we would need this for all edx repositories.  Does adding edx-platform, cs_comments_service and edx-ora (+ edx-theme) to this make sense (@feanil  - or would you prefer to see a separate PR?)

**Comment by feanil** [comment]
@trungpham that looks great.  Have you signed edX CLA?

@yarko seperate PRs would be good.

**Comment by nedbat** [comment]
@trungpham Details on the contributor agreement are at https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst

**Comment by hkim823** [comment]
@trungpham please let us know if you've signed the contributor agreement

**Comment by singingwolfboy** [comment]
@trungpham We still haven't received a contributor agreement from you, and this pull request has conflicts and needs to be rebased. I'm going to close this pull request, but if you want to come back to this feature, feel free to submit a new pull request once you've sent in the contributor agreement.

**Pull request closed without merging**
