### PR TITLE
Move docker to 16.04 for the ecommerce app.

### PR DESCRIPTION
**Pull request by feanil**
Configuration Pull Request
---

Make sure that the following steps are done before merging

  - [ ] @devops team member has commented with :+1:
  - [ ] are you adding any new default values that need to be overriden when this goes live?  
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

### CODE REVIEW

**Comment by jibsheet** [comment]
Can you do me a favor and make a dummy change in the ecommerce role so we see travis build the docker image?  After that, you can roll back the change.

Otherwise, 👍

**Comment by feanil** [comment]
I was holding off on pushing this up until after I got a review. I'll build the image now and push it to dockerhub.

**Comment by feanil** [comment]
Also, it looks like that wouldn't really help since they don't run tests the same way on the ecommerce app yet.

https://github.com/edx/ecommerce/blob/master/.travis.yml

@clintonb @rlucioni @schenedx FYI  looks like the way tests are run on the programs IDA and the ecommerce IDA are different.

**Comment by jibsheet** [comment]
I guess I'm missing which part of that .travis.yml can't be pushed down into running on the docker image?  Can you call out a particular part for me @feanil ?

**Comment by rlucioni** [comment]
@feanil I've got the same question as @jibsheet. Prior to @jibsheet's changes, the [programs travis.yml](https://github.com/edx/programs/blob/9eb184381f976826cc33569eca3970aa7bec900b/.travis.yml) was structured similarly to the ecommerce travis.yml.

**Comment by feanil** [comment]
Ah, Nevermind, @jibsheet I see what you're saying.  I'll make the PR over there to update their travis.yml shortly.  I thought it was something they had done but looking at the history of programs I see you made that change for them.  I can do the same for ecommerce.

**Comment by jibsheet** [comment]
@feanil Great, I assumed this was the confusion but wanted to make sure.  Unfortunately, the link to my programs change was added to the forums ticket as an FYI, but never made it to ecom.

**Comment by feanil** [comment]
@jibsheet @rlucioni this is also ready for re-review.

**Review by clintonb — APPROVED** [review]
Remember to squash your commits.

**Review by jibsheet — APPROVED** [review]
I'm actually OK unsquashed - the 3 commits are discrete bugfixes.

**Review by rlucioni — APPROVED** [review]

**Pull request merged**
