### PR TITLE
Upgrade `requests` module

### PR DESCRIPTION
**Pull request by singingwolfboy**
Pretty minor upgrade: http://docs.python-requests.org/en/latest/api/#migrating-to-2-x

Here's the companion PR for edx-platform: edx/edx-platform#4026

### CODE REVIEW

**Comment by hkim823** [comment]
What is the main driver to move to this version?

**Comment by singingwolfboy** [comment]
Fixing this issue: https://groups.google.com/d/msg/edx-code/0TWdOF5bmVk/IqSg65iKpjcJ

**Comment by feanil** [comment]
:+1:

**Comment by jarv** [comment]
@singingwolfboy I'm worried about upgrading requests on edx-platform to 2.x because of requests api changes.

The fix for https://groups.google.com/forum/#!msg/edx-code/0TWdOF5bmVk/IqSg65iKpjcJ was just merged into master, https://github.com/edx/edx-platform/pull/4023

**Comment by singingwolfboy** [comment]
@jarv Did you read [the migration guide for 2.x?](http://docs.python-requests.org/en/latest/api/#migrating-to-2-x) I don't think the backward-incompatible changes affect us.

**Comment by jarv** [comment]
The 0.x->1.x was pretty bad it looks like this one will be much safer.
Just wanted to let you know the other issue is now resolved in edx-platform master if that was a driving reason for the change.

**Comment by singingwolfboy** [comment]
@jarv It's good that the issue is resolved. However, we should still stay on the upgrade treadmill if possible, since other issues like this one may end up biting us in the ass in the future. Also, developers who want to work on the edx-platform code may want to use features present in `requests` 2.x that are not present in `requests` 1.x. So I still think we should do this upgrade. (It's not urgent, but it is important.)

**Comment by feanil** [comment]
@jzoldak if the requests module is upgraded, do you need to build wheels for the new package first?

**Comment by jzoldak** [comment]
The pip wheels that are created on the jenkins workers should be in step with the platform. I.e. https://github.com/edx/edx-platform/blob/master/requirements/edx/base.txt

So DO NOT MERGE this until after https://github.com/edx/edx-platform/pull/4026 (and whatever the PR for oauthlib is) make it through.

Every jenkins job for a commit with a different requirement will need to get and install the version of requests and oathlib that _it_ needs, which is at the moment an earlier version than will be in the local wheel.

**Comment by tusbar** [comment]
@jzoldak I think this can be merged now?

**Comment by singingwolfboy** [comment]
I mentioned this issue to @jzoldak yesterday, and he agreed that the `requests` module version in the configuration repo needed to be updated, so I'm interpreting that as a thumbs-up from him for this PR.

**Pull request merged**
