### PR TITLE
Updated programs role to support static assets

### PR DESCRIPTION
**Pull request by clintonb**
ECOM-2559

This is copied from ecommerce.

@feanil @jimabramson @rlucioni @jibsheet

### CODE REVIEW

**Comment by rlucioni** [comment]
Is static asset configuration part of the Ansible IDA template?

**Comment by clintonb** [comment]
@rlucioni nope. I am going to leave that addition to the next person who needs an IDA with static assets.

**Comment by rlucioni** [comment]
:+1:

**Comment by jimabramson** [comment]
looks reasonable to me :+1:

**Pull request merged**
