### PR TITLE
Waits for edx folder mount, if present, before starting services

### PR DESCRIPTION
**Pull request by javimudi**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @javimudi! I've created [OSPR-2066](https://openedx.atlassian.net/browse/OSPR-2066) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by nedbat** [comment]
@javimudi Thanks for the contribution! Will you be able to sign the contributor agreement, or indicate your organizational affiliation?  I know this contribution is small, but you only have to do it once, and then you'll be ready to make more contributions in the future.

**Comment by javimudi** [comment]
@nedbat You're welcome! I'm glad to contribute.

Just let me know the proper way to indicate my organizational affiliation.

Regards

**Comment by nedbat** [comment]
@javimudi You should have someone at your organization that oversees the contribution process to Open edX.  They should send an email to legal@edx.org, providing your name, email, GitHub username, and affirming that you are covered by the company's agreement.

**Comment by nedbat** [comment]
Thanks, we've received your agreement.

**Comment by feanil** [comment]
Sorry for the late reply but adding the target without context doesn't make sense I think.  Also what happens if the target doesn't exist?  It seems like a reasonable problem to solve but is there a way to make sure all the mounting is done before we start supervisord?  That seems like a safer general solution.  Closing this for now, pleas feel free to open a new PR with something more general if you have it.  Happy to discuss more here as well but not likely to accept this change as is.

**Comment by openedx-webhooks** [comment]
@javimudi Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4275&entry.1484655318=https://github.com/javimudi&entry.752974735=2018-01-09+13:50&entry.1917517419=2018-10-12+20:13&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
