### PR TITLE
Stop celery workers using SIGINT instead of SIGTERM.

### PR DESCRIPTION
**Pull request by feanil**
According to the documentation TERM should do a graceful shutdown:
http://celery.readthedocs.org/en/latest/userguide/workers.html#process-signals

but this is not actually the case:
https://groups.google.com/forum/#!topic/celery-users/t8g5KvIvQZ8

SIGINT on the other hand seems to do what we want.

@edx/devops

### CODE REVIEW

**Comment by e0d** [comment]
:+1:

**Comment by maxrothman** [comment]
Are we sure their documentation is wrong? if so, have we notified them?

**Comment by feanil** [comment]
@maxrothman please see the links in the description.

**Comment by maxrothman** [comment]
Is there a way to formally file a bug other than posting in the google group?

**Comment by feanil** [comment]
https://github.com/celery/celery/issues/2700

**Comment by maxrothman** [comment]
:+1:

**Pull request merged**
