### PR TITLE
remove pip installs for android utils

### PR DESCRIPTION
**Pull request by estute**
@benpatterson @jzoldak @jibsheet 
adb used to be in tools and adding a symlink makes for nicer scripting.
Also, the mobile app now uses a makefile with make requirements, so no need for the pip installs here

### CODE REVIEW

**Comment by benpatterson** [comment]
What kind of effect will this have on the time it takes to get an environment ready?

**Comment by estute** [comment]
@benpatterson negligible (seconds). I did this so that in case requirements change, mobile can manage it without a change here. It does open up to pip timeouts, but this is very small risk IMO

**Comment by benpatterson** [comment]
👍

**Comment by jzoldak** [comment]
Nice. 👍 

If we want to post codecov coverage in non-python repos, we can (and should) use the [bash uploader](http://docs.codecov.io/docs/about-the-codecov-bash-uploader).

**Review by jibsheet — APPROVED** [review]

**Pull request merged**
