### PR TITLE
DEVOPS-3036: Add MODULE_PREVIEW_URL insights setting

### PR DESCRIPTION
**Pull request by maxrothman**
@dsjen @edx/devops 

Relates to
- https://github.com/edx-ops/edge-secure/pull/168
- https://github.com/edx-ops/edx-secure/pull/620

### CODE REVIEW

**Comment by dsjen** [comment]
LGTM! :+1:

**Comment by fredsmith** [comment]
:+1:

**Comment by dsjen** [comment]
FYI @dan-f

**Comment by dan-f** [comment]
Thanks for this. :+1:

**Pull request merged**
