### PR TITLE
Be more explicit when failed to connect on sqs or ec2

### PR DESCRIPTION
**Pull request by rodo**
Add region in error message to help debugging wrong configuration.

### CODE REVIEW

**Comment by feanil** [comment]
@rodo This looks great, can you please sign the edX CLA(https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst#step-1-sign-a-contribution-agreement)

@jarv or @fredsmith can you please do the second review.

**Comment by jarv** [comment]
:+1:

**Comment by rodo** [comment]
I added myself to the AUTHORS file, signed and sent the CA to Jennifer.

**Comment by antoviaque** [comment]
FYI @rodo PRs are part of a recruitment test tasks, and can be assigned to my org in terms of contributor agreement.

**Pull request merged**
