### PR TITLE
chore: update Problem Builder XBlock

### PR DESCRIPTION
**Pull request by Agrendalath**
Resolves https://github.com/openedx/edx-platform/issues/32355.

---

Make sure that the following steps are done before merging:

  - [ ] A SRE team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [x] <s>Are you adding any new default values that need to be overridden when this change goes live? If so:</s>
    - [x] <s>Update the appropriate internal repo (be sure to update for all our environments)</s>
    - [x] <s>If you are updating a secure value rather than an internal one, file a SRE ticket with details.</s>
    - [x] <s>Add an entry to the CHANGELOG.</s> I didn't find changelog entries for updating any of these dependencies, so I skipped this step.
  - [x] <s>If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/spaces/SRE/pages/28967861/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).</s>
  - [x] <s>Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?</s>

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Agrendalath!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by Agrendalath** [comment]
@mtyaka, @pomegranited, would you mind reviewing this?

**Review by pomegranited — APPROVED** [review]
:+1: @Agrendalath

I can confirm that this change installs fine, but I haven't tried to check that it resolves the original issue. Do you need me to?

- [x] I tested this by ensuring that the modified requirement installs without error
- [x] I read through the code
- [x] <strike>I checked for accessibility issues</strike> N/A
- [x] <strike>Includes documentation</strike> N/A

**Comment by Agrendalath** [comment]
Thanks, @pomegranited!

> I can confirm that this change installs fine, but I haven't tried to check that it resolves the original issue. Do you need me to?

No, this is just a version bump.

**Comment by openedx-webhooks** [comment]
@Agrendalath 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/configuration&entry.867055334=https://github.com/openedx/configuration/pull/6937&entry.1484655318=https://github.com/Agrendalath&entry.752974735=2023-06-05+07:52&entry.1917517419=2023-06-05+20:46&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
