### PR TITLE
veda pipeline worker

### PR DESCRIPTION
**Pull request by muhammad-ammar**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

### CODE REVIEW

**Comment by muhammad-ammar** [comment]
@feanil This is the new role and it combined the 3 different video pipeline workers(deliver, ingest, youtubecallback). I have tested the changes as per step [1](https://tools-edx-jenkins.edx.org/job/Sandboxes/job/CreateSandbox/7221/) & [2](https://tools-edx-jenkins.edx.org/job/Sandboxes/job/CreateSandbox/7220/) from [Ops+Ansible+Testing+Checklist](https://openedx.atlassian.net/wiki/spaces/EdxOps/pages/28967861/Ops+Ansible+Testing+Checklist). Do you think this testing is enough or should I also perform step 3, 4 and 5. BTW I have no idea about step 4 & 5. And if you think this is ready for review than can please review the changes.

**Comment by muhammad-ammar** [comment]
@feanil Did further testing using step [3](https://tools-edx-jenkins.edx.org/job/Sandboxes/job/CreateSandbox/7250/) & 4 from [Ops+Ansible+Testing+Checklist](https://openedx.atlassian.net/wiki/spaces/EdxOps/pages/28967861/Ops+Ansible+Testing+Checklist). I think now this is ready for review.

**Comment by muhammad-ammar** [comment]
@feanil ^^

**Comment by muhammad-ammar** [comment]
@yro Can you also look at the changes. This role combines the 3 different video pipeline workers(deliver, ingest, youtubecallback).

**Review by feanil — APPROVED** [review]

**Pull request merged**
