### PR TITLE
Add linting of dockerfiles

### PR DESCRIPTION
**Pull request by cpennington**
(Due to limitations of the tool, this doesn't actually exit if the linter turns up errors)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
# PR Cover Letter
- [ ] A detailed description of the changes in the body of the PR
- [ ] If available, a link to the relevant JIRA ticket in the body of the PR
  - `[PROJ-XXXX](https://openedx.atlassian.net/browse/PROJ-XXXX)`

# Sandbox
- [ ] Build a sandbox for your branch and add a link here

# Testing
- [ ] i18n
- [ ] RTL
- [ ] Unit, integration, acceptance tests as appropriate
- [ ] Analytics
- [ ] Performance
- [ ] Database migrations are backwards-compatible

# Reviewers

If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [ ] Code review #1
- [ ] Code review #2
- [ ] UI strings/error msgs review
- [ ] UX review
- [ ] Accessibility review
- [ ] Product review

# DevOps assistance

If it's needed, or even if you suspect it might be needed, do any/all these things as early as possible. Don't surprise devops right before merging! For example, touching envs/aws.py or or envs/common.py are dead giveaways that you'll need assistance when pushing your changes out. Things that require devops attention include, but are not limited to:
- configuration changes
- feature flags
- migrations
  Ways to get devops attention, pick-and-choose whichever is most appropriate for your specific PR:
- [ ] Tag devops on your PR (`@edx/devops`), either for review (more specific to devops = better) or just a general FYI
- [ ] File a support ticket

FYI: Tag anyone who might be interested in this PR here.

# Post-review
- [ ] Squash commits

**Comment by cpennington** [comment]
Hey, look, the coverletter thing works! I'll add another PR to make a configuration-specific coverletter. (It will only apply to my PRs right now, because the tool is still in beta).

**Comment by cpennington** [comment]
@e0d: Review?

**Comment by e0d** [comment]
@cpennington looking at this old PR.  I haven't looked in depth at the Docker linting tools, but is running linting from a container our only or the best option?

**Comment by cpennington** [comment]
The particular linter can be compiled, but doesn't (as far as I can tell) have a ubuntu package at the moment. I'm not entirely sure if its suggestions are ones we want to follow anyway.

**Pull request closed without merging**
