### PR TITLE
add enterprise catalog to sandboxes

### PR DESCRIPTION
**Pull request by fredsmith**

### CODE REVIEW

**Review by adzuci — APPROVED** [review]

**Review by edx-abolger — APPROVED** [review]
Thank you!

**Comment by edx-abolger** [comment]
@adzuci since Fred is gone now, should I just merge this in? Trying to clean up the last pieces needed to actually make an Enterprise sandbox

**Comment by adzuci** [comment]
Hey @edx-abolger, I've merged this and am trying to remember how I can test the new playbook in a sandbox, if it happens to have unintended consequences though, we can of course revert the change.

**Comment by edx-abolger** [comment]
@adzuci let me just rebuild mine, it doesn't have data yet but is configured to have enterprise catalog so I'll be able to see if it's there in about an hour

**Pull request merged**
