### PR TITLE
updated the blockstore config to deploy on python 3.8

### PR DESCRIPTION
**Pull request by mraarif**
Configuration Pull Request
---
Relevant JIRA issue here: https://openedx.atlassian.net/browse/BOM-1964
Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code-shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by mraarif** [comment]
I've created a sandbox here: https://tools-edx-jenkins.edx.org/job/sandboxes/job/CreateSandbox/31689/ using this branch and build seems to be successful.

**Comment by mraarif** [comment]
I've created a JIRA issue here: https://openedx.atlassian.net/browse/DOS-1428 for the SRE team to verify Python 3.8 installation.

**Review by nadeemshahzad — APPROVED** [review]

**Comment by jmbowman** [comment]
I've created [TNL-7441](https://openedx.atlassian.net/browse/TNL-7441) for TNL to review this.

**Review by kdmccormick — APPROVED** [review]
This can merge at any point, which will allow me to push the upgrade to Stage Blockstore.

I will wait until Monday comes to push the change to Prod Blockstore.

@bradenmacdonald or any other OpenCraft CC -- feel free to push the button whenever you want this on Stage.

**Comment by kdmccormick** [comment]
@natabene has asked that we go to Stage today, so I'll merge and deploy this to Stage now.

**Comment by kdmccormick** [comment]
This is now on blockstore.stage.edx.org

**Comment by natabene** [comment]
@bradenmacdonald Could someone verify this on stage if your team has bandwidth?

**Comment by bradenmacdonald** [comment]
@natabene @kdmccormick Just did a smoke test with LX stage, reading writing and learning from library/blockstore XBlock works well 👍

**Comment by kdmccormick** [comment]
Great @bradenmacdonald! I'll deploy to production Monday around 11am ET. fyi @natabene

**Comment by natabene** [comment]
@kdmccormick Excellent! Does it need testing on prod?

**Comment by kdmccormick** [comment]
@natabene We will need to monitor and be ready to roll back on the off chance that something breaks, but we don't need any testing per se.

**Comment by kdmccormick** [comment]
@natabene @bradenmacdonald This is going to production now.

**Pull request merged**
