### PR TITLE
MAYN-217: Enhance ansible provisioning script to support Otto Theming

### PR DESCRIPTION
**Pull request by saleem-latif**
Hi @e0d , @arbabnazar , @mattdrayer 

Kindly review this PR, it contains ansible updates for ecommerce theming related to [PR#649](https://github.com/edx/ecommerce/pull/649). 

Here is a summary of the changes.
During provisioning and with offline compression enabled, We run `compress` management command for template compression after running `collectstatic`. After the changes introduced in  Otto Theming ( [PR#649](https://github.com/edx/ecommerce/pull/649)) we need to compile/collect theme and system sass before running `compress` command, so that the required css files are present and template compression does not error out.

I created a sandbox with '[saleem-latif/MAYN-217](https://github.com/edx/configuration/pull/2978)' branch of edx/configuration and '[saleem-latif/WL-330](https://github.com/edx/ecommerce/pull/649/files)' branch of edx/ecommerce to verify the change set. Here is the link of sandbox and links of applied themes.

Default Theme:
1. https://otto-theming.sandbox.edx.org (ecommerce: https://ecommerce-otto-theming.sandbox.edx.org/)

Red Theme:
2. https://red.sandbox.edx.org/ (ecommerce: https://ecommerce-red.sandbox.edx.org)

@clintonb , @jimabramson -- FYI

### CODE REVIEW

**Comment by mattdrayer** [comment]
@jibsheet, FYI on this PR -- it's the reason I had to revert the Otto PR on Friday that was causing the test failures on master

**Comment by jibsheet** [comment]
I agree I don't understand the github timeout issue with checking out that repo.
Master now has a fix for ffi in it.

The change itself looks fine 👍 but I am concerned that nothing else seems to be consistently failing .5

**Comment by mattdrayer** [comment]
I've rebased the branch to at least resolve the issue with the .3 build -- we'll need to take a closer look at .5 tonight.

**Comment by mattdrayer** [comment]
Annnnd I am now seeing the .5 build is GREEN -- @saleem-latif, I have discussed with @jibsheet and we are going to hold off on the merge until tomorrow.

**Comment by mattdrayer** [comment]
Running the Travis checks one more time before moving forward with the merge

**Comment by mattdrayer** [comment]
Okay, checks are still passing -- going ahead with the merge now

**Pull request merged**
