### PR TITLE
SOL-2037: Make sure ssh private keys are not leaked into the jenkins job logs

### PR DESCRIPTION
**Pull request by saleem-latif**
## Configuration Pull Request

**Description:**
After the merge of sandbox-secure, setting a git ssh key for the themes role, it began leaking an ssh private key into the jenkins job logs. We're going to have to rotate this key now.

@mattdrayer , @jibsheet -- FYI

Make sure that the following steps are done before merging
- [x] @devops team member has commented with :+1:
- [ ] are you adding any new default values that need to be overriden when this goes live?  
  - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
  - [ ] Add an entry to the CHANGELOG.

### CODE REVIEW

**Comment by mattdrayer** [comment]
Let's be sure to test this changeset prior to shipping to ensure we've addressed all of the spots.

**Comment by feanil** [comment]
Did you verify that this works as expected?

**Comment by saleem-latif** [comment]
@feanil yes, I have tested it on sandbox with "/edx/bin/update" command, but I would need branch name for secure configuration (branch that contains theming overrides, I think it was merged and later reverted yesterday) to test it for sandbox creation.

**Comment by feanil** [comment]
:+1:

**Comment by saleem-latif** [comment]
@mattdrayer I have completed the ansible testing checklist (https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist), for these changes.

**Comment by mattdrayer** [comment]
:+1:

**Comment by saleem-latif** [comment]
Going ahead with the merge now

**Comment by jibsheet** [comment]
@saleem-latif Both Build #5310 SaleemLatif-prod-edx-edxapp-1472024059 and Build #5311 SaleemLatif-prod-edx-ecommerce-1472024086 are still running because the ansible died.

How was this tested, since those appear to be the AMI builds you kicked off specifically for this branch?

We're now seeing the same failures impacting those builds and someone else's IDA builds.

**Comment by jibsheet** [comment]
Confirmed this broke @schenedx and @rlucioni builds of discovery 

```
Aug 25 15:35:10 ip-10-2-120-228 user-data: TASK: [git_clone | Set git fetch.prune to ignore deleted remote refs] ********* 
Aug 25 15:35:10 ip-10-2-120-228 user-data: <localhost> REMOTE_MODULE command (no_log enabled, args censored)
Aug 25 15:35:10 ip-10-2-120-228 user-data: <localhost> EXEC ['/bin/sh', '-c', 'mkdir -p /tmp/ansible-tmp-1472139310.69-17026471107468 && chmod a+rx /tmp/ansible-tmp-1472139310.69-17026471107468 && echo /tmp/ansible-tmp-1472139310.69-17026471107468']
Aug 25 15:35:10 ip-10-2-120-228 user-data: <localhost> PUT /tmp/tmpfBZNcb TO /tmp/ansible-tmp-1472139310.69-17026471107468/command
Aug 25 15:35:10 ip-10-2-120-228 user-data: <localhost> EXEC ['/bin/sh', '-c', 'chmod a+r /tmp/ansible-tmp-1472139310.69-17026471107468/command']
Aug 25 15:35:10 ip-10-2-120-228 user-data: <localhost> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=gtxmekzvsrjtszrmeqrgkxzvrhqeigvn] password: " -u discovery /bin/sh -c '"'"'echo BECOME-SUCCESS-gtxmekzvsrjtszrmeqrgkxzvrhqeigvn; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /tmp/ansible-tmp-1472139310.69-17026471107468/command'"'"''
Aug 25 15:35:11 ip-10-2-120-228 user-data: <localhost> EXEC ['/bin/sh', '-c', 'rm -rf /tmp/ansible-tmp-1472139310.69-17026471107468/ >/dev/null 2>&1']
Aug 25 15:35:11 ip-10-2-120-228 user-data: changed: [localhost] => {"censored": "results hidden due to no_log parameter", "changed": true, "rc": 0}
Aug 25 15:35:11 ip-10-2-120-228 user-data: fatal: [localhost] => Traceback (most recent call last):
Aug 25 15:35:11 ip-10-2-120-228 user-data:   File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 585, in _executor
Aug 25 15:35:11 ip-10-2-120-228 user-data:     exec_rc = self._executor_internal(host, new_stdin)
Aug 25 15:35:11 ip-10-2-120-228 user-data:   File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 788, in _executor_internal
Aug 25 15:35:11 ip-10-2-120-228 user-data:     return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
Aug 25 15:35:11 ip-10-2-120-228 user-data:   File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 1120, in _executor_internal_inner
Aug 25 15:35:11 ip-10-2-120-228 user-data:     self.callbacks.on_ok(host, data)
Aug 25 15:35:11 ip-10-2-120-228 user-data:   File "/usr/local/lib/python2.7/dist-packages/ansible/callbacks.py", line 548, in on_ok
Aug 25 15:35:11 ip-10-2-120-228 user-data:     super(PlaybookRunnerCallbacks, self).on_ok(host, host_result)
Aug 25 15:35:11 ip-10-2-120-228 user-data:   File "/usr/local/lib/python2.7/dist-packages/ansible/callbacks.py", line 347, in on_ok
Aug 25 15:35:11 ip-10-2-120-228 user-data:     call_callback_module('runner_on_ok', host, res)
Aug 25 15:35:11 ip-10-2-120-228 user-data:   File "/usr/local/lib/python2.7/dist-packages/ansible/callbacks.py", line 179, in call_callback_module
Aug 25 15:35:11 ip-10-2-120-228 user-data:     method(*args, **kwargs)
Aug 25 15:35:11 ip-10-2-120-228 user-data:   File "/var/tmp/edx-cfg/configuration/playbooks/callback_plugins/hipchat_plugin.py", line 129, in runner_on_ok
Aug 25 15:35:11 ip-10-2-120-228 user-data:     if res['invocation']['module_name'] != "setup":
Aug 25 15:35:11 ip-10-2-120-228 user-data: KeyError: 'invocation'
Aug 25 15:35:11 ip-10-2-120-228 user-data: 
Aug 25 15:35:11 ip-10-2-120-228 user-data: 
Aug 25 15:35:11 ip-10-2-120-228 user-data: FATAL: all hosts have already failed -- aborting
Aug 25 15:35:11 ip-10-2-120-228 user-data: 
```

This error was visible in the failed builds I quoted above also, so the testing process caught this failure, but the branch was merged anyway?

Reverting to clean up master.

**Comment by saleem-latif** [comment]
@mattdrayer , @jibsheet  Sorry, I was under the impression that failing build usually report 10-20 minutes from build, I will be more carful in future.

**Pull request merged**
