### PR TITLE
Add configuration variables for pluggable payment processors

### PR DESCRIPTION
**Pull request by kaizoku**
Configuration Pull Request
---
This PR adds configuration variables for configuring additional payment processors external to the ecommerce codebase.
These variables are required to utilize changes made by https://github.com/edx/ecommerce/pull/3297

External payment processors can be configured by setting the path to the payment processor class in `ECOMMERCE_ADDL_PAYMENT_PROCESSORS`, similar to how the [built-in processors are configured in ecommerce](https://github.com/edx/ecommerce/blob/2151b73b00bcb6528ae45945a460e2665ff0c5cd/ecommerce/settings/_oscar.py#L128).

--

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @kaizoku! I've created [OSPR-5614](https://openedx.atlassian.net/browse/OSPR-5614) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@kaizoku Thank you for your contribution. Please let me know once this is ready for our review.

**Comment by natabene** [comment]
@kaizoku Just checking if this is still relevant for you.

**Comment by pomegranited** [comment]
@kaizoku https://github.com/edx/configuration/pull/6300 makes this PR unnecessary (yay!). You can now do the same thing with:

```yaml
ECOMMERCE_EXTRA_CONFIG_OVERRIDES:
  ADDL_PAYMENT_PROCESSORS: ...
```

So I'm closing this -- feel free to re-open if you disagree?

**Comment by openedx-webhooks** [comment]
@kaizoku Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6282&entry.1484655318=https://github.com/kaizoku&entry.752974735=2021-02-06+15:00&entry.1917517419=2021-03-11+00:06&entry.2133058324=No) so we can improve your experience in the future.

**Comment by kaizoku** [comment]
Ah yep @pomegranited. Thanks for closing this. I had considered that we could use https://github.com/edx/configuration/pull/6300 instead, but hadn't gotten back here to verify. I'll test that the ecommerce feature I was adding to use this variable will work correctly even if it's not set (https://github.com/edx/ecommerce/pull/3297). We had some concern that it would cause issues because of [how ecommerce overloads local variables from the yaml config](https://github.com/edx/ecommerce/blob/bfee85bf7dbde45ccb03af3de6505ca2df674860/ecommerce/settings/production.py#L66), but I can probably work around this in that PR.

**Pull request closed without merging**
