### PR TITLE
New config format for the modulestore.

### PR DESCRIPTION
**Pull request by feanil**

### CODE REVIEW

**Comment by jarv** [comment]
can you run this on continuous integration as a sanity test before merging? :+1:

**Comment by feanil** [comment]
Running it on my sandbox right now, LMS works but CMS is having an issue.  Will update with fixes.

**Comment by feanil** [comment]
@jarv tested on my single instance sandbox, do you also want me to run ci on this branch?

**Comment by e0d** [comment]
LGTM

**Pull request merged**
