### PR TITLE
Fix typo in default 'from' email

### PR DESCRIPTION
**Pull request by tusbar**

### CODE REVIEW

**Comment by feanil** [comment]
@tusbar  Have you signed the Contributor License Agreement with edX(https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.md)

**Comment by tusbar** [comment]
@feanil Yes, I sent it a few hours ago!

**Comment by feanil** [comment]
cool, @jtauber can you confirm you have it?

**Comment by jtauber** [comment]
Yep, received and all set.

**Pull request merged**
