### PR TITLE
SE-1841 fix oauth retirement user provision

### PR DESCRIPTION
**Pull request by samuelallan72**
Currently, there are both `EDXAPP_RETIREMENT_SERVICE_USER_NAME` and `EDXAPP_RETIREMENT_SERVICE_WORKER_USERNAME` used for what appears to be the same thing (please correct me if I'm wrong). 

We believe that this is what is causing [this ansible task](https://github.com/edx/configuration/blob/42431cf549a1e74b2892bd71e9bafc5f412b52dd/playbooks/roles/oauth_client_setup/tasks/main.yml#L71-L90) (create oauth configuration) to fail on the [retirement service entry](https://github.com/edx/configuration/blob/42431cf549a1e74b2892bd71e9bafc5f412b52dd/playbooks/roles/oauth_client_setup/defaults/main.yml#L94-L99) with the default configuration and retirement service enabled (`COMMON_RETIREMENT_SERVICE_SETUP: true`).

Also having two different variables for the same thing is confusing.

This PR renames all remaining instances of the former to the latter.

For background on these recent retirement changes, please see:     https://github.com/edx/configuration/pull/5040 and     https://github.com/edx/configuration/pull/5488. It's unknown when this issue was introduced though.

See also related PR which added a default for `RETIREMENT_SERVICE_USER_NAME` to edx-platform:    https://github.com/edx/edx-platform/pull/22087 This also appears to be the only other usage of this variable across the edx repositories. Also that PR failed to explain why the change was necessary.

**JIRA tickets**: [https://openedx.atlassian.net/browse/OSPR-3935](OSPR-3935)

**Dependencies**: None

**Sandbox URL**: 

The following sandbox was deployed using this configuration branch:

-    LMS: https://se-1541-test.stage.opencraft.hosting/
 -  Studio: https://studio.se-1541-test.stage.opencraft.hosting/

**Merge deadline**: ASAP - this is breaking provisioning that was previously working

**Testing instructions**:

1. enable the retirement service setup with `COMMON_RETIREMENT_SERVICE_SETUP: true` See also https://github.com/open-craft/configuration/blob/samuel/oauth-retirement-vars-fix/playbooks/roles/user_retirement_pipeline/README.md for retirement specific config possibly required.
2. provision a master devstack
3. verify that it provisions successfully.

**Author notes and concerns**:

- https://github.com/edx/edx-platform/pull/22087 should be at least partially reverted since they introduce vars not used anywhere else.

**Reviewers**
- [x] @giovannicimolin 
- [ ] edX reviewer[s] TBD

**Settings**
```yaml
```

### CODE REVIEW

**Review by giovannicimolin — APPROVED** [review]
:+1:

- [x] I tested this: 
1. Spawned a new master instance with the retirement service enabled.
2. Checked that the instance was successfully deployed :heavy_check_mark: 
3. Checked that the retirement service is working :heavy_check_mark: 
- [x] I read through the code
- [ ] ~~I checked for accessibility issues~~ NA
- [ ] ~~Includes documentation~~ NA

@swalladge Nice work catching this issue. Since we already have a temporary fix for this issue, I'll prioritize this in the usual way.

**Comment by samuelallan72** [comment]
Thanks @giovannicimolin !

@natabene This is ready for edX review. :slightly_smiling_face:

**Comment by natabene** [comment]
@fredsmith Can you give this a look when you have a chance?

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @swalladge! I've created [OSPR-3935](https://openedx.atlassian.net/browse/OSPR-3935) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by fredsmith** [comment]
closing in favor of https://github.com/edx/configuration/pull/5619 which doesn't rename all the things and also change the format of the documentation arbitrarily

**Comment by openedx-webhooks** [comment]
@swalladge Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/5503&entry.1484655318=https://github.com/swalladge&entry.752974735=2019-11-14+05:09&entry.1917517419=2020-01-24+20:41&entry.2133058324=No) so we can improve your experience in the future.

**Comment by samuelallan72** [comment]
@fredsmith 

> closing in favor of #5619 which doesn't rename all the things and also change the format of the documentation arbitrarily

That's fine, but feel free to request that documentation format changes be dropped or query why the things were renamed, instead of abruptly closing. :)

**Pull request closed without merging**
