### PR TITLE
New base box for devstacks that includes fixes for the chrome depreca…

### PR DESCRIPTION
**Pull request by jibsheet**
…tion

### CODE REVIEW

**Comment by arbabnazar** [comment]
:+1:

**Comment by nedbat** [comment]
Any chance we can standardize on either "2016-03-09" or "20160309"?  I see both forms used for devops-built boxes.

**Comment by jibsheet** [comment]
@nedbat I'll check what the job does and we should just standardize to that, I thought I did that, but maybe not (since I had to build this locally).

**Comment by jibsheet** [comment]
Script uses dashes, I like dashes, I've renamed my file and am running a provision locally then will merge.

**Pull request merged**
