### PR TITLE
feat: install atlas in `mfe` role FC-0012

### PR DESCRIPTION
**Pull request by OmarIthawi**
### Description
Download the openedx-atlas executable for all Micro-frontends to be used in `make pull_translations`

This installs `atlas` on all Ansible build targets such as Native Installation and Devstack.

Once merged it will make the [`atlas`](https://github.com/openedx/openedx-atlas) CLI executable available on all Micro-frontend Dockerfiles and native installation such as Profile, Account, Learning and others. It will make the following command possible: `atlas pull` which replaces `transifex pull` as part of the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification) project.

Testing
---------
 - [ ] Re-build a devstack docker image and run `atlas pull`

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A SRE team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? [Omar] No, the default value is safe to be used.
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a SRE ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/spaces/SRE/pages/28967861/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?  
    - [Omar] The documentation update is work-in-progress.

References
----------

This contribution is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

Up-to-date project overview and details are available in the [Approach Memo and Technical Discovery: Translations Infrastructure Implementation](https://docs.google.com/document/d/11dFBCnbdHiCEdZp3pZeHdeH8m7Glla-XbIin7cnIOzU/edit#) document.

Join the conversation on [Open edX Slack #translations-project-fc-0012](https://openedx.slack.com/archives/C04R6TUJB7T).

Check the links above for full information about the overall project.

Internalization is being rearchitected in Open edX Python, XBlock, Micro-frontend, and other projects. There are a number of immediately visible changes:
 - Remove source and language translations from the repositories, hence no `.json`, `.po` or `.mo` files will be committed into the repos.
 - Add standardized `make extract_translations` in all repositories
 - Push user-facing messages strings into [openedx/openedx-translations](https://github.com/openedx/openedx-translations/).
 - Integrate root repositories with [openedx/openedx-atlas](https://github.com/openedx/openedx-atlas/) to pull translations on build/deploy time

Breaking Changes
----------------

One of the primary goals of the project is to **avoid breaking changes**. If you noticed any suspicious code, please raise your concern. But before that, please know the strategy we're following to avoid breaking changes:

 - All variable have sane-defaults.
 - The changes are backward compatible and don't break any existing deployments.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @OmarIthawi! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by brian-smith-tcril** [comment]
I think we should wait until we implement https://github.com/openedx/openedx-atlas/issues/34 and use npm here

**Comment by brian-smith-tcril** [comment]
@OmarIthawi do we know the status on this one? Is this still something we're planning on doing or can it be closed?

**Comment by OmarIthawi** [comment]
@brian-smith-tcril this is waiting for both: 1) Me completing the edx-platform work to have free time for this, 2) 2U input on how should we copy/mimic the Tutor MFE `atlas pull` logic into `configurations`.

I think we can start with (2) and ping someone from 2U. The [review input document](https://docs.google.com/spreadsheets/d/1da5_DzlZ_fEMQf6dR_pa6jvKVpZCkITBXiUhZC0D9Xw/edit#gid=0) we have doesn't list the `configuration` repo.

**Comment by kdmccormick** [comment]
I'm noticing that this is would be the only NPM package which we'd specifically install into the playbook. I imagine we'll need to make sure the same version is also installed into Tutor.

All other build requirements are installed transitively via frontend-build, I believe (correct me if I'm wrong). So, instead of installing Atlas here, would it be possible to install it via frontend-build as well?

**Comment by brian-smith-tcril** [comment]
in https://github.com/overhangio/tutor-discovery/pull/41 we install `atlas` via pip

**Comment by kdmccormick** [comment]
Right, okay. I was going to say that these requirements should all go into package.json and requirements/yada.in like everything else, but now that I'm thinking about it more, I guess the client of Atlas is not the upstream repo itself, but rather the *builder* of the repo. In other words, Tutor and Ansible are the users of Atlas, so they will each maintain their own version pins and handle Atlas upgrades separately.

You folks probably came to this conclusion a while ago. Sorry for the distraction. This change LGTM.

**Comment by OmarIthawi** [comment]
@kdmccormick @brian-smith-tcril as far as the place to install the `openedx-atlas` package is concerned the current approach is to install `openedx-atlas` in each repository in order to benefit from the [automatic bot package updates (example)](https://github.com/openedx/course-discovery/pull/4117/files#diff-eec14310e29cef9d8ae421c606788e73774112c68cda8ab743ad4257ff73d156R562) and to cause the least surprise to future maintainers looking to change the packages.

> in https://github.com/overhangio/tutor-discovery/pull/41 we install atlas via pip

This was the first attempt to integrate atlas into a builder, and we should remove this pin to avoid confusion now course-discovery has its requirement.

I'm keeping this pull request merely as a "todo" item, but I'll close it and re-open once I'm done with the edX Platform work:

 - https://github.com/openedx/edx-platform/pull/33698

I've created a pull request to remove the redundant install:

 - https://github.com/overhangio/tutor-discovery/pull/53

**Comment by openedx-webhooks** [comment]
@OmarIthawi Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/configuration&entry.867055334=https://github.com/openedx/configuration/pull/6968&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2023-07-30+14:34&entry.1917517419=2023-11-18+05:20&entry.2133058324=No) so we can improve your experience in the future.

**Comment by openedx-webhooks** [comment]
@OmarIthawi Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/configuration&entry.867055334=https://github.com/openedx/configuration/pull/6968&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2023-07-30+14:34&entry.1917517419=2023-11-18+05:20&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
