### PR TITLE
add static and media files basic django configuration

### PR DESCRIPTION
**Pull request by zubair-arbi**
ECOM-3694
@awais786 @ahsan-ul-haq @tasawernawaz 
- Add basic configuration for `media` and `static` files
- Add configuration task to create credentials var dirs
- Add missing `nginx` route for media files

Changes related to: https://github.com/edx/configuration/pull/2758
Provision: http://jenkins.edx.org:8080/view/Ansible/job/ansible-provision/5615/console
Sandbox: https://credentials-zubair-arbi.sandbox.edx.org/

### CODE REVIEW

**Comment by zubair-arbi** [comment]
I have verified this configuration on my sandbox: https://credentials-zubair-arbi.sandbox.edx.org/
@ahsan-ul-haq Please review
@cpennington  I have moved the basic configuration for media files here from https://github.com/edx/configuration/pull/2758/. Please review
FYI: @maxrothman

**Comment by ahsan-ul-haq** [comment]
:+1:

**Comment by zubair-arbi** [comment]
@cpennington Please review

**Comment by zubair-arbi** [comment]
@maxrothman Would you mid reviewing this as I want merge it before adding config for file storage backend.

**Comment by maxrothman** [comment]
Just so I'm on the same page, this is to support writes from the file storage backend?

**Comment by zubair-arbi** [comment]
@maxrothman yes.

**Comment by maxrothman** [comment]
:+1:

**Pull request merged**
