### PR TITLE
devstack vagrantfile: mount "themes" from host

### PR DESCRIPTION
**Pull request by sefk**
This mounts the "themes" directory on the host.  This will enable people
who have configured "stanford-style" themes to check out their themes on
the host and have it useable in the devstack.

Two things are a bit odd about this that are worth highlighting.
1. For people not using Stanford-style theming, which are most
   developers and certainly everyone at edX.org, this is a wasted
   export.  It doesn't do any harm, but would it be confusing?  I
   think that's OK.
2. The provision steps checks out the other repos that you need
   (edx-platform, cs_comment_service, etc.).  We're not checking out
   the theme repo ourselves here, counting on the user to do so
   yourself later.  I know this isn't consistent, but I couldn't
   plumb through the theming stuff into the rest of devstack
   provision, at least not right now.

### CODE REVIEW

**Comment by caesar2164** [comment]
@sef - This works awesome!

**Comment by sefk** [comment]
@e0d -- can you take a look at this when you get a chance?  quickie.

**Comment by e0d** [comment]
Makes sense to me, but I'm a little further away from this stuff than others.  @hkim823 Thoughts?

**Comment by hkim823** [comment]
I'm concerned that someone not familiar with themes will see an empty themes subdirectory and get confused, especially from the open source community.

**Comment by jambonbill** [comment]
I prefer to see an empty directory than no directory at all !

On 16 April 2014 21:47, Han Su Kim notifications@github.com wrote:

> I'm concerned that someone not familiar with themes will see an empty
> themes subdirectory and get confused, especially from the open source
> community.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/edx/configuration/pull/884#issuecomment-40643433
> .

## 

pierre

**Comment by hkim823** [comment]
Fair enough, :+1:

**Comment by hkim823** [comment]
@sefk feel free to merge this in

**Comment by yarko** [comment]
@sefk -   I like that you've linked this into /edx/app/edxapp/themes

You can test out the concept of getting ansible-playbooks populating manually this way:  follow the gist you and @caesar2164 used on edx-platform PR#3049 tests (https://gist.github.com/yarko/10711787).
Note the theme settings  (repo, version, django enabling) at the bottom of that build-version.yml.

This should have ansible checkout into your themes, and it should show up in your host.

Once #3094/edx-platform is merged,  this PR,  I'll make the PR for Vagrantfile to add the extra-vars processing of "build-version.yml" and this group will make it _awesome_ - thanks!

/cc @hkim823

**Comment by sefk** [comment]
Merging with @hkim823's blessing, thanks.

**Comment by yarko** [comment]
@jambonbill @hkim823 @sefk - with this, and #3094 now merged, the "empty directory" effect is almost history:  I'm working on the "last piece" of getting `build-version.yml` into / part of both `Vagrantfile` processing, and `/edx/bin/update` - which will make spec'ing and forking theme, repo, and general development uniform and defer any need to _understand_ ansible-playbooks fully to get the starting basics (forking, etc.).   We are really on our way now!    Thanks for this, @sefk

**Pull request merged**
