### PR TITLE
Performing shallow clone of Git repos

### PR DESCRIPTION
**Pull request by clintonb**
This should help decrease build times.

ECOM-6600

### CODE REVIEW

**Comment by clintonb** [comment]
@edx/devops please review

**Comment by feanil** [comment]
@clintonb did you test what happens when you run ansible a second time on a shallow clone?  Did that cause any issues?

**Comment by clintonb** [comment]
@feanil I, incidentally, have. As I've been making devstack images, I've used the previous image as a base to save time for edxapp. I have not observed any issues with git when doing this.

**Comment by maxrothman** [comment]
It appears you have failing tests.

**Comment by clintonb** [comment]
@feanil @maxrothman tests are now passing after rebasing

**Comment by feanil** [comment]
Generally looks good to me, I'm building a sandbox from this to make sure we don't break that.  @clintonb can you also build some AMIs with alton using this branch and make sure that won't have any issues?

If those two checks come back clean, I'm good with merging this.  @edx/devops any objections?

**Comment by clintonb** [comment]
I successfully built ami-8857a69e for stage edx credentials.

```
@alton cut ami for stage-edx-credentials from prod-edx-credentials with credentials_version=master configuration=clintonb/shallow-clone configuration_secure=master
```

**Comment by jibsheet** [comment]
Assuming we throw in a build from scratch of an AMI, I'm good with it.

**Comment by clintonb** [comment]
@jibsheet remind me how I build from scratch, please.

**Comment by jibsheet** [comment]
@clintonb https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist step 2b shows you how to get a base AMI (substitute 16.04 for 12.04) and then run alton with "using ami-foo" on the end.

I'd also love to do an edxapp AMI build since it's the weirdest one (and pulls themes).

**Comment by clintonb** [comment]
Build from scratch succeeded for credentials: ami-115eaf07 for stage edx credentials

```
@alton cut ami for stage-edx-edxapp from prod-edx-edxapp with credentials_version=master configuration=clintonb/shallow-clone configuration_secure=master using ami-46ab4850
```

**Comment by clintonb** [comment]
FYI @rlucioni

**Comment by rlucioni** [comment]
Awesome. See related: https://github.com/edx/devstack/pull/43.

**Comment by clintonb** [comment]
@edx/devops are we good to merge?

**Comment by feanil** [comment]
I've been having trouble getting this tested on sandboxes, but I'm still trying to test this there.

**Comment by clintonb** [comment]
@feanil Acknowledged. Let me know if there is anything I can do to help debug.

**Review by feanil — APPROVED** [review]

**Comment by feanil** [comment]
Sandbox build and sandbox build from scratch succeeded.

**Comment by nedbat** [comment]
We had to undo this change for Ficus.  If you use `depth: 1`, and specify a tag for `version`, it will fail.  I wrote an Ansible bug for it: https://github.com/ansible/ansible/issues/21316.

So we should discuss what to do about this for the future. This will be a problem when it comes time to create Ginkgo releases.  Options include:
1. Don't use depth=1 ever.
2. Use depth=1 conditionally based on something (not sure what, maybe an explicit option?)
3. Hope that ansible fixes the problem in time.
4. Patch the git module ourselves (we've done this before) while we wait for the ansible fix.

If this needs a bigger discussion, we can move it someplace besides this pull request.

**Comment by rlucioni** [comment]
@nedbat just to make sure I understand, it fails because the tag isn't available in the `depth: 1` checkout?

**Comment by nedbat** [comment]
Right.  The same thing happens with raw git:
```
$ git clone --depth=1 git@github.com:edx/ecommerce
Cloning into 'ecommerce'...
remote: Counting objects: 1367, done.
remote: Compressing objects: 100% (1034/1034), done.
remote: Total 1367 (delta 284), reused 833 (delta 219), pack-reused 0
Receiving objects: 100% (1367/1367), 1.53 MiB | 0 bytes/s, done.
Resolving deltas: 100% (284/284), done.
Checking connectivity... done.
$ cd ecommerce/
$ git checkout open-release/ficus.1rc4
error: pathspec 'open-release/ficus.1rc4' did not match any file(s) known to git.
```
Raw git also fails with a branch:
```
$ git checkout open-release/ficus.master
error: pathspec 'open-release/ficus.master' did not match any file(s) known to git.
```
but the Ansible module can handle the branch case, not the tag case.

**Comment by nedbat** [comment]
Ansible now has a fix: https://github.com/ansible/ansible/pull/21712 which we should test, and then track for an Ansible release to upgrade to.

**Comment by nedbat** [comment]
I've tried the fix, it does what it says. We need to track what Ansible release it gets into.

**Pull request merged**
