### PR TITLE
Killing celery processes shouldn't depend on being interactive

### PR DESCRIPTION
**Pull request by nedbat**

### CODE REVIEW

**Comment by nedbat** [comment]
@feanil The old code only killed celery processes if it was run interactively, which seems wrong.  I made it run all the time, was it supposed to only be run if the target is cypress?

**Comment by feanil** [comment]
@nedbat this was written as a workaround to a bug in the version of celery in Birch.  That version specifically got into a state where it was stuck running but not picking up any work and wouldn't restart.  So in cypress we wanted to actually re-start it after we upgraded it.

**Comment by nedbat** [comment]
OK, adjusted to be conditional on cypress.  Look OK @feanil ?

**Comment by feanil** [comment]
:+1:

**Pull request merged**
