### PR TITLE
Setting sql_mode for IDAs to prevent data loss

### PR DESCRIPTION
**Pull request by clintonb**
This setting ensures truncation warnings are escalated as errors. See https://docs.djangoproject.com/en/1.10/ref/databases/#mysql-sql-mode for additional info.

### CODE REVIEW

**Comment by clintonb** [comment]
@edx/devops @edx/learner please review

FYI @edx/platform-team @edx/analytics you'll want to do the same for other services.

**Review by feanil — APPROVED** [review]

**Comment by feanil** [comment]
@doctoryes something like this should also be done for edx-platform as well.  Can you or someone from the platform team put in a PR?

**Comment by doctoryes** [comment]
@feanil Will do.

**Comment by doctoryes** [comment]
https://openedx.atlassian.net/browse/PLAT-1781 was created to convert edxapp.

**Pull request merged**
