### PR TITLE
Add configuration for extra middleware classes

### PR DESCRIPTION
**Pull request by haikuginger**
Contains configuration changes necessary for changing setting added in edx/edx-platform#16108.

---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [x] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @haikuginger! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fconfiguration&number=4112"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Review by feanil — APPROVED** [review]

**Review by UmanShahzad — APPROVED** [review]
:+1:

- [x] I tested this: Ran the changes on a fresh VM and saw the variable available for configuration
- [x] I read through the code
- [x] I checked for accessibility issues
- [x] Includes documentation

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @haikuginger! I've created [OSPR-1939](https://openedx.atlassian.net/browse/OSPR-1939) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by haikuginger** [comment]
@feanil, can you confirm we're still good to go? I assume you knew this was an OSPR before I created the ticket, but I wanted to double-check.

**Comment by openedx-webhooks** [comment]
@haikuginger 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4112&entry.1484655318=https://github.com/haikuginger&entry.752974735=2017-09-26+20:49&entry.1917517419=2017-10-03+15:29&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
