### PR TITLE
Add and rearrange ecommerce settings.

### PR DESCRIPTION
**Pull request by feanil**
@rlucioni FYI

### CODE REVIEW

**Comment by rlucioni** [comment]
Looks good to me. Are database settings like `ATOMIC_REQUESTS` and `CONN_MAX_AGE` only configured in the secure repo?

**Comment by feanil** [comment]
They are set in secure, but I should update the defaults as well.

**Comment by rlucioni** [comment]
Nice. :+1:

**Comment by maxrothman** [comment]
:+1:

**Pull request merged**
