### PR TITLE
Add ansible install log

### PR DESCRIPTION
**Pull request by xionglun**
I think it good for us to have an install log.
A log file can record install failed tasks, it's helpful to track where the problem is.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @xionglun! I've created [OSPR-539](https://openedx.atlassian.net/browse/OSPR-539) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams. 

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ('this must be merged by XX date', and why that is)
- partner information ('this is a course on edx.org')
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the Github pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

We can't start reviewing your pull request until you've submitted a [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf) or indicated your institutional affiliation and added yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS) file. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst) file for more information.

**Comment by sarina** [comment]
@xionglun thanks for the contribution! As the bot mentions, we can't move forward with review until we get your contributor's agreement & you add yourself to AUTHORS. Let me know if you have any questions.

**Comment by sarina** [comment]
@xionglun we got your agreement, thanks for that! I put this in the Devops team backlog to review.

**Comment by feanil** [comment]
Hi @xionglun Thanks for the contribution but I do not think we'll be able to accept it.  While it is nice to have logs for some of the ansible runs we have, I think it's dangerous to have a default logging location.  Part of the reason for this is because if you run ansible in verbose mode you are likely to log various credentials into the log file.  Many of our ansible runs do get piped to log files but it is usually done explicitly so we know when we have to clean up those logs and when we don't.

**Pull request closed without merging**
