### PR TITLE
Allow installing ecommerce from the custom repo.

### PR DESCRIPTION
**Pull request by jghyllebert**
This PR makes it easier to configure the ecommerce git repo.

**Dependencies**: None

**Merge deadline**: 
None

**Testing instructions**:

1. Deploy a server
2. Change the upstream git repository folder 

**Reviewers**
- [ ] @kaizoku
- [ ] edX reviewer[s] TBD

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @jghyllebert! I've created [OSPR-2772](https://openedx.atlassian.net/browse/OSPR-2772) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@jghyllebert Thank you for your contribution! @edx/devops  Can you have a look at this?

**Comment by kaizoku** [comment]
:+1:

- [✓] I tested this: (deployed edX instances using this commit)
- [✓] I read through the code
~- [n/a] I checked for accessibility issues~
~- [n/a] Includes documentation~

**Comment by natabene** [comment]
@edx/ecommerce  , @robrap  Can you have a look at this before devops do?

**Comment by kaizoku** [comment]
I just realized this wasn't using the variables for ecommerce version or the SSH key.
I pushed another commit with those changes, and I can squash commits if we get the a-okay from review.

**Comment by kaizoku** [comment]
@robrap @edx/ecommerce, have you had a chance to look at this one yet?

**Comment by robrap** [comment]
@kaizoku: I think our devops team will need to review. I think it may have gotten missed, so I'll see if I can get you a reviewer.  Thanks.

**Review by feanil — APPROVED** [review]

**Review by coryleeio — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@jghyllebert 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4863&entry.1484655318=https://github.com/jghyllebert&entry.752974735=2018-11-02+23:18&entry.1917517419=2019-01-28+16:07&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
