### PR TITLE
Install normal (not tiny) vim

### PR DESCRIPTION
**Pull request by nedbat**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

### CODE REVIEW

**Comment by nedbat** [comment]
@edx/devops an improvement!

**Comment by nedbat** [comment]
I don't understand why the tests failed....

**Comment by coryleeio** [comment]
At a glance, I don't see exactly why this failed.  I bet you it's something being dependent on curl.  I would put curl back, see if it passes with just the vim change.  I would love to merge that.

**Review by feanil — APPROVED** [review]

**Comment by nedbat** [comment]
@coryleeio I didn't remove curl, I removed the duplicate entry for curl.  Surely we don't need to install it twice? :)

**Comment by coryleeio** [comment]
Ha, I missed that.  Still though, you never know... ;)

**Pull request merged**
