### PR TITLE
Preparation for Ficus devstack release

### PR DESCRIPTION
**Pull request by gsong**
@edx/devops @nedbat 

* Pin Firefox to v45 to prevent accidental upgrades
* Update Vagrant requirement
* Update releases map

Make sure that the following steps are done before merging

- [x] Base box built successfully
- [x] Release box built successfully
- [x] Paver test executed successfully
- [ ] @devops team member has commented with :+1:

### CODE REVIEW

**Comment by gsong** [comment]
Using Vagrant 1.9.1 and VirtualBox 5.1.10, and the [public instructions](http://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/installation/devstack/install_devstack.html):

* Guest box built successfully on OS X 10.11.6
* Guest box built with sporadic results on macOS 10.12.2 due to [Sierra nfsd bug](https://github.com/mitchellh/vagrant/issues/8061)
* `paver test` [exhibit the same two errors](https://github.com/edx/configuration/pull/3557#issuecomment-267174761) as before, @benpatterson @nasthagiri.
* `paver test_bokchoy` [exhibits the same hanging behavior](https://github.com/edx/configuration/pull/3525#issuecomment-265496859) as before, @nedbat @benpatterson.

**Comment by benpatterson** [comment]
re: bokchoy... my question goes out to Ned on whether or not that's been an issue in the past.
re: `paver test`... I couldn't give you much assistance at this point. It's not an area of code I'm familiar with. I'm hoping Nimisha can give context. If she can't, we could get Cale's opinion, too.

**Comment by gsong** [comment]
@nedbat @benpatterson Here’s more info:

* When running as part of the entire `paver test` suite, the two tests still error out.
* For `test_provider_login_can_handle_unicode_email_inactive_account`, invoking the specific test module via `paver test_system -t openedx/core/djangoapps/external_auth/tests/test_openid_provider.py` succeeds.
* For `capa.safe_exec.tests.test_safe_exec.TestRealProblems`, invoking the specific test module via `paver test_system -t common/lib/capa/capa/safe_exec/tests/test_safe_exec.py` will produce the same error.

**Review by nedbat — APPROVED** [review]
This will all be examined again when we merge into master, BTW.

**Pull request merged**
