### PR TITLE
Deploy edx-themes:master instead of edx-themes:release

### PR DESCRIPTION
**Pull request by douglashall**
We want the release pipelines to deploy edx-themes:master to avoid
the additional step of merging edx-themes:master to edx-themes:release
in order to deploy changes to edx-themes.

WL-1018

Configuration Pull Request
---

Make sure that the following steps are done before merging

  - [ ] A devops team member has commented with :+1:
  - [ ] are you adding any new default values that need to be overridden when this goes live?
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

### CODE REVIEW

**Comment by douglashall** [comment]
@fredsmith Is this all we need to do to get the release pipelines (edxapp and ecommerce) to build AMIs with the master branch of edx-themes instead of the release branch?

**Comment by e0d** [comment]
@douglashall I assume this has been socialized broadly with the affected teams?

**Comment by douglashall** [comment]
@e0d Up to this point, contributions to this repository have almost entirely come from WL/Solutions. I'm attempting to preemptively avoid friction as other teams begin contributing. I think the step of merging master to release is not something other teams would expect when trying to get their changes deployed.

**Review by fredsmith — APPROVED** [review]

**Comment by douglashall** [comment]
@fredsmith This change does not seem to have had an effect on the edx-themes branch that is used to build AMIs in the release pipelines. Can you help me debug?

**Pull request merged**
