### PR TITLE
Some fixes required for mongodb to be deployed

### PR DESCRIPTION
**Pull request by fredsmith**

### CODE REVIEW

**Comment by feanil** [comment]
:+1:

**Comment by carsongee** [comment]
Why are we switching to  a string instead of copying a file?

**Comment by fredsmith** [comment]
@carsongee as I understand it, the {{ secure_dir }}/files/ directory isn't used by any other ansible code anymore, and all the other recipes embed keys in a variable in the secure-vars file.  if it's problematic for you, I think I can work logic into the deployment steps to use either the variable or the file.

**Comment by carsongee** [comment]
I guess I missed that decision though I have been feeling the effects of it.  I'll change, no biggie, just makes for uglier var include files with all these big keys in them.

**Pull request merged**
