### PR TITLE
Fix issue with `SameSite=None` cookies from being blocked when `django_cookies_samesite.middleware.CookiesSameSite` is enabled for `production` environment.

### PR DESCRIPTION
**Pull request by ztraboo**
This is a fix for `production` default value set to `Lax` for `DCS_SESSION_COOKIE_SAMESITE`. It was defaulting to `SameSite=None` which requires a secure site which `localhost` site does not by default.

Setting this `SameSite` cookie attribute to something other than `None` will continue to allow login to the LMS for `production` environment.

Regards to https://github.com/edx/edx-platform/pull/23671 and https://discuss.openedx.org/t/lti-xblock-and-samesite/759/16

Regards to https://github.com/edx/edx-platform/pull/24593

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ztraboo! I've created [OSPR-5005](https://openedx.atlassian.net/browse/OSPR-5005) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@ztraboo Thank you for your contribution. Is this ready for our review?

**Comment by ztraboo** [comment]
@natabene Ready for review.

**Comment by ztraboo** [comment]
@fredsmith These are the same changes that I did for `master` branch here https://github.com/edx/configuration/pull/6043 for the `open-release/juniper.master`. Can you review this too? 

cc: @natabene

**Comment by openedx-webhooks** [comment]
@ztraboo 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6044&entry.1484655318=https://github.com/ztraboo&entry.752974735=2020-09-24+22:08&entry.1917517419=2020-11-10+20:12&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
