### PR TITLE
EDXAPP_DJFS needs to be in YAML style?

### PR DESCRIPTION
**Pull request by usernamenumber**
Perhaps I'm just misunderstanding something, but the bash-style variable here appears to be incorrect, and it definitely caused an error for me, which went away after applying this change. See [this comment](https://github.com/edx/configuration/commit/96223cf48ad5abe4c8e477b1e76172af46d19966#commitcomment-9096894) for details on the error.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @usernamenumber! I've created [OSPR-327](https://openedx.atlassian.net/browse/OSPR-327) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams. 

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ('this must be merged by XX date', and why that is)
- partner information ('this is a course on edx.org')
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the Github pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

We can't start reviewing your pull request until you've added yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS) file. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst) file for more information.

**Comment by e0d** [comment]
The $ variable is an ansible variable that is supported in the version we specify in requirements.txt.  What version of ansible were you testing with?  

We have plan to upgrade ansible, but there are some breaking changes in the new version that we need to navigate.

**Comment by usernamenumber** [comment]
Ah, thanks for the clarification. I'm currently running 1.8.2, but it's possible I've upgraded since my last attempt, and unfortunately I don't have everything I would need to try again right now.

**Comment by e0d** [comment]
Yeah, unfortunately we are stuck on 1.5.5 until we can resolve some issues.  Either in our code or by getting this, http://github.com/ansible/ansible/issues/9362, fixed.

I'm going to close this as we will be removing all $vars via a separate effort.

**Pull request closed without merging**
