### PR TITLE
Remove `edx-west` directory

### PR DESCRIPTION
**Pull request by stvstnfrd**
This directory was used for Stanford's plays. While it made sense at the
time, it should no longer be neccessary to store this upstream, given
that we maintain an in-house fork/repository anyway.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @stvstnfrd! I've created [OSPR-856](https://openedx.atlassian.net/browse/OSPR-856) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).
We can't start reviewing your pull request until you've   added yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS) file . Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst) file for more information.

**Comment by stvstnfrd** [comment]
I had originally postponed this deletion until we had caught up with
merging `upstream/master`. Even though we haven't done that yet, I don't
see why this needs delayed further.

When the time comes, we'll pull some git-fu to make things jibe;
perhaps as easy as `git mv edx-west stanford`.

Am I overlooking any here, @caesar2164 @dcadams @kluo ?

**Comment by e0d** [comment]
:+1:
@edx/devops  second review?

**Comment by jibsheet** [comment]
:+1:

**Comment by e0d** [comment]
@stvstnfrd thanks for this.

**Pull request merged**
