### PR TITLE
Jarv/fabric for deploys

### PR DESCRIPTION
**Pull request by jarv**

### CODE REVIEW

**Comment by jbau** [comment]
i think you need to rebase this one first.

**Comment by jbau** [comment]
I will merge this branch, jarv/fab-new-requirements, and master and run on our servers, and report back

**Comment by jarv** [comment]
done

**Comment by jbau** [comment]
This ran fine for me last night, so I think it's good to merge.

A couple of questions tho:
1. I didn't notice this bouncing gunicorn and nginx, is that correct?  I just manually ran fab afterwards to do so
2. Does this set permisons on /opt/wwc/edx-platform to www-data:www-data recursively?  If so, I am wondering if you guys ever rake gather_assets manually on the instance?  Because those perms make it difficult.

**Comment by jarv** [comment]
# 1

In package_data.yaml we do this, which will stop edxapp service before the repo checkout which is an upstart job that has the lms, lm-xml(for us), cms, and lms-preview as its children:

```
+      if [[ -n $edxapp_status ]]; then
+        if [[ $edxapp_status == *running* ]]; then
+          service edxapp stop;
+        fi
+      fi
+      if [[ -n $edx_workers_status ]]; then
+        if [[ $edx_workers_status == *running* ]]; then
+          service edx-workers stop;
+        fi
+      fi
```

and the in the post_repo_checkout block:

```
+      if [[ -n $edxapp_status ]]; then
+        if [[ $edxapp_status == *stop* ]]; then
+          service edxapp start;
+        fi
+      fi
+      if [[ -n $edx_workers_status ]]; then
+        if [[ $edx_workers_status == *stop* ]]; then
+          service edx-workers start;
+        fi
+      fi
```

Here is what the upstart script for edxapp looks like:

```
#/etc/init/edxapp.conf

description "Starts and stops multiple edX services, e.g., lms, cms, etc., installed in a stacked configuration."

start on runlevel [2345]
stop on runlevel [!2345]

##
## Each awaited service is responsible for ensuring that it is ready
## for service when it returns.
##
pre-start script

if [ -e /etc/init/lms-xml.conf ]; then
  start wait-for-state WAIT_FOR=lms-xml WAITER=$UPSTART_JOB
fi

if [ -e /etc/init/lms.conf ]; then
  start wait-for-state WAIT_FOR=lms WAITER=$UPSTART_JOB
fi

if [ -e /etc/init/lms-preview.conf ]; then
  start wait-for-state WAIT_FOR=lms-preview WAITER=$UPSTART_JOB
fi

if [ -e /etc/init/cms.conf ]; then
  start wait-for-state WAIT_FOR=cms WAITER=$UPSTART_JOB
fi

end script

script
  # Noop process for other edX components to take their
  # marching orders from.  In the edxapp deployment, 
  # lms, cms, etc. will listen for this process to start
  # and stop and follow suit.
  while true
    do
      logger -t $0 "edX App Shell Daemon is running..."
      sleep 600
    done
end script

pre-stop script

if [ -e /etc/init/lms-xml.conf ]; then
  start wait-for-state WAIT_FOR=lms-xml WAITER=$UPSTART_JOB TARGET_GOAL="stop"
fi

if [ -e /etc/init/lms.conf ]; then
  start wait-for-state WAIT_FOR=lms WAITER=$UPSTART_JOB TARGET_GOAL="stop"
fi

if [ -e /etc/init/lms-preview.conf ]; then
  start wait-for-state WAIT_FOR=lms-preview WAITER=$UPSTART_JOB TARGET_GOAL="stop"
fi

if [ -e /etc/init/cms.conf ]; then
  start wait-for-state WAIT_FOR=cms WAITER=$UPSTART_JOB TARGET_GOAL="stop"
fi

end script

```

# 2

I'm not happy that we are changing permissions like this.  Best security practices would have ownership set to root (or ideally another user) and the read access for the www-data group.
Whenever we run commands we generally do them as www-data, for django-admin commands we will do something like:
`sudo -u www-data SERVICE_VARIANT=lms /opt/edx/bin/django-admin.py ...`

**Comment by jbau** [comment]
right.  i'd see edxapp before and should have noticed its purpose here. my bad.  I will add it back into ansible.  But it looks like you are not restarting nginx then?

Also, go ahead and merge when ready.

**Comment by jarv** [comment]
Right, our deploy logic never will force an nginx restart.

**Pull request merged**
