### PR TITLE
[BD-6] Bootstrap ansible virtualenv with python3.5

### PR DESCRIPTION
**Pull request by morenol**
Use python3.5 to bootstrap ansible.

## Reviewers
- [ ] @awais786

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @morenol! I've created [BLENDED-451](https://openedx.atlassian.net/browse/BLENDED-451) to keep track of it in Jira.  More details are on the [BD-06](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1594000004/BD-06+Python+3.8+Upgrade) project page.

When this pull request is ready, tag your edX technical lead.

**Comment by morenol** [comment]
I am testing this changes running `make docker.build.xenial-common` and `make docker.build.bionic-common`

**Review by feanil — APPROVED** [review]
I tested by running ```docker run -v `pwd`:/repo -it ubuntu:xenial /bin/bash``` in the configuration repo and then running the script directly in the container.  It worked fine for me I did have to remove the `sudo` from line 96 because it wasn't installed at the beginning of the script run but that's unrelated to your changes.

@jmbowman I'll leave merging to you in case you want to do a second review.

**Review by jmbowman — APPROVED** [review]
Looks good to me also.  @awais786 , could someone from your team try building a sandbox using this and make sure that doesn't hit any unexpected problems?  If that goes well, we should be ok to merge this (near the beginning of a work day so people are around when the first deployments go out using it).

**Comment by awais786** [comment]
@jmbowman 
Tried to create sandbox form 3 users with these config values and all failed.
```
configuration_version	        lmm/ansible_bootstrap_py35
configuration_source_repo	https://github.com/eduNEXT/configuration.git
```

[Nadeem Shahzad ](https://tools-edx-jenkins.edx.org/job/sandboxes/job/CreateSandbox/31296/console)
[Arif](https://tools-edx-jenkins.edx.org/job/sandboxes/job/CreateSandbox/31301/consoleFull)
[Awais ](https://tools-edx-jenkins.edx.org/job/sandboxes/job/CreateSandbox/31298/console)

All give similar error
```
10:26:31     "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error",
10:26:31     "rc": 127
10:26:31 }
10:26:31 	to retry, use: --limit @/edx/var/jenkins/jobs/Sandboxes/jobs/CreateSandbox/workspace@3/configuration/playbooks/edx_provision.retry
10:26:31 
10:26:31 PLAY RECAP *********************************************************************
10:26:31 127.0.0.1                  : ok=9    changed=5    unreachable=0    failed=0   
10:26:31 52.87.254.38               : ok=0    changed=0    unreachable=0    failed=1   
10:26:31 
10:26:32 + ret=2
10:26:32 + [[ 2 -ne 0 ]]
10:26:32 + exit 2
10:26:32 Build step 'Virtualenv Builder' marked build as failure
10:26:32 Set build name.
10:26:32 New build name is '#31301 mraarif py35configuration2'
10:26:32 Variable with name 'BUILD_DISPLAY_NAME' already exists, current value: '#31301 mraarif py35configuration2', new value: '#31301 mraarif py35configuration2'
10:26:32 [ssh-agent] Stopped.
10:26:32 Finished: FAILURE
```

**Comment by awais786** [comment]
@jmbowman  I created my own branch using `eduNext` code in this [PR](https://github.com/edx/configuration/pull/5888)  and tried building a new [sandbox](https://tools-edx-jenkins.edx.org/job/sandboxes/job/CreateSandbox/31300/console) with this branch and it failed also.

```
11:03:51 TASK [jwt_signature : create JWT signature settings] ***************************
11:03:59 changed: [awais786.sandbox.edx.org]
11:03:59 ERROR! Unexpected Exception, this is probably a bug: cannot import name 'is_subpath'
11:03:59 to see the full traceback, use -vvv
11:03:59 + ret=250
11:03:59 + [[ 250 -ne 0 ]]
11:03:59 + exit 250
11:03:59 Build step 'Virtualenv Builder' marked build as failure
11:03:59 Set build name.
11:03:59 New build name is '#31300 awais786 '
11:03:59 Variable with name 'BUILD_DISPLAY_NAME' already exists, current value: '#31300 awais786 ', new value: '#31300 awais786 '
11:03:59 [ssh-agent] Stopped.
11:03:59 Finished: FAILURE
```

**Comment by awais786** [comment]
@morenol FYI

**Comment by awais786** [comment]
Now I am building sandbox with default params just to make sure its running fine. Will update soon.

With default setting its working fine. So issue is coming with this PR.
https://tools-edx-jenkins.edx.org/job/sandboxes/job/CreateSandbox/31305/console

**Comment by morenol** [comment]
@awais786 as far as I can see, ansible_bootstrap is downloaded from edX repo: 

https://github.com/edx/configuration/blob/958ed3b1fda3c7d5ac4693059d60e2ff3558161c/playbooks/edx_provision.yml#L31

So, I will try to identify the error in your second comment. 

Could you try again to do that running that with -vvv?

https://github.com/ansible/ansible/blob/1fb35cd857b59fb07f0201abe021092a508b3efc/bin/ansible#L155

**Comment by awais786** [comment]
@morenol sandbox works this time using my branch `chery-pic-edunext-pr`. I have rebased my branch first.
https://tools-edx-jenkins.edx.org/job/sandboxes/job/CreateSandbox/31398/consoleFull

**Comment by morenol** [comment]
@awais786 perfect. Then, as Jeremy said we should be ok to merge tomorrow near the beginning of a work day.

**Pull request merged**
