### PR TITLE
replacing deploy tags with taggged include

### PR DESCRIPTION
**Pull request by jarv**

### CODE REVIEW

**Comment by carsongee** [comment]
Didn't know that trick, cool. :+1:

**Comment by jarv** [comment]
Yeah I've also seen the pattern where in `main.yml` you have a single include

```
---
include <role>.yml tags=<role>
```

Which automatically tags every task in the role with the name of the role.

**Comment by carsongee** [comment]
That is a cool pattern, can you do it with roles too? so something like:

``` yaml
- {role: edxapp, tags: edxapp }
```

so you can run specific roles of a play with tags instead of messy per task tags or having lots of plays?  I know that works with when:

**Comment by jarv** [comment]
yeah you can do that as well at the play level. The only caveat is is that I don't believe the dependencies will be run since they won't have the tag.

**Comment by e0d** [comment]
:+1:

**Comment by feanil** [comment]
looks good to me.

**Pull request merged**
