### PR TITLE
allow ansible to be pulled from a private repo

### PR DESCRIPTION
**Pull request by trungpham**

### CODE REVIEW

**Comment by feanil** [comment]
@e0d this seems good, but I seem to remember you mentioning a better way to deal with checking out private repositories, can you provide details here or review the changes made by @trungpham

**Comment by e0d** [comment]
Missed this PR, @feanil did you test this when you originally reviewed it?

**Comment by feanil** [comment]
I believe so but I'll do it again just to be sure.

**Comment by feanil** [comment]
Looks like this also needs a rebase as well @trungpham

**Comment by hkim823** [comment]
One thing that this PR doesn't take into account is changing repos all together, say you were working in the edX/platform repo and then wanted to checkout trungpham/edx-platform, from what I can tell these changes will fail because the directory already exists and the git module cannot do a checkout of a fork it doesn't know about.

**Comment by feanil** [comment]
@hkim823 I think that is a known issue in the way we do this in all our roles right now.  This just allows you to provide private sources of the ansible repo in the way we do in some of the other roles.

@trungpham Closing this since we haven't heard back from you in a while.

**Comment by trungpham** [comment]
I couldn't figure out how to reopen this PR after rebasing. So I created a new PR #1697.

**Pull request closed without merging**
