### PR TITLE
Update main.yml

### PR DESCRIPTION
**Pull request by lvnilesh**
Change custom theme related variables to ALL-CAPS, since they are meant to be externally overridden

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @lvnilesh! I've created [OSPR-383](https://openedx.atlassian.net/browse/OSPR-383) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams. 

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ('this must be merged by XX date', and why that is)
- partner information ('this is a course on edx.org')
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the Github pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

We can't start reviewing your pull request until you've submitted a [signed contributor agreement](http://code.edx.org/individual-contributor-agreement.pdf) or indicated your institutional affiliation and added yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS) file. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst) file for more information.

**Comment by sarina** [comment]
We have received your contributor's agreement. This is waiting now for review from our Devops team.

**Comment by feanil** [comment]
@lvnilesh can we do this in a backwards compatible way for now and then clean it up later?  Leave the old vars in, and add the new vars to refer to the values of the old vars.  Then use the new vars in tasks and templates(which you are not doing yet).  Let me know if you need more info.

**Comment by lvnilesh** [comment]
ok

**Comment by sarina** [comment]
@lvnilesh do you intend on completing this work? If not, kindly close the pull request and reopen it when you are ready to address feedback.

If you have questions, please ask them here.

**Comment by openedx-webhooks** [comment]
Hello @lvnilesh: We are unable to continue with review of your submission at this time. Please see the associated JIRA ticket for more explanation.

**Pull request closed without merging**
