### PR TITLE
default the small bulk email jobs to be sent through the low priority…

### PR DESCRIPTION
**Pull request by adampalay**
… queue

Configuration Pull Request
---
Sets the default value for this queue to be the low priority queue.

Make sure that the following steps are done before merging:

  - [x] A DevOps team member has approved the PR. ( @fredsmith )
  - [x] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [x] ~Update the appropriate internal repo (be sure to update for all our environments)~ (**N/A**)
    - [x] ~If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.~ (**N/A**)
    - [x] Add an entry to the CHANGELOG.
  - [x] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

Building a sandbox off this branch: https://tools-edx-jenkins.edx.org/job/Sandboxes/job/CreateSandbox/1707/parameters/

### CODE REVIEW

**Review by fredsmith — APPROVED** [review]

**Comment by adampalay** [comment]
will merge once I verify that my sandbox was created correctly

**Comment by adampalay** [comment]
@fredsmith , I'm not sure why the check is failing. It looks like the error has something to do with docker? but my change doesn't touch docker

**Comment by adampalay** [comment]
rebased off https://github.com/edx/configuration/pull/3936; hopefully that will fix the failure!

**Comment by adampalay** [comment]
Also, this set the value correctly on my sandbox, so will merge once the check passes

**Pull request merged**
