### PR TITLE
Upgraded browsers for Trusty servers

### PR DESCRIPTION
**Pull request by clintonb**
Firefox: 45.0.2
Chrome: 59.0.3071.115

LEARNER-509

### CODE REVIEW

**Comment by clintonb** [comment]
FYI @edx/devops @edx/educator-devs

**Review by feanil — APPROVED** [review]
Looks good to me assuming ORA2 team is good with it.

**Comment by clintonb** [comment]
I have confirmed the team is not using Chrome, and has tested with Firefox 45 in the past.

**Comment by clintonb** [comment]
@edx/devops I would like to get the new .deb file uploaded before merging this. See https://openedx.atlassian.net/browse/DEVOPS-6154 for a link to the file.

**Pull request merged**
