### PR TITLE
Changing out dollar vars for {{

### PR DESCRIPTION
**Pull request by hkim823**

### CODE REVIEW

**Comment by jarv** [comment]
can you run this branch on continuous integration and grep through the json files to ensure there are no `$` signs in them?

**Comment by hkim823** [comment]
@jarv that was my plan, i'm starting on devstack first

**Comment by feanil** [comment]
@hkim823 can you rebase this now the my edxapp change has merged to pick that up as well

**Comment by hkim823** [comment]
git commits are starting to get messy, closing this will re-open

**Pull request closed without merging**
