### PR TITLE
Fix for browsermob proxy

### PR DESCRIPTION
**Pull request by mulby**
@feanil @e0d 

This is split out from the analytics devstack PR

### CODE REVIEW

**Comment by feanil** [comment]
:+1:

**Comment by e0d** [comment]
I'm  :+1: 

@jzoldak or @benpatterson can one of you weigh in

**Comment by mulby** [comment]
some context for testeng, it looks like the S3 link to this file is now dead, causing "from scratch" devstack builds to fail

I couldn't find that exact zip file anywhere, but github does host the stable 2.0.0 release which I'm hoping is sufficiently close to the beta-9 release.

**Comment by jzoldak** [comment]
:+1:

**Pull request merged**
