### PR TITLE
Updated the JWT ISSUERS list to correct formatting

### PR DESCRIPTION
**Pull request by staubina**
Configuration Pull Request
---

This PR corrects a configuration issue on the Docker devstack that is not present in Production.

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.

### CODE REVIEW

**Review by clintonb — APPROVED** [review]

**Comment by staubina** [comment]
@clintonb Please take a look and let me know if this is how the devstack_worker should look.

@feanil Who on the devops team should I ask to review this change?

**Comment by staubina** [comment]
@edx/devops Please review when you have a moment.

**Review by fredsmith — CHANGES_REQUESTED** [review]
- Please add a changelog entry.
 - Please make sure you update https://github.com/edx/edx-internal/blob/master/ansible/vars/edx.yml#L795

**Comment by staubina** [comment]
@fredsmith https://github.com/edx/edx-internal/pull/251

**Pull request closed without merging**
