### PR TITLE
Passing the var

### PR DESCRIPTION
**Pull request by e0d**

### CODE REVIEW

**Comment by jibsheet** [comment]
If this works on sandboxes, I definitely prefer it 👍

**Comment by e0d** [comment]
This seems to do the trick, building from scratch once more to confirm.  Some more investigation into the precedence issues and circular dependencies between var definitions is required.

http://jenkins.edx.org:8080/job/ansible-provision/8168/console

Here's an example of the sweet failure mode

```
22:30:33 TASK: [vhost | Create all service directories] ******************************** 
22:30:34 changed: [54.226.10.149] => (item={'key': 'home', 'value': {'owner': 'root', 'path': u'/edx/app/aws', 'group': 'root', 'mode': '0755'}})
22:30:35 changed: [54.226.10.149] => (item={'key': 'data', 'value': {'owner': 'root', 'path': u'/edx/var/aws', 'group': 'root', 'mode': '0700'}})
22:30:36 changed: [54.226.10.149] => (item={'key': 'logs', 'value': {'owner': 'syslog', 'path': u'/edx/var/log/aws', 'group': 'syslog', 'mode': '0650'}})
22:30:36 
---snip---
22:31:02 TASK: [aws | Create s3 log sync script] *************************************** 
22:31:03 failed: [54.226.10.149] => {"failed": true}
22:31:03 msg: Destination directory /edx/app/vhost does not exist
22:31:03 
22:31:03 FATAL: all hosts have already failed -- aborting
```

Where the task is

```
- name: Create s3 log sync script
  template:
    dest: "{{ aws_s3_sync_script }}"
    src: send-logs-to-s3.j2
    mode: 0755
    owner: root
    group: root
  when: COMMON_OBJECT_STORE_LOG_SYNC
```

And the dest var is 

```
aws_s3_sync_script: "{{ vhost_dirs.home.path }}/send-logs-to-s3"
```

And the task from vhosts

```
- name: Create all service directories
  file:
    path: "{{ item.value.path }}"
    state: directory
    owner: "{{ item.value.owner }}"
    group: "{{ item.value.group }}"
    mode: "{{ item.value.mode }}"
  with_dict: "{{ vhost_dirs }}"
```

**Comment by e0d** [comment]
@jibsheet @bradenmacdonald from scratch build has gotten past the error.

**Comment by e0d** [comment]
Note that the original error was

```
14:37:02 TASK: [aws | Create s3 log sync script] *************************************** 
14:37:03 failed: [54.242.240.229] => {"failed": true}
14:37:03 msg: Destination directory /edx/app/aws does not exist
14:37:03 
14:37:03 FATAL: all hosts have already failed -- aborting
```

**Comment by bradenmacdonald** [comment]
FYI: I provisioned an OpenStack instance with b84a26e (2nd latest commit), which worked fine, but I realized the playbook never includes the `openstack` role. So after it finished provisioning, I pulled 2a89908 ("Comments, plus fixing openstack role") and ran that with "ansible-playbook ./run_role.yml" which worked fine, and created `/edx/app/openstack/`, `/edx/var/openstack/` etc. Now I'm trying one more provision from scratch with a playbook that includes the OpenStack role.

**Comment by e0d** [comment]
I have a successful build from scratch http://jenkins.edx.org:8080/job/ansible-provision/8171/

NPM issues caused other failures in the builds from last night.

**Comment by e0d** [comment]
@pwnage101 when this merges the issue you're seeing will be resolved, hopefully later today.

**Comment by bradenmacdonald** [comment]
@e0d My from-scratch OpenStack build was successful too and has `/edx/app/openstack/` etc.

**Comment by e0d** [comment]
I'm going to merge this to unblock various things. @edx/devops

**Comment by jibsheet** [comment]
👍

**Pull request merged**
