### PR TITLE
Make devpi optional

### PR DESCRIPTION
**Pull request by tusbar**
To enable, set the `devpi_enabled` variable to `"yes"`.
The vagrant devstack installs devpi by default.

### CODE REVIEW

**Comment by tusbar** [comment]
I’m not sure if it needs to be enabled in other playbooks (edx-{we,ea}st).
Please let me know.

**Comment by jarv** [comment]
A few things:
(1) `edxapp_pypi_local_mirror: "http://localhost:{{ devpi_port }}/root/pypi/+simple"` is in `edxapp/defaults/main.yml` so we will need to point that to pypi as the default (assuming that devpi off is default behavior)
(2) I would set a var `edxapp_devpi_enabled` in the edxapp role, default it to false 
(3) Assuming (2) you just need to do a `when: edxapp_devpi_enabled`

**Comment by tusbar** [comment]
Sorry for the delays, I’ll work on this ASAP.

I was wondering, why do you sometimes use booleans and strings ("yes" when enabled)? What’s best to use?

**Comment by tusbar** [comment]
@jarv I’ve updated this. Let me know what you think. :)

**Comment by hkim823** [comment]
@jarv let me know if you still want this to be merged in, seems still like a good idea

**Comment by jarv** [comment]
@hkim823 @tusbar I'm going to close this because the current code on master defaults to not using devpi (though it's still installed).

**Comment by tusbar** [comment]
@jarv, the point of this pull request was to be able to install edxapp without installing devpi, not to stop using it.

**Pull request closed without merging**
