### PR TITLE
Update the jenkins worker to use the mongo role.

### PR DESCRIPTION
**Pull request by feanil**
The common role also has to be included because vars that were previously being set in group_vars_all are now in
the slimmed down common.

Review: @wedaly @jarv

### CODE REVIEW

**Comment by jarv** [comment]
lgtm

**Comment by wedaly** [comment]
Should probably remove `mongodb` from `jenkins_worker/defaults/main.yml` so it doesn't try to install the Ubuntu system package.  Other than that, this looks good.

**Comment by feanil** [comment]
@wedaly already did that.

**Comment by wedaly** [comment]
sorry, didn't see that :)

:+1:

**Comment by feanil** [comment]
@wedaly realized that I had left the mongo conf stuff in the worker but it should not bee needed anymore so I removed it.

**Comment by wedaly** [comment]
that makes sense

**Pull request merged**
