### PR TITLE
refactor: remove obsolete CAS settings

### PR DESCRIPTION
**Pull request by pdpinch**
the CAS authentication features of edx-platform were removed in DEPR-6

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [x] ~~Are you adding any new default values that need to be overridden when this change goes live? If so:~~
    - [x] ~~Update the appropriate internal repo (be sure to update for all our environments)~~
    - [x] ~~If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.~~
    - [x] Add an entry to the CHANGELOG.
  - [x] ~~If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).~~
  - [x] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

Since this feature was removed several releases ago, there's no reason to update the wiki.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pdpinch! I've created [OSPR-5839](https://openedx.atlassian.net/browse/OSPR-5839) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@pdpinch Thank you for your contribution. Is this ready for our review?

**Comment by pdpinch** [comment]
It’s ready. Should be trivial — and not at all urgent. 

I do need to rebase, but that’s just the changelog.

**Comment by natabene** [comment]
@pdpinch Please let me know once you have rebased, and we will review and merge.

**Comment by natabene** [comment]
@pdpinch Just checking if we should still keep it open. Let me know.

**Comment by sarina** [comment]
This seems reasonable but I don't know how to validate the playbook, so I can't offer a review. But echoing Natalia, @pdpinch do you want me to find a reviewer for you?

**Comment by natabene** [comment]
@pdpinch Just checking if you are still interested in pursuing this. Let me know!

**Comment by natabene** [comment]
@pdpinch We have not heard from you in a while, so I will close this for now. Should you decide to pursue this again, please feel free to re-open.

**Comment by openedx-webhooks** [comment]
@pdpinch Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/configuration&entry.867055334=https://github.com/openedx/configuration/pull/6440&entry.1484655318=https://github.com/pdpinch&entry.752974735=2021-06-05+19:02&entry.1917517419=2022-05-19+18:54&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
