### PR TITLE
Replace mongodb_user module with javascripts

### PR DESCRIPTION
**Pull request by carsongee**
This add fullsupport of new authentication model in mongodb 2.6.

I know this isn't the most elegant fix, but using the latest module in ansible didn't work, and I was having issues modifying to work properly so I've fallen back to stripping that out and just using mongo javascripts.

I have tested this with the cluster build and devstack (including a "from scratch" on mongodb 2.6 devstack as well as an upgraded version.

One of the upshots is that it will actually work on a cluster and not fail on the slaves since the scripts check if they are master before attempting to modify anything so I removed the "create_users" flag and just run that each time.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @carsongee! I've created [OSPR-200](https://openedx.atlassian.net/browse/OSPR-200) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams. 

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ('this must be merged by XX date', and why that is)
- partner information ('this is a course on edx.org')
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the Github pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by e0d** [comment]
@carsongee I've been planning to look into this, can you characterize what the issues with the module are?

**Comment by carsongee** [comment]
Updating to the newest module (as of three weeks ago), and the latest pymongo, it would just fail to create the users (at least in the cluster/replicaset mode).  The craziest thing was when I attached a remote debugger (epdb) and stepped through line by line, it had no problem but would always fail during a real play run.  There were a couple other issues with it that I can't remember right now, but it seemed like a lot less effort to use the dropped javascript files instead of digging in further.  

There were also a couple issues in the ansible repo before they split the modules referencing some of the issues that got closed and haven't been ported, so maybe there is a combination of 1.5 and the module that are causing the issue, notably https://github.com/ansible/ansible/issues/7157.

All that said, at this point it could have been something strange in my setup alone, since it worked in the debugger.  Some extra context from when I started looking at this a couple weeks ago: https://github.com/edx/configuration/pull/1637

**Comment by e0d** [comment]
It also isn't working in a similar way in our single-instance-sandboxes, though we don't get an exception.  In fact, users are created if I log on to mongo as root from the box.  The user's are associated with the correct database.  I had debugged as well and to the point I got, things looked likel they were being done correctly.  We've been using a crappy temporary workaround, https://gist.github.com/e0d/4ce5f0de1d1fac459e75, but I had hoped to fix.  It's possible our issues is unrelated.  Do you have the error you see handy?

**Comment by carsongee** [comment]
The specific error was just in the cluster case as the single instance would just silently not work.  It says "not master and slaveOk != true" even on the master node with the latest version that theoretically supports replicaSets. This branch fixes it for all types of mongo installs and is idempotent so I'd rather not have to put too much effort into fixing the module at this point, unless you have strong feelings about it.

**Comment by e0d** [comment]
Not asking you to fix the module, I'm happy to do it, but wanted to collect what we know about the issue.

**Comment by dmitchell** [comment]
:+1: the ansible script is way out of date. `authenticate` raises `PyMongoError` if the user/pswd is invalid (since pymongo 2.5 I believe). The ansible script doesn't catch this when checking if the user already exists. The ansible script uses undocumented `admin` methods.

**Comment by e0d** [comment]
@dmitchell Unless I'm missing something OperationFailure is what is raised in this case, with the 2.7.x driver in any case.

```
[e0d-sandbox] e0d@e0d i-e6741c0c:~$ pip freeze | grep pymongo
pymongo==2.7.2

In [5]: from pymongo import MongoClient

In [6]: inspect.getfile(MongoClient)
Out[6]: '/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.pyc'

In [7]: c = MongoClient("localhost",27017)

In [8]: c['edxapp'].authenticate("no-such-user","password")

... snip ...

OperationFailure: command SON([('authenticate', 1), ('user', u'no-such-user'), ('nonce', u'4818224770da08f7'), ('key', u'0f6a97df250ef7aa473583b657eeeeda')]) failed: auth failed
```

**Comment by dmitchell** [comment]
Hmm, I suppose empirical evidence trumps documentation. The doc string on `Database.authenticate` says

```
        .. versionchanged:: 2.5
           Added the `source` and `mechanism` parameters. :meth:`authenticate`
           now raises a subclass of :class:`~pymongo.errors.PyMongoError` if
           authentication fails due to invalid credentials or configuration
           issues.
```

However, now that I check `OperationFailure` is a subclass of `PyMongoError`; so, it is consistent. Now I'm just wondering if the other auth mechanisms also raise `OperationFailure`.

**Comment by carsongee** [comment]
No longer needed thanks to #1696

**Pull request closed without merging**
