### PR TITLE
Allow configurable password reset support link.

### PR DESCRIPTION
**Pull request by UmanShahzad**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [x] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [x] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [x] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)? -- (This link does not work for me; "Page not found")

This is a child PR of [#15196 from edx/edx-platform](https://github.com/edx/edx-platform/pull/15196), where we allow the password reset support link to be configurable. It is also blocked by it.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @UmanShahzad! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fconfiguration&number=3888"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Review by douglashall — APPROVED** [review]
Please rebase/squash.

**Comment by douglashall** [comment]
@edx/devops Please review and merge.

**Comment by UmanShahzad** [comment]
@douglashall Done!

**Review by feanil — APPROVED** [review]

**Pull request merged**
