### PR TITLE
Extra optional identifier for CD AMI names

### PR DESCRIPTION
**Pull request by macdiesel**
@edx/pipeline-team PTAL.

### CODE REVIEW

**Review by doctoryes — COMMENTED** [review]
So - this change is for the case when you want to create an AMI with the same `"{{ edx_environment }} -- {{ deployment }} -- {{ play }} -- {{ app_version }}"` and yet have a different AMI ID?

**Comment by macdiesel** [comment]
@doctoryes we accomplish 2 things via this PR:
- Each run of a B/M/D pipeline will always generate an AMI artifact. Prior to this change an AMI would only be created if the sha of the app repository was different from the last run. 
- If changes to other repositories are made this new AMI will capture those changes (configuration, config-secure, etc). 

On a really basic level, each run of a pipeline should generate a new AMI. We were not doing this before this change.

**Comment by doctoryes** [comment]
Agreed - 👍 

Will we be using the pipeline run ID for the extra number?

**Comment by macdiesel** [comment]
I modified the pattern to use the pipeline counter.

**Pull request merged**
