### PR TITLE
Always autorestart edxapp workers

### PR DESCRIPTION
**Pull request by mtyaka**
By default supervisor will only automatically restart services when they exit code is not `0` or `2`.
Edxapp workers sometimes exit with a code of `0` on certain network failures, so make sure they are restarted even if exit code is `0`.

JIRA ticket: [OSPR-1713](https://openedx.atlassian.net/browse/OSPR-1713)

Configuration Pull Request
---

Make sure that the following steps are done before merging

  - [x] @devops team member has commented with :+1:
  - [ ] ~~are you adding any new default values that need to be overridden when this goes live?~~ nope
    - ~~[ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.~~
    - ~~[ ] Add an entry to the CHANGELOG.~~

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @mtyaka! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=3661&repo=edx%2Fconfiguration"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Comment by e0d** [comment]
@mtyaka can you rebase on top of master please, should fix the CI failure.

**Comment by mtyaka** [comment]
Thanks @e0d! I rebased and the build is passing now.

**Comment by bdero** [comment]
:+1:

- [x] I tested this: I verified that `/edx/app/supervisor/conf.d/workers.conf` had this change on one of our instances and terminated a worker, verifying that it started up again immediately afterwards with a reset uptime.
- [x] I read through the code
- [ ] ~I checked for accessibility issues~
- [ ] ~Includes documentation~

**Comment by feanil** [comment]
@mtyaka can I also ask you to file an up-stream bug or find a relevant upstream bug?  Let's add a comment to the change to explain why it's happening as well.  Ideally with a link to the upstream bug.

**Comment by mtyaka** [comment]
@feanil Thanks! I included a comment linking to [the Celery bug](https://github.com/celery/celery/issues/2024). The bug was fixed in Celery 4.x, so we can remove this when we upgrade to Celery 4.

**Comment by edx-webhook** [comment]
Thanks for the pull request, @mtyaka! I've created [OSPR-1713](https://openedx.atlassian.net/browse/OSPR-1713) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Review by feanil — APPROVED** [review]

**Comment by feanil** [comment]
@edx/devops  second review.

**Review by jibsheet — APPROVED** [review]

**Comment by mtyaka** [comment]
@feanil @jibsheet Thank you for reviewing this! Do we need anything else or can I go ahead and merge?

**Comment by jibsheet** [comment]
Go ahead and merge, we'll need to keep an eye on stage/prod as it rolls out

**Pull request merged**
