### PR TITLE
Updated CREDENTIALS_OAUTH_URL_ROOT

### PR DESCRIPTION
**Pull request by tasawernawaz**
Use `EDXAPP_LMS_ROOT_URL` instead of `EDXAPP_LMS_ISSUER` for base LMS url.

_**Related PR (Add `EDXAPP_LMS_ROOT_URL` variable):** https://github.com/edx/configuration/pull/2933_

Please review this. @maxrothman @zubair-arbi @awais786 @ahsan-ul-haq @waheedahmed

### CODE REVIEW

**Comment by maxrothman** [comment]
👍

**Comment by zubair-arbi** [comment]
@maxrothman the build is failing on `insights` task. Any idea how to resolve it?

```
TASK: [insights | install node dependencies] ********************************** 
failed: [127.0.0.1] => {"failed": true, "parsed": false}
BECOME-SUCCESS-njvdczwumtucdssfjgtedsntjtbwhzoz
Traceback (most recent call last):
  File "/tmp/ansible-tmp-1462437251.49-205661862385769/npm", line 1876, in <module>
    main()
  File "/tmp/ansible-tmp-1462437251.49-205661862385769/npm", line 244, in main
    installed, missing = npm.list()
  File "/tmp/ansible-tmp-1462437251.49-205661862385769/npm", line 168, in list
    data = json.loads(self._exec(cmd, True, False))
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")

ValueError: No JSON object could be decoded
```

**Comment by zubair-arbi** [comment]
@maxrothman Ok, got it. This issue is seemed to be worked on by @e0d  https://github.com/edx/configuration/pull/3013

**Comment by waheedahmed** [comment]
👍

**Pull request merged**
