### PR TITLE
refactor: add CELERY_RESULT_BACKEND with default django-cache

### PR DESCRIPTION
**Pull request by navinkarkera**
## Description
**Cherry pick of https://github.com/openedx/edx-platform/pull/30244**

At Opencraft, we want to run multiple instances of celery workers in separate servers. The celery workers need to be able to share task results. Currently, the `CELERY_RESULT_BACKEND` is hard coded to use `django-cache`.

So this PR allows to setup `CELERY_RESULT_BACKEND` via configuration.

To use django ORM as celery backend, one can set `CELERY_RESULT_BACKEND` to `django-db` as described in [docs](https://docs.celeryq.dev/en/stable/django/first-steps-with-django.html#django-celery-results-using-the-django-orm-cache-as-a-result-backend).

## Supporting information

- Task: https://tasks.opencraft.com/browse/BB-6077

## Deadline

"None"

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @navinkarkera! I've created [OSPR-6788](https://openedx.atlassian.net/browse/OSPR-6788) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@navinkarkera Thank you for your contribution, is this ready for our review?

**Comment by navinkarkera** [comment]
@natabene Thank you! Yes it s ready for your review.
cc: @kaustavb12

**Review by kaustavb12 — APPROVED** [review]
:+1:

Looks good to go from my end.

- [X] I tested this: I tested the configuration in the PR sandbox
- [X] I read through the code
- [X] Includes documentation

**Comment by adzuci** [comment]
@navinkarkera Would you mind rebasing this PR?

**Comment by navinkarkera** [comment]
> @navinkarkera Would you mind rebasing this PR?

@adzuci It is already up to date with nutmeg branch.

**Review by NIXKnight — APPROVED** [review]
LGTM :+1:

**Comment by openedx-webhooks** [comment]
@navinkarkera 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/configuration&entry.867055334=https://github.com/openedx/configuration/pull/6772&entry.1484655318=https://github.com/navinkarkera&entry.752974735=2022-06-13+05:44&entry.1917517419=2022-07-14+06:36&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
