### PR TITLE
Add devstack birch RC1 vagrant box

### PR DESCRIPTION
**Pull request by singingwolfboy**
And add alias for new naming convention for Aspen. @maxrothman, can you review this?

### CODE REVIEW

**Comment by feanil** [comment]
http://files.edx.org/vagrant-images/20150203-birch-devstack-rc1.box needs to be made public @maxrothman 

same with the md5 file for it.

**Comment by maxrothman** [comment]
@feanil Should be good now

**Comment by feanil** [comment]
:+1:

**Comment by maxrothman** [comment]
:+1:

**Pull request merged**
