### PR TITLE
youtube API key setting

### PR DESCRIPTION
**Pull request by fredsmith**

### CODE REVIEW

**Comment by feanil** [comment]
:+1:  can you also link to the relevant edx-platform PR that adds the setting to  aws.py

**Comment by sarina** [comment]
@fredsmith @feanil this needs to get into Cypress, along with any relevant edx-platform PRs

Can you please make those PRs to the relevant Cypress branches, and add their links to https://openedx.atlassian.net/wiki/display/OPEN/Cypress+Bugfixes

**Comment by fredsmith** [comment]
@feanil FYI, I've merged this change into the cypress.rc branch via PR https://github.com/edx/configuration/pull/2164.  It should be included when we cut a new release candidate.

**Comment by feanil** [comment]
cool, ty

**Pull request merged**
