### PR TITLE
Vagrant stacks use ansible pull to update

### PR DESCRIPTION
**Pull request by wedaly**
First attempt at using the new `edx_ansible` role to simplify the Vagrant release process.

1) Base boxes (in configuration/vagrant/base) are provisioned using playbooks that now include `edx_ansible`.
2) Release boxes (in configuration/vagrant/release) assume that Ansible is installed in the base box, then use a shell script to execute Ansible playbooks on the Vagrant localhost ("ansible-pull" model).

Advantages:
1) Developers using the release stacks don't need to have Ansible installed in their host machines, which greatly simplifies the setup process.
2) Changes to playbooks/roles in the configuration repo won't break the release stacks.

I still need to do a lot of testing to make sure this works correctly, but I'm interested in feedback on the general approach.

### CODE REVIEW

**Comment by jarv** [comment]
@wedaly if it wasn't clear from the other pull i created a helper script for ansible-pull for app updates.
What we will probably want to do is add a devstack option (or make it the default) to set the devstack extra var as well as an option for a full config:

https://github.com/edx/configuration/blob/master/playbooks/roles/edx_ansible/templates/update.j2

```
/edx/bin/update -h

    Usage: update <repo> <version>
            -v        add verbosity to edx_ansible run
            -h        this

    <repo> - must be one of [forums,ease,discern,xqueue,xserver,edx-platform,configuration,edx-ora]
    <version> - can be a commit or tag
```

Example:

```
# /edx/bin/update xqueue master

PLAY [Deploy xqueue] ********************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]
localhost: not importing file: /edx/app/edx_ansible/edx_ansible/playbooks/edx-east/{{secure_vars}}

TASK: [xqueue | writing supervisor scripts - xqueue, xqueue consumer] ********* 
ok: [localhost] => (item=xqueue)
ok: [localhost] => (item=xqueue_consumer)

TASK: [xqueue | create xqueue application config] ***************************** 
ok: [localhost]

TASK: [xqueue | create xqueue auth file] ************************************** 
ok: [localhost]

TASK: [xqueue | git checkout xqueue repo into xqueue_code_dir] **************** 
ok: [localhost]

TASK: [xqueue | install python pre-requirements] ****************************** 
ok: [localhost]

TASK: [xqueue | install python post-requirements] ***************************** 
changed: [localhost]

TASK: [xqueue | syncdb and migrate] ******************************************* 
skipping: [localhost]

TASK: [xqueue | create users] ************************************************* 
changed: [localhost]

TASK: [xqueue | update supervisor configuration] ****************************** 
ok: [localhost]

TASK: [xqueue | ensure xqueue, consumer is running] *************************** 
ok: [localhost] => (item=xqueue)
ok: [localhost] => (item=xqueue_consumer)

NOTIFIED: [xqueue | restart xqueue] ******************************************* 
changed: [localhost] => (item=xqueue)
changed: [localhost] => (item=xqueue_consumer)

PLAY RECAP ******************************************************************** 
localhost                  : ok=11   changed=3    unreachable=0    failed=0   

```

**Comment by wedaly** [comment]
@jarv That makes so much sense.

What do you think about changing the update script to not use "--deploy" for the configuration repo?  I'm thinking about the change I made that added a new role, which broke the --deploy steps because the user/directories didn't exist.

**Comment by jarv** [comment]
maybe add a `-r` option for reconfigure?
I was thinking that this script would primarily be used to update a repo since I assume most devs are primarily concerned about moving a given repo to a new tag/branch.

**Comment by wedaly** [comment]
OK, I think this is just about ready.  The release Vagrantfiles still have "TODO"s for the base box URLs; these should be updated when we finish cutting the release images.

**Comment by jarv** [comment]
I'm unclear about the new directory structure, here is what i think I understand:

```
vagrant/base/{fullstack,devstack}/Vagrantfile -  bring up instances from scratch, these vagrant files should use the ansible provisioner
vagrant/release/<release name>/{fullstack,devstack}/ - bring up instances using a vagrant image and run update on fullstack or re-configure for devstack after bringup
```

should we remove vagrant/{devstack,fullstack}
why do the vagrant/{devstack,fullstack} directories exist? There should be a release directory there no?

**Comment by wedaly** [comment]
Updated the directory structure and removed provisioning from fullstack Vagrantfile.

**Comment by jarv** [comment]
:+1:

**Pull request merged**
