### PR TITLE
Don't install into a subdirectory

### PR DESCRIPTION
**Pull request by nedbat**
Now the install happens in the current directory, with logs in a 'logs'
subdirectory.

Other improvements: curl now fails if the Vagrantfile can't be
downloaded, because the RELEASE value is invalid.  Curl also doesn't
print as large a progress bar.  The script fails early if there's no
RELEASE specified.

### CODE REVIEW

**Comment by nedbat** [comment]
@gsong @edx/devops Opinions?
cc: @cptvitamin

**Comment by gsong** [comment]
@nedbat Definite improvement. 👍

**Comment by nedbat** [comment]
@gsong I'll take that as an approval to merge.  We usually use :+1: as an unambiguous signal.

**Comment by gsong** [comment]
@nedbat I edited my comment above. I guess GitHub doesn't send out update notifications. 👍

**Pull request merged**
