### PR TITLE
Fix missing boto configuration on GCP VMs (Hawthorn backport)

### PR DESCRIPTION
**Pull request by OmarIthawi**
Backport #4812 to `hawthorn.master`.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @OmarIthawi! I've created [OSPR-2770](https://openedx.atlassian.net/browse/OSPR-2770) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@nedbat Will you have a look /merge this?

**Comment by OmarIthawi** [comment]
https://github.com/edx/configuration/pull/4812 has an issue, marking this as `(WIP)`

**Comment by nedbat** [comment]
Should this get #4869 added to it?

**Comment by OmarIthawi** [comment]
Thanks for the reminder @nedbat! I've cherry-picked https://github.com/edx/configuration/pull/4869. This PR is now ready.

**Comment by openedx-webhooks** [comment]
@OmarIthawi 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4862&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2018-11-02+18:22&entry.1917517419=2018-11-13+19:31&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by OmarIthawi** [comment]
Thanks @nedbat!

**Pull request merged**
