### PR TITLE
Change to the new stable version: 1.4.7

### PR DESCRIPTION
**Pull request by idqweb**
Relesease Note : https://sqoop.apache.org/docs/1.4.7/sqoop-1.4.7.releasenotes.html

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @idqweb! I've created [OSPR-2297](https://openedx.atlassian.net/browse/OSPR-2297) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by nedbat** [comment]
@idqweb Thanks for the contribution! :)   Let me know when you have sent in your contributor agreement so that we can start discussing the change.

**Comment by mduboseedx** [comment]
@idqweb Did you have a chance to send in and sign the Contributors Agreement? Thanks

**Comment by idqweb** [comment]
@mduboseedx Today I send the document to legal@edx.org

**Comment by mduboseedx** [comment]
@idqweb Great! I'll check with our legal team and then update our records. Thanks for sending that in.

**Comment by mduboseedx** [comment]
@edx/devops Could you take a look at this?

**Comment by jibsheet** [comment]
@mduboseedx This is @edx/edx-data-engineering 's play, so I'd defer to them.  They can merge something like this without us.

**Comment by macdiesel** [comment]
@mduboseedx we won't be able to merge this until we upgrade our EMR to a version that supports sqoop which is 5.14.0. We are hoping to do this work soon and it is covered under: https://openedx.atlassian.net/browse/DE-766

**Comment by natabene** [comment]
@edx/edx-data-engineering Can you give this a look?

**Comment by macdiesel** [comment]
Work on https://openedx.atlassian.net/browse/DE-766 has been de-prioritized at this point. I'm going to close this ticket as the version will likely have changed the next time we upgrade EMR.

**Comment by openedx-webhooks** [comment]
@idqweb Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4383&entry.1484655318=https://github.com/idqweb&entry.752974735=2018-03-14+16:14&entry.1917517419=2018-12-06+20:54&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
