### PR TITLE
Remove default datadog-uninstall

### PR DESCRIPTION
**Pull request by shaidar**
When `COMMON_ENABLE_DATADOG` is not defined, the datadog-uninstall role runs causing the removal of the apt key and eventually leading to the error below when running `apt-get update`: 

```W: Failed to fetch https://apt.datadoghq.com/dists/stable/Release.gpg  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4B4593018387EEAF```

Not sure why a call to uninstall datadog is made by default and think it's best to remove that from running by default. Asked in Slack about it prior to submitting this PR to see if someone with better knowledge of the codebase can justify it, but did not get a response. Guessing it's part of some legacy deployments and is harmless to remove now.

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @shaidar! I've created [OSPR-3711](https://openedx.atlassian.net/browse/OSPR-3711) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by feanil** [comment]
@shaidar thanks for the PR.  Yea it's definitely legacy.  Would you be willing to remove the installation of datadog as well?  That is also legacy and can be killed.

**Comment by shaidar** [comment]
@feanil Should I go ahead and remove the playbook roles and any references to Datadog as well?

**Comment by feanil** [comment]
@shaidar yes.

**Comment by natabene** [comment]
@shaidar Please let me know once you have addressed feedback.

**Comment by shaidar** [comment]
@natabene I believe I addressed the feedback now

**Comment by natabene** [comment]
@shaidar Thanks for letting me know. Can you also address the failing test?

**Comment by natabene** [comment]
@shaidar We have not heard from  you in a while, so I am will close this PR for now. Please feel free to re-open if you want to pursue this again.

**Pull request closed without merging**
