### PR TITLE
Support setting the LTI_USER_EMAIL_DOMAIN in edxapp/lms

### PR DESCRIPTION
**Pull request by carsongee**
This is the configuration side of: https://github.com/edx/edx-platform/pull/8979

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @carsongee! I've created [OSPR-712](https://openedx.atlassian.net/browse/OSPR-712) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams. 

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ('this must be merged by XX date', and why that is)
- partner information ('this is a course on edx.org')
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the Github pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by feanil** [comment]
:+1:   @fredsmith second review?

**Comment by fredsmith** [comment]
:+1:

**Comment by carsongee** [comment]
Thanks!

**Comment by sarina** [comment]
@fredsmith @feanil are you going to review the edx-platform side of this as well? https://github.com/edx/edx-platform/pull/8979

**Pull request merged**
