### PR TITLE
Install MySQL 5.6 from an edX repo

### PR DESCRIPTION
**Pull request by nedbat**
Configuration Pull Request
---

Make sure that the following steps are done before merging

  - [ ] @devops team member has commented with :+1:
  - [ ] are you adding any new default values that need to be overridden when this goes live?  
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

### CODE REVIEW

**Comment by nedbat** [comment]
(sorry about the trailing space changes, btw...)

**Comment by nedbat** [comment]
@edx/devops To fix the problem with ondrej's MySQL 5.6 PPA disappearing.

**Review by feanil — APPROVED** [review]
Assuming the testing confirms my manual test of this PPA.

**Comment by nedbat** [comment]
My native installation worked from this branch.  Is there other testing needed?

**Comment by feanil** [comment]
We don't use this in anything but devstacks and sandboxes, maybe kick off a sandbox from scratch using this branch and make sure it doesn't have any issues. If that passes, I think we are good to merge.

**Comment by nedbat** [comment]
A from-scratch sandbox worked, merging.

**Pull request merged**
