### PR TITLE
feat: PSRE-974 | Update Data Czar scripts from boto to boto3

### PR DESCRIPTION
**Pull request by arbabkhalil**
I have updated the code and tested it by running code locally to create organization, group, policy, and adding user to it. I was using edx-prod-admin role for this which worked fine locally, test it in jenkins after merging.

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Review by adzuci — CHANGES_REQUESTED** [review]
Nice job updating this script to use boto3, could you squash your commits and prefix them with either chore: or feat: so that they follow conventional commits?

Also, could you add a note about how you tested these changes in the PR description?

**Comment by adzuci** [comment]
Adding @jdmulloy as a second reviewer as well since I haven't given the actual logic a thorough review.

**Comment by arbabkhalil** [comment]
> Nice job updating this script to use boto3, could you squash your commits and prefix them with either chore: or feat: so that they follow conventional commits?
> 
> Also, could you add a note about how you tested these changes in the PR description?

Done with these changes, once this review get resolved, I will be able to merge these changes.

**Review by adzuci — APPROVED** [review]
LGTM

**Review by adzuci — CHANGES_REQUESTED** [review]
Hmm, I still see five commits which don't have a prefix in the commit message.  Do you think we should squash it to one commit and do you feel that this should be prefixed as chore: or feat:

**Review by nadeemshahzad — APPROVED** [review]

**Comment by nadeemshahzad** [comment]
Please squash the comments before merge.

**Pull request merged**
