### PR TITLE
Use COMMON_PYPI_MIRROR_URL in discern,ora,edx_ansible,supervisor,xqueue,...

### PR DESCRIPTION
**Pull request by pku9104038**
...xserver

Make it easier to use a local pypi mirror in the roles listed above

### CODE REVIEW

**Comment by nedbat** [comment]
@pku9104038 Have you signed a contributor's agreement?  Details are at https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst

**Comment by pku9104038** [comment]
I have signed the contributor's agreement and send to jennifer@edx.org. And add my name to the AUTHORS according to the suggestions of CONTRIBUTING.rst

**Comment by feanil** [comment]
@jarv I think this should be merged in

**Comment by jarv** [comment]
lgtm

**Comment by feanil** [comment]
@pku9104038 Can you rebase this from master?

**Comment by jarv** [comment]
I think this will be covered in https://github.com/edx/configuration/pull/966/files

**Comment by feanil** [comment]
This is for all the roles outside of edxapp whereas that one is just fixing the edxapp values to match this scheme.

**Comment by feanil** [comment]
Closing this and mering the rebased PR 977.

**Pull request closed without merging**
