### PR TITLE
Analytics Jenkins: Support common vars, secure branch override, and text parameters

### PR DESCRIPTION
**Pull request by mulby**
1. Allow the specification of a "common vars file" see this PR for more info: https://github.com/edx-ops/edx-jenkins-job-dsl/pull/24
2. Allow the seed job to be re-run manually using the Jenkins UI while overriding the secure branch and the job DSL branch. This allows for tight-loop iteration using changes made to those two repos.
3. Make most of the EXTRA_VARS parameters text parameters again. They can still use directly-entered YAML, so I figured we should maintain that feature since it's relatively easy to support.

Reviewers:
- [ ] @jibsheet 
- [ ] @pomegranited 
- [ ] @jbzdak 

FYI: @brianhw @HassanJaveed84 

TODO:
- [x] Read through the documentation and see what needs to be updated.

Screenshots:
(this screenshot has an out-of-date description for SECURE_BRANCH that has since been fixed in the PR)
screenshot from 2016-04-14 11 14 32

### CODE REVIEW

**Comment by pomegranited** [comment]
@mulby Looks good!  👍   

I ran it on my vagrant instance, tested the `COMMON_VARS` overrides, and ensured that raw YAML and JSON still work in `COMMON_VARS` and the `*_EXTRA_VARS` parameters.

One recommended change: [as I mentioned in your PR #24](https://github.com/edx-ops/edx-jenkins-job-dsl/pull/24/files#r59841734), the AnalyticsSeedJob gets marked UNSTABLE due to an [old JUnit plugin version](https://github.com/edx/configuration/blob/master/playbooks/roles/jenkins_master/defaults/main.yml#L47) installed by the jenkins_master role.  I tested upgrading the plugin to v1.11, and that makes the build succeed.

**Comment by mulby** [comment]
@jibsheet - This has been rebased and is ready for review.

**Comment by jbzdak** [comment]
LGTM :+1:

**Comment by mulby** [comment]
Closing in favor of #2963

**Pull request closed without merging**
