### PR TITLE
Upgrades mysql to 5.6

### PR DESCRIPTION
**Pull request by e0d**
@jarv @feanil @benpatterson @jzoldak

### CODE REVIEW

**Comment by feanil** [comment]
:+1:

**Comment by benpatterson** [comment]
:+1:

**Comment by e0d** [comment]
@benpatterson @feanil rebased.  Want to merge today.

**Comment by benpatterson** [comment]
:+1:

@clytwynec FYI

**Comment by jzoldak** [comment]
@singingwolfboy this upgrade we should put on the list of things to test for aspen -> birch

**Comment by benpatterson** [comment]
@e0d could we get this merged? If not, what needs to move for it to happen?

**Pull request merged**
