### PR TITLE
fix: remove dummy order history url

### PR DESCRIPTION
**Pull request by kaustavb12**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A SRE team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a SRE ticket with details.
    - [x] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/spaces/SRE/pages/28967861/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

## Description

This PR changes the default value of `MFE_ORDER_HISTORY_URL` to emptry string `""` from a dummy url configured earlier.

MFE headers [renders](https://github.com/openedx/frontend-component-header/blob/faf1b8522a43a4a995f8f3671e48d25f4ee439ab/src/Header.jsx#L73-L76) the `Order History` option in the dropdown, only if `MFE_ORDER_HISTORY_URL` is configured.

Having the dummy url as default value here meant, the `Order History` option is rendered by default in MFEs which redirects to a broken link. This could be confusing for users.

With this change, the `Order History` option will not be rendered by default, unless the `MFE_ORDER_HISTORY_URL` is configured.

## Supporting information

Link to other information about the change, such as Jira issues, GitHub issues, or Discourse discussions.
Be sure to check they are publicly readable, or if not, repeat the information here.

## Testing instructions

1. Register and login to this [sandbox](https://order-history-url.opencraft.hosting/dashboard).
2. Go to the [account page](https://app.order-history-url.opencraft.hosting/account)
3. Click on username in the right hand corner of the MFE header.
4. Verify `Order History` option is missing.

## Deadline

"None" if there's no rush, or provide a specific date or event (and reason) if there is one.

## Other information

Private Ref: [BB-6761](https://tasks.opencraft.com/browse/BB-6761)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @kaustavb12!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by tecoholic — APPROVED** [review]
@kaustavb12  :+1:

- [x] I tested this: Verified that the order history is missing from the Sandbox as expected.
- [x]I read through the code
- [x] I checked for accessibility issues
- [x] Includes documentation

**Comment by mphilbrick211** [comment]
Hi @kaustavb12! Is this PR ready for review?

**Comment by kaustavb12** [comment]
Hi @mphilbrick211 

Thanks for checking. This PR is ready for review.

**Comment by mphilbrick211** [comment]
Hi @adzuci - flagging for your review!

**Comment by mphilbrick211** [comment]
Hi @adzuci! Friendly ping on this :)

**Comment by mphilbrick211** [comment]
Hi @adzuci just checking to see if you have an ETA on when you'll be able to review/merge this request. Thanks!

**Comment by ali-hugo** [comment]
Hi @mphilbrick211. I'm available to review this if @adzuci doesn't have availability (I'm a Core Contributor who is part of the Product Working Group).

**Comment by ali-hugo** [comment]
@mphilbrick211 Whoops again - I've noticed that this ticket isn't tagged with "product review" either, so I don't think I can review it as a Product Working Group member, can I?

**Comment by mphilbrick211** [comment]
> @mphilbrick211 Whoops again - I've noticed that this ticket isn't tagged with "product review" either, so I don't think I can review it as a Product Working Group member, can I?

Hi @ali-hugo! Sure you can take a look and provide feedback, though @adzuci is the repo so he'd need to do a final look and merge. I appreciate all the help you're offering!

**Comment by ali-hugo** [comment]
@mphilbrick211 My pleasure! I'd like to help where I can to get some of these PR's reviewed so they can be merged.

**Comment by ali-hugo** [comment]
Hi @kaustavb12. I followed the testing instructions in the description (thanks for making them so clear) and can confirm that the `Order History` option is missing from the dropdown in the top right:

Screenshot 2023-02-14 at 14 30 36

Please let me know if there's anything else I can help with. 🙂

**Comment by kaustavb12** [comment]
Thank you so much @ali-hugo for reviewing and verifying the changes.

**Comment by mphilbrick211** [comment]
Hi @kaustavb12 - would you mind resolving the branch conflicts?

CC: @adzuci for review.

Thanks!

**Comment by kaustavb12** [comment]
Hi @mphilbrick211 

Done. Branch rebased and conflicts resolved.

cc. @adzuci

**Review by pshiu — APPROVED** [review]
Great contribution, thanks @kaustavb12!

**Comment by pshiu** [comment]
@kaustavb12, sorry you've had to repeatedly rebase so often.

I tried to help by rebasing your branch myself, but found I did not have the permissions to do so.

Could you update the date in CHANGELOG.md then rebase one more time? Please tag me so I can merge soon after so we can close out this PR.

**Comment by kaustavb12** [comment]
Thanks a lot @pshiu for the review.

I have now rebased the branch and resolved the conflict.

**Comment by openedx-webhooks** [comment]
@kaustavb12 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/configuration&entry.867055334=https://github.com/openedx/configuration/pull/6820&entry.1484655318=https://github.com/kaustavb12&entry.752974735=2022-10-14+16:42&entry.1917517419=2023-03-27+18:17&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by pshiu** [comment]
Thanks, @kaustavb12!

**Pull request merged**
