### PR TITLE
use global python packages when possible

### PR DESCRIPTION
**Pull request by trungpham**
speed up installing python packages by reusing the global packages if exist

### CODE REVIEW

**Comment by trungpham** [comment]
https://github.com/edx/configuration/issues/1367

**Comment by hkim823** [comment]
Testing on a sandbox now

**Comment by hkim823** [comment]
I ran into issues trying to get this to work but it could be my environment that I was using.  Hold tight.

**Comment by hkim823** [comment]
This works for me @feanil care to take a 2nd look?

**Comment by trungpham** [comment]
I ran into a problem with getting devpi to run because of the out dated zope.interface.

Traceback (most recent call last):
  File "/edx/app/devpi/venvs/devpi/bin/devpi-server", line 9, in <module>
    load_entry_point('devpi-server==2.0.3', 'console_scripts', 'devpi-server')()
  File "/edx/app/devpi/venvs/devpi/local/lib/python2.7/site-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/edx/app/devpi/venvs/devpi/local/lib/python2.7/site-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/edx/app/devpi/venvs/devpi/local/lib/python2.7/site-packages/pkg_resources.py", line 2190, in load
    ['**name**'])
  File "/edx/app/devpi/venvs/devpi/local/lib/python2.7/site-packages/devpi_server/main.py", line 16, in <module>
    from . import extpypi, replica, mythread
  File "/edx/app/devpi/venvs/devpi/local/lib/python2.7/site-packages/devpi_server/replica.py", line 5, in <module>
    from pyramid.view import view_config
  File "/edx/app/devpi/venvs/devpi/local/lib/python2.7/site-packages/pyramid/view.py", line 21, in <module>
    from pyramid.threadlocal import get_current_registry
  File "/edx/app/devpi/venvs/devpi/local/lib/python2.7/site-packages/pyramid/threadlocal.py", line 3, in <module>
    from pyramid.registry import global_registry
  File "/edx/app/devpi/venvs/devpi/local/lib/python2.7/site-packages/pyramid/registry.py", line 5, in <module>
    from zope.interface.registry import Components
ImportError: No module named registry

**Comment by trungpham** [comment]
maybe virtualenv_site_packages=yes is not a good idea after all. I can try to find another to get venv to not blindly recompile the C extensions.

**Comment by hkim823** [comment]
I also ran into the DevPi issue once or twice but it went away.  Hm

**Comment by trungpham** [comment]
@hkim823 i had to rebuild the DevPi venv to make it go away.

**Comment by trungpham** [comment]
@hkim823 @feanil I won't pursue this option anymore. I think I have an alternative way to speed up the build time. You can close this issue now.

**Pull request closed without merging**
