### PR TITLE
Updated JWT configuration for IDAs 

### PR DESCRIPTION
**Pull request by clintonb**
The JWT configuration for IDAs that depend on edxapp's JWT configuration have been updated to actually reference the edxapp variables.

ECOM-4414

### CODE REVIEW

**Comment by clintonb** [comment]
@feanil please review

FYI @edx/ecommerce

**Comment by clintonb** [comment]
This is necessary before merging feanil/devops-4207 in secure configuration.

**Comment by feanil** [comment]
👍

**Comment by rlucioni** [comment]
👍

**Pull request merged**
