### PR TITLE
Updated the jenkins worker Dockerfile to use ubuntu 20 as base image

### PR DESCRIPTION
**Pull request by mraarif**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by mraarif** [comment]
I created a sandbox here: https://tools-edx-jenkins.edx.org/job/sandboxes/job/CreateSandbox/34618/ with ubuntu 20 option and the build seems fine.

**Comment by mraarif** [comment]
I tried to create an image locally with these change (using `make docker.build.jenkins_worker`) but it failed with the following error message
```
---> Running in 09d4355af92e
ERROR! the playbook: RUN could not be found
The command '/bin/sh -c sudo /edx/app/edx_ansible/venvs/edx_ansible/bin/ansible-playbook jenkins_worker.yml     -c local -i '127.0.0.1,'     --extra-vars="@/jenkins_worker/ansible_overrides.yml"     --extra-vars="@/devstack/ansible_overrides.yml" RUN apt-get update   && apt-get install -y openssh-server   && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 1
docker.mk:59: recipe for target 'docker.build.jenkins_worker' failed
```
based on the changes I've made this shouldn't be occurring given that this was working fine before.

**Comment by mraarif** [comment]
filed an SRE ticket here: https://openedx.atlassian.net/browse/DOS-1734 to get access to `testeng-secure`

**Review by adzuci — APPROVED** [review]

**Comment by jmbowman** [comment]
The `playbook: RUN could not be found` is due to a trailing `\` in the ansible command in the Dockerfile, which docker seems to have gotten stricter about.  Removing that got me past that problem and on to `Failed to update apt cache: `, which is presumably due to some `sources.list.d` misconfiguration or such.

**Comment by jmbowman** [comment]
Here's the output from `apt-get update` that's causing Ansible to choke:

```
apt-get update
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease                                                                                
Err:1 http://security.ubuntu.com/ubuntu focal-security InRelease
  At least one invalid signature was encountered.
Hit:3 http://ppa.launchpad.net/git-core/ppa/ubuntu focal InRelease
Err:2 http://archive.ubuntu.com/ubuntu focal InRelease
  At least one invalid signature was encountered.
Get:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]  
Err:3 http://ppa.launchpad.net/git-core/ppa/ubuntu focal InRelease                 
  At least one invalid signature was encountered.
Get:5 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease [18.1 kB]     
Err:5 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease 
  At least one invalid signature was encountered.
Get:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
Err:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease
  At least one invalid signature was encountered.
Err:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease
  At least one invalid signature was encountered.
Fetched 342 kB in 1s (310 kB/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://security.ubuntu.com/ubuntu focal-security InRelease: At least one invalid signature was encountered.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://archive.ubuntu.com/ubuntu focal InRelease: At least one invalid signature was encountered.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://ppa.launchpad.net/git-core/ppa/ubuntu focal InRelease: At least one invalid signature was encountered.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease: At least one invalid signature was encountered.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://archive.ubuntu.com/ubuntu focal-updates InRelease: At least one invalid signature was encountered.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://archive.ubuntu.com/ubuntu focal-backports InRelease: At least one invalid signature was encountered.
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal/InRelease  At least one invalid signature was encountered.
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease  At least one invalid signature was encountered.
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease  At least one invalid signature was encountered.
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease  At least one invalid signature was encountered.
W: Failed to fetch http://ppa.launchpad.net/deadsnakes/ppa/ubuntu/dists/focal/InRelease  At least one invalid signature was encountered.
W: Failed to fetch http://ppa.launchpad.net/git-core/ppa/ubuntu/dists/focal/InRelease  At least one invalid signature was encountered.
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

Related Ansible issue: https://github.com/ansible/ansible/issues/30754

I've filed https://openedx.atlassian.net/servicedesk/customer/portal/15/DOS-1863 to ask SRE for tips on resolving, in case they already know of a good fix.

**Comment by mraarif** [comment]
currently figuring out the permission issue while running `bokchoy` tests: https://build.testeng.edx.org/job/build-packer-ami/15144/console

**Comment by jmbowman** [comment]
@mraarif Is this PR still needed?  I thought we were already on 20.04 for the Jenkins workers now.

**Pull request closed without merging**
