### PR TITLE
Create ~/.ssh directory when using Git via SSH

### PR DESCRIPTION
**Pull request by stvstnfrd**
Previously, if the `${HOME}/.ssh` directory did not already exist when
attempting to checkout a Git repository via SSH, the
`checkout edx-platform repo` and `checkout theme` tasks would fail.

This issue doesn't appear when checking out code as the `edxapp` user
(default: presumably this directory is created elsewhere), but will
surface if run as another user who lacks a `${HOME}/.ssh` directory.

The code now looks before it leaps.

### CODE REVIEW

**Comment by feanil** [comment]
@stvstnfrd  When do you see this error?  I have not run into it before?

**Comment by stvstnfrd** [comment]
@feanil Yeah, I suspect edx.org doesn't run into this issue, as it appears to work for the default user/config.

```
edxapp_user: CUSTOM_USERNAME_HERE
EDXAPP_USE_GIT_IDENTITY: true
EDXAPP_GIT_IDENTITY: KEY GOES HERE
```

`${HOME}/.ssh` appears to already exist for the `edxapp` user, whereas it doesn't if you're attempting to checkout platform/theme via SSH under a different user account. Since the `accept_hostkey=yes` flag is set on the `git` module calls, it tries to save the hostkey file to your `${HOME}/.ssh` dir, which doesn't exist yet, in this case.

It appears that in the default case, this directory is created by some other task; this change explicitly ensures it exists, if the user is enabling a feature that depends on it.

Hopefully that makes sense.

**Comment by feanil** [comment]
@stvstnfrd Can you elaborate a bit more,  What user are you trying to checkout the platform as?  It shouldn't be that different since the home directory is always set for the user you pass in: https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/tasks/main.yml#L7

**Comment by stvstnfrd** [comment]
After discussion, I'm closing this in favor of a better solution; will readdress, if needed.

**Pull request closed without merging**
