### PR TITLE
Include CORS_ORIGIN_WHITELIST in programs defaults

### PR DESCRIPTION
**Pull request by rlucioni**
This will allow us to configure whitelisted domains/hostnames for stage and production.

@jimabramson @edx/devops please review.

### CODE REVIEW

**Comment by jimabramson** [comment]
good call @rlucioni thanks.  :+1:  

For future reference, if the value is omitted in configuration secure, will CORS domains default to completely open or completely closed?

**Comment by rlucioni** [comment]
@jimabramson completely closed.

**Comment by feanil** [comment]
Should there be a corresponding requirements change as well?

**Comment by rlucioni** [comment]
@feanil Programs requirements have already been updated: https://github.com/edx/programs/blob/master/requirements/base.txt#L3

**Comment by rlucioni** [comment]
@feanil ping.

**Comment by fredsmith** [comment]
:+1:

**Pull request merged**
