### PR TITLE
Added HTTP Strict Transport Security headers to ensure clients always

### PR DESCRIPTION
**Pull request by davestgermain**
use SSL (helps prevent MITM attacks).

### CODE REVIEW

**Comment by davestgermain** [comment]
@feanil @e0d I'm not sure if these are the only places to set the header (or if there's an exception to the rule somewhere).

**Comment by feanil** [comment]
@davestgermain can you also add this to the cms template?  Also, have you tested this setting on a single instance sandbox?

**Comment by davestgermain** [comment]
@feanil done. How do I test it on a sandbox?

**Comment by feanil** [comment]
You can bring up a single instance sandbox at 'http://jenkins.edx.org:8080/job/ansible-provision/' which will bring up an ec2 instance and then you can run '/edx/bin/update configuration <hash>' to update the configuration repo to be your branch and verify that it doesn't cause any problems.

**Comment by davestgermain** [comment]
@feanil I don't have access to that jenkins instance, as far as I can tell

**Comment by davestgermain** [comment]
@feanil well, the header seems to have no effect one way or the other.  but the bug report recommended adding it... [HTTP Strict Transport Security](http://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security)

**Comment by feanil** [comment]
Hmm. Ok.  If the header is being passed through to the client, I think that is fine.  Can you see the header being set?

**Comment by davestgermain** [comment]
yup

**Comment by feanil** [comment]
cool, merge it.

**Pull request merged**
