### PR TITLE
Unindent a few entries that needd to be unindented (#6450)

### PR DESCRIPTION
**Pull request by BbrSofiane**
(cherry picked from commit 945fe9df4aaef4bc1dfc565eab4bbcc0b12f9ee8)

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @BbrSofiane! I've created [OSPR-5901](https://openedx.atlassian.net/browse/OSPR-5901) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by BbrSofiane** [comment]
@regisb I've cherry-picked the commit.

**Review by regisb — APPROVED** [review]
note: I suggested this change but I have no idea how to check this is correct.

**Comment by regisb** [comment]
@edx-community-bot merge

(please)

**Comment by regisb** [comment]
This does not look like it's working... cc @sarina

**Comment by regisb** [comment]
cc @nedbat

**Comment by pomegranited** [comment]
Thanks for submitting this fix @BbrSofiane @regisb  -- I'm going to test it with our periodic build system, first with the current lilac.master (to watch it fail), and then with this change (to make sure it fixes it). Will get it merged ASAP!

**Review by pomegranited — APPROVED** [review]
:+1: Thanks @BbrSofiane !

- [x] I tested this
   * deployed a sandbox on Ocim with `open-release/lilac.master`, and watched it fail at
      ```
      TASK [edxapp : install single-beat to run only one celerybeat scheduler]       
      ****************************************************************************************************
      fatal: [149.202.181.235]: FAILED! => {
          "changed": false,
          "msg": "Unsupported parameters for (pip) module: become_user, tags, when Supported parameters include: chdir, editable, executable, extra_args, name, requirements, state, umask, use_mirrors, version, virtualenv, virtualenv_command, virtualenv_python, virtualenv_site_packages"
      }
      ``` 
   * updated the sandbox to use this PR branch for deployment, and deployment passed that step without error.
- [x] I checked the code against the original https://github.com/edx/configuration/pull/6450

**Comment by openedx-webhooks** [comment]
@BbrSofiane 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6467&entry.1484655318=https://github.com/BbrSofiane&entry.752974735=2021-07-04+20:05&entry.1917517419=2021-07-06+05:57&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by natabene** [comment]
Thank you all!

**Pull request merged**
