### PR TITLE
Added install:configuration tag to step that sets up forum env

### PR DESCRIPTION
**Pull request by blarghmatey**
When updating configuration settings on the Forum service, changed passwords for MongoDB were not being set if the Ansible playbook is targeting the `install:configuration` tag. Adding that tag to the `setup the forum env` step addresses this issue.
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @blarghmatey! I've created [OSPR-1876](https://openedx.atlassian.net/browse/OSPR-1876) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by feanil** [comment]
Seems good to me, is there an equivalent PR in master?

**Comment by blarghmatey** [comment]
Not yet, I'll add that in.

**Comment by gsong** [comment]
@blarghmatey Why don't we change the target of this PR to be `master`? Once it's merged then we can cherry pick and back port to `open-release/ginkgo.master` and `open-release/ficus.master`?

Thanks.

**Comment by openedx-webhooks** [comment]
@blarghmatey 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4049&entry.1484655318=https://github.com/blarghmatey&entry.752974735=2017-08-17+16:50&entry.1917517419=2017-10-03+16:48&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
