### PR TITLE
add ENABLE_HTML_DISPLAY_NAME

### PR DESCRIPTION
**Pull request by jagonzalr**
[OSPR-1986](https://openedx.atlassian.net/browse/OSPR-1986)

Configuration Pull Request
---

Adds the default value for showing display name of HTML components using this var ```EDXAPP_ENABLE_HTML_DISPLAY_NAME```

This PR is related to this [PR](https://github.com/edx/edx-platform/pull/16195)

Reviewers
- Code review: ¯_(ツ)_/¯

cc @gsong @nedbat

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @jagonzalr! I've created [OSPR-1991](https://openedx.atlassian.net/browse/OSPR-1991) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Review by feanil — APPROVED** [review]
This looks good but I'll wait till the edx-platform PR lands before merging this in case anything here changes.

**Comment by feanil** [comment]
The equivalent platform PR never merged and was closed so closing this as well.

**Comment by openedx-webhooks** [comment]
@jagonzalr Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4184&entry.1484655318=https://github.com/jagonzalr&entry.752974735=2017-10-31+11:40&entry.1917517419=2018-10-12+20:10&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
