### PR TITLE
Feanil/jarv abbey ami

### PR DESCRIPTION
**Pull request by feanil**

### CODE REVIEW

**Comment by jarv** [comment]
I think we need to broadly communicate this one, also wiki updates.

**Comment by carsongee** [comment]
Why are we changing the variable name? Is this just to be more consistent with the ansible docs?

**Comment by feanil** [comment]
Also to be consistent across roles.  

I'll send an e-mail to the edx-code list to make sure they see it coming and update the wiki.

**Comment by carsongee** [comment]
Sounds good.  I really like the idea of having a change log directly in the repo with variable name changes or other backwards compat changes...maybe call it COMPAT.md or something.  I end up only updating my repo once every week or so and forgot the changes sometimes.  just a thought.  The wiki would probably be adequate, it just means I'll have to start going to it ;)

**Comment by feanil** [comment]
@jarv Wiki updated and mail sent to edx-code.

**Comment by jarv** [comment]
I think we should merge this so we can start the next release tomorrow morning :+1:

**Pull request merged**
