### PR TITLE
Optionally use aws/openstack role in edx_sandbox/edx-stateless

### PR DESCRIPTION
**Pull request by mtyaka**
This proposes an alternative approach to #3423, which was reverted in #3517.

Instead of trying to implicitly determine whether to install the `aws` role from values of other ansible variables, this adds two explicit new variables to common_vars:

- `COMMON_ENABLE_AWS_INTEGRATION`
- `COMMON_ENABLE_OPENSTACK_INTEGRATION`

They are both set to `False` by default. When set to `True`, the corresponding role (`aws`/`openstack`) will be automatically included in `edx_sandbox.yml` and `edx-stateless.yml` playbooks.

**JIRA ticket**: [OSPR-1615](https://openedx.atlassian.net/browse/OSPR-1615)

**Merge deadline**: ASAP - we'd like to get this into the ficus RC1 cut. CC @nedbat 

**Partner information**: 3rd party-hosted open edX instance

**Testing instructions**:

This is difficult to test without spinning up new AWS and OpenStack instances.

**Author notes and concerns**:

`COMMON_ENABLE_AWS_INTEGRATION` and `COMMON_ENABLE_OPENSTACK_INTEGRATION` may not be the best names for these variables. Better suggestions are welcome.

**Steps before merging**

  - [x] OpenCraft member has commented with 👍 
  - [ ] @devops team member has commented with :+1:
  - [ ] are you adding any new default values that need to be overriden when this goes live?  
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @mtyaka! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fconfiguration&number=3522"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Review by itsjeyd — APPROVED** [review]
@mtyaka :+1:

- [x] I tested this: Verified that instances with different combinations of values for `COMMON_ENABLE_AWS_INTEGRATION` and `COMMON_ENABLE_OPENSTACK_INTEGRATION` provisioned successfully, and that Ansible produced expected output in each case.
- [x] I read through the code
- [x] ~~I checked for accessibility issues~~ N/A
- [x] Includes documentation: CHANGELOG entry present, that'll probably do for now.

**Comment by edx-webhook** [comment]
Thanks for the pull request, @mtyaka! I've created [OSPR-1615](https://openedx.atlassian.net/browse/OSPR-1615) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by nedbat** [comment]
I like that it is explicit.

**Comment by pomegranited** [comment]
@nedbat @edx/devops Do we need any more approvals before merging this?  It would be great to get this into the first Ficus cut.

**Comment by pomegranited** [comment]
@gsong Can you help us get this reviewed?

**Comment by feanil** [comment]
I don't think this will work as intended, because both the aws, and openstack roles define the `vhost_name` variable.  The core problem is that variables that are defined in `defaults/main.yml` are resolved wether or not the role is conditionalized, so what ends up happening is that the vhost_name is always set to `openstack`.

**Comment by jibsheet** [comment]
I agree with @feanil I don't see how this resolves the issue I encountered in early December.
My explanation of the variable precedence issue is explained here https://github.com/edx/configuration/pull/3519

**Comment by mtyaka** [comment]
@feanil @jibsheet Ah, thank you for the explanation, I missed that part.

I pushed some more changes to this PR to remove the `vhost_name` variable and to add ability for finer grained control over tracking log syncing to further decouple `aws`, `openstack`, and `vhost` roles.

I would really appreciate your thoughts on this before I start testing these changes thoroughly tomorrow. Does this look like the correct approach?

**Comment by feanil** [comment]
Moving back a bit,  I'm wondering why not just new playbooks for openstack?  We already have separate playbooks for vagrant, docker, and aws(edx-east).  It seems like having separate playbooks for openstack wouldn't be unreasonably.

**Comment by mtyaka** [comment]
@feanil Thanks for the quick response!

Separate playbook is certainly a possibility and we plan to be using the new [edx-stateless.yml playbook](https://github.com/open-craft/configuration/blob/ab84421155a50eccc7d189ef1ad5a49447b47e7d/playbooks/edx-stateless.yml) for our deployments going forward, ~~so I think we are fine with leaving both `aws` and `openstack` roles out of `edx_sandbox.yml`~~. **update**: There are still some issues we will have to resolve before being able to use `edx-stateless.yml` playbook for deployments. We probably won't be able to sort out the issues before ficus is released, so we would prefer to keep the changes to `edx_sandbox.yml`, if at all possible.

However we have a use case where we will have to run **both** `aws` and `openstack` roles on the same deployment (for instances running mostly on openstack while still using some AWS services), so we would still like to get changes from this PR merged. Would you be willing to accept the code if I remove the changes from edx_sandbox.yml? I still need to do some thorough testing, but in theory changes from this PR should be backwards compatible.

**Comment by mtyaka** [comment]
@nedbat @feanil @jibsheet We would really like to get this change into ficus. Can some please review again? I made some additional changes to resolve issues discovered while testing various combinations of `COMMON_ENABLE_AWS_INTEGRATION` and `COMMON_ENABLE_OPENSTACK_INTEGRATION`.

**Comment by nedbat** [comment]
@edx/devops thoughts?

**Comment by feanil** [comment]
@e0d perhaps you could take a look at the removal of `vhost` all together.  I don't remember all the goals for this var.

**Comment by nedbat** [comment]
I have to admit to being a little afraid of the size of this change...

**Comment by mtyaka** [comment]
Rebased from 7575c1d7d8fa89d2766be593d1736ccb71923e67.

**Review by e0d — APPROVED** [review]
I'm OK with removeing the COMMON_VHOST_NAME.  Originally the intent was that this would be available later to indicate which system was being installed, but isn't used and I'd probably ultimately not want it to be used in conditionals anyway in retrospect.

**Comment by feanil** [comment]
@mtyaka looking at this again.  It looks like you change the generic object store vars back to have s3 and swift vars? What was the reason for that?  That is a backwards incompatible change and would result in anyone who has overridden them to update the config(again, since we made them change in the other direction last time).

I'm fine with the removal of the VHost and making it clear which integration you want but I don't think we should change the s3/swift related vars.

**Comment by mtyaka** [comment]
Thanks for looking at this @feanil.

The generic object store vars are still supported - s3/swift vars take their default values from the values of generic vars, so this should be _mostly_ backwards compatible, see: https://github.com/open-craft/configuration/blob/47f5ef03fe9c136a6e2233ca18a3759917548edf/playbooks/roles/common_vars/defaults/main.yml#L25-L37

You do have to set either `COMMON_ENABLE_AWS_INTEGRATION` or `COMMON_ENABLE_OPENSTACK_INTEGRATION` to `True` for tracking log sync to work, though.

Also `COMMON_OBJECT_STORE_LOG_SYNC_SCRIPT` [was removed](https://github.com/edx/configuration/pull/3522/files#diff-bc223d8e1006f4c717bde617c73a7a6eL23), but I am not sure why anybody would want to use/override it. I can look into adding support for that variable back in, if desired.

**Comment by mtyaka** [comment]
Rebased from 47f5ef03fe9c136a6e2233ca18a3759917548edf

**Comment by nedbat** [comment]
@edx/devops one last look?

**Comment by feanil** [comment]
I'm still testing that this does not cause issues on our production side, we also need to merge the Flags to our secure repos so that merging this doesn't break our AMI builds.

**Comment by feanil** [comment]
I'm hoping to get an AMI built and tested by Friday. If that works I'll make the secure PRs on our side and drop an approval on this ticket.

**Comment by bradenmacdonald** [comment]
@feanil @mtyaka ping - is this still moving forward?

**Comment by pomegranited** [comment]
@feanil @jibsheet ping - Is there anything we can do to help get this merged?

**Comment by pomegranited** [comment]
Hi @feanil @jibsheet @gsong , is this change still being tested?  Is there anything we need to fix, or demonstrate before it can be merged?  Thank you!

**Comment by feanil** [comment]
Sorry, this got lost in the shuffle.  I tested this and saw a failure in s3 syncing scripts.  They did not work correctly after the change.  I think this PR doesn't need to be as invasive as it is, I think using the two flags to decide which settings files to use and not using them to decide which syncing vars to use might be the way forward here.

**Comment by gsong** [comment]
@pomegranited Do you plan on revisiting this PR?

**Comment by pomegranited** [comment]
@gsong Yes, we do!  Thank you for the reminder; we're trying to get it into an upcoming sprint.  I've added the Waiting on Author flag, and will remove that when we've addressed @feanil 's comments.

**Comment by mtyaka** [comment]
@feanil Thank you very much for testing this and sorry I haven't been more responsive. I'll make sure to schedule enough time to actively monitor this issue and address any comments during the next couple of weeks.

I think the problem you were seeing was due to a change that was introduced somewhere some time after eucalyptus. The edxapp role installs the `s3cmd` package using native package manager, which does not create a symlink to the binary in `/usr/local/bin/s3cmd`. If the `aws` role is run *after* `edxapp`, `pip install s3cmd` will not do anything because it sees the `s3cmd` package is already installed and aborts, without creating the `/usr/local/bin/s3cmd` symlink like it does if the package is installed via pip.

I updated this PR to move `aws` and `openstack` above `edxapp` and things now work fine. I successfully spawned three EC2 servers, each with a different set of aws and log sync variables and verified that tracking logs are being synced correctly. The first server syncs tracking logs to S3 only, the second one sync to swift only, and the third one is set up to sync to both S3 and swift. I added [your github ssh key](https://github.com/feanil.keys) to all three servers, so you can log in as the `ubuntu` user and take a look.

- 54.167.47.150 (S3)
- 54.173.108.224 (SWIFT)
- 52.54.222.207 (S3 + SWIFT)

We also use this patch on one of our production openstack deployments where we configured the instance to sync tracking logs to both S3 and SWIFT object storage.

>  I think this PR doesn't need to be as invasive as it is, I think using the two flags to decide which settings files to use and not using them to decide which syncing vars to use might be the way forward here.

I am not sure what you would like us to change? The two flags (`COMMON_ENABLE_AWS_INTEGRATION` and `COMMON_ENABLE_OPENSTACK_INTEGRATION`) are only used in combination with `COMMON_ENABLE_OBJECT_STORE_LOG_SYNC` for backwards compatibility to define default values for `COMMON_S3_LOG_SYNC` and `COMMON_SWIFT_LOG_SYNC`. I would actually prefer to remove `COMMON_OBJECT_STORE_LOG_SYNC_*` variables completely. I only kept them for backwards compatibility, but if you think it's better to just remove them, I'll happily do that.

**Comment by mtyaka** [comment]
Rebased from 4c4b8974c3268b6c3e6e84cbdb14f131e8220d9a.

**Comment by mtyaka** [comment]
@feanil Can you please schedule some time to finish reviewing this? We would like to get this in before the next named release. I'll be happy to make any changes that will make it more likely for this to get merged, as long as there is an option to send logs to *both* S3 and SWIFT from the same instance.

It might make sense to split tracking log syncing out of s3 and openstack playbooks into separate playbook(s), but that's going to increase the size of this change even further.

**Comment by bradenmacdonald** [comment]
@feanil @nedbat FYI - this is one PR we'd really like to get in for Gingko. Please let us know what we can do on our side to get this completed.

**Comment by gsong** [comment]
@edx/devops Can we get this back on the radar as we prepare for Gingko?

**Comment by feanil** [comment]
@mtyaka @bradenmacdonald @gsong unfortunately this PR touches a bunch of code that is tied to how we off-load tracking logs from edx-platform.  This means it will require a lot of testing that I don't think we'll have time to do before the next release gets cut.  We need to schedule some time to do some thorough testing of this.  I'll try to figure out a good time with @fredsmith after everyone gets back from 4th of July break.

**Comment by gsong** [comment]
@feanil @fredsmith Can we get this on your radar?

@mtyaka When you get a chance, can you resolve the conflict?

**Comment by mtyaka** [comment]
Rebased on top of master from a806107c15a8598988e44ba759e4783da6f39019.

**Comment by mtyaka** [comment]
@feanil @fredsmith @gsong Sorry this took so long, I missed your last comment. This is now rebased and conflicts resolved.

**Comment by mtyaka** [comment]
@feanil @fredsmith @gsong I rebased and resolved conflicts again. Let me know if I can do anything else.

**Comment by mtyaka** [comment]
Rebased from https://github.com/edx/configuration/pull/3522/commits/479136088db6f1cb9769e2040d2c8a4f2b46148d.

**Comment by nedbat** [comment]
@edx/devops what are the chances of getting this reviewed?

**Comment by mtyaka** [comment]
@feanil @fredsmith Any idea when we could get this reviewed?

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mtyaka! I've created [OSPR-2090](https://openedx.atlassian.net/browse/OSPR-2090) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by smarnach** [comment]
We are planning to close this PR in favour of several simpler PRs.  I'm not sure why the bot created an OSPR ticket just now.  (I can't close the PR since I'm not the author.)

**Comment by mtyaka** [comment]
Closing in favor of https://github.com/edx/configuration/pull/4279 and several other small PRs yet to follow.

**Comment by openedx-webhooks** [comment]
@mtyaka Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/3522&entry.1484655318=https://github.com/mtyaka&entry.752974735=2016-12-03+09:48&entry.1917517419=2018-01-12+08:36&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
