### PR TITLE
Add more conditionals for applying 'aws' role

### PR DESCRIPTION
**Pull request by markbreedlove**
**Background**: The task `aws : Install aws python packages` is applied even when we have `COMMON_ENABLE_AWS_ROLE: False` in our Ansible vars.

This PR will add more conditionals for applying the `aws` role, as is done already in
some files, like [playbooks/edxapp.yml](https://github.com/edx/configuration/blob/8afeda16e07f4ed2fd9b0283945a3f650243c616/playbooks/edxapp.yml#L11-L12).

The checkboxes below are from the PR template. I don't think that any of them apply.

I'm happy to redo this PR against the master branch, or another branch if that's more appropriate.

### PR template checkboxes

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @markbreedlove! I've created [OSPR-4096](https://openedx.atlassian.net/browse/OSPR-4096) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@markbreedlove Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions. Thanks

**Comment by markbreedlove** [comment]
Hi, @natabene ! I'm happy to, but before I do, am I covered already as an employee of MIT Open Learning?

**Comment by natabene** [comment]
@markbreedlove Thank you for letting me know. We will need first to get a confirmation of your coverage from MIT. Once they confirm, I will post an update here. Please note it may take a while - our key contact @pdpinch is away next week. Please stay tuned.

**Comment by markbreedlove** [comment]
Thanks, @natabene ! My immediate manager is @blarghmatey (Tobias Macey) and he's around today, if that helps.

**Comment by natabene** [comment]
@markbreedlove Thank you for joining the Open edX community! We have added your user to our records and can now review your code going forward.

**Review by fredsmith — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@markbreedlove 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/5652&entry.1484655318=https://github.com/markbreedlove&entry.752974735=2020-02-13+21:20&entry.1917517419=2020-02-14+17:57&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by nedbat** [comment]
Hi, this is a big change applied directly to juniper.alpha1.  Ideally, it would be put on master first, and then cherry-picked back to juniper.alpha1 if needed.  Who is making sure these changes are also on master?

**Pull request merged**
