### PR TITLE
This converts lms-preview variant to supervisor

### PR DESCRIPTION
**Pull request by carsongee**
and adds a clause to rake not to gather assets as it fails

### CODE REVIEW

**Comment by jarv** [comment]
@carsongee do you still use lms-preview? I didn't think there was any reason to run it now.

**Comment by carsongee** [comment]
That is a good question @jarv.  Did I miss a memo?  Is it no longer used in studio?  If it is dead I'd be happy to withdraw this and swap it for a PR that deletes those dead templates then.

**Comment by carsongee** [comment]
I just tested with my platform that is on release-2013-11-13 and it still has links to preview in studio.

**Comment by jarv** [comment]
Yeah there was new middleware added to detect draft or non-draft.  You might not have the chagne though if you aren't caught up to your master branch, see this PR - https://github.com/edx/edx-platform/pull/1156/files

**Comment by carsongee** [comment]
Missed that, thanks.  Is it alright if we merge this anyway since it won't hurt anything, and then after the commit makes it to a release tag I can put in a PR to nuke these all together?  I'm cool either way mind you.  I can just close this if you prefer.

**Comment by jarv** [comment]
sure thing, :+1:

**Pull request merged**
