### PR TITLE
Node 8

### PR DESCRIPTION
**Pull request by arizzitano**
Changelog here: https://nodejs.org/en/blog/release/v8.0.0/. [No explicit upgrade guide](https://github.com/nodejs/node/issues/14225), unfortunately, but here's what we can expect:
- faster npm installs
- faster builds
- every project running node will need to check in a `package-lock.json` file (I've created [an epic to track this](https://openedx.atlassian.net/browse/FEDX-397))

### Ops Ansible Checklist
- [x] Sandbox: https://ari-node-8.sandbox.edx.org/
- [x] Sandbox from scratch: https://ari-node-8-from-scratch.sandbox.edx.org/
- [x] Sandbox with manual update: https://ari-node-8-manual-update.sandbox.edx.org/
- AMIs
    - [x] edx-platform: ari-prod-edx-edxapp-1515004918
    - [x] ecommerce: ari-prod-edx-ecommerce-1515013728
    - [x] Testeng jenkins worker: https://build.testeng.edx.org/job/build-packer-ami/8439/

---

Make sure that the following steps are done before merging:

  - [x] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [x] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

### CODE REVIEW

**Comment by arizzitano** [comment]
I think this is the failure:
```
TASK [edx_django_service : install development requirements] *******************
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": ["make", "requirements"], "delta": "0:00:07.209741", "end": "2017-11-27 19:16:47.613636", "failed": true, "rc": 2, "start": "2017-11-27 19:16:40.403895", "stderr": "npm ERR! Cannot read property '0' of undefined\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /edx/app/ecommerce/.npm/_logs/2017-11-27T19_16_47_598Z-debug.log\nmake: *** [requirements.js] Error 1", "stdout": "npm install\nMakefile:34: recipe for target 'requirements.js' failed", "stdout_lines": ["npm install", "Makefile:34: recipe for target 'requirements.js' failed"], "warnings": []}
	to retry, use: --limit @/edx/app/edx_ansible/edx_ansible/docker/plays/ecommerce.retry
```
Going to debug in a devstack.

**Comment by feanil** [comment]
Looks like that error can happen when the version of node and the version of npm mismatch?  We use [nodeenv](https://github.com/ekalinin/nodeenv) under the covers to install the correct version of node.  I'm not sure how it determines which versions of npm to install by default so that might be the issue.

**Comment by arizzitano** [comment]
Yeah, looks like [8.9.1 uses node 5.5.1](https://github.com/nodejs/node/blob/master/deps/npm/package.json#L2), which has caused this issue for a number of other people. Per [this thread](https://github.com/npm/npm/issues/17858), the go-to fix is pinning npm to 5.2.0. This is not a great solution as it gets our npm version out-of-sync with the stock npm version that comes with node, plus it adds additional complexity to our configuration.

For now I'm going to see if the 8.9.2 candidate (https://github.com/nodejs/node/pull/17204) fixes this. If yes, let's wait for it to drop; if not, I'd say let's use an earlier, stable version of 8.x.

**Comment by arizzitano** [comment]
Check it out, [8.9.2 dropped yesterday](https://github.com/nodejs/node/releases/tag/v8.9.2)! If tests pass let's go with that, otherwise here are our options (in order of preference)
- Install an older version of Node that comes bundled with an older npm; add a follow-on ticket to check back in on this in a month or so. Interestingly, no Node release has ever bundled `npm@5.2.0`, which supposedly fixes this issue. Node versions to try, ranked: 
    - [x] ~8.9.0~
    - [x] ~8.8.1~
    - [x] ~8.7.0~
    - [ ] 8.6.0
    - [ ] 8.5.0
    - [ ] 8.4.0
    - [ ] 8.3.0
    - [ ] 8.2.1
    - [ ] 8.1.4
- Stick with Node 8.9.2, but add a `common_npm_version` pointing at a different release of npm. We should first try 5.6.0 (latest and the npm team claims it fixes this issue), then 5.2.0 (old, but multiple users in the above linked thread claim it fixes the issue for them). Add an Ansible step to explicitly install that version of npm:
```
npm install -g npm@version
```
- Triage any of the following workarounds locally. If any of them works, add Ansible steps to force it. This is not a desirable solution.
    - [ ] https://github.com/npm/npm/issues/17858#issuecomment-346422421
    - [ ] https://github.com/npm/npm/issues/17858#issuecomment-342002048
    - [ ] https://github.com/npm/npm/issues/17858#issuecomment-348470869

**Review by fredsmith — APPROVED** [review]

**Pull request merged**
