### PR TITLE
Updated base Dockerfiles

### PR DESCRIPTION
**Pull request by clintonb**

### CODE REVIEW

**Comment by clintonb** [comment]
Thoughts @gsong?

FYI @rlucioni

**Review by rlucioni — APPROVED** [review]

**Review by gsong — APPROVED** [review]

**Comment by clintonb** [comment]
@edx/devops any input/approvals?

**Comment by feanil** [comment]
What is generating zombie processes?

**Comment by clintonb** [comment]
We don't necessarily have zombie processes. Some processes may not respond appropriately to the exit signal, which could lead to Docker Compose timing out and potentially shutting down databases in the middle of write operations.

@gsong can provide a better explanation.

**Comment by gsong** [comment]
I believe gunicorn expects SIGINT or SIGQUIT, and `manage runserver` expects SIGINT. Docker sends SIGTERM, so we need something to make that translation, such as [Tini](https://github.com/krallin/tini).

**Comment by feanil** [comment]
Looks like supervisor handles all the signals except for SIGUSR1 in a resonable way: http://supervisord.org/running.html#signals

I'm concerned with making an unofficial container the base of our containers.  I think it's not a reasonable thing to do from a security perspective.

**Comment by gsong** [comment]
@feanil I think the intent is that there are cases where we won't use supervisor. We can also just install Tini manually in the Dockerfile instead of using the image.

```
ARG TINI_VERSION
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
```

You can then override entry points using Compose files for containers that need Tini:

```
entrypoint:
  - /tini
  - "--"
```

**Comment by feanil** [comment]
@gsong It seems strange to have two tools that do similar things, in my mind, supervisor is just a python based init engine, not sure what the benefit is to having tini instead.  I buy that there might be slightly extra overhead with this, but I think before we commit to TINI we should update the OEP and get consensus.  This is a small technical change but not a small technology decision.

**Comment by feanil** [comment]
At the very least the OEP should be corrected.

**Pull request closed without merging**
