### PR TITLE
chmod and chown the edx_ansible_venv_dir to make vagrant provision more reliable

### PR DESCRIPTION
**Pull request by macdiesel**
Make sure that the following steps are done before merging

  - [ ] A devops team member has commented with :+1:
  - [ ] are you adding any new default values that need to be overridden when this goes live?
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

### CODE REVIEW

**Review by doctoryes — APPROVED** [review]
I hit this problem when configuring a new open-release/ficus.2 Vagrant devstack. I solved it using `sudo chown -R edx-ansible.edx-ansible /edx/app/edx_ansible/venvs/edx_ansible/lib` as the vagrant user - but this Ansible addition would work better.

**Review by fredsmith — APPROVED** [review]

**Comment by jibsheet** [comment]
While this may help devstacks, in Slack someone is reporting failed sandboxes and @benpatterson is reporting failing packer builds.

please revert until it can be tested further.

**Comment by doctoryes** [comment]
Is the gauntlet of tests which need to be run for particular configuration changes written down anywhere? If so, perhaps a link to it should be in the repo commit message.

**Comment by jibsheet** [comment]
@doctoryes  https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist

If you want to PR it into the .github/PULL_REQUEST_TEMPLAT.md I won't object.
I expect it may want some updating for the GoCD world we now live in.

**Comment by benpatterson** [comment]
@doctoryes @jibsheet speaking for the packer builds, that's something we *could* hook up; however, we haven't added it to CI in here because it can take 1.5-2 hrs (part of what it does is build the venv from scratch).

**Comment by jibsheet** [comment]
Yes, we don't run our full CI because the hourly one takes 70 minutes and the from scratch one takes a few hours.  We provide instructions to run them yourself and examine the output on potentially breaking changes (link above).  Same link refers to packer I believe.

**Pull request merged**
