### PR TITLE
Remove unused insights variable

### PR DESCRIPTION
**Pull request by kluo**
@e0d

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @kluo! I've created [OSPR-580](https://openedx.atlassian.net/browse/OSPR-580) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams. 

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ('this must be merged by XX date', and why that is)
- partner information ('this is a course on edx.org')
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the Github pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by sarina** [comment]
@kluo I don't know how to verify this is unused. I'm hoping someone from @dsjen 's team can take a look at this 1 line change and confirm/deny.

**Comment by dsjen** [comment]
That does look like an unused setting to me, but I'm unsure of how the configs map to settings in Insights.  @e0d, can you shed some light on `INSIGHTS_OATH2_KEY` is unused?  It looks like a typo to me.

**Comment by feanil** [comment]
Looks like this is a mis-spelled version of line 23 below it.

**Comment by e0d** [comment]
Agree :+1:

**Pull request merged**
