### PR TITLE
Make the special exams toggle configurable

### PR DESCRIPTION
**Pull request by fghaas**
`ENABLE_SPECIAL_EXAMS` being set to `True` is a prerequisite for enabling timed exams, which are documented as standard Open edX course features in

* https://edx.readthedocs.io/projects/open-edx-ca/en/latest/course_features/timed_exams.html
* https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/course_features/timed_exams.html

Make this flag configurable from the `edxapp` role, via the variable `EDXAPP_ENABLE_SPECIAL_EXAMS`, retaining the previously hardcoded value (`false`) as the default.

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @fghaas! I've created [OSPR-4853](https://openedx.atlassian.net/browse/OSPR-4853) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@fghaas Thank you for your contribution. @fredsmith Could you give this a look when you have a chance?

**Comment by fghaas** [comment]
@natabene @fredsmith Taking the liberty to follow up on this — I try to do this once a week, just so you know I haven't lost interest in getting this landed. 🙂

**Comment by fghaas** [comment]
Weekly follow-up on this one, courtesy tag for @natabene and @fredsmith.

**Comment by natabene** [comment]
@fghaas Thanks for reminding, we have not forgotten about your PRs. Right now we lack bandwidth to review them. We will try to get to them in the next few weeks.

**Comment by fghaas** [comment]
@natabene Just following up here again, after 3½ weeks.

**Comment by fghaas** [comment]
@natabene, it's been a month since the most recent reply. Do you still think that this patch will be reviewed, or should I close it and move on?

The same functionality that this patch adds can also be enabled by overriding all of `EDXAPP_FEATURES`, and setting `ENABLE_SPECIAL_EXAMS: True` in that.

**Comment by natabene** [comment]
@fghaas Our team is stretched thin, so unfortunately we had little bandwidth to address this. We will review it in the coming weeks, just not sure when. It is up to you if you want to bear with us more or close it now.

**Review by fredsmith — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@fghaas 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/5886&entry.1484655318=https://github.com/fghaas&entry.752974735=2020-07-23+21:38&entry.1917517419=2020-09-09+15:02&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by fghaas** [comment]
Thanks @fredsmith — Juniper cherry-pick is in #6000 (courtesy tag for @nedbat).

**Pull request merged**
