### PR TITLE
Increasing No of gunicorn workers

### PR DESCRIPTION
**Pull request by muzaffaryousaf**

### CODE REVIEW

**Comment by muzaffaryousaf** [comment]
@fredsmith Do we need to merge this PR or should i close ?

**Comment by muzaffaryousaf** [comment]
I'm also not sure if we need to add hashlib or not.

**Comment by feanil** [comment]
This setting should be managed in secure config as it is specific to the sizing of the hardware we use in our deployment.

**Comment by muzaffaryousaf** [comment]
@feanil Thanks for looking into. I suppose that's something Ops can do and maybe @fredsmith already made the changes in secure repo ?

**Comment by e0d** [comment]
The value is 6 in secure config, I think this PR should be closed.

**Comment by muzaffaryousaf** [comment]
Thanks @e0d for looking into.

**Pull request closed without merging**
