### PR TITLE
Remove ORA1 references

### PR DESCRIPTION
**Pull request by stvstnfrd**
I noticed these were still floating around..

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @stvstnfrd! I've created [OSPR-1358](https://openedx.atlassian.net/browse/OSPR-1358) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by shaunagm** [comment]
@adampalay, any thoughts about this?

**Comment by adampalay** [comment]
@shaunagm , I think it makes more sense for devops to look at this, but since we don't have ORA1 anymore, I don't see why this wouldn't be an issue! (thanks @stvstnfrd ) @jibsheet ?

**Comment by jibsheet** [comment]
I'm luckily blissfully unaware of ORA1, but I threw this in as one of our OSPRs for the sprint planning happening tomorrow.

**Comment by feanil** [comment]
@stvstnfrd this looks great,  it looks like there is still a dangling reference [here](https://github.com/edx/configuration/blob/edc67b6875ad0f2e6e34b845442d208e2b6972a6/playbooks/roles/nginx/defaults/main.yml#L94-L95) in the nginx defaults. Mind grabbing that as well?  Then I think we can merge this.

**Comment by feanil** [comment]
I noticed that that change was only on your branch and is gone from master.

**Pull request merged**
