### PR TITLE
Fix S3 edxapp_media_dir leading slash issue

### PR DESCRIPTION
**Pull request by lgp171188**
`django-storages` 1.8 throws an error when the storage location path for an S3 bucket starts with a leading `/`. (Reported in [CRI-206](https://openedx.atlassian.net/browse/CRI-206)). This happens because `edxapp_media_dir` used as the default value of the `location` parameter and it has a default value of `/edx/var/edxapp/media`. The older versions of `django-storages` automatically translated `/edx/var/edxapp/media` to the path `edx/var/edxapp/media` on the S3 buckets. But in 1.8 they raise an `ImproperlyConfigured` exception ([code](https://github.com/jschneier/django-storages/blob/1.8/storages/utils.py#L82)).

This PR attempts to fix this issue by removing the leading `/` from the variable passed to the `location` parameters.

Reference: [discussion on Slack](https://openedx.slack.com/archives/CSAC4QHC7/p1589971174063800)

CC @nedbat 

Sandbox URL: https://s3-leading-slash.opencraft.hosting (credentials: the default demo staff user credentials)

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @lgp171188! I've created [OSPR-4566](https://openedx.atlassian.net/browse/OSPR-4566) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Review by nedbat — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@lgp171188 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/5789&entry.1484655318=https://github.com/lgp171188&entry.752974735=2020-05-20+14:28&entry.1917517419=2020-05-20+17:06&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by misilot** [comment]
This breaks access to uploading video transcripts in Juniper, as the path becomes a relative path for the location instead of being ``` location: /edx/var/edxapp/media/``` is is ``` location: edx/var/edxapp/media/```

CRI-220

**Comment by lgp171188** [comment]
@misilot, `django-storages==1.8`, which is the version in Juniper, has a check for a leading slash in the value of `location` and throws an error if there is one ([code](https://github.com/jschneier/django-storages/blob/1.8/storages/utils.py#L81-L90)) and this fix was added to prevent the library from throwing that error. When we tested the fix, we verified and confirmed that with `edx/var/edxapp/media` as the value, the files were getting stored under the same directory structure on the S3 bucket.

Since this variable is used only when S3 is used, it shouldn't affect the non-S3 scenarios at all.

So can you provide more details about the issue that you ran into, the version of the `django-storages` library installed (if you have customized it) and the steps to reproduce it?

**Comment by misilot** [comment]
@lgp171188 sure let me try and explain my scenario

1. Native install of Juniper
2. Utilizing the update script and server-vars.yml
3. using ```django-storages               1.8```. No customizations
4. Create Course
5. Add video
6. Add transcript. This fails to upload because it cannot find the directory, defined in https://github.com/edx/configuration/blob/open-release/juniper.master/playbooks/roles/edxapp/defaults/main.yml#L884-L890

Which the ansible built studio.yml has the values
```yaml
VIDEO_TRANSCRIPTS_SETTINGS:
    DIRECTORY_PREFIX: video-transcripts/
    STORAGE_KWARGS:
        base_url: /media/
        location: edx/var/edxapp/media/
    VIDEO_TRANSCRIPTS_MAX_BYTES: 3145728
```

Once I added the leading slash to the location field and restarted studio/lms and tried adding a transcript, it uploaded successfully. 


This value is built from the following inheritance of variables. This doesn't appear to have any logic built into it determine if you are using S3 or not, so it always uses the S3 value.

```yaml
# This is django storage configuration for Video Transcripts settings.
EDXAPP_VIDEO_TRANSCRIPTS_SETTINGS:
  VIDEO_TRANSCRIPTS_MAX_BYTES : 3145728
  STORAGE_KWARGS:
    location: "{{ edxapp_media_dir_s3 }}/"
    base_url: "{{ EDXAPP_MEDIA_URL }}/"
  DIRECTORY_PREFIX: 'video-transcripts/'
```

```yaml
edxapp_media_dir_s3: "{{ edxapp_media_dir | regex_replace('^\\/', '') }}"
```

```yaml
edxapp_media_dir: "{{ edxapp_data_dir }}/media"
```

```yaml
edxapp_data_dir: "{{ COMMON_DATA_DIR }}/edxapp"
```

```yaml
COMMON_BASE_DIR: /edx
COMMON_DATA_DIR: "{{ COMMON_BASE_DIR}}/var"
```

I hope this helps explain what I am running into.

**Comment by lgp171188** [comment]
@misilot, does your setup use the local filesystem storage or does it use S3?

**Comment by misilot** [comment]
Local file system

**Comment by lgp171188** [comment]
@misilot, @nedbat, there is a [PR](https://github.com/edx/configuration/pull/6014) for fixing this issue. FYI.

**Pull request merged**
