### PR TITLE
feat: added new setting CUSTOM_RESOURCE_TEMPLATES_DIRECTORY

### PR DESCRIPTION
**Pull request by keithgg**
**Note: This PR has a corresponding edx-platform PR https://github.com/openedx/edx-platform/pull/30108**

## Description

At Opencraft, we have clients that want to be able to add custom HTML templates that show up while creating course components in Studio.

Currently, there's no way to achieve this besides forking `edx-platform` and adding the `yaml` files to `common/lib/xmodule/xmodule/templates/`

This PR allows operators to set a custom directory where templates can be additionally loaded from.

- Checks if `settings.CUSTOM_RESOURCE_TEMPLATES_DIRECTORY` exists.
- If so, load the `yaml` files with the same logic as in the `xmodule/templates` directory.

## Supporting information

- Platform PR: https://github.com/openedx/edx-platform/pull/30108
- Forked PR: https://github.com/open-craft/edx-platform/pull/453
- JIRA: https://tasks.opencraft.com/browse/BB-5885
- Sandbox: https://studio.pr30108.sandbox.opencraft.hosting/ [Sandbox]

## Testing instructions

- Update the setting `settings.CUSTOM_RESOURCE_TEMPLATES_DIRECTORY` to a valid path.
- In that directory create an `html` directory.
- Copy a template from `common/lib/xmodule/xmodule/templates/html` to the above directory with a different filename.
- In the Studio, edit a Unit. Under the **Text** component you should see your new template list.

## Deadline

"None"

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @keithgg! I've created [OSPR-6541](https://openedx.atlassian.net/browse/OSPR-6541) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@keithgg Thank you for your contribution. Is this ready for our review?

**Comment by keithgg** [comment]
@natabene yes it is. Thank you.

**Review by nadeemshahzad — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@keithgg 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/configuration&entry.867055334=https://github.com/openedx/configuration/pull/6706&entry.1484655318=https://github.com/keithgg&entry.752974735=2022-03-25+08:24&entry.1917517419=2022-04-04+09:13&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
