### PR TITLE
Added programs service to devstack

### PR DESCRIPTION
**Pull request by clintonb**
ECOM-2184

@feanil @jimabramson @rlucioni

FYI @bderusha @peter-fogg @cpennington

### CODE REVIEW

**Comment by rlucioni** [comment]
:+1:

**Comment by clintonb** [comment]
@fredsmith @maxrothman review please?

**Comment by maxrothman** [comment]
Same comment as https://github.com/edx/configuration/pull/2321

**Comment by clintonb** [comment]
Yes. At this point were are waiting on DevOps.

## 

Clinton Blackburn

**Comment by feanil** [comment]
Have you successfully built this?  What about fullstack?

**Comment by clintonb** [comment]
@feanil yes, I have built it. We are not focusing on fullstack at the moment.

**Comment by jimabramson** [comment]
any outstanding issues with this?   Having programs in devstack is about to become very useful.

**Comment by clintonb** [comment]
@jibsheet Review?

**Comment by feanil** [comment]
@singingwolfboy What are your thoughts on having full stack and devstack not matching with respect to which apps are running?  If this is okay from the opensource perspective it is fine by me but I would want those two to match so that we can have go parity for the open source community when they switch between these.

**Comment by jimabramson** [comment]
@singingwolfboy @feanil FYI this will become a blocker soon, as we need for platform and programs to be able to talk to each other inside devstack to get development work done.

**Comment by jbarciauskas** [comment]
How much effort is it to add fullstack?

**Comment by clintonb** [comment]
@jbarciauskas I have never touched fullstack; however, I would estimate 1-2 days. This is work that can be done later, closer to when we are ready to support open source installations of the programs service.

**Comment by jbarciauskas** [comment]
OK, I don't have a particular burning need for these to be done at the same time, but I want to make sure it doesn't get lost. If you're confident of that, then we can push ahead here

**Comment by clintonb** [comment]
ECOM-2597 created to track fullstack development.

**Comment by feanil** [comment]
:+1:

**Comment by clintonb** [comment]
@feanil what are the next steps for getting a new base box, and updating the release `Vagrantfile`?

**Pull request merged**
