### PR TITLE
Add a task to install paver requirements.

### PR DESCRIPTION
**Pull request by jarv**

### CODE REVIEW

**Comment by singingwolfboy** [comment]
Why not install paver globally?

**Comment by hkim823** [comment]
looks fine to me

**Comment by jarv** [comment]
@singingwolfboy  I think the issue with that is going to be if other code requires paver (and I assume it will eventually) what we do about multiple versions in multiple virtualenvs. If we always want to use the global paver then I think the thing to do is _not_  install this requirements file via ansible and instead have a global paver installed in the common role.

**Comment by singingwolfboy** [comment]
@jarv Sounds reasonable to me.

**Pull request merged**
