### PR TITLE
Updated credentials play to use edx_django_service play

### PR DESCRIPTION
**Pull request by clintonb**
- This removes the duplication across the various IDA configurations
- Updated Dockerfile for Docker-based devstack

LEARNER-816

**Testing**
- [x] Docker
- [x] Sandbox
- [x] Loadtest

### CODE REVIEW

**Comment by clintonb** [comment]
Loosely-dependent/related to https://github.com/edx/configuration/pull/3917.

**Comment by clintonb** [comment]
FYI @edx/devops I still need to resolve static file/media storage; but, feel free to take a cursory look at the rest of the changes.

**Comment by clintonb** [comment]
@edx/learner @edx/devops please review

**Comment by feanil** [comment]
@clintonb have you deployed this branch to LT yet?

**Comment by clintonb** [comment]
@feanil, yes, loadtest-credentials is running this branch.

**Comment by clintonb** [comment]
Rebuilding my sandbox since I used the wrong branch.

**Comment by clintonb** [comment]
Sandbox build was successful! It even includes the site and site configuration.

**Review by feanil — APPROVED** [review]

**Pull request merged**
