### PR TITLE
Allow the xqueue session engine to be configurable.

### PR DESCRIPTION
**Pull request by UmanShahzad**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

Complementary xqueue PR at https://github.com/edx/xqueue/pull/133.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @UmanShahzad! I've created [OSPR-2200](https://openedx.atlassian.net/browse/OSPR-2200) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by nedbat** [comment]
@edx/devops Another configuration change to support an xqueue pull request in your queue.

**Comment by UmanShahzad** [comment]
Thanks @nedbat :)

Note: I may have to update this PR to also allow a configurable `CACHES` var: the main reason for adding this configurable session engine is to allow it to use Memcache, but that has to be set by `CACHES` otherwise it'll default to the local memory cache.

**Comment by UmanShahzad** [comment]
@nedbat Ready for review!

**Review by smarnach — APPROVED** [review]
:+1: Looks good to me. I read through the code and tested this on an app server deployed using this and the related PRs, and it works fine.

**Comment by jibsheet** [comment]
@UmanShahzad This branch has conflicts, please rebase

**Comment by UmanShahzad** [comment]
@jibsheet Sorry for the lateness -- done.

**Comment by jibsheet** [comment]
I'm fine with this change but will wait until it plays well with the xqueue PR (when this is left as nulls)

**Review by jibsheet — APPROVED** [review]

**Comment by UmanShahzad** [comment]
@jibsheet Note that I don't have merge rights.

**Comment by openedx-webhooks** [comment]
@UmanShahzad 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4313&entry.1484655318=https://github.com/UmanShahzad&entry.752974735=2018-02-05+23:18&entry.1917517419=2018-03-16+13:59&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
