### PR TITLE
Variable to add extra custom config blocks to lms and cms nginx templ…

### PR DESCRIPTION
**Pull request by xirdneh**
- [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

**Rationale:**
This PR introduces two new optional variables `NGINX_EDXAPP_LMS_EXTRA` and `NGINX_EDXAPP_CMS_EXTRA`. The idea is to use these variables in case there's any extra custom configuration needed for nginx.
Our main use for this are clients who have other services running to manage their main site (e.g. wordpress) and they want specific redirects for the top domain. For instance, the site **learning.myschool.edu** wants every user to land on their wordpress site (**learning.myschool.edu/school**) instead of the default lms landing view. This can be managed through [edx-django-sites-extensions](https://github.com/edx/edx-django-sites-extensions) redirect app. The issue with this redirect app is that it will apply the redirect for the entire domain and since studio and lms share the same database then the previously described redirect applies for both lms' root and studio root. We end up with a redirect when a user goes to either **learning.myschool.edu** or **studio.learning.myschool.edu** to the wordpress site.
By adding this new variables we can add an nginx rule such as 
```
location = / {
    redirect 301 https://$hostname/school;
}
```
That will only apply for lms (or cms if needed) and will not conflict with other subsites (e.g. studio).
The variables are optional in the case that they are not defined the jinja template will not print anything. This way we do not break previously provisioned instances.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @xirdneh! I've created [OSPR-2919](https://openedx.atlassian.net/browse/OSPR-2919) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@xirdneh This is great, thank you for your contribution. @edx/devops  Can you have a look?

**Comment by openedx-webhooks** [comment]
@xirdneh Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4911&entry.1484655318=https://github.com/xirdneh&entry.752974735=2018-12-20+16:15&entry.1917517419=2019-01-11+20:59&entry.2133058324=No) so we can improve your experience in the future.

**Comment by openedx-webhooks** [comment]
Hello @xirdneh: We are unable to continue with review of your submission at this time. Please see the associated JIRA ticket for more explanation.

**Pull request closed without merging**
