### PR TITLE
First stab at getting the sqlite fix script in

### PR DESCRIPTION
**Pull request by bmedx**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

### CODE REVIEW

**Comment by feanil** [comment]
Did the conversation about making the unit tests use MySQL already happen somewhere else?  I believe we use MySQL when testing with Jenkins don't we?

**Comment by jibsheet** [comment]
Jenkins uses in-memory sqlite for unit tests (mysql for bokchoy)
https://github.com/edx/edx-platform/blob/master/lms/envs/test.py#L192-L200

**Comment by feanil** [comment]
Ah, was confusing the two.  Got it.

**Comment by bmedx** [comment]
These changes are specifically for devstack anyway. I believe, we're using sqlite for performance reasons there.

**Review by macdiesel — APPROVED** [review]

**Review by feanil — CHANGES_REQUESTED** [review]
Instead of putting a shell script on the remote server and executing, all of that could be done via ansible.  Rather than making it a part of the edxapp role, it should just be a new role(something like `fix_docker_sqlite` maybe?) that does this work and is included in the docker devstack playbooks.

**Comment by bmedx** [comment]
@feanil Ok, I'll kill this branch and start from scratch on a new PR then.

**Pull request closed without merging**
