### PR TITLE
Fix jinja2 syntax for remove unnecessary white spaces or line breaks …

### PR DESCRIPTION
**Pull request by smaeda-ks**
…within cms/lms.env.json

ref. http://jinja.pocoo.org/docs/dev/templates/#whitespace-control

Just for output json beautify.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @smaeda-ks! I've created [OSPR-1294](https://openedx.atlassian.net/browse/OSPR-1294) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by nedbat** [comment]
@edx/devops should be a quick review.

**Comment by feanil** [comment]
:+1:   looks good to me, @edx/devops second review?

**Comment by jibsheet** [comment]
👍

**Pull request merged**
