### PR TITLE
ECOM-2979

### PR DESCRIPTION
**Pull request by tasawernawaz**
## Configuration Pull Request

Make sure that the following steps are done before merging
- [x] @devops team member has commented with :+1:
- [x] are you adding any new default values that need to be overriden when this goes live?  
  - [x] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
  - [x] Add an entry to the CHANGELOG.

Added new setting variable "EXPIRING_SOON_WINDOW: 28"

FYI @schenedx

### CODE REVIEW

**Review by schenedx — APPROVED** [review]
👍  Please remember to file a devops ticket to have this value in the secure configuration repo as well

**Comment by tasawernawaz** [comment]
@edx/devops Please review this.

**Comment by tasawernawaz** [comment]
@schenedx Are we going to replace this value in secure vars? Do I really need to file a ticket to add this in secure configuration ?

**Comment by schenedx** [comment]
@tasawernawaz Good question about the value in secure-vars. Now that thinking this through, I guess you don't. But I don't have the knowledge to say it definitively. @edx/devops Can you confirm we don't need the value override in secure-config repo?

**Comment by jibsheet** [comment]
You can skip the DEVOPS ticket if you don't want your new variable passed down.
The top level variable here is overridden in secure vars for our ID verification code.
If you do not request an update to include your new variable, it will not be available in stage/prod/edge

Otherwise - code is fine 👍

**Comment by tasawernawaz** [comment]
@jibsheet Actually we require this variable on stage/prod. But it is not required to override this value which is `28 days`. Do we still need to file a ticket ?

**Comment by jibsheet** [comment]
@tasawernawaz If you don't request a secure override, prod and stage will not see your new addition to the data structure.  Is that clear?

**Comment by tasawernawaz** [comment]
@jibsheet 
- I have created a ticket https://openedx.atlassian.net/browse/DEVOPS-4948. Let me if I need to add any other information in ticket.
- How I can add entry in CHANGELOG, where it is ?

**Comment by tasawernawaz** [comment]
FYI @schenedx ^

**Comment by schenedx** [comment]
@tasawernawaz The CHANGELOG is https://github.com/edx/configuration/blob/master/CHANGELOG.md. So just add a new line to that file

**Comment by tasawernawaz** [comment]
@schenedx Thanks!
Added entry in CHANGLOG.md

**Pull request merged**
