### PR TITLE
Allow for extra dev packages to be installed on docker images.

### PR DESCRIPTION
**Pull request by feanil**
Review: @e0d  @clintonb @jibsheet 

Here is what I was thinking regarding this conversation(https://github.com/edx/ecommerce/pull/1026#discussion_r89206094).

### CODE REVIEW

**Review by clintonb — APPROVED** [review]
This will be needed for all IDAs.

**Review by jibsheet — APPROVED** [review]

**Comment by e0d** [comment]
@feanil I have some questions about this.  Let me write them out and we can discuss.

**Comment by feanil** [comment]
@clintonb I'm happy to merge this but will not be making the changes to the other IDAs.  If we're happy with this as an approach to achieve this, I think in general, we should be documenting the best practice and let the IDA teams update as it makes sense to them.  Thoughts?

**Comment by feanil** [comment]
@clintonb @e0d thinks this merits further discussion and so I setup a meeting for tomorrow to do that.  Given that this is about designing a new approaching to keep test and production settings separate, I think this should not hold up the work I have previously done.  Once we have decided on a final approach, the IDA teams can update their testing based on what is decided.  In the meantime I'd like to merge https://github.com/edx/ecommerce/pull/1026 as is.

**Pull request closed without merging**
