### PR TITLE
[SE-4304] Cherry-pick add celerybeat configuration

### PR DESCRIPTION
**Pull request by gabor-boros**
This PR cherry-picks commits from PR https://github.com/edx/configuration/pull/6407 and https://github.com/edx/configuration/pull/6442.

The first PR added was responsible for adding a custom scheduler configuration while the second PR fixes that in a way to let workers scale.

**Dependencies**: None

**Merge deadline**: ASAP

**Testing instructions**:

* Proofread the configuration changes

**Author notes and concerns**:

_The PRs were already tested._

**Reviewers**
- [ ] @jdmulloy -- sorry for directly mentioning you on this PR, but you have the most context as you approved both previous PRs. If you'd like me to find another reviewer, please let me know!

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @gabor-boros! I've created [OSPR-5871](https://openedx.atlassian.net/browse/OSPR-5871) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@gabor-boros Thank you for your contribution. I assume this is ready for our review?

**Comment by gabor-boros** [comment]
@natabene I'll create an instance based on this configuration to test instance creation, but yes, this should be ready for review. 

Side note: A reviewer is already mentioned in the description who has the most context.

**Review by jdmulloy — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@gabor-boros 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6455&entry.1484655318=https://github.com/gabor-boros&entry.752974735=2021-06-21+08:09&entry.1917517419=2021-07-02+15:29&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by itsjeyd** [comment]
(Necessary follow-up changes from https://github.com/edx/configuration/pull/6450 for fixing [this issue](https://github.com/edx/configuration/pull/6442#issuecomment-873583281) have been added to Lilac via https://github.com/edx/configuration/pull/6467.)

**Pull request merged**
