### PR TITLE
updated format of cert template languages setting

### PR DESCRIPTION
**Pull request by McKenzieW**
Configuration Pull Request
dict --> list of tuples
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

### CODE REVIEW

**Comment by McKenzieW** [comment]
@edx/devops can I get a quick review on this data structure change to a config variable I recently added?

**Comment by jibsheet** [comment]
@McKenzieW Got a platform PRl ink?  Or was the format wrong and you're fixing to match what platform wants?

**Comment by McKenzieW** [comment]
@jibsheet the format was wrong, this is a fix for what platform wants

**Comment by jibsheet** [comment]
Have you tested the yaml -> json of this on a sandbox or something else that goes through ansible?  As best I can tell, your current version is a list of 2 strings.  You can get a list of lists by doing something like
```
- ["en","English"] 
```
or
```
-
  - en
  - English
```
 but that's a list, not a tuple.  Tuples are harder and I'm honestly not sure ansible is going to support them since pyyaml only does so with tags. http://pyyaml.org/wiki/PyYAMLDocumentation#YAMLsyntax

**Comment by McKenzieW** [comment]
@jibsheet you're right. In all honesty I don't have much experience with yaml and made some incorrect assumptions about how it would be converted. It seems like it will probably make more sense to just update the lms-side logic to deal with the data in its existing format. So no need for this PR anymore.

**Comment by jibsheet** [comment]
@McKenzieW If it's easier on the platform side to do list of lists -> list of tuples, I'm happy to help you get the lists of lists right (although list of dicts -> list of tuples should also be an easy comprehension)

**Comment by McKenzieW** [comment]
@jibsheet Thank you! I think I've got the dict --> tuples logic down though, so we should be all set here.

**Pull request closed without merging**
