### PR TITLE
Add BROKER_URL setting to ecommerce defaults

### PR DESCRIPTION
**Pull request by rlucioni**
Corresponds to the changes introduced in https://github.com/edx/ecommerce/pull/336.

@feanil, @clintonb, and/or @jimabramson, please review.

### CODE REVIEW

**Comment by clintonb** [comment]
:+1:

**Comment by fredsmith** [comment]
:+1:

**Comment by feanil** [comment]
:+1:

**Comment by rlucioni** [comment]
@feanil or @fredsmith, is there anything I can do to help make sure this is set for stage and prod?

**Comment by rlucioni** [comment]
I answered my own question by filing [DEVOPS-2895](https://openedx.atlassian.net/browse/DEVOPS-2895).

**Pull request merged**
