### PR TITLE
Feat/announcements update

### PR DESCRIPTION
**Pull request by jamestang12**
Update config for course announcements banner

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @jamestang12! I've created [OSPR-5789](https://openedx.atlassian.net/browse/OSPR-5789) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by nedbat** [comment]
@jamestang12 looks like this pull request was meant to go somewhere else?

**Comment by jamestang12** [comment]
Yea I’m sorry

**Comment by nedbat** [comment]
np! :)

**Comment by openedx-webhooks** [comment]
@jamestang12 Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6411&entry.1484655318=https://github.com/jamestang12&entry.752974735=2021-05-17+21:23&entry.1917517419=2021-05-18+01:40&entry.2133058324=No) so we can improve your experience in the future.

**Comment by jamestang12** [comment]
Finished, thank you

**Pull request closed without merging**
