### PR TITLE
fix NOTIFIER_DD_API_KEY to follow convention

### PR DESCRIPTION
**Pull request by jbau**
@feanil @hkim823 @jarv 

A simple bugfix, I think.  DATADOG_API_KEY was not following convention in notifier playbook

### CODE REVIEW

**Comment by e0d** [comment]
I don't think this is the right thing to do as typically there would be a single dd key that would be used by all of your applications.  Doing 

FOO_DD_API_KEY: "{{ DD_API_KEY }}" 

in each role seems like a bit much.  Either way, this will definitely break our current installation without secrets changes.

**Comment by jbau** [comment]
ok. well, it seemed a bit inconsistent with the rest of notifier, and it was the other way at somepoint, but nbd.

**Comment by e0d** [comment]
Upon reflection, the right thing to do here is probably to merge this and use this convention:

FOO_DD_API_KEY: "{{ DD_API_KEY }}"

In our private vars files, though it is clutter, it makes each individual role stand on its own.

**Comment by jbau** [comment]
OK.  I'll leave the merging up to you guys, then, (i.e. when you're done modifying the secrets files)

**Comment by jarv** [comment]
The datadog api key has been moved into common so I don't think we want to merge this

**Pull request closed without merging**
