### PR TITLE
[WIP] [DO NOT MERGE] Branch for community deployment test

### PR DESCRIPTION
**Pull request by morenol**
This PR has the commits from:
1) https://github.com/edx/configuration/pull/6088
2) https://github.com/edx/configuration/pull/6049

On top of that it changes the native installation script to clone this branch of configuration from the edunext fork (in order to use this branch for the deployment) and also disables the installation of forum because it is having problems unrelated to MFEs

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @morenol! I've created [OSPR-5111](https://openedx.atlassian.net/browse/OSPR-5111) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by morenol** [comment]
Instrucciones for deployment, similar to the native installation recommendations:
1) run these commands:
```bash
export OPENEDX_RELEASE=master
wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/ansible-bootstrap.sh -O - | sudo -E bash
wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/generate-passwords.sh -O - | bash
```
2) Create a config.yml with something similar to this, make sure of change the domains and certificates:

```yaml
#config.yml
EDXAPP_LMS_BASE: "mfe.stage.edunext.co"
EDXAPP_CMS_BASE: "studio.mfe.stage.edunext.co"
MFE_DEPLOY_COMMON_HOSTNAME: "app.mfe.stage.edunext.co"

EDXAPP_LMS_BASE_SCHEME: https
MFE_BASE_SCHEMA: https

NGINX_ENABLE_SSL: yes

NGINX_SSL_CERTIFICATE: 'mfe.pem'
NGINX_SSL_KEY: 'mfe.key'

EDXAPP_SESSION_COOKIE_DOMAIN: ".mfe.stage.edunext.co"

EDXAPP_CSRF_COOKIE_SECURE: true
EDXAPP_SESSION_COOKIE_SECURE: true 
EDXAPP_CROSS_DOMAIN_CSRF_COOKIE_DOMAIN: ".mfe.stage.edunext.co"
EDXAPP_CROSS_DOMAIN_CSRF_COOKIE_NAME: "cross-domain-cookie-mfe"

EDXAPP_CORS_ORIGIN_WHITELIST:
- studio.mfe.stage.edunext.co
- app.mfe.stage.edunext.co

EDXAPP_LOGIN_REDIRECT_WHITELIST:
- studio.mfe.stage.edunext.co
- app.mfe.stage.edunext.co

EDXAPP_CSRF_TRUSTED_ORIGINS:
- app.mfe.stage.edunext.co

# Needed to link the LMS instructor dashboard to the writable gradebook micro-frontend
EDXAPP_LMS_WRITABLE_GRADEBOOK_URL: https://app.mfe.stage.edunext.co/gradebook

# Needed to link to the new profile micro-frontend.
EDXAPP_PROFILE_MICROFRONTEND_URL: https://app.mfe.stage.edunext.co/profile/u/

# Needed to link to the new account micro-frontend.
EDXAPP_ACCOUNT_MICROFRONTEND_URL: https://app.mfe.stage.edunext.co/account

EDXAPP_LMS_SSL_NGINX_PORT: 443
EDXAPP_CMS_SSL_NGINX_PORT: 443

module_lang: en_US.UTF-8
module_set_locale: True

EDXAPP_ENABLE_CORS_HEADERS: true
EDXAPP_ENABLE_CROSS_DOMAIN_CSRF_COOKIE: true

# This will override the logo in the header with a dummy logo
MFE_NPM_OVERRIDES: ["@edx/frontend-component-header@git+https://github.com/edunext/frontend-component-header-edunext.git"]

# Needed to use the branches of the  PRs to update the MFEs
MFE_DEPLOY_GIT_PATH: 'edunext'
MFE_DEPLOY_VERSION: 'lmm/build',
```

3) Run the native installation script from this branch
```
wget https://raw.githubusercontent.com/edunext/configuration/mfe/community_deployment/util/install/native.sh -O - | bash
```

**Comment by natabene** [comment]
@morenol Thank you for your contribution. Please let me know once it is ready for our review.

**Comment by openedx-webhooks** [comment]
@morenol Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6128&entry.1484655318=https://github.com/morenol&entry.752974735=2020-11-05+15:53&entry.1917517419=2020-11-15+21:05&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
