### PR TITLE
Make the condition on migrate_db a bit safer for using in var_prompt

### PR DESCRIPTION
**Pull request by jbau**
@feanil  @jarv 

Since we use vars_prompt for migrate_db, I wanted to reduce the possibility of accidentally running migrations.  So I've make the condition on it a bit stronger.

### CODE REVIEW

**Comment by jarv** [comment]
looks good

**Comment by feanil** [comment]
Looks good.

**Comment by jarv** [comment]
I think we should eventually do a db migration dry run and then prompt if one is necessary but that can come later.

**Comment by jbau** [comment]
@jarv yeah, I think that feature would be nice. (future PR =) )

**Pull request merged**
