### PR TITLE
Updated LOG_DIR parameter for edxapp and xqueue

### PR DESCRIPTION
**Pull request by blarghmatey**
There was a typo on the `LOG_DIR` parameter for edxapp and xqueue
which results in the application trying to write logs to a directory
that never gets created, thereby silencing those logs. Updated to use
the `COMMON_LOG_DIR` value rather than composing the directory ad-hoc
in only those two places.

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @blarghmatey! I've created [OSPR-1791](https://openedx.atlassian.net/browse/OSPR-1791) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by jibsheet** [comment]
This looks fine and trivial, I'm just super confused what's going on with the real logs (I'm used to seeing logs into /edx/var/log/[cl]ms/edx.log )  I'll see if I can chase further later.

**Comment by jibsheet** [comment]
Ah, hah.  Yes, so logsettings.py in edx-platform + rsyslog in configuration is what gets logs into /edx/var/log/lms/edx.log 

I'd want to build a sandbox with this and see what happens (and suspect the right thing here is to actually fix this config to align with all the other log config settings).

**Comment by e0d** [comment]
@jibsheet is this good to merge?

**Comment by jibsheet** [comment]
@e0d no, haven't had cycles to build the sandbox.  Given current workloads, we really need to be better about pulling OSPRs into sprints to review.  I don't have cycles to do a test like that out-of-sprint right now.

**Pull request closed without merging**
