### PR TITLE
Ensure ansible is run on the release vagrant box

### PR DESCRIPTION
**Pull request by mulby**
Release the analyticstack Vagrantfile.

Note that for this to work the box file needs to be uploaded to files.edx.org. I submitted [a ticket for that work.](https://openedx.atlassian.net/browse/DEVOPS-2804)

Reviewers: @e0d, @feanil

### CODE REVIEW

**Comment by feanil** [comment]
@mulby what is the motivation behind running ansible on startup, I know we currently do this for the release devstack but I've been seriously considering not doing so.

**Comment by mulby** [comment]
The repos aren't being checked out into the NFS mounted folders, we could manually do those steps in the Vagrantfile?

**Comment by mulby** [comment]
@feanil I didn't want to replicate the logic associated with the git checkout since it was non-trivial and governed by a bunch of variables... I suppose we could create a tag that only performed checkouts?

**Comment by feanil** [comment]
Why not just let the user manage the checkouts themselves?  This is what I was thinking of doing with the release version of devstack.  This is already the expectation for day to day use so I figure the odd this is doing an update for them at all in the first place.

**Comment by mulby** [comment]
We wanted a "one-click" setup. So you would just "vagrant up" and everything would work instead of "vagrant up" followed by "checkout 6 different repos into the correct folders".

**Comment by mulby** [comment]
@feanil and @e0d - Note that there is a bit of time pressure here, since we want to release our documentation and this Vagrantfile along with a blog post next week. Everything is ready to go, but we need to merge this to master before we publish the docs since they instruct users to download this file.

**Comment by feanil** [comment]
:+1:

**Comment by e0d** [comment]
:+1:

**Pull request merged**
