### PR TITLE
OPS-1383: Add role for turning on enhanced networking

### PR DESCRIPTION
**Pull request by maxrothman**
@edx/devops

### CODE REVIEW

**Comment by feanil** [comment]
You use a profile when directly calling the aws cli but not when you are using the `ec2` module?  What's the reason for the inconsistency?

**Comment by smaeda-ks** [comment]
Hi,

Anyway it looks like need few more tasks for this role if we use Ubuntu, right?

http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html#enhanced-networking-ubuntu

**Comment by maxrothman** [comment]
@smaeda-ks we only ever run this role on Ubuntu 14.04 which already has the kernel module installed, so those steps are not necessary. However, I will add a check to the beginning of this role that makes sure you've got >14.04.

**Comment by smaeda-ks** [comment]
@maxrothman 

Thank you for the information.
I understood.

Thanks

**Comment by jibsheet** [comment]
@smaeda-ks I added some kernel module checking (Rather than explicit OS checking) but we're running this on 14.04 for our mongo hosts.
@feanil I don't know why profile was missing from the ec2 module call, I've added it while I was touching up the kernel module checking.

**Pull request merged**
