### PR TITLE
Once this mv runs on the base box, it fails on provision

### PR DESCRIPTION
**Pull request by jibsheet**
Just ensure the file is gone.

FYI @benpatterson @nedbat 
@edx/devops  this plus my new base box will resolve devstacks from release.

### CODE REVIEW

**Comment by nedbat** [comment]
I tested this by cherry-picking onto named-release/dogwood.rc, and it is good. :+1:

**Comment by feanil** [comment]
:+1:

**Comment by benpatterson** [comment]
Awesome. Could you kick off a packer build for this branch just to be sure? That said, :+1:

**Comment by jibsheet** [comment]
@benpatterson https://build.testeng.edx.org/view/packer/job/build-packer-ami/830/console

**Pull request merged**
