### PR TITLE
Fix incorrect variable used for mongo clustered

### PR DESCRIPTION
**Pull request by rohitkode**
Change mongo_clustered --> MONGO_CLUSTERED

Fixed Issue #1450

### CODE REVIEW

**Comment by sarina** [comment]
Hi @rohit-k, Thanks for the contribution! However, we can't review or merge it until you've submitted a [signed contributors agreement](http://code.edx.org/individual-contributor-agreement.pdf) and added yourself to the [AUTHORS](https://github.com/edx/edx-platform/blob/master/AUTHORS) file, as documented in the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst) file in the repository. Once you've done those two things, a core committer can review your pull request, and hopefully we can get it merged!

**Comment by rohitkode** [comment]
Hi Sarina,

I've sent the signed, scanned copy of the agreement to jennifer@edx.org, and added a commit to this pull request, with my info in AUTHORS.

Thanks!
Rohit

**Comment by feanil** [comment]
looks good to me @rohit-k.  @fredsmith can you do the second review?

**Comment by fredsmith** [comment]
:+1: - that's been bugging me.

**Comment by feanil** [comment]
@rohit-k this looks good, can you add a change log entry so that people who may have been using the lowercase version can know that this will break them.  Then I think this is good to merge.

**Comment by feanil** [comment]
Also please leave a comment when that is done because we don't get notifications for just new commits added.

**Comment by rohitkode** [comment]
Oops, sorry  I deleted the previous branch hence the pull request got closed.
I'm issuing a new one ASAP.

**Pull request closed without merging**
