### PR TITLE
edxapp on django 1.8

### PR DESCRIPTION
**Pull request by fredsmith**

### CODE REVIEW

**Comment by nedbat** [comment]
@fredsmith can you help me understand what these changes have to do with Django 1.8?

**Comment by fredsmith** [comment]
@nedbat - our pre-supervisor script checks to see if any migrations are pending before starting edxapp.  in Django 1.8, the mechanism for checking for migrations is different.

**Comment by feanil** [comment]
:+1:

**Comment by smarnach** [comment]
This PR (specifically the first commit) likely caused the error mentioned in this post: https://groups.google.com/d/msg/openedx-ops/_3n07gcUq0A/tkLGogdjAAAJ

The problem also causes all of our sandbox deployments to fail.

I currently don't have time to properly debug this, but I thought it might be helpful to leave a comment about this anyway.

**Pull request merged**
