### PR TITLE
Add jenkins to splunk

### PR DESCRIPTION
**Pull request by maxrothman**

### CODE REVIEW

**Comment by maxrothman** [comment]
This stanza needs to be added to the appropriate var files:

```
  - source: /var/lib/jenkins/jobs/*/builds/*/log
    index: '{{ COMMON_DEPLOYMENT }}-jenkins'
    sourcetype: jenkins
    followSymlink: false
```

**Comment by feanil** [comment]
Please add your statement re:updating `SPLUNKFORWARDER_LOG_ITEMS` as a comment in the playbooks you are changing.

**Comment by feanil** [comment]
:+1:  after that.

**Comment by fredsmith** [comment]
👍

**Pull request merged**
