### PR TITLE
Don't restart edxapp after updating edx-platform using script on devstack

### PR DESCRIPTION
**Pull request by bdero**
@carsongee When using `/edx/bin/update edx-platform (branch)`, the "restart edxapp" task isn't skipped on the devstack - this fixes that.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @bdero! I've created [OSPR-172](https://openedx.atlassian.net/browse/OSPR-172) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams. Feel free to add information to the ticket which can help Product understand the context for the PR - supporting documentation, edx-code email threads, timeline information ('this must be merged by XX date', and why that is), partner information (this is for a course on edx.org, for example), etc. 

All technical communication about the code itself will still be done via the Github pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

We can't start reviewing your pull request until you've added yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS) file. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst) file for more information.

**Comment by feanil** [comment]
Why would you want to not restart the application?  The changed code won't be picked up until you do.

**Comment by bdero** [comment]
Because, on the devstack, apps are not managed by supervisor out of the box. Instead, direct instantiation of the dev server is encouraged by the official guide: https://github.com/edx/configuration/wiki/edX-Developer-Stack#lms-workflow

**Comment by feanil** [comment]
Makes sense.  Rather than putting the conditional there, I think it makes more sense to just add that to the extra_args var since it is used in multiple services not just exdapp.

**Comment by bdero** [comment]
Good point - this applies for many other roles as well. I made it add it to extra_args instead

**Comment by sarina** [comment]
@bdero please add yourself to `AUTHORS` for any new edX repo you add code to.

**Comment by bdero** [comment]
@sarina Oops, added my name to authors

**Comment by feanil** [comment]
Cool.  @jarv can you do the second review.

**Comment by jarv** [comment]
:+1:

**Pull request merged**
