### PR TITLE
[FAL-2000] Remove jdk role from openedx-native playbook and elasticsearch role dependencies

### PR DESCRIPTION
**Pull request by alfredchavez**
Configuration Pull Request
---
[FAL-2000](https://tasks.opencraft.com/browse/FAL-2000)
This PR will remove the oraclejdk role from openedx-native playbook and elasticsearch dependencies
Elasticsearch version 7.* uses its own bundled jdk version, so it does not need of the jdk role as its dependency, and the oraclejdk role is not needed to be executed from the openedx_native playbook, as there is no other role/task invoked there that uses jdk.
Tested it on a sandbox checking that elasticsearch(SearchEngine) worked correctly after applying the changes(no java/jdk installed in the sandbox instance) 

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @alfredchavez! I've created [OSPR-5925](https://openedx.atlassian.net/browse/OSPR-5925) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@alfredchavez Thank you for your contribution. Is this ready for our review?

**Comment by mtyaka** [comment]
Looks good to me :+1: Elasticsearch 7 bundles its own JVM, so no need to include the `oraclejdk` in the `openedx_native.yml` playbook.

- [x] I tested this: I verified that a sandbox was built successfully with this patch, and that ES on the sandbox functions correctly.
- [x] I read through the code

**Comment by alfredchavez** [comment]
@pomegranited I think this PR is ready for merge 😃

**Review by pomegranited — APPROVED** [review]
:+1: Thank you for this change @alfredchavez ! Removing the unneeded oraclejdk dependency will make our native deployments faster and more reliable -- we've been having intermittant trouble downloading the JDK from Oracle. 

FYI @nedbat and @feanil -- I'll merge this in 2 days if there are no objections?

- [x] I tested this on the sandbox server:
   - logged in as one of the test users
   - visited the discussion forum in the DemoX course
   - added a test post
   - ensured that i could search for terms used, and find that post
- [x] I read through the code
- [x] <strike>I checked for accessibility issues</strike> N/A
- [x] <strike>Includes documentation</strike> N/A
- [ ] Commit structure follows [OEP-0051](https://github.com/edx/open-edx-proposals/pull/189) - @alfredchavez Could you please ensure that future commits follow the correct format?

**Comment by openedx-webhooks** [comment]
@alfredchavez 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6483&entry.1484655318=https://github.com/alfredchavez&entry.752974735=2021-07-19+16:00&entry.1917517419=2021-07-26+22:23&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
