### PR TITLE
mroytman/add docker to tools jenkins

### PR DESCRIPTION
**Pull request by michaelroytman**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

### CODE REVIEW

**Comment by michaelroytman** [comment]
The following PR makes use of the Docker install on the tools_jenkins image: https://github.com/edx/jenkins-job-dsl/pull/169.

**Comment by michaelroytman** [comment]
@edx/devops Please review.

**Comment by jibsheet** [comment]
Is there a reason we're not doing this in Ansible so that the docker image and the running ec2 instance both have Docker installed the same way?

**Comment by michaelroytman** [comment]
Closing to focus instead on https://github.com/edx/configuration/pull/3871, per discussion with Feanil and Kevin.

**Pull request closed without merging**
