### PR TITLE
Open release/ginkgo.master

### PR DESCRIPTION
**Pull request by idqweb**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @idqweb! I've created [OSPR-2467](https://openedx.atlassian.net/browse/OSPR-2467) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by mduboseedx** [comment]
@idqweb Thank you for the contribution! I have a few questions about your Pull Request. 

First, could you explain why you are using the ginkgo.master branch? Your PR includes a number of commits since ginkgo.master so perhaps you should use the master branch instead?

Also, before we can merge any of your code changes, you will actually have to send in the signed Contributor Agreement mentioned in the earlier comment. This will only have to be done once as we can then review your code going forward. Thanks again for the contribution!

**Comment by mduboseedx** [comment]
@idqweb Thank you for sending in the signed contributor agreement!

Just to check in again, did you mean to use the ginkgo.master branch? I only ask because of the additional commits associated with the Pull Request

**Comment by idqweb** [comment]
@mduboseedx  Let's cancel this pull request. I'm rethinking the solution to this problem.

**Comment by idqweb** [comment]
Let's cancel this pull request. I'm rethinking the solution to this problem.

**Comment by mduboseedx** [comment]
@idqweb Ok, that sounds good. I'll close this one, but feel free to submit another.

**Comment by openedx-webhooks** [comment]
@idqweb Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4614&entry.1484655318=https://github.com/idqweb&entry.752974735=2018-06-12+08:46&entry.1917517419=2018-06-15+13:26&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
