### PR TITLE
Small improvements to json_lint.sh

### PR DESCRIPTION
**Pull request by ciupicri**
Note: I'm wondering why is it necessarily to keep track of the directory
from which the script was launched. The working directory of the parent
process isn't modified by its children.

### CODE REVIEW

**Comment by ciupicri** [comment]
@jrbl, could you please have a look at this?

**Comment by jarv** [comment]
I completely forgot about this script.
We are currently doing some basic json and yaml syntax checking in our travis-ci config here -> https://github.com/edx/configuration/blob/master/.travis.yml

**Comment by hkim823** [comment]
@ciupicri otherwise it looks good to me. thanks for your contribution.  I can't seem to find it so if you have already signed out code contributor contribution agreement, thanks again and I will merge this in.  If not, please let us know when you complete and return this.  http://code.edx.org/individual-contributor-agreement.pdf

**Comment by jarv** [comment]
I think we should probably remove this script since we have the travis file that does the same thing.

**Comment by feanil** [comment]
+1 to removing this file.

**Comment by ciupicri** [comment]
I haven't signed the Contributor Agreement yet, but I declare the patches public domain.

Though I guess removing the file seems to be the best option.

**Comment by hkim823** [comment]
If that's the case, what I'll do is close this PR, and setup a PR to just remove the file all together, but thank you again for bringing this to our attention.

**Pull request closed without merging**
