### PR TITLE
[SE-4612] Cherry-pick #6482 into lilac.master

### PR DESCRIPTION
**Pull request by ha-D**
## Description

Cherry-picks #6482 into `open-release/lilac.master`

## Supporting information
**Sandbox Link**: [SE-4612: (Lilac) Discussion Forum / ES Configs](https://manage.opencraft.com/instance/29210/edx-appserver/20051/)
**Sandbox Server IP**: 149.202.161.121

## Testing instructions
Since this was an issue that occurred when configuring new servers, you could launch a new server to make sure everything is fine. However the sandbox I've provided is a freshly configured one without any manual intervention so it should suffice to check that.

#### Testing by using the forums
We can test that elasticsearch is running be testing the discussion forums, since this forums won't work if ES is not running:

- Go to the [course page](https://se-4612-lilac.opencraft.hosting/courses/course-v1:edX+DemoX+Demo_Course/discussion/forum/) on the sandbox instance
- Click on the 'Discussions' link
- The page should open without errors, creating and searching for posts should work

#### Testing by checking heartbeat

- Visit the [heartbeat URL](https://se-4612-lilac.opencraft.hosting/heartbeat?extended) on the sandbox server and check that all endpoints are healthy 

#### Testing on the server
If you have SSH access to the server (I can give you access if you need it):

- Check that the elasticsearch service is running (systemctl status elasticsearch)
- Check that the elasticsearch process is running with the right configurations. To do this check it's enough to check elasticsearch is running with a 512m heapsize rather than the default 1g. You can check this by running the command below:
    ```
    ps aux | grep elasticsearch | awk 'match($0,/-Xmx[0-9]+m/) {print substr($0,RSTART,RLENGTH)}'
    ```
    If it outputs `-Xmx512m` then we're good, if it outputs `-Xmx1g` then it's using the wrong configurations.

## Reviewers
- [ ] @nizarmah 
- [ ] @arbrandes

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ha-D! I've created [OSPR-5943](https://openedx.atlassian.net/browse/OSPR-5943) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@ha-D Thank you for your contribution. Please let me know once it is ready for our review.

**Comment by arbrandes** [comment]
@ha-D, LGTM!

@edx-community-bot merge

**Comment by ha-D** [comment]
@natabene Ready for you to take a look, thanks

**Comment by arbrandes** [comment]
Huh.  Did the merge not go through?  Maybe I have to issue the command on a standalone comment.  Trying again.

**Comment by arbrandes** [comment]
@edx-community-bot merge

**Comment by arbrandes** [comment]
@sarina, looks like the community bot isn't working, here.  Do you mind asking your team to take a look?

**Comment by sarina** [comment]
UGH it looks like the github workflow isn't present for some reason. I'll merge this PR and then merge the workflow to the Lilac branch (so you don't have to deal with rebasing this PR)

**Pull request merged**
