### PR TITLE
add configuration for segment.io key

### PR DESCRIPTION
**Pull request by jimabramson**
@jibsheet @fredsmith OK?
@clintonb @rlucioni FYI

### CODE REVIEW

**Comment by feanil** [comment]
@jimabramson you didn't set a default for the 'ECOMMERCE_SEGMENT_KEY' var.  Can you please set one.

**Comment by rlucioni** [comment]
@jimabramson the default should be "None," which disables tracking.

**Comment by jimabramson** [comment]
@rlucioni thanks / @feanil sorry bout that, fixed.

**Comment by clintonb** [comment]
:+1:

**Comment by rlucioni** [comment]
:+1:

**Comment by fredsmith** [comment]
:+1:

**Comment by feanil** [comment]
Quoted none here won't resolve correctly.  It will return a string 'None' not the literal `None`

**Comment by jimabramson** [comment]
@feanil do i just need to lose the quotes?

**Comment by feanil** [comment]
@jimabramson the ansible fix has not been merged yet but once it is, you'll just need to set the default to `!!null`

**Comment by jimabramson** [comment]
@feanil thanks.   this one right?  https://github.com/ansible/ansible/pull/10957

**Comment by feanil** [comment]
That's the one.

**Comment by feanil** [comment]
@jimabramson I merged the change to our fork: https://github.com/edx/configuration/pull/1995

You can update this to use `!!null` as the default value and then I think it's ready to go.

**Comment by jimabramson** [comment]
@feanil updated

**Comment by feanil** [comment]
:+1:

**Pull request merged**
