### PR TITLE
CRI-171 Makes the forum mongo authentication mechanism configurable

### PR DESCRIPTION
**Pull request by pomegranited**
Adds ansible variable to set the forum mongo authentication mechanism.

**JIRA tickets**: [CRI-186](https://openedx.atlassian.net/browse/CRI-186), [OSPR-4403](https://openedx.atlassian.net/browse/OSPR-4403), [SE-2321](https://tasks.opencraft.com/browse/SE-2321)

**Discussions**: [Discussion forum errors in latest master with mongo 3.2](https://discuss.openedx.org/t/discussion-forum-errors-in-latest-master-with-mongo-3-2/1843/5)

**Dependencies**: Relates to https://github.com/edx/cs_comments_service/pull/316

**Sandbox URL**: See https://github.com/edx/cs_comments_service/pull/316

**Merge deadline**: ASAP, fix needed in Juniper

**Testing instructions**:

See https://github.com/edx/cs_comments_service/pull/316 under "Sandbox".

**Reviewers**
- [ ] @toxinu
- [ ] edX reviewer[s] TBD

FYI @bderusha 

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [x] Are you adding any new default values that need to be overridden when this change goes live? No, default value leaves behaviour unchanged.
    If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [x] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Simple change.
        Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?
         Will post info on [Juniper Confluence](https://openedx.atlassian.net/wiki/spaces/COMM/pages/940048716/Juniper).

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pomegranited! I've created [OSPR-4403](https://openedx.atlassian.net/browse/OSPR-4403) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@pomegranited Thank you for your contribution. Please let me know once it is ready for our review.

**Review by bderusha — APPROVED** [review]
:shipit:

**Comment by toxinu** [comment]
@pomegranited Tested as part of [!316](https://github.com/edx/cs_comments_service/pull/316) and it is good to merge. 😄

**Comment by pomegranited** [comment]
@bderusha  Squashed  f522c13 to eb55361 in preparation for merge.  Do we need any more reviewers?

CC @natabene

**Review by bderusha — APPROVED** [review]

**Review by bderusha — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@pomegranited 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/5755&entry.1484655318=https://github.com/pomegranited&entry.752974735=2020-04-21+07:31&entry.1917517419=2020-04-24+13:36&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
