### PR TITLE
Put all keys in the authorized_keys file.

### PR DESCRIPTION
**Pull request by feanil**

### CODE REVIEW

**Comment by e0d** [comment]
Seems reasonable, what's the motivation?

**Comment by jarv** [comment]
no strong preference here

**Comment by feanil** [comment]
authorized_keys2 was not getting picked up on ec2 linux.

**Comment by benpatterson** [comment]
Just noticed this, @feanil . If we run a second user with this playbook, would that erase any previous authorized_keys?

**Comment by feanil** [comment]
Re-running this play for the same user multiple times will replace their authorized_keys file each time.  Running it for one user will not affect the authorized keys for a different user.

**Pull request merged**
