### PR TITLE
Ability to configure notifier database.

### PR DESCRIPTION
**Pull request by mtyaka**
This patch makes it possible to configure notifier to use an external MySQL database. The database engine still defaults to sqlite3 and the change is backwards compatible (although the `NOTIFIER_DB_DIR` variable is deprecated in favor of `NOTIFIER_DATABASE_NAME`).

Motivation: Currently you can not run more than one notifier instance at the same time since each notifier instance works independently, which results in users receiving duplicate digest messages.
We plan to use external MySQL to synchronize multiple notifier instances to make it safe for muliple instances to run concurrently.

**Discussions**: This was discussed in a Configuration Hangout several months ago.

**Dependencies**: https://github.com/edx/notifier/pull/42

**JIRA Ticket**: https://openedx.atlassian.net/browse/OSPR-1674

**Reviewers**
- [x] @haikuginger
- [ ] edX reviewer[s] TBD

---

Make sure that the following steps are done before merging

  - [ ] A devops team member has commented with :+1:
  - [ ] are you adding any new default values that need to be overridden when this goes live?
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @mtyaka! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=3695&repo=edx%2Fconfiguration"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Review by haikuginger — APPROVED** [review]
:+1:

- [x] I tested this: I verified on a devstack that, with this version of configuration installed, I was able to run `ansible-playbook run_role.yml notifier` with extra vars set to the relevant database variables, that those variables propagated into `notifier_env`, as expected by the changes in edx/notifier#42, and that the syncdb command executed by the playbook filled the MySQL database referred to by the extra vars with the tables for the notifier app.
- [x] I read through the code
- [x] ~~I checked for accessibility issues~~ N/A
- [x] Includes documentation

**Comment by edx-webhook** [comment]
Thanks for the pull request, @mtyaka! I've created [OSPR-1674](https://openedx.atlassian.net/browse/OSPR-1674) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by gsong** [comment]
@edx/devops Can someone from the team review this one?

**Comment by gsong** [comment]
@e0d Can someone from your team take a look at this?

**Comment by gsong** [comment]
@edx/devops Can this be scheduled for a review? @mtyaka Can you rebase to resolve conflict?

**Comment by mtyaka** [comment]
@gsong Rebased, thanks!

**Comment by bradenmacdonald** [comment]
@edx/devops @nedbat FYI - this is another PR we'd really like to have available in Ginkgo. It's required to scale any deployment where notifier is not on a single VM.

**Review by feanil — APPROVED** [review]
@edx/devops this looks good to me, please do a second review.

**Review by jibsheet — APPROVED** [review]

**Comment by feanil** [comment]
@mtyaka can you please rebase and resolve the merge conflict in the CHANGELOG.md. Once that's resolved this can be merged.

**Comment by mtyaka** [comment]
Thanks @jibsheet and @feanil! I rebased, will merge once build goes green.

**Pull request merged**
