### PR TITLE
Replace nginx redirect method from rewrite to return for speeding up

### PR DESCRIPTION
**Pull request by smaeda-ks**
Nginx "rewrite" method is slower than "return" method.
So we should use "return" method if we do not need to specify regular expression rules.

[Additional]
- [Official doc](http://wiki.nginx.org/Pitfalls#Taxing_Rewrites)

As you know regexes are expensive. "rewrite" will start a new rewrite search.
But do not need expensive options for the simple case like just convert protocol from http to https.
This is very tiny improvement.
So difficult to measure and feel differences but it is definitely improvement of performance.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @smaeda-ks! I've created [OSPR-1210](https://openedx.atlassian.net/browse/OSPR-1210) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by e0d** [comment]
@smaeda-ks Thanks for this.  Can you point to the docs?  Are there other differences that we should be aware of?  Do you have any metrics from your testing that you can share?

**Comment by smaeda-ks** [comment]
@e0d 
Thanks for the reply.
I added some informations to the top comment. Please check.

**Comment by e0d** [comment]
@arbabnazar please review

**Comment by arbabnazar** [comment]
@e0d verified on the sandbox, working well. Thanks @smaeda-ks for this contribution. 

:+1:

**Comment by e0d** [comment]
@smaeda-ks looks good, please add a commit to add  yourself to the AUTHORS file and we'll merge soon.  Thanks for your contribution.

**Comment by smaeda-ks** [comment]
@arbabnazar @e0d Thanks! I just added myself to AUTHORS.

[edited]
Sorry I separated commits.

**Comment by smaeda-ks** [comment]
@arbabnazar @e0d All right. Passed tests.

**Comment by jibsheet** [comment]
:+1:

**Pull request merged**
