### PR TITLE
Allows override of nginx configuration templates via simple variable

### PR DESCRIPTION
**Pull request by carsongee**
The only downside I can see is that you have to override for all sites, but I don't really see that as a major problem.

### CODE REVIEW

**Comment by jarv** [comment]
I think I'm ok with this and it's better than using try_files.
@jbau @feanil @e0d @jrbl  ok with you?

**Comment by feanil** [comment]
seems good.

**Comment by e0d** [comment]
I think this is going to be a use case that we have to support in multiple places.  Do we just want to have a convention for providing overrides?  I fine with overrides in general and think it's highly preferable to conditionals in the templates.

**Comment by hkim823** [comment]
@carsongee is this still a valid PR?  Let us know

**Comment by carsongee** [comment]
I'm still using it since my templates are different enough from stock.  I'll rebase it to get rid of merge conflicts.

**Comment by hkim823** [comment]
:+1:

**Pull request merged**
