### PR TITLE
add symlink to jarsigner for cleaner scripting

### PR DESCRIPTION
**Pull request by estute**
@benpatterson @jibsheet

### CODE REVIEW

**Comment by benpatterson** [comment]
@estute `jarsigner` would also point to the java implementation? Why is this necessary?

No objections at this point; just want to understand.

**Comment by estute** [comment]
@benpatterson this is just to make scripting a little cleaner/reliable (a.k.a don't need to use a full, versioned, path)

**Comment by benpatterson** [comment]
Thanks @estute 

It would be great if you updated the commit message to explain a bit more. Then merge when ready as far as I'm concerned.

👍

**Comment by jibsheet** [comment]
👍

**Pull request merged**
