### PR TITLE
fix: removes certs from list of nginx sites

### PR DESCRIPTION
**Pull request by pomegranited**
Removes a leftover reference to the now-removed `certs` module.

Without this change, deployments using the `openedx_native.yml` playbook fail with this error:

```
failed: [137.74.28.224] (item="certs") => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": "certs",
    "msg": "Could not find or access 'edx/app/nginx/sites-available/certs.j2'\nSearched in:\n\t/tmp/tmp9a5n7g0u/playbooks/roles/nginx/templates/edx/app/nginx/sites-available/certs.j2\n\t/tmp/tmp9a5n7g0u/playbooks/roles/nginx/edx/app/nginx/sites-available/certs.j2\n\t/tmp/tmp9a5n7g0u/playbooks/roles/nginx/tasks/templates/edx/app/nginx/sites-available/certs.j2\n\t/tmp/tmp9a5n7g0u/playbooks/roles/nginx/tasks/edx/app/nginx/sites-available/certs.j2\n\t/tmp/tmp9a5n7g0u/playbooks/templates/edx/app/nginx/sites-available/certs.j2\n\t/tmp/tmp9a5n7g0u/playbooks/edx/app/nginx/sites-available/certs.j2 on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"
}
```

cf https://github.com/edx/configuration/pull/6501#issuecomment-902496617

Configuration Pull Request
---

CC @crice100 @tuchfarber 

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pomegranited! I've created [OSPR-5982](https://openedx.atlassian.net/browse/OSPR-5982) to keep track of it in JIRA.

As a core committer in this repo, you can merge this once the pull request is approved per the [core committer reviewer requirements](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529675973/Open+edX+Core+Committers#Reviews-and-Ownership) and according to the agreement with your edX Champion.

**Review by tuchfarber — APPROVED** [review]

**Comment by pomegranited** [comment]
Thanks @tuchfarber , ok if I merge?

**Comment by tuchfarber** [comment]
Yep! Sorry meant to leave a comment with the approval. Thanks for fixing this :) and sorry we missed it.

**Comment by openedx-webhooks** [comment]
@nedbat, @feanil: thought you might like to know that pomegranited merged this pull request.

**Comment by crice100** [comment]
Thank you!

**Comment by natabene** [comment]
@pomegranited Thank you!

**Comment by openedx-webhooks** [comment]
@pomegranited 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6524&entry.1484655318=https://github.com/pomegranited&entry.752974735=2021-08-23+01:05&entry.1917517419=2021-08-23+10:48&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
