### PR TITLE
Add the mongo backup cron only if mongo S3 backup is enabled

### PR DESCRIPTION
**Pull request by bdero**
The cron for running the mongo backup script should only be added if MONGO_S3_BACKUP is enabled.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @bdero! I've created [OSPR-226](https://openedx.atlassian.net/browse/OSPR-226) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams. 

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ('this must be merged by XX date', and why that is)
- partner information ('this is a course on edx.org')
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the Github pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by e0d** [comment]
:+1:

**Comment by feanil** [comment]
:+1:

**Comment by sarina** [comment]
@e0d @feanil can one of you please merge this OSPR if it looks good to you? Open source contributors don't have the ability to merge their pull requests.

**Comment by e0d** [comment]
@sarina @bdero works with @carsongee .  I can merge, but Carson has the bits as well.

**Comment by sarina** [comment]
@e0d - in the future if you're not going to merge it, it would be good to explicitly let @bdero know to ask Carson to merge it.

**Pull request merged**
