### PR TITLE
Add lifecycle tags for analytics

### PR DESCRIPTION
**Pull request by mrgnr**
Add lifecycle tags for analytics roles.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @emrob! I've created [OSPR-876](https://openedx.atlassian.net/browse/OSPR-876) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).
We can't start reviewing your pull request until you've   submitted a [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)   or indicated your institutional affiliation   and   added yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS) file . Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst) file for more information.

**Comment by feanil** [comment]
:+1:

**Comment by fredsmith** [comment]
:+1:

**Comment by sarina** [comment]
@emrob @natea We don't have a contributor's agreement on file for Appsembler - can we get the ball rolling on getting one, or have you sign an individual agreement?

**Comment by natea** [comment]
@sarina is there one on file for NodeRabbit (the official company name for Appsembler)?

**Comment by sarina** [comment]
Nate, not that I can see. You are actually not even covered under an
agreement yourself. We have one for Jazkarta.

**Comment by natea** [comment]
Ok, we should get one setup for the company. I think I'm covered under the Jazkarta one already, but for Appsembler team members, we should have that fall under a company-wide contributor's agreement.

**Comment by sarina** [comment]
Great I will note you under Jazkarta's agreement.

Do you need me to resend you the company agreement?

**Comment by natea** [comment]
Yes, please resend it so we can get that taken care of. Thanks!

**Pull request merged**
