### PR TITLE
Allow enabling HTTP basic auth for individual services.

### PR DESCRIPTION
**Pull request by smarnach**
This is a fixed version of #2322, which was reverted due to a bug.

**Explanation of the bug in the original version**. The problem with the original PR was that there was no default value for `COMMON_ENABLE_BASIC_AUTH`.  So far, this variable was only used in Jinja2 conditionals, like

```
{% if COMMON_ENABLE_BASIC_AUTH %}
```

In this context, the undefined variable was interpreted as falsy.  With the original PR applied, `COMMON_ENABLE_BASIC_AUTH` was also used in Jinja2 variable expansions like

```
EDXAPP_LMS_ENABLE_BASIC_AUTH: "{{ COMMON_ENABLE_BASIC_AUTH }}"
```

An undefined variable in this context results in the string being unchanged, so `EDXAPP_LMS_ENABLE_BASIC_AUTH` becomes the literal string `"{{ COMMON_ENABLE_BASIC_AUTH }}"`, which is considered truthy in a conditional.  This way, the Ansible equivalent of variable assignment turned a falsy value into a truthy one, resulting in undesired defaults.

The fix is to add a default value for `COMMON_ENABLE_BASIC_AUTH`.

**Original PR description**. Currently, there is a single flag COMMON_ENABLE_BASIC_AUTH to decide whether to enable basic auth in the nginx config. This change allows to enable basic auth selectively for individual services.

I tested this locally targetting a virtual machine and using variations of this playbook:

``` yaml

---
- hosts: all
  sudo: True
  gather_facts: True
  vars:
    COMMON_ENABLE_BASIC_AUTH: True
    EDXAPP_LMS_ENABLE_BASIC_AUTH: False
  roles:
    - role: nginx
      nginx_sites:
      - cms
      - lms
      nginx_default_sites:
      - lms
    - edxapp
```

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @smarnach! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?number=2481&repo=edx%2Fconfiguration

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @smarnach! I've created [OSPR-955](https://openedx.atlassian.net/browse/OSPR-955) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).
We can't start reviewing your pull request until you've   added yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS) file . Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst) file for more information.

**Comment by mtyaka** [comment]
:+1: Interesting ansible behaviour... I'm not sure why it doesn't raise an error when trying to use an undefined variable in `"{{}}"` expressions.

**Comment by feanil** [comment]
@smarnach I'm gonna try to test them this week or early next week.  FYI it's almost Thanksgiving so people will be on holiday at the end of the week and we might be slow to respond.

**Comment by smarnach** [comment]
@feanil Thanks for letting me know.  This is not urgent from our point of view, but we'd really like to eventually get this merged.

**Comment by smarnach** [comment]
@feanil Since finally our sandboxed build again, I could test this in a real-world setup, and I found out that this PR is still broken.  While everything I wrote in the PR description is basically true, another even bizarrer aspect of Ansible gets in our way here.  Basically, if you transfer a Boolean value from one variable to another, it becomes a string, and the string "False" will be considered truthy or falsy depending on context.

Here's a minimal example:

``` yaml
---
- hosts: localhost
  become: false
  gather_facts: false
  vars:
    A: false
    B: "{{ A }}"
  tasks:
  - debug: msg="A is true."
    when: A
  - debug: msg="B is true."
    when: B
  - debug: msg="A or B is true."
    when: A or B
  - debug: msg="A is {% if A %}true{% else %}false{% endif %}."
  - debug: msg="B is {% if B %}true{% else %}false{% endif %}."
```

The first two tasks are both skipped, so both `A` and `B` are considered falsy in the context of a `when` clause.  At least sometimes, since the third task gets executed.  The fourth task returns "A is false.", while the last one returns "B is true.".

This behaviour is just plain broken.  It has been reported to Ansible at least twice, but this seems to be considered "expected" behaviour.  It's not what I would expect.

I'm currently trying to find a work-around that isn't completely insane.

**Comment by smarnach** [comment]
Apparently you have to use the `|bool` filter in some places to convert the strings back into proper Boolean values.  I've pushed a fix, and tested the latest version by running the playbook again.

I'm sorry for this not being properly tested before.  I triggered a sandbox build, but that didn't go through for more then a week.  In the meantime, I assumed that printing the variables using `debug` is enough to check whether they have the correct values.  I didn't know there are two different values of `False` that are completely indistinguishable in debug output. :)

@mtyaka If you have time, could you please take another look at this?

**Comment by feanil** [comment]
@smarnach can you rebase this on the latest version of configuration?  That will allow us to easily test this on our sandboxes.  Also, we removed the ora role yesterday since we no longer officially support FYI.

**Comment by smarnach** [comment]
@feanil I rebased on top of current master.  The ora role (and ora.j2 in the nginx templates) seem to be still available on master.

**Comment by maxrothman** [comment]
@smarnach I'd like to help get this merged before New Years. Could you rebase again so I can test?

**Comment by antoviaque** [comment]
@maxrothman Sorry for the delay in the answer - @smarnach is currently on parental leave, but I'll see if someone else can take this on in his absence - it might be a bit tricky due to the holidays season though. Is it urgent on your side?

**Comment by maxrothman** [comment]
@antoviaque this isn't urgent for us; we're just trying to be responsive to you! If you would prefer to table it, let me know and I'll deprioritize it until next year.

**Comment by antoviaque** [comment]
@maxrothman Thanks, I appreciate it! In this case, given that Sven is away, let's table it for the new year then - we'll assign someone to replace Sven, and ping you once the rebase is done. How much heads up do you want?

**Comment by maxrothman** [comment]
@antoviaque once you notify us that this is ready for work, I'd suspect it'd take us at most 2 weeks (though probably only 1) to get it into a sprint.

**Comment by feanil** [comment]
@antoviaque I'm gonna close this PR for now. Please re-open it and comment when it's ready to be re-reviewed.

**Comment by mtyaka** [comment]
@smarnach FYI when your back, I had to change this when trying to only put the CMS behind HTTP auth: https://github.com/Unow/configuration/commit/21831f623997ec5c43320fc19b57ce009a43cdc5

I didn't spent much time trying to understand what's happening, but I'm guessing it's another incarnation of ansible's weird variable type coercion. It looks like variables are treated as strings inside `{{}}`, so `{{ "False" or "True" or ... }}` results in `"False"` which is then coerced back into boolean `False` in `when: NGINX_CREATE_HTPASSWD_FILE`.

**Comment by smarnach** [comment]
@mtyaka Thanks for the fix.  I actually changed the Boolean expression in exactly the way you did during development, but since tests with various combinations of `True` and `False` for the individual services seemed to indicate that the `|bool` filter wasn't necessary in this expression, I dropped it again.  Weird.

**Comment by smarnach** [comment]
@feanil I'm back from leave, and have updated this PR.  Could you please schedule a review?

**Comment by bradenmacdonald** [comment]
@feanil ping - please let us know if you can review this?

**Comment by jbarciauskas** [comment]
@feanil @e0d how can we move this forward?

**Comment by feanil** [comment]
Sorry it took so long to get to this.  Changes look good to me. 👍

**Comment by jbarciauskas** [comment]
What's the next step to get this merged @feanil @bradenmacdonald

**Comment by smarnach** [comment]
@jbarciauskas This needs to be rebased by me, which I will do today.  I got one thumbs up from @mtyaka and one from @feanil, so I think I can merge after rebasing.

**Comment by smarnach** [comment]
@feanil I rebased on top of maser, but the Travis build is timing out now, which probably isn't caused by the changes in this PR.  Is this a known issue?

**Comment by jbarciauskas** [comment]
I just tried retriggering this build.

**Comment by jbarciauskas** [comment]
Hm, no dice. @feanil any idea? @benpatterson ?

**Comment by benpatterson** [comment]
Joel and Sven... Yes the timeouts are a known issue and devops has it
queued; however, they are heads down this week on a couple other items...
HTH

sent via Android

**Comment by e0d** [comment]
@jbarciauskas @smarnach the timeouts are almost certainly not related to your changes and I don't think they should block committing this to master.

**Comment by jbarciauskas** [comment]
Awesome. Who want's to press the button? @feanil @smarnach

**Comment by smarnach** [comment]
@jbarciauskas @e0d Thanks a lot!  Nice to get this finally merged. :)

**Pull request merged**
