### PR TITLE
udpated the edxapp MySql host to use mysql 5.7

### PR DESCRIPTION
**Pull request by mraarif**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by adzuci** [comment]
Hey @mraarif, is there also a linked devstack PR for this change?  That you could link here?

**Comment by mraarif** [comment]
sure @adzuci , PR:https://github.com/edx/devstack/pull/643 to update `docker-compose` in devstack

**Comment by mraarif** [comment]
I was able to start a sandbox: https://tools-edx-jenkins.edx.org/job/sandboxes/job/CreateSandbox/33815/ using this branch and the build seems successful.

**Comment by mraarif** [comment]
LMS failing locally with error:

> MySQLdb._exceptions.OperationalError: (2005, "Unknown MySQL server host 'edx.devstack.mysql' (0)")

there are quite a few setting files that have `HOST: edx.devstack.mysql` ... not sure if we need to replace all those with `edx.devstack.mysql57`

**Comment by mraarif** [comment]
looks like lms container is using `mysql57` but the edx-platform codebase being used by edxops/edxapp image is still using `mysql` devstack configuration ... not sure how would one go about rebuilding edxapp image locally

**Review by jmbowman — APPROVED** [review]
This part looks good once the corresponding devstack PR is ready to merge.

**Pull request merged**
