### PR TITLE
Added Support for Django 1.7 for Analytics API and Insights

### PR DESCRIPTION
**Pull request by clintonb**
@e0d @feanil

### CODE REVIEW

**Comment by e0d** [comment]
Do we need to support backward compatibility?  If so, I'd prefer to have separate tasks with conditionals.  This is simple and terse, but maybe too so.

**Comment by clintonb** [comment]
@e0d We only need backward compatibility in the event that we do something admittedly silly like merge this configuration before actually upgrading to Django 1.7. My plan was to remove the Django 1.6 command once we were certain we would stick with Django 1.7. I'm fine with removing that now since the odds of us getting to a point of mixed versions is pretty low.

**Comment by clintonb** [comment]
@e0d Updated.

**Comment by e0d** [comment]
@jbau you may already be aware that this is coming. 

@clintonb we should add change log entries for this as well.

**Comment by clintonb** [comment]
@e0d Changelog updated.

**Comment by clintonb** [comment]
@e0d Are we good to merge?

**Comment by e0d** [comment]
:+1:

**Pull request merged**
