### PR TITLE
Added continous delivery playbook to discovery service refresh metadata

### PR DESCRIPTION
**Pull request by clintonb**
ECOM-5134

### CODE REVIEW

**Comment by clintonb** [comment]
@edx/pipeline-team please review

**Comment by e0d** [comment]
@clintonb does this obviate the Jenkins job?  Seems like a better place for this particular job anyway.

**Comment by clintonb** [comment]
I wish it did @e0d, but we need to update data every hour still.

**Comment by doctoryes** [comment]
@clintonb Although our current policy is to keep timed, non-AWS-specific jobs like this on Jenkins, GoCD is capable of having pipelines which run on a timed basis, like cron:
https://docs.go.cd/16.5.0/configuration/admin_timer.html

**Comment by macdiesel** [comment]
👍

**Pull request merged**
