### PR TITLE
Add lifecycle tags for mongo role.

### PR DESCRIPTION
**Pull request by mrgnr**
Add lifecycle tags for mongo role. Lifecycle tags allow users to run specific sets of related tasks within a role. See the [proposal](https://openedx.atlassian.net/wiki/display/OpenOPS/Role+Life-cycle) for details.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @emrob! I've created [OSPR-904](https://openedx.atlassian.net/browse/OSPR-904) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).
We can't start reviewing your pull request until you've   submitted a [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)   or indicated your institutional affiliation   and   added yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS) file . Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst) file for more information.

**Comment by sarina** [comment]
@emrob again we can't take a look until your contributor's info is straightened out. cc @natea

**Comment by natea** [comment]
@sarina i just sent you an email re contributor's agreement for the company, so @emrob should be all set now.

**Comment by sarina** [comment]
@natea thanks much!

@emrob Can you please add a description to your PR to explain the nature of your PR? We have a long list of potential questions here: http://edx-developer-guide.readthedocs.org/en/latest/process/cover-letter.html - but generally speaking, what you're doing and why.

**Comment by feanil** [comment]
Cherry-picking this into master.

**Pull request closed without merging**
