### PR TITLE
Set devstack base box to empanada release

### PR DESCRIPTION
**Pull request by wedaly**
Will work once permissions on the S3 bucket are set to public.

### CODE REVIEW

**Comment by wedaly** [comment]
I got an error from the `hostsupdater` plugin that I suspect is the same one @mulby ran into with the datajam box.  I suspect this is an interaction between the shell provisioner and the plugin.  For the time being, I've removed it and will update the wiki documentation once this gets merged.

**Comment by yarko** [comment]
[update: this comment was in error / ignore]
Are you really intending to take away the full build on a particular
platform away from base?

Where will people do base builds for their intended targets then?

I think you don't want to do this here, unless there is someplace else in
the tree for this which I am not aware of.

**Comment by wedaly** [comment]
@yarko This change affects the Vagrantfile in `vagrant/release`, not `vagrant/base`.  Users who want to build the box from scratch can use `vagrant/base/devstack`

**Comment by feanil** [comment]
looks good.

**Comment by mulby** [comment]
LGTM :rocket: 

As an aside - you will likely want to update the docs to indicate that you have to manually add the entry to /etc/hosts to get preview to work properly.

**Comment by yarko** [comment]
yeah, sorry @wedaly - read it wrong from mobile (565/566 confusion);  LGTM indeed!

**Pull request merged**
