### PR TITLE
Fix a bug in the git module: branches might not check out properly

### PR DESCRIPTION
**Pull request by nedbat**
If a git version is specified as a branch, and the commit referred to is
already on the local working tree, but the branch is not, then the
checkout will fail.

This is because the Ansible 1.9.3 module would check to see if the
commit was already present, and if so, did not fetch. This meant the
branch wasn't defined in the local working tree.

This can happen if you make a branch but there aren't any changes on the
branch.

### CODE REVIEW

**Comment by edx-webhook** [comment]
## PR Cover Letter
- [ ] A detailed description of the changes in the body of the PR
- [ ] If available, a link to the relevant JIRA ticket in the body of the PR
  - `[PROJ-XXXX](https://openedx.atlassian.net/browse/PROJ-XXXX)`

## Sandbox
- [ ] Build a sandbox for your branch and add a link here

## Testing
- [ ] i18n
- [ ] RTL
- [ ] Unit, integration, acceptance tests as appropriate
- [ ] Analytics
- [ ] Performance
- [ ] Database migrations are backwards-compatible

## Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [ ] Code review #1
- [ ] Code review #2
- [ ] Docs review (required for UI strings/error messages)
- [ ] UX review
- [ ] Accessibility review
- [ ] Product review

## Documentation considerations
- [ ] Are there user visible changes? If so, list who is affected, and include a pointer to the relevant code.
- [ ] Should this be mentioned in the release notes? If so, make sure that you included a description.

## DevOps assistance
If it's needed, or even if you suspect it might be needed, do any/all these things as early as possible. Don't surprise devops right before merging! For example, touching envs/aws.py or or envs/common.py are dead giveaways that you'll need assistance when pushing your changes out. Things that require devops attention include, but are not limited to:
- configuration changes
- feature flags
- migrations
Ways to get devops attention, pick-and-choose whichever is most appropriate for your specific PR:
- [ ] Tag devops on your PR (`@edx/devops`), either for review (more specific to devops = better) or just a general FYI
- [ ] File a support ticket

FYI: Tag anyone who might be interested in this PR here.

## Post-review
- [ ] Squash commits

**Comment by nedbat** [comment]
@feanil @e0d I changed all of the mentions of the git module that used a version= parameter.  Not sure if this is the way you would go, but I like that it will keep this mysterious problem from happening to others in the future.

**Comment by feanil** [comment]
Instead of local, can you name it based on the version you copied from?  ie. `git_2_0` so we know when we can get rid of it.  Also if it's just 1.9.4 that is something we can move our fork to so I assume it's at least 2.0 that the module needs to come from?

**Comment by nedbat** [comment]
The fix is not in 1.9.4, so we are stuck with a local version.  The fix is in 2.0.1 and not in 2.0, so I guess "git_2_0_1" is what you want?

**Comment by feanil** [comment]
Yes, please.

**Comment by nedbat** [comment]
OK: I've added "git_2_0_1", which is the git.py from 2.0.1.  It has this fix, plus a new option, verify_commit, which is the bulk of the difference.  I'm trying to find a way to show the diff between the 1.9.3 version and the 2.0.1 version, but GitHub doesn't have a way?

**Comment by nedbat** [comment]
@e0d @feanil ping ping

**Comment by feanil** [comment]
:+1:

**Comment by e0d** [comment]
:+1:

**Pull request merged**
