### PR TITLE
Removed ENABLE_JWT_AUTH feature flag from edxapp

### PR DESCRIPTION
**Pull request by clintonb**
This functionality should be permanently enabled.

ECOM-4221

### CODE REVIEW

**Comment by rlucioni** [comment]
👍

**Comment by jimabramson** [comment]
N.B. - if i'm not mistaken, removing the this feature + its overrides, before merging + deploying https://github.com/edx/edx-platform/issues/12162, will break things and/or introduce potential vulnerabilities.  👍  assuming that's understood by @edx/devops

**Comment by maxrothman** [comment]
Thanks @jimabramson. Paging @e0d (this week's release buddy) and @jibsheet (next week's release buddy). You should wait for their go-ahead before merging this.

**Comment by clintonb** [comment]
The build breakage is unrelated. It is due to the addition of the `cryptography` Python package to edx/course-discovery. This package cannot be compiled/installed because `libffi-dev` is needed, but missing from the system packages.

**Comment by clintonb** [comment]
@jibsheet I saw that the private settings were removed. Any objections to this being merged?

**Comment by jibsheet** [comment]
@clintonb 👍 🚀

**Pull request merged**
