### PR TITLE
Add a jinja2 syntax checker for Travis

### PR DESCRIPTION
**Pull request by carsongee**
Sometimes the ansible playbook syntax check doesn't source in all the templates we use, so I wrote a jinja2 syntax checker to add to the Travis builds.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @carsongee! I've created [OSPR-332](https://openedx.atlassian.net/browse/OSPR-332) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams. 

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ('this must be merged by XX date', and why that is)
- partner information ('this is a course on edx.org')
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the Github pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by feanil** [comment]
:+1:

**Comment by sarina** [comment]
@feanil does this need a second reviewer or can Carson merge?

**Comment by feanil** [comment]
@e0d can you do the second review.

**Comment by e0d** [comment]
Curious how long this takes to run.
Could we do something like this to only check files changed in the branch?

```
git diff --name-only  e0d/edx-notes-api $(git merge-base e0d/edx-notes-api master)
```

A useful extension might be to load the main.yml file from the path relative defaults directory.

Either way I'm :+1:

**Comment by carsongee** [comment]
Agreed on the time to run, it takes a minute or two.  I tried dropping in `for j2 in $(git diff --name-only origin/master..$(git rev-parse --abbrev-ref HEAD) |grep -E '.+\.j2$|.+\.yml'); do` as the file set, and travis said that it was ambiguous (https://travis-ci.org/edx/configuration/builds/46120085), so it doesn't look like it has the full git tree.  Any ideas, or shall I just merge as is?

**Comment by carsongee** [comment]
nm, looks like I got that sorted by using refs

**Comment by e0d** [comment]
Nice, :rocket:

**Pull request merged**
