### PR TITLE
Feanil/update ansible

### PR DESCRIPTION
**Pull request by feanil**

### CODE REVIEW

**Comment by feanil** [comment]
I've tested various jenkins jobs and have built the continuous integration play using these changes without any issue.

**Comment by maxrothman** [comment]
:+1:

**Comment by fredsmith** [comment]
:+1:

**Comment by maxrothman** [comment]
@feanil I think the ansible update might be causing [these errors](http://jenkins.edx.org:8080/job/ansible-provision-continuous-integration/10282/console). As far as I can tell, the continuous integration box still has ansible 1.5.5.

**Pull request merged**
