### PR TITLE
Try to nudge folks towards slack/mailing list for installation issues

### PR DESCRIPTION
**Pull request by jibsheet**
@edx/devops @nedbat Encourage folks towards slack/mailing list for install issues.
https://github.com/blog/2111-issue-and-pull-request-templates

Wording thoughts appreciated, I just wanted to get it written quickly.

### CODE REVIEW

**Comment by maxrothman** [comment]
Why not just turn off issues?

**Comment by nedbat** [comment]
Worth a shot! :)  :+1:

**Comment by feanil** [comment]
👍   since it is easy for developers outside edx to create issues there for actual bugs.

**Comment by maxrothman** [comment]
Make the second section a template rather than instructions, e.g.

```
Configuration ref:
edx-platform ref:
other refs:

#Steps to replicate:
- one
- two
- three
```

**Comment by feanil** [comment]
that seems like a separate PR @maxrothman

**Comment by maxrothman** [comment]
How so? @jibsheet asked for wording thoughts, I provided them. I'm happy to make the commit myself.

**Comment by feanil** [comment]
This PR seems to be about the wording of the nudge, not about wording in the template generally but perhaps I misunderstood.

**Comment by jibsheet** [comment]
I'm fine with blocking the merge until I can type in some better words for the prompt, there's no real rush, I just didn't want to forget to push the PR when it was so simple to turn on.

**Comment by feanil** [comment]
I think we should merge this since it's already an improvement.  We can make more improvements later but don't need to block on them to make this available.

**Comment by jibsheet** [comment]
Updated with wording changes and merging.  We can iterate further as needed.  I will test in the Issue creation screen after merging.

**Pull request merged**
