### PR TITLE
Deploy Catalog (Discovery) Service to Sandboxes

### PR DESCRIPTION
**Pull request by clintonb**
[ECOM-3877](https://openedx.atlassian.net/browse/ECOM-3877)

### CODE REVIEW

**Comment by clintonb** [comment]
FYI @jibsheet See ES 1.5.2 commit.

**Comment by e0d** [comment]
I see this as blocked by merging the cs_comments_service changes to master. @clintonb do you disagree?

**Comment by clintonb** [comment]
I agree.

**Comment by clintonb** [comment]
FYI @edx/devops @edx/learner we can now resume this effort.

**Comment by clintonb** [comment]
Not sure how I missed the fact that this was not merged. This has low priority on my list of projects to complete before I leave. Looks like the work was transferred to the Enterprise Team: [ENT-459](https://openedx.atlassian.net/browse/ENT-459). @edx/business @brittneyexline, if you want assistance with this, you should schedule some time on my calendar soon.

**Pull request closed without merging**
