### PR TITLE
All web pages that contain user-controllable content must opt-out of …

### PR DESCRIPTION
**Pull request by btelnes**
What does this PR do? Please provide some context

Sends the X-Content-Type-Options response header with the value nosniff to prevent browsers from MIME-sniffing a response away from the declared content-type
Where should the reviewer start?

lms.j2, cms.j2, lms-preview.j2
How can this be manually tested? (brief repro steps)

Install OXA (devstack/fullstack), navigate to the LMS/CMS/preview site(s), then review the response headers for various files
What are the relevant TFS items? (list id numbers)

User Story 97860, Task 97923
Definition of done:

    Title of the pull request is clear and informative
    Add pull request hyperlink to relevant TFS items
    For large or complex change: schedule an in-person review session
    This change has appropriate test coverage

Reminders BEFORE merging

    Get at least two approvals
    If you're merging from a feature branch into the development branch then "flatten" or "squash" commits
    If merging from the development branch into master (or porting changes from upstream) then use github's UI to get review feedback, but use the git command line interface to complete the actual merge.

Reminders AFTER merging

    Delete the remote feature branch
    Resolve relevant TFS items
    (reverse merge) If you merged from the development branch into master then check to see if there are any changes in master that can be merged down to the development branch (like hotfixes, etc). In this case, use github's UI for feedback and the git command line interface for the actual merge.

Configuration Pull Request
(For changes proposed to upstream)

Make sure that the following steps are done before merging

    @devops team member has commented with +1
    are you adding any new default values that need to be overridden when this goes live?
        Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
        Add an entry to the CHANGELOG.

### CODE REVIEW

**Comment by feanil** [comment]
@nedbat this looks like a first time contribution but the OSPR bot didn't pick it up, can you take a look.

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @btelnes! I've created [OSPR-2338](https://openedx.atlassian.net/browse/OSPR-2338) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by mduboseedx** [comment]
@btelnes Have you had a chance to send in the signed contributor agreement?

**Comment by natabene** [comment]
@edx/devops Can you give this a look?

**Review by feanil — APPROVED** [review]

**Comment by natabene** [comment]
@feanil Would you like to merge it now?

**Review by fredsmith — APPROVED** [review]
LGTM

**Review by coryleeio — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@btelnes 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4488&entry.1484655318=https://github.com/btelnes&entry.752974735=2018-04-18+21:09&entry.1917517419=2019-01-07+15:57&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
