### PR TITLE
DEVOPS-2620 - DISPLAY_ANALYTICS_ENROLLMENTS

### PR DESCRIPTION
**Pull request by fredsmith**

### CODE REVIEW

**Comment by jibsheet** [comment]
@dsjen  If we ship this as defaulting to False in configuration, is that going to conflict with the default in the LMS (so in devstacks?).  You mentioned that this will change something in production and I just want to understand what.

**Comment by dsjen** [comment]
@jibsheet -- good question.  I wasn't picturing that this would change anything in devstack--just in our deployments.  The default setting in lms/env/common.py remains the same and the setting isn't overwritten in lms/envdevstack.py.

**Comment by jibsheet** [comment]
@fredsmith looks like this should default to True to match common.py https://github.com/edx/edx-platform/blob/master/lms/envs/common.py#L338 and then we can override in secure.

**Comment by jibsheet** [comment]
:+1:

**Pull request merged**
