### PR TITLE
E0d/upgrade rabbitmq

### PR DESCRIPTION
**Pull request by e0d**
@edx/devops running upgraded RabbitMQ from our play, tested on sandbox and verified that tasks are processes as expected.

`/job/ansible-provision/6116/console`

```
[edward@alexis configuration]$ docker run  edxops/docker:v0
              RabbitMQ 3.6.1. Copyright (C) 2007-2016 Pivotal Software, Inc.
  ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
  ##  ##
  ##########  Logs: /var/log/rabbitmq/rabbit@c6f48a3ac24f.log
  ######  ##        /var/log/rabbitmq/rabbit@c6f48a3ac24f-sasl.log
  ##########
              Starting broker... completed with 6 plugins.
```

On a sandbox 

```
With workers down 

# rabbitmqctl list_queues
Listing queues ...
edx.cms.core.default    0
edx.cms.core.high   0
edx.lms.core.low    0
edx.lms.core.default    0
certificates    0
edx.lms.core.high_mem   1
edx.cms.core.low    0
edX-Open_DemoX  0
edx.lms.core.high   0
celeryev.c1b794e8-dc28-47a2-a647-8423691e4aed   0

With workers restarted

# rabbitmqctl list_queues
Listing queues ...
celery@edx.lms.core.high_mem.e0d-rabbit-upgrade.celery.pidbox   0
edx.cms.core.default    0
celery@edx.lms.core.low.e0d-rabbit-upgrade.celery.pidbox    0
edx.cms.core.high   0
celeryev.d666d333-0045-4865-a9be-d8538749ca8a   0
edx.lms.core.low    0
edx.lms.core.default    0
certificates    0
celery@edx.lms.core.high.e0d-rabbit-upgrade.celery.pidbox   0
edx.lms.core.high_mem   0
edx.cms.core.low    0
celeryev.e9597f14-ed41-4b91-81b9-6c5d857ebd86   0
celeryev.05c5c455-1bff-4e48-9f6e-23da6e43e610   0
celery@edx.lms.core.default.e0d-rabbit-upgrade.celery.pidbox    0
celeryev.b4e7e467-593f-4940-bda2-06a53aefd405   0
edX-Open_DemoX  0
edx.lms.core.high   0
celeryev.c1b794e8-dc28-47a2-a647-8423691e4aed   0
```

### CODE REVIEW

**Comment by e0d** [comment]
@bilalahmad99 take a look.

**Comment by bilalahmad99** [comment]
looks pretty apt to me. +1

**Comment by maxrothman** [comment]
Ran this in olive, it worked great.

EDIT: turns out it didn't upgrade rabbit. Retroactively retracting my thumb since I implemented the fix.

**Comment by jibsheet** [comment]
I think we still need to wait to merge into master until we run edxapp against it, but this looks good (or we can stand up a sandbox with it, but the only places we can tests actual rabbit tasks is sandbox/stage/prod).

:+1:

**Comment by e0d** [comment]
:+1:

**Comment by jibsheet** [comment]
If we merge this, does our (correct) decision to enforce the version mean we can't run this play on the common cluster (to update config or to build a new machine) until we juggle a rabbit upgrade (which is going to be super annoying).

We should consider if we want to pick max's commit into another branch, or add some 'skip the upgrade' flagging?

**Comment by maxrothman** [comment]
@edx/devops bump

**Comment by jibsheet** [comment]
@maxrothman have you answered my question about the forced upgrade?

**Comment by maxrothman** [comment]
Fair enough. So it seems like the upgrade should be optional?

**Comment by jibsheet** [comment]
Or at least turnoffable, since there's no inplace rabbit upgrade process, but I do want to run this to update cluster members in config, etc.

**Comment by maxrothman** [comment]
@jibsheet whadyathink?

**Comment by maxrothman** [comment]
@team we built olivex rabbit off of this PR. Could I get a review so we can merge it?

**Comment by maxrothman** [comment]
This needs to be rebased, but @feanil made a good point in f45f735edb18edbd267021209fca7d384ec438c8, that rabbit was not getting installed from the custom PPA. The PPA in question only has 3.6.2-1 and 3.6.2. Are we worried enough about it changing from under us that we want to continue installing rabbit from files.edx.org? Should I just grab the deb file for 3.6.2 and stick it there?

**Comment by e0d** [comment]
@maxrothman I think removing the cruft and not pulling into files makes sense.  We've pulled things in selectively for specific reasons, missing archives, reliability.  If those aren't relevant now, use the simpler solution.

**Comment by jibsheet** [comment]
@e0d I'm going to close and delete this once https://github.com/edx/configuration/pull/3297 lands (which I expect is tomorrow-ish)

**Comment by jibsheet** [comment]
Merged #3297 instead

**Pull request closed without merging**
