### PR TITLE
Add edx-east explanation.

### PR DESCRIPTION
**Pull request by doctoryes**
@nedbat @cpennington Could you check this explanation and suggest edits _or_ more information? Thanks.

@feanil Please review as well.
## Configuration Pull Request

Make sure that the following steps are done before merging
- [ ] @devops team member has commented with :+1:
- [ ] are you adding any new default values that need to be overriden when this goes live?  
  - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
  - [ ] Add an entry to the CHANGELOG.

### CODE REVIEW

**Comment by cpennington** [comment]
:+1:

Would it be crazy to just symlink edx-east to some more clearly named directory?

**Comment by doctoryes** [comment]
@feanil Thoughts on a symlink?

**Comment by nedbat** [comment]
:+1: Definitely better (we can quibble about line-wrapping....)

**Comment by doctoryes** [comment]
This is a documentation change only. Merging.

**Pull request merged**
