### PR TITLE
Add CREDENTIALS_BASE_URL to MFE environment.

### PR DESCRIPTION
**Pull request by mtyaka**
**Description**

Some of the micro-frontend apps expect `CREDENTIALS_BASE_URL` variable to be provided when building the frontend.
For example [app-frontend-profile](https://github.com/edx/frontend-app-profile/blob/f09ffdf75b1703ab56b1a4df3792cf7a9650032c/src/profile/ProfilePage.jsx#L47) uses this value to construct a link for the "View My Records" button on user's profile page.

**Test instructions**:
1. Log into the sandbox and go to the profile page.
2. Verify that the "View My Records" is present and points to https://fakecredentials.example.com/records (a fake URL the sandbox was set up with).

TODO: I'm building a sandbox with `MFE_CREDENTIALS_BASE_URL` set to a custom URL.

**Sandbox**:
- https://mfeplayground-master.opencraft.hosting/
Note: This sandbox was built with `MFE_CREDENTIALS_BASE_URL` set to `"https://fakecredentials.example.com"`.

**Related**:
- https://github.com/edx/frontend-app-profile/pull/421

**Reviewers**:
- [x] @s0b0lev
- [ ] edX?

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mtyaka! I've created [OSPR-5829](https://openedx.atlassian.net/browse/OSPR-5829) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@mtyaka Thank you for your contribution. Please let me know once it is ready for our review.

**Comment by s0b0lev** [comment]
@mtyaka :+1:
- [x] I tested this: (describe what you tested)
- [x] I read through the code

**Comment by mtyaka** [comment]
@natabene This is ready for edX review.

**Review by jdmulloy — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@mtyaka 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6438&entry.1484655318=https://github.com/mtyaka&entry.752974735=2021-06-03+07:43&entry.1917517419=2021-06-07+15:23&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by mtyaka** [comment]
Thank you @jdmulloy! Can we also merge https://github.com/edx/configuration/pull/6441, which cherry-picks these changes into the lilac branch? /cc @nedbat

**Pull request merged**
