### PR TITLE
Activating nodeenv to use bower

### PR DESCRIPTION
**Pull request by clintonb**
The nodeenv needs to be active in order to add `node` to the `PATH`. The `bower` command makes calls to `node`.

@e0d @feanil

### CODE REVIEW

**Comment by feanil** [comment]
What settings does this need to set, is it just the NODE_PATH?  If so, I would prefer to set that as an environment setting.  If it's more complicated then this is fine but I would rather you say `source` than `.`

**Comment by clintonb** [comment]
The activate script updates PATH as well. `source` failed on both my sandbox and during the AMI build. I'll make the environment setting change.

**Comment by clintonb** [comment]
@feanil The activate script sets a few other variables as well. It's not complicated, just a bit tedious. I'd prefer to stick with using it. Let me know if you have thoughts on `source` not working.

**Comment by clintonb** [comment]
@e0d @feanil Can this be merged?

**Comment by feanil** [comment]
:+1:

**Pull request merged**
