### PR TITLE
Fix determining video storage location

### PR DESCRIPTION
**Pull request by gabor-boros**
Based on the `EDXAPP_DEFAULT_FILE_STORAGE` determine which `edxapp_media_dir` should be used. In case the storage is a file system storage, use the default media dir with the leading slash (`edxapp_media_dir`), otherwise use the S3 based one (`edxapp_media_dir_s3`) without leading slash.

**JIRA tickets**: If there is a related publicly viewable JIRA ticket, mention that here. Also mention the OSPR ticket
number here once it gets created (after you open the PR), if applicable. Otherwise omit this.

**Discussions**: 

* [GitHub PR introduced the issue](https://github.com/edx/configuration/pull/5789#issuecomment-689131337)

**Dependencies**: None

**Screenshots**: 
Screenshot 2020-09-18 at 14 25 14

**Sandbox URL**: https://se-3316.stage.opencraft.hosting/ (credentials: the default demo staff user credentials)

**Merge deadline**: None

**Testing instructions**:

1. Create a course
2. Add video
3. Add transcript

You can use the following content for transcript:

```
1
00:00:00,00 --> 00:01:00,00
Hello, this is working fine
```

**Author notes and concerns**:

1. In case there is a third storage type beside Local File System Storage and S3, and the new storage type requires a leading slash, the media upload will fail. - I don't think this will be an issue in the near future

**Reviewers**
- [x] @toxinu
- [ ] edX reviewer[s] TBD

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @gabor-boros! I've created [OSPR-4971](https://openedx.atlassian.net/browse/OSPR-4971) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@gabor-boros Thank you for your contribution. Please let me know once tests are green.

**Comment by gabor-boros** [comment]
> @gabor-boros Thank you for your contribution. Please let me know once tests are green.

@natabene As far as I can see the tests are passing, but Travis is not reporting back. For example, if you check https://travis-ci.com/github/edx/configuration/jobs/384978403 that shows green.

**Comment by gabor-boros** [comment]
@natabene I checked the Travis build related to this PR:

For some reason, the **exact same** checks is shown twice, but the first one (which still seems running) is not reporting back to Travis that it is already successful. Weird, but I've seen this issue with other repos as well from time to time. If you check the job IDs, you can see that they are the same.

**The successful task**
Screenshot 2020-09-16 at 7 17 42


**The task which is not reporting back**
Screenshot 2020-09-16 at 7 18 20

Please note that I did not add the sandbox URL yet, but I'm on it.

**Comment by natabene** [comment]
@gabor-boros Thanks, I see. @jmbowman Could you give this test a look when you have a chance?

**Comment by gabor-boros** [comment]
FYI: I converted the PR to draft, since I would like to validate one more thing before this is ready for a review. Sorry for the inconveniences.

**Comment by gabor-boros** [comment]
It seems everything works fine. Please check the attached screenshot (and feel free try it out).
@toxinu Could you please take a look on this?

**Comment by toxinu** [comment]
Looks good to merge 👍🏻

**Comment by gabor-boros** [comment]
@natabene @nedbat This is ready for review

**Comment by natabene** [comment]
@fredsmith Can you please give it a look when you have a chance?

**Review by fredsmith — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@gabor-boros 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6014&entry.1484655318=https://github.com/gabor-boros&entry.752974735=2020-09-15+08:38&entry.1917517419=2020-09-21+15:18&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by misilot** [comment]
Can this be backported to juniper?

**Comment by nedbat** [comment]
@misilot Sure we can put it on Juniper.  Since it's six commits (squash and merge, @fredsmith? :) ), can you make a new pull request into "open-release/juniper.master"?  Tag me on it, and reference this pull request.  Thanks.

**Pull request merged**
