### PR TITLE
SE-2298 Makes the ecommerce OSCAR_DEFAULT_CURRENCY configurable.

### PR DESCRIPTION
**Pull request by samuelallan72**
(cherry picked from commit 436092e2ab1a4dd8db3e5e077dfb6d8dd7151d71)

This allows overriding the default currency in ecommerce during deployment. Useful for instances where the desired currency isn't USD. Originally introduced in https://github.com/open-craft/configuration/pull/119

**Jira tickets**: [OSPR-4409](https://openedx.atlassian.net/browse/OSPR-4409)

**Dependencies**: For this to successfully configure ecommerce, ecommerce requires the changes in https://github.com/edx/ecommerce/pull/2916

**Sandbox URL**: 

-    LMS: https://ecommercepr2916.sandbox.opencraft.hosting/
-    Studio: https://studio.ecommercepr2916.sandbox.opencraft.hosting/

**Merge deadline**: None

**Test instructions**:

1. Set `ECOMMERCE_OSCAR_DEFAULT_CURRENCY` and deploy a new appserver using this branch and the ecommerce branch from https://github.com/edx/ecommerce/pull/2916.
1. Ensure that the ecommerce `settings.OSCAR_DEFAULT_CURRENCY` matches the setting.

**Reviewers**:

- [x] @pomegranited
- [ ] edX reviewers TBD

**Settings**:
```yaml
SANDBOX_ENABLE_ECOMMERCE: yes
ECOMMERCE_OSCAR_DEFAULT_CURRENCY: "GBP"
ECOMMERCE_VERSION: samuel/override-default-currency
ECOMMERCE_REPOS:
  - PROTOCOL: "{{ COMMON_GIT_PROTOCOL }}"
    DOMAIN: "{{ COMMON_GIT_MIRROR }}"
    PATH: "open-craft"
    REPO: "ecommerce.git"
    VERSION: "{{ ECOMMERCE_VERSION }}"
    DESTINATION: "{{ ecommerce_code_dir }}"
    SSH_KEY: "{{ ECOMMERCE_GIT_IDENTITY }}"
```

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @swalladge! I've created [OSPR-4409](https://openedx.atlassian.net/browse/OSPR-4409) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@swalladge Thank you for your contribution. Please let me know once it is ready for our review.

**Comment by pomegranited** [comment]
:+1:

- [x] I tested this using the PR instructions on the [sandbox created for this issue](https://ecommercepr2916.sandbox.opencraft.hosting/) which was built with the following configuration variables: 
   ```yaml
   SANDBOX_ENABLE_ECOMMERCE: yes
   ECOMMERCE_OSCAR_DEFAULT_CURRENCY: "GBP"
   ECOMMERCE_VERSION: samuel/override-default-currency
   ECOMMERCE_REPOS:
     - PROTOCOL: "{{ COMMON_GIT_PROTOCOL }}"
       DOMAIN: "{{ COMMON_GIT_MIRROR }}"
       PATH: "open-craft"
       REPO: "ecommerce.git"
       VERSION: "{{ ECOMMERCE_VERSION }}"
       DESTINATION: "{{ ecommerce_code_dir }}"
       SSH_KEY: "{{ ECOMMERCE_GIT_IDENTITY }}"
   ```

- [x] I read through the code, and checked it against original Ironwood https://github.com/open-craft/configuration/pull/119, which is deployed to a client and working.
- [x] <strike>I checked for accessibility issues</strike> N/A
- [x] <strike>Includes documentation</strike> N/A
- [x] <strike>I made sure any change in configuration variables is reflected in the corresponding
    client's `configuration-secure` repository.</strike> N/A

**Review by pomegranited — APPROVED** [review]

**Comment by samuelallan72** [comment]
@natabene, this is ready for edX review. :)

**Comment by natabene** [comment]
@swalladge Thank you for letting me know. @fredsmith I assume you will want to wait until edx/ecommerce#2916 merges?

**Comment by pomegranited** [comment]
@feanil  Could my review here count as a CC review? We can get another OpenCraft internal review if needed too, just let me know. CC @nedbat

**Comment by feanil** [comment]
@pomegranited I think your review here can count as a CC review so feel free to merge.

**Comment by openedx-webhooks** [comment]
@swalladge 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/5757&entry.1484655318=https://github.com/swalladge&entry.752974735=2020-04-22+00:18&entry.1917517419=2020-07-22+06:00&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
