### PR TITLE
Updates to apache role to make it more flexible and inline with nginx

### PR DESCRIPTION
**Pull request by carsongee**
This removes the include file so that apache sites are more like nginx sites, allows more than one port in case you want to do ssl for example, and untags the tasks.

@jbau and @sefk You will want to double check that I didn't mess anything up for your installs.

### CODE REVIEW

**Comment by hkim823** [comment]
@carsongee going through old PRs, is this still valid and needed?

**Comment by carsongee** [comment]
Yep

**Comment by feanil** [comment]
@jbau or @sefk can you please review this.

**Comment by jbau** [comment]
@sefk this requires a few changes to our vars, can u try it out during this week's release?

Basically we need to define
`apache_ports` and `apache_template_dir`

**Comment by jbau** [comment]
and maybe default `apache_template_dir` will actually work, but we def have to change `apache_ports`

**Comment by sefk** [comment]
OK I'll try it out tomorrow with @stvstnfrd

**Comment by feanil** [comment]
@sefk any update on this?

Also, @carsongee it looks like this needs a rebase.

**Comment by carsongee** [comment]
Rebased

**Comment by sefk** [comment]
I didn't have time to try with this week's install to staging, will try again later this week.

**Comment by feanil** [comment]
@sefk or @jbau I would like to merge this unless it is going to cause a lot of pain for you down the road to deal with it.

**Comment by jbau** [comment]
Hi @feanil that's fine with me.

**Pull request merged**
