### PR TITLE
Add optional task to rebuild the forum elasticsearch index

### PR DESCRIPTION
**Pull request by pomegranited**
This change is required for deployments maintain an persistent database of forum posts, but run ElasticSearch on localhost, so that the index is recreated with each openedx appserver.

Set FORUM_REBUILD_INDEX to run the rebuild_index rake task.

**JIRA tickets**: [OSPR-1825](https://openedx.atlassian.net/browse/OSPR-1825)

**Merge deadline**: Prior to the Gingko.RC1 cut, if possible.  CC @nedbat 

**Testing instructions**:

1. Snapshot your devstack, for safety.
1. As a user with sudo access (e.g. `vagrant`), run: 
   ```
    source /edx/app/edx_ansible/venvs/edx_ansible/bin/activate
    cd /edx/app/edx_ansible/edx_ansible/playbooks/
    ansible-playbook -i localhost, -c local \
                     -e '{"migrate_db": "yes"}' \
                     -e '{"role": "forum",  }' \
                     run_role.yml
   ```
1. Note that `[forum : initialize elasticsearch]` is run, but `[forum : rebuild elasticsearch indexes]` is skipped.
1. Now run: 
   ```
    ansible-playbook -i localhost, -c local \
                     -e '{"migrate_db": "yes", "FORUM_REBUILD_INDEX": "yes"}' \
                     -e '{"role": "forum" }' \
                     run_role.yml
   ```
1. Note that `[forum : initialize elasticsearch]` is run, then `[forum : rebuild elasticsearch indexes]` is run.

**Reviewers**
- [x] @mtyaka 
- [x] @feanil  
- [ ] Second devops review

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [x] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [x] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pomegranited! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=3988&repo=edx%2Fconfiguration"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Comment by mtyaka** [comment]
Thanks @pomegranited! :+1:

- [x] I tested this: I verified that the index was properly rebuild on a new appserver using external MySQL/Mongo, but local ES, when running edx_sandbox playbook using this patch and `FORUM_REBUILD_INDEX: true`.
- [x] I read through the code
- [x] I checked for accessibility issues
- [x] Includes documentation

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pomegranited! I've created [OSPR-1825](https://openedx.atlassian.net/browse/OSPR-1825) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Review by feanil — APPROVED** [review]
@edx/devops second review.

**Comment by pomegranited** [comment]
Thanks, @gsong !

@nedbat  Can this be cherry-picked into ginkgo?  Thank you!

**Comment by gsong** [comment]
@pomegranited Feel free to make a PR to that branch and /cc @nedbat and me.

**Comment by pomegranited** [comment]
Done: https://github.com/edx/configuration/pull/4001

Thanks @gsong !

**Pull request merged**
