### PR TITLE
[BD-13][BB-6735] refactor: rename hidden_module.HiddenDescriptor -> hidden_block.HiddenBlock

### PR DESCRIPTION
**Pull request by 0x29a**
## Description

This PR is a part of the change done in https://github.com/openedx/edx-platform/pull/31113. It updates the path to `HiddenDescriptor` module.

## Testing instructions

Same as for https://github.com/openedx/edx-platform/pull/31113.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @0x29a!


When this pull request is ready, tag your edX technical lead.

**Review by Agrendalath — APPROVED** [review]
:+1:

* [x] I tested this: tested in https://github.com/openedx/edx-platform/pull/31113
* [x] I read through the code
* [x] I checked for accessibility issues: n/a
* [x] Includes documentation: n/a
* [x] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository: n/a

**Comment by ormsbee** [comment]
@jristau1984: is there a corresponding configuration like this in edx-internal?

**Comment by jristau1984** [comment]
@ormsbee it looks like there are alternate versions in edx-internal for `lms.yml` and `studio.yml`, but I see no `main.yml`.

**Review by pomegranited — APPROVED** [review]
:+1: -- I will merge this tomorrow if there are no objections.

- [x] I tested this by deploying a new appserver for https://extpr31113.sandbox.opencraft.hosting/ using this configuration branch.
- [x] I read through the code
- [x] <strike>I checked for accessibility issues</strike> N/A
- [x] <strike>Includes documentation</strike> N/A
- [x] <strike>I made sure any change in configuration variables is reflected in the corresponding
    client's `configuration-secure` repository.</strike> N/A

**Comment by openedx-webhooks** [comment]
@0x29a 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/configuration&entry.867055334=https://github.com/openedx/configuration/pull/6833&entry.1484655318=https://github.com/0x29a&entry.752974735=2022-11-12+16:46&entry.1917517419=2022-12-20+23:44&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
