### PR TITLE
Remove Tender references

### PR DESCRIPTION
**Pull request by stvstnfrd**
The relevant code was removed from edx-platform six months ago [1][2].

[1] https://github.com/edx/edx-platform/pull/9738
[2] fec5129a493e53b10a1b63c2766dc347d9f17790

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @stvstnfrd! I've created [OSPR-1120](https://openedx.atlassian.net/browse/OSPR-1120) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by stvstnfrd** [comment]
CC: @peter-fogg

**Comment by peter-fogg** [comment]
Thanks for cleaning this up, @stvstnfrd. :+1:

**Comment by feanil** [comment]
I've made the secure PRs for this to remove it from our side. :+1:

**Comment by stvstnfrd** [comment]
Hrm, it looks like one of the Docker builds is failing while waiting for interactive user input:

``` sh
sudo apt-get install docker-engine
> ...
> Do you want to continue? [Y/n]
> ...
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

My guess would be about adding a `-y` flag to the `apt-get install`, though that doesn't seem like something that should have been affected by this PR.

Please advise, @feanil .

**Comment by feanil** [comment]
@stvstnfrd I've made PR https://github.com/edx/configuration/pull/2755 to fix the issue.  If that resolves it, I can merge it and this PR can be rebased on top of it.

**Comment by feanil** [comment]
@stvstnfrd looks like the docker test failures are un-related, I believe this is safe to merge.  :+1:

**Comment by stvstnfrd** [comment]
Hey @feanil I rebased from master, but I'm still seeing Docker-related failures.

Assuming those are irrelevant, please merge when ready.

**Pull request merged**
