### PR TITLE
support gerrit AWS provisioning with cloud formation

### PR DESCRIPTION
**Pull request by mulby**
Note:
- Sets up a VPC.  Is that overkill?
- Deploys the app server and the ELB into the public subnet, RDS into the private.  I considered putting the app server in the private subnet, but that would require also running a NAT/bastion host, which seemed like a lot of overhead for a single app server.
- Removes the nginx reverse proxy since the ELB can now server that purpose.
- Completely untested.

Reviewers: @e0d, @jarv, @gwprice

### CODE REVIEW

**Comment by gwprice** [comment]
I didn't look at the CloudFormation template at all, but the rest looks good to me

**Comment by singingwolfboy** [comment]
Needs to be rebased.

**Comment by jarv** [comment]
@mulby This is pretty old, please re-open after rebase if you still want to merge it

**Comment by mulby** [comment]
heh, yeah I thought we already closed these.

**Pull request closed without merging**
