### PR TITLE
Added ecommerce host to LMS CORS whitelist for sandboxes

### PR DESCRIPTION
**Pull request by clintonb**
ECOM-2469

@feanil @rlucioni @jimabramson

### CODE REVIEW

**Comment by feanil** [comment]
@clintonb why a new variable?

**Comment by clintonb** [comment]
@feanil is there a better way to append to a list?

**Comment by feanil** [comment]
What would set it that you're afraid of overwriting?

**Comment by clintonb** [comment]
I want the changes from configuration_secure in addition to the sandbox host. How would I combine those two values?

**Comment by clintonb** [comment]
@devops Any feedback?

**Comment by feanil** [comment]
@clintonb does the cors origin whitelist take wildcards?  This seems like the sort of thing we can add in sandbox-secure if that is the case.

**Comment by clintonb** [comment]
@feanil that would be awesome, assuming exposing `*.sandbox.edx.org` is not a security risk.

**Comment by feanil** [comment]
For sandboxes I think it's probably fine, actually I think the correct thing is to pas the hostname to ansible and then do it in sandbox secure, I think this is not a code change but a config change to sandbox secure.  Can you put in a ticket for that?

**Comment by clintonb** [comment]
@feanil DEVOPS-3093

**Pull request closed without merging**
