### PR TITLE
workaround invalid upstream certs when installing browsers

### PR DESCRIPTION
**Pull request by fredsmith**

### CODE REVIEW

**Comment by e0d** [comment]
Seems like the simplest possible fix, but do we know why this has started now?

Still, :+1:

**Comment by fredsmith** [comment]
My guess is that s3 changed their cert to one that's incompatible with ansible 1.5.5

**Comment by jibsheet** [comment]
I assumed it was the SSLv3 deprecation.  I assumed those would all have broken on May 20th, but maybe they found more buckets to deprecate?

**Comment by ghost** [comment]
Hi folks! Is there any way to fix it for the birch release also? Can't get my head on how to fix it myself.

**Pull request merged**
