### PR TITLE
[ENT-486] Add `ENTERPRISE_SUPPORT_URL` variable.

### PR DESCRIPTION
**Pull request by UmanShahzad**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [x] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

This adds a new variable, `ENTERPRISE_SUPPORT_URL`, to be used in the `edx-enterprise` repo and beyond... a corresponding PR for `edx-platform` -- https://github.com/edx/edx-platform/pull/15970

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @UmanShahzad! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=4081&repo=edx%2Fconfiguration"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Comment by feanil** [comment]
@UmanShahzad can you link to the relevant edx-platform PRs as well?

**Comment by UmanShahzad** [comment]
@feanil Yes absolutely, sorry I had forgotten to update it: https://github.com/edx/edx-platform/pull/15970

**Review by feanil — APPROVED** [review]

**Review by haikuginger — APPROVED** [review]
:+1:

- [x] ~~I tested this~~ Variable is configured appropriately with a high-level default with the EDXAPP prefix, and an LMS level default that derives from same.
- [x] I read through the code
- [x] I checked for accessibility issues
- [x] Includes documentation

**Comment by UmanShahzad** [comment]
@douglashall @brittneyexline Good for you guys?

**Comment by UmanShahzad** [comment]
@douglashall @brittneyexline One more ping :D Sorry for disturbing, just doing to be sure you guys are aware about this one.

**Review by douglashall — APPROVED** [review]

**Pull request merged**
