### PR TITLE
Remove the default edxapp secret key to ensure secure defaults

### PR DESCRIPTION
**Pull request by OmarIthawi**
Configuration Pull Request
---

While it's all caps, if no one takes a look at the `lms.env.json` it's going to slip. I think it's better to break on deployment than having such insecure default slip through.

---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [x] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @OmarIthawi! I've created [OSPR-2613](https://openedx.atlassian.net/browse/OSPR-2613) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by mduboseedx** [comment]
@edx/devops This removes the default edxapp secret. What do you think?

**Comment by nedbat** [comment]
I can see the thinking here.  But this will require a change in the Native installation instructions, and will require everyone to use randomized passwords.  Should we do that?

**Comment by coryleeio** [comment]
@nedbat We definitely should IMO - knowing the secret key of an application may let you fake signed values, setting a default in a public application is fairly dangerous, somewhat depending on your implementation. 

We should probably make the application fail in a nice way when it doesn't have a defined secret key though.

**Comment by OmarIthawi** [comment]
> @nedbat I can see the thinking here. But this will require a change in the Native installation instructions, and will require everyone to use randomized passwords. Should we do that?

That's correct, while I'm not pretty comfortable with the blast change that this PR will do, I have the following in my mind:

 - The [native installation currently recommends](https://openedx.atlassian.net/wiki/spaces/OpenOPS/pages/146440579/Native+Open+edX+Ubuntu+16.04+64+bit+Installation#NativeOpenedXUbuntu16.0464bitInstallation-Automatedinstallation) randomizing keys and generates `my-passwords.yml` file. We can modify the docs to require it, we don't deviate much of the existing instructions by doing so.
 - Leaving such key would favor the knowledgeable attacker over the novice system admin. I think we should favor the latter, even at the cost of their own inconvenience.
 
What do you think?

**Comment by OmarIthawi** [comment]
@coryleeio @nedbat a gentle reminder about this PR.

**Comment by coryleeio** [comment]
@feanil @nedbat What do you guys want to do here?

It's a tradeoff, removing it is harder for people running our stack to get themselves into trouble, but makes installation require an additional step that we might need to document.

Should be safe to merge for us though, if it breaks anyone downstream its because they are using a default key.

I say merge it, personally.

**Comment by OmarIthawi** [comment]
Thanks @coryleeio, one thing though, how's the devstack being built these days? Probably devstack needs that dummy value, but where we should put it?

**Comment by coryleeio** [comment]
Yeah I think you're right.  I think it would need to go in the
ansible-overrides beside the dockerfile in configuration repo for all the
correct Dockerfiles
https://github.com/edx/configuration/blob/master/docker/build/edxapp/ansible_overrides.yml

**Comment by OmarIthawi** [comment]
Done @coryleeio. But I don't know how to quickly verify that it will work on devstack builds.

**Comment by OmarIthawi** [comment]
@coryleeio let's not merge right now. Marking as `(WIP)`, I need to test something.

**Comment by OmarIthawi** [comment]
@coryleeio all should be good for now. Do you mind taking a look and let me know what do you think?

cc: @mduboseedx

**Comment by coryleeio** [comment]
I need a decision made regarding how we want to go forward before I can merge this @nedbat @feanil

**Comment by OmarIthawi** [comment]
Thanks for the update @coryleeio! Appreciate your help.

**Comment by OmarIthawi** [comment]
@feanil @coryleeio @nedbat Pinging you about this PR as it's been about a month without any decision. I appreciate your feedback!

**Review by feanil — APPROVED** [review]

**Comment by natabene** [comment]
@nedbat  Do you want to merge this?

**Comment by feanil** [comment]
@natabene yes, waiting for a second review from the team.

**Review by coryleeio — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@OmarIthawi 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4778&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2018-09-17+14:05&entry.1917517419=2019-01-25+18:16&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by nedbat** [comment]
@feanil @coryleeio Thanks.  Can you update the Ironwood page with the implications of this change, and I will cherry-pick this if it makes sense.

**Comment by feanil** [comment]
@nedbat  I added a note to the ironwood page.

**Comment by OmarIthawi** [comment]
@nedbat @coryleeio @feanil @natabene thank you!

**Comment by nedbat** [comment]
I've cherry-picked this onto ironwood.master.

**Pull request merged**
