### PR TITLE
Upgrade setuptools, pip, and virtualenv

### PR DESCRIPTION
**Pull request by jmbowman**
Upgrade setuptools, pip, virtualenv, and virtualenvwrapper to the latest consistent versions.  Preparation for removing the "pre.txt" requirements file from edx-platform.

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [x] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

### CODE REVIEW

**Comment by jmbowman** [comment]
I used this branch to create both a normal sandbox and a from-scratch sandbox, both built and are running normally.  I didn't test much further than that, but for these changes the risk of breakage after successfully installing everything seems pretty low.

**Review by jibsheet — APPROVED** [review]
This looks reasonable to me, do you mind merging on Monday to minimize any weird gocd strangeness over the weekend (we're going to update the go-agent on Monday, so I'll tag Nadeem about it)

**Comment by jibsheet** [comment]
@nadeemshahzad Heads that I think this is a second change to the go-agent that we may want to roll up with your change?  Possible two separate builds/deploys

**Comment by jmbowman** [comment]
Sure, I don't really want to mess with this until the edx-platform Django 1.11 ugprade settles down anyway.  Just want it in before the PR that switches edx-platform to pip-tools.

**Comment by nadeemshahzad** [comment]
@jmbowman @jibsheet I will rebase my PR and deploy go-agent after this PR is merged to make sure go-agent build contain both changes.

**Comment by doctoryes** [comment]
FYI - when it comes time to remove references to `pre.txt` here:

```
$ rg pre.txt
playbooks/roles/edxapp/defaults/main.yml
1411:pre_requirements_file:    "{{ edxapp_code_dir }}/requirements/edx/pre.txt"

playbooks/roles/jenkins_worker/tasks/python_platform_worker.yml
24:    - pre.txt

$ rg pre_requirements_file
playbooks/roles/edxapp/vars/devstack.yml
9:  - "{{ pre_requirements_file }}"

playbooks/roles/edxapp/defaults/main.yml
1411:pre_requirements_file:    "{{ edxapp_code_dir }}/requirements/edx/pre.txt"
1431:  - "{{ pre_requirements_file }}"
1444:  - "{{ pre_requirements_file }}"
```

**Pull request merged**
