### PR TITLE
Fix issues related to JOURNALS_API_URL

### PR DESCRIPTION
**Pull request by SSPJ**
This has to do with the `./manage` command in [edx/configuration/playbooks/roles/ecommerce/defaults/main.yml](edx/configuration/playbooks/roles/ecommerce/defaults/main.yml) contianing `--journals_api_url={{ JOURNALS_API_URL }}` where JOURNALS_API_URL is defined in [edx/configuration/playbooks/roles/edxapp/defaults/main.yml](edx/configuration/playbooks/roles/edxapp/defaults/main.yml). That role (edxapp) does not share variable scope with the ecommerce role, hence JOURNALS_API_URL is undefined in the ecommerce role. Ansible deployments using ecommerce fail.

**JIRA tickets**: 
**Discussions**: 
**Dependencies**: 
**Screenshots**: 
**Sandbox URL**:
**Merge deadline**: Unknown

**Testing instructions**:

1. Use the Vagrantfile in vagrant/base/test_role/ with the ecommerce env variable (after commenting out the config.vm.box_url and setting the config.vm.box to, say, geerlingguy/ubuntu1604, because the current box is link rot).
2. Observe that the role fails as described above.
3. Repeat with this branch. Ansible finishes without error.

**Author notes and concerns**:

1. This is the "easy" fix. It prevents the ecommerce role from raising an error when JOURNALS_API_URL is undefined. Given that I am new to the codebase, I do not feel comfortable attempting the "elegant" solution, which is that JOURNALS_API_URL should have a default value declared once for the entire repository. To do so would require:
    - making the common_vars role a dependency of the ecommerce role (is this safe?)
    - moving the JOURNALS_API_URL var up to the common_vars role
    - moving the EDXAPP_LMS_BASE var which JOURNALS_API_URL interpolates up to the common_vars role

**Reviewers**
- [ ] @itsjeyd 
- [ ] edX reviewer

---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @SSPJ! I've created [OSPR-2710](https://openedx.atlassian.net/browse/OSPR-2710) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@SSPJ Thank you for your contribution. @edx/devops and @bill-filler , can you give this a look?

**Review by bill-filler — APPROVED** [review]
looks good

**Review by itsjeyd — APPROVED** [review]
@SSPJ This LGTM as well. For future reference it would be great if you could update the commit message to provide some context on this change, but other than that this is :+1:

- [x] I tested this: Verified that with this change in place, provisioning process did not error out at [run post-migrate commands](https://github.com/edx/configuration/blob/f754d0eff236ddc0d058d5e41482c4ace331b83c/playbooks/roles/edx_django_service/tasks/main.yml#L126-L138) task for `ecommerce`.
- [x] I read through the code
- [x] ~~I checked for accessibility issues~~ N/A
- [x] ~~Includes documentation~~ N/A

**Comment by itsjeyd** [comment]
Thanks @natabene and @bill-filler for the quick turnaround on this one! I reviewed and approved the change as well; is there anything else you need from us before merging it?

**Comment by natabene** [comment]
@SSPJ , @itsjeyd We'll need to have devops team have a look before merging. @edx/devops This is ready to merge, just needs a quick look from you.

**Review by coryleeio — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@SSPJ 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4852&entry.1484655318=https://github.com/SSPJ&entry.752974735=2018-10-17+19:56&entry.1917517419=2018-10-23+21:21&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by itsjeyd** [comment]
@natabene 

> We'll need to have devops team have a look before merging.

Ah, yes -- I was under the impression that we already had that covered (via @bill-filler's review) :) But anyway, thanks again for the coordination here, it was great to see this merge quickly!

And thanks @coryleeio for the second look.

**Pull request merged**
