### PR TITLE
Add registration extra fields setting to configuration.

### PR DESCRIPTION
**Pull request by wedaly**
This exposes a Django setting to configure the registration form.  The values in this PR are identical to the [current defaults](https://github.com/edx/edx-platform/blob/master/lms/envs/common.py#L1425-L1441)

Eventually, we'll need to override the defaults to set `country` to "optional" for [ECOM-128](https://openedx.atlassian.net/browse/ECOM-128).

@jarv please review.

### CODE REVIEW

**Comment by jarv** [comment]
Did we investigate putting these settings into the configuration model instead of settings?

**Comment by jarv** [comment]
:+1:

**Comment by wedaly** [comment]
The configuration was added back in January by Xavier -- I don't know if they discussed using a configuration model instead of settings.  I'm expecting that the ecommerce team will rework the registration dialog down the road, and we can certainly revisit that decision.

**Comment by jbau** [comment]
just curious, what do you guys mean by configuration model?  do you mean django model fields, or is this something else?

**Comment by jarv** [comment]
@jbau we would like to migrate most of the settings into the database, see https://github.com/edx/edx-platform/blob/master/common/djangoapps/config_models/models.py

**Comment by jbau** [comment]
ah ok, thx.

**Pull request merged**
