### PR TITLE
E0d/fix edxapp

### PR DESCRIPTION
**Pull request by e0d**
@cpennington working edxapp builds.

### CODE REVIEW

**Comment by e0d** [comment]
Fixes the timeout but exhausts travis memory :facepunch:

**Comment by e0d** [comment]
@cpennington until I understand what our options are for making more memory available to Travis or constraining memory usage during CI, we will likely need to disable CI for edxapp.  I don't want to do so using by renaming the file, since this container will build outside of Travis.  Thoughts on the best way to achieve that?  Perhaps a CI `.excludes` file?

**Comment by cpennington** [comment]
By my reading of the logs, it's still timing out. Why do you think it's memory exhaustion?

Also, as far as excluding it from CI: yeah, adding a .ci-excludes would be fine.

**Comment by e0d** [comment]
I was misinterpreting the sig 137 I think, I agree that it is still probably a timeout issue.  20 minutes is going to be the max we can wait without output

**Comment by cpennington** [comment]
We should be able to make it log incrementally, I would think.

**Comment by e0d** [comment]
Yes, agree, will track down and see what can be done.

Ed.

**Comment by e0d** [comment]
@cpennington see that last commit.

**Comment by cpennington** [comment]
:+1:

**Pull request merged**
