### PR TITLE
Jenkins should save the state of the rbenv

### PR DESCRIPTION
**Pull request by singingwolfboy**
Companion to #1049, but for Ruby instead of Python. The companion edx-platform pull request is https://github.com/edx/edx-platform/pull/3603. @feanil @jzoldak, can you two review?

### CODE REVIEW

**Comment by feanil** [comment]
:+1:

**Comment by jzoldak** [comment]
@singingwolfboy did you run the playbook to verify that this works correctly?
I think you'd need to run a bundle install the first time to populate the rbenv. Does this get done somewhere?

**Comment by feanil** [comment]
The bundle install gets done as part of the rbenv role which is a dependency(https://github.com/edx/configuration/blob/master/playbooks/roles/jenkins_worker/meta/main.yml)

**Comment by singingwolfboy** [comment]
@jzoldak I just successfully tested the playbook locally, with a fair amount of help from @feanil. It works the way I expected.

**Pull request merged**
