### PR TITLE
Add JWT_ISSUERS configuration for ecommerce.

### PR DESCRIPTION
**Pull request by peter-fogg**
@rlucioni @jimabramson @clintonb @feanil

### CODE REVIEW

**Comment by rlucioni** [comment]
:+1:

**Comment by jimabramson** [comment]
:+1:

**Comment by clintonb** [comment]
Why are there two issuers?

**Comment by clintonb** [comment]
Never mind. :+1:

**Comment by peter-fogg** [comment]
@clintonb The ecommerce service needs to accept JWTs from both the LMS and the worker process.

**Comment by clintonb** [comment]
Reverting because `ecommerce_worker_service_name` is undefined. See http://jenkins.edx.org:8080/view/Ansible/job/ansible-provision/3698/console.

@feanil please advise how we should share variables across roles.

**Comment by rlucioni** [comment]
From the [Ansible docs](http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable):

> Generally speaking, variables set in one role are available to others. This means if you have a `roles/common/vars/main.yml` you can set variables in there and make use of them in other roles and elsewhere in your playbook.

Sounds like what was being done here was legal. @peter-fogg if variables can't be shared across roles in this way, you might try passing the issuer name to the ecommerce_worker role as a parameter; see "parameterized roles" in the link above.

**Pull request merged**
