### PR TITLE
Coryleeio/ip disclosure

### PR DESCRIPTION
**Pull request by coryleeio**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

### CODE REVIEW

**Comment by coryleeio** [comment]
This includes the http->https redirect fixes for edxapp and for the other idas

curl http://loadtest-edx-ecommerce.edx.org/heartbeat --http1.0 -H"Host:" -u "USER:PW" -v
curl http://loadtest-edx-edxapp.edx.org/heartbeat --http1.0 -H"Host:" -u "USER:PW" -v

**Comment by coryleeio** [comment]
I also consolidated the copies of the same logic in the nginx role

**Comment by coryleeio** [comment]
We should also verify that HTTP->HTTPS normal redirects without protocol downgrades etc are still working.

curl http://loadtest-edx-edxapp.edx.org/heartbeat -u "USER:PW" -v
curl http://loadtest-edx-ecommerce.edx.org/heartbeat -u "USER:PW" -v

**Comment by coryleeio** [comment]
The servers being in the ELB in loadtest validates that healthchecks still function

**Review by feanil — APPROVED** [review]

**Review by jibsheet — APPROVED** [review]

**Pull request merged**
