### PR TITLE
Add support for HLS-related codecs.

### PR DESCRIPTION
**Pull request by benpatterson**
Addresses #3728.

This would allow @muhammad-ammar to test his changes via bok-choy.

Also @muzaffaryousaf @gsong @estute. Feedback welcome.

Configuration Pull Request
---

Make sure that the following steps are done before merging

  - [ ] A devops team member has commented with :+1:
  - [ ] are you adding any new default values that need to be overridden when this goes live?
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

### CODE REVIEW

**Review by gsong — APPROVED** [review]

**Comment by muhammad-ammar** [comment]
@benpatterson This is great. Can we run our tests on Jenkins with this change?

**Comment by benpatterson** [comment]
@muhammad-ammar you can use the wrapper jobs in the short-term with the worker label `jenkins-hls`. 

@estute could you connect separately with Ammar to go over those details with him? I haven't merged this yet; i'd like to hear @estute and @muhammad-ammar 's opinion before doing so. I want to be sure it addresses Ammar's needs.

**Comment by muhammad-ammar** [comment]
@benpatterson I have tried the js build with `jenkins-hls` but getting [errors](https://build.testeng.edx.org/job/edx-platform-js-pr/32110/console). I am not what is missing.

**Comment by benpatterson** [comment]
I will ping you offline.

**Comment by benpatterson** [comment]
@muhammad-ammar verified that this works for the JS tests that rely on this capability through the special-worker job. I'll merge now and put in a ticket to get the workers updated.

**Pull request merged**
