### PR TITLE
Override DISCOVERY_VERSION in install script

### PR DESCRIPTION
**Pull request by myleshk**
Currently the value of `DISCOVERY_VERSION` is `master`, so the installed code located at `/edx/app/discovery/discovery` is on `master` branch instead of the expected release version, e.g. `open-release/ginkgo.2`.

I'm not sure if the code of this "course-discovery" repo is actually being used, but I've checked the vagrant Fullstack box and in it this repo is on release version tag, and thus I made this PR.

This change applies override of variable `DISCOVERY_VERSION` by the value of environment variable `OPENEDX_RELEASE` set by user during installation.

---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @myleshk! I've created [OSPR-2064](https://openedx.atlassian.net/browse/OSPR-2064) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by nedbat** [comment]
@myleshk thanks, good catch.  I'm going to change this into a pull request against master, and then cherry-pick the result onto Ginkgo, which is how we usually make changes unless they are only for Ginkgo.

**Comment by nedbat** [comment]
Oops, never mind, doing that from GitHub didn't work right.  Would you mind changing the base to "master"?

**Comment by openedx-webhooks** [comment]
@myleshk Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4274&entry.1484655318=https://github.com/myleshk&entry.752974735=2018-01-09+02:34&entry.1917517419=2018-01-12+02:37&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
