### PR TITLE
Add 3 new vars to define edx-platform, comments_service and theme repositories

### PR DESCRIPTION
**Pull request by rodo**
The 3 new vars will be used later, comments are added to in job definition to be more explicit, the comments come from abbey.py

### CODE REVIEW

**Comment by feanil** [comment]
@rodo You shouldn't need to be using explicit parameters for the comment service, platform and theme.  This is what the `refs` section is for.  You provide all version overrides there.

**Comment by rodo** [comment]
@feanil I'll look to `refs` to better understand it's usage, I removed the 3 vars and left this PR open as I kept the descriptions on other vars.

**Comment by rodo** [comment]
@feanil have you some samples of `refs` usage, can't find in the docs or code.

**Comment by feanil** [comment]
Refs is of the form `<repo_name>_version`, The default values are in the
defaults.yml for various roles.
https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml#L547
and
https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml#L553
in the edxapp role for example are keys that you can override in the refs
section.

**Comment by rodo** [comment]
@feanil thanks again for this information, as I saw a TODO in this file I permit myself to uppercase variables in my last commit 8a0e4ece5b4d5e0869894f86bbc25795e29b965c
I started too a wiki page about these parameters https://github.com/edx/configuration/wiki/Jenkins-build_ami probably not a good title, please feel free to retitle it.

**Comment by hkim823** [comment]
Closing this PR since nothing more to do

**Pull request closed without merging**
