### PR TITLE
Added PhantomJS to Jenkins workers

### PR DESCRIPTION
**Pull request by clintonb**
LEARNER-509

### CODE REVIEW

**Comment by clintonb** [comment]
@edx/devops @edx/testeng please review. What is involved in getting this deployed?

**Comment by estute** [comment]
@clintonb we already have phantomJS installed on the Jenkins workers (via the browsers role - https://github.com/edx/configuration/blob/master/playbooks/roles/browsers/defaults/main.yml). However, we are planning on getting rid of it

**Comment by clintonb** [comment]
@estute Why do you want to get rid of it?

Question for @edx/devops: any opposition to my adding Firefox and PhantomJS to the tools_jenkins Docker image? In order to actually run my tests I either need to do that, or run a worker (for which we do not currently have a Docker image).

**Comment by estute** [comment]
@clintonb because PhantomJS either unmaintained or will be soon, and just creates more tools spread. We currently only use it for a11y testing, and plan to do that with FF (or eventually headless chrome)

**Comment by clintonb** [comment]
This has been a bit painful. Does no one test their DSL locally? If so, how do they test e2e tests without a browser?

**Comment by estute** [comment]
@clintonb Ah, sorry if that was misleading. The only use of Phantom JS in the a11y tests. We use Chrome and FF for all other testing. The e2e tests are run with FF

**Comment by jibsheet** [comment]
We run the browsers role on tools_jenkins for the ora2 tests, so you have what they have.

**Pull request closed without merging**
