### PR TITLE
Disabled basic authentication for the /api paths of ecommerce and programs

### PR DESCRIPTION
**Pull request by clintonb**
ECOM-4414

### CODE REVIEW

**Comment by clintonb** [comment]
@jibsheet please review

**Comment by clintonb** [comment]
FYI @edx/ecommerce

**Comment by rlucioni** [comment]
I'd like to understand why this hasn't affected us on stage (or prod) before.

**Comment by peter-fogg** [comment]
Code looks good to me, but I'd also be interested in knowing the answer to @rlucioni's question.

**Comment by clintonb** [comment]
We don't use basic auth for stage-edx-ecommerce.

**Comment by rlucioni** [comment]
@clintonb or prod-edx-ecommerce, I'm guessing? 👍, thanks for looking into this.

**Comment by feanil** [comment]
👍

**Pull request merged**
