### PR TITLE
Fixed dead link in README.md (ansible.cc -> ansible.com)

### PR DESCRIPTION
**Pull request by dhpollack**
The ansible link is dead.  I changed it from ansible.cc to ansible.com.

### CODE REVIEW

**Comment by feanil** [comment]
@dhpollack thanks for the update. Can you please sign the CLA(https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst#step-1-sign-a-contribution-agreement)?

**Comment by dhpollack** [comment]
Yup, I just signed it and sent it to jennifer@edx.org.  Let me know what else I need to do.

**Comment by dhpollack** [comment]
sorry, I'll delete this second commit... still trying ot figure out how to use git in general...

**Comment by dhpollack** [comment]
apologies for mucking up this pull.  I'm new to the git world.  But yea, the intended changes will be made with a bunch of extra commits.  If need be, I could probably roleback all those commits with the proper hand holding as clearly I'm a little lost.

**Comment by feanil** [comment]
@dhpollack When making changes it's probably best to do them on a branch on your fork and keep your master branch in sync with ours.  This make it easy to take updates we've made and merge then in with your work at your own pace.  What I would suggest here is making an new branch at the inital commit and making a new PR from that branch onto our master branch.

```
$ git checkout 645e7b4
$ git checkout -b update_readme
$ git push origin update_readme
```

This will go the correct commit, create a new branch, and then push that branch to your fork.  Once that's done you can make a new PR from that.  Once that's done, we can close this PR and merge the other one when Jeniffer has processed your CLA.

**Comment by dhpollack** [comment]
@feanil thanks.  I think that I got it.

**Comment by feanil** [comment]
Yea, looks good.  Closing this one.

**Pull request closed without merging**
