### PR TITLE
E0d/common refactor

### PR DESCRIPTION
**Pull request by e0d**
@jibsheet @fredsmith @feanil 

Finally, getting around to what was discussed here:

https://github.com/edx/configuration/issues/1760

### CODE REVIEW

**Comment by feanil** [comment]
Perhaps the readme in the `common` role should actually just be a comment at the top of the `common/defaults/main.yml` file that is otherwise empty?

**Comment by e0d** [comment]
@feanil removed the readme files in favor of empty files with comments.

@edx/devops FYI

**Comment by feanil** [comment]
:+1:

**Comment by e0d** [comment]
@arbabnazar FYI, this is a change to how common vars will be managed.

**Pull request merged**
