### PR TITLE
whitelisting 10.0.0.0/8

### PR DESCRIPTION
**Pull request by e0d**

### CODE REVIEW

**Comment by feanil** [comment]
:+1:

**Comment by jarv** [comment]
Hm, there was a reason why we removed this - https://github.com/edx/configuration/commit/7ea2fbeb2ab657453a92f366c4f5d715115aedf8#diff-b10b3eecfbcafe1bc698b53a5c470f9e

I think it was because it was disabling basic auth in all cases for traffic through an ELB

**Comment by e0d** [comment]
@jarv I've made tis specific for now until we can decide upon a better solution.

**Comment by jarv** [comment]
:+1:

**Pull request merged**
