### PR TITLE
Add Allow-Credentials header so POSTs can work with cross origin

### PR DESCRIPTION
**Pull request by tuchfarber**
@georgebabey was right.

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

### CODE REVIEW

**Comment by tuchfarber** [comment]
@georgebabey Wasn't sure if this was supposed to sit in 'OPTIONS' only section or where I have it.

**Review by georgebabey — APPROVED** [review]
My understanding is that because `GET`s may also need credentials to be passed, and those don't require the OPTION preflights, you should include the `Access-Control-Allow-Credentials` on all request.

**Comment by feanil** [comment]
This will add it for all the IDAs is that the right intent?  Any security concerns with allowing this everywhere?

**Comment by georgebabey** [comment]
@feanil Yes I believe all IDAs should set this. It is needed to allow SSO via JWT Cookies throughout our applications.

The only reason we didn't need it for the enterprise portal is we are not currently following the JWT Cookies and instead passing authorization bearer tokens, but that doesn't work for SSO scenarios.

**Comment by tuchfarber** [comment]
As I'm reading it, it would only be set in the following two cases:
1) The /static/ directory of all IDAs. There shouldn't be any security issue as there are no APIs, just assets. 
2) IDAs with `edx_django_service_allow_cors_headers` set to True, which right now seems to be Analytics API and Journals. These both also have CORS whitelists, which protects us from the CSRF attack this would otherwise make available.

**Review by feanil — APPROVED** [review]

**Pull request merged**
