### PR TITLE
Vagrantfile dev utilize

### PR DESCRIPTION
**Pull request by dangtrinhnt**
Trying to use the pre-downloaded devstack box before downloading from edx server.

### CODE REVIEW

**Comment by hkim823** [comment]
I'm not sure why this is necessary, the box if it's downloaded once should be stored in ~/.vagrant.d/ and doing a vagrant box list should show the boxes available.

**Comment by dangtrinhnt** [comment]
It's the matter of Internet connection. I always have to download the box with a download manager before running the vagrant up to fasten up the process. I think this is useful.

**Comment by feanil** [comment]
Vagrant allows you to add the file manually from a URL or local disk. https://docs.vagrantup.com/v2/getting-started/boxes.html

I don't think it makes sense to add logic to the vagrantfile for this.

**Comment by dangtrinhnt** [comment]
Thanks @feanil , just noted.

**Pull request closed without merging**
