### PR TITLE
add DEFAULT_MOBILE_AVAILABLE

### PR DESCRIPTION
**Pull request by jagonzalr**
[OSPR-1986](https://openedx.atlassian.net/browse/OSPR-1986)

Configuration Pull Request
---

Adds the default value for course mobile available using this var ```EDXAPP_DEFAULT_MOBILE_AVAILABLE```

This PR is related to this [PR](https://github.com/edx/edx-platform/pull/16372)

Reviewers
- Code review: ¯_(ツ)_/¯

cc @nedbat

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @jagonzalr! I've created [OSPR-1986](https://openedx.atlassian.net/browse/OSPR-1986) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by feanil** [comment]
I don't see any mention of this in the edx-platform code base.  Can you please point to what part of that code picks up this var and does something with it?

**Comment by jagonzalr** [comment]
@feanil the description of the PR already points to this but here it goes [again](https://github.com/edx/edx-platform/pull/16372).

**Comment by jagonzalr** [comment]
@nedbat @feanil  would appreciate a push on this PR since this [one](https://github.com/edx/edx-platform/pull/16372) has already been merged :)

**Review by feanil — APPROVED** [review]

**Review by jdmulloy — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@jagonzalr 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4180&entry.1484655318=https://github.com/jagonzalr&entry.752974735=2017-10-28+15:19&entry.1917517419=2017-11-21+15:52&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
