### PR TITLE
Add setting to update XBLOCK_SETTINGS

### PR DESCRIPTION
**Pull request by tusbar**
It’s already in edx-platform:
- https://github.com/edx/edx-platform/blob/master/lms/envs/aws.py#L596
- https://github.com/edx/edx-platform/blob/master/cms/envs/aws.py#L343

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @tusbar! I've created [OSPR-653](https://openedx.atlassian.net/browse/OSPR-653) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams. 

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ('this must be merged by XX date', and why that is)
- partner information ('this is a course on edx.org')
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the Github pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by sarina** [comment]
@e-kolpakov this makes sense to you, yes? (will have the ops team do final review/merge)

**Comment by feanil** [comment]
:+1:   @e0d second review?

**Comment by fredsmith** [comment]
:+1:

**Comment by tusbar** [comment]
:+1:

**Comment by e-kolpakov** [comment]
@sarina a bit late for the party - I was on vacation :) Nevertheless, yes, it makes sense. :+1:

**Pull request merged**
