### PR TITLE
Set default for GIT_REPO_EXPORT_DIR

### PR DESCRIPTION
**Pull request by lvnilesh**
Setting GIT_REPO_EXPORT_DIR to default to `/edx/var/edxapp/export_course_repos`

Thanks Carson Gee. https://groups.google.com/forum/#!topic/edx-code/nBfcPQy_W0k

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @lvnilesh! I've created [OSPR-439](https://openedx.atlassian.net/browse/OSPR-439) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams. 

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ('this must be merged by XX date', and why that is)
- partner information ('this is a course on edx.org')
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the Github pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by carsongee** [comment]
Cool, thanks for adding, I must have missed this when the code got added. You will also need to add it around https://github.com/lvnilesh/configuration/blob/patch-4/playbooks/roles/edxapp/defaults/main.yml#L730 to reference the variable you've added

**Comment by carsongee** [comment]
Actually since it is just cms specific, you should probably add it around https://github.com/lvnilesh/configuration/blob/patch-4/playbooks/roles/edxapp/defaults/main.yml#L763

**Comment by lvnilesh** [comment]
Thanks. I added.

**Comment by sarina** [comment]
@carsongee  if you wouldn't mind taking another look at this, that'd be great.

**Comment by carsongee** [comment]
:+1:

**Comment by sarina** [comment]
@lvnilesh thanks for the patch! Someone from our ops team will look at it as soon as they're able to.

**Comment by maxrothman** [comment]
:+1:

**Pull request merged**
