### PR TITLE
Fix missing variable `edxapp_app_dir` in demo role

### PR DESCRIPTION
**Pull request by OmarIthawi**
Fixes the issue reported by @zainab-amir in https://github.com/edx/configuration/pull/4812#issuecomment-436603924.

Zainab could you please check this out and let me know if it works?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @OmarIthawi! I've created [OSPR-2781](https://openedx.atlassian.net/browse/OSPR-2781) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@OmarIthawi Thank you for your contribution, just let us know when you think it is ready to be reviewed.

**Comment by OmarIthawi** [comment]
Thanks @natabene! It is ready for review. I need someone to test it though on `devstack` since it was broken for `@zainab-amir`. I'm not ready to rebuild my devstack at the moment though.

**Comment by zainab-amir** [comment]
@OmarIthawi okay will check.

**Comment by OmarIthawi** [comment]
Thanks @zainab-amir! it'll be a bit tricky to verify, because you need my fork to be used instead of the edX's! 

So :man_shrugging:

**Comment by macdiesel** [comment]
I was just looking in to fixing this issue as it is also causing CI failures on devstack: https://travis-ci.org/edx/devstack/jobs/452003610.  @OmarIthawi I am testing this now and will let you know how it goes.

**Review by macdiesel — APPROVED** [review]
Just tested this locally from @OmarIthawi 's Branch and I was able to load the demo course. I'm going to merge this.

**Comment by openedx-webhooks** [comment]
@OmarIthawi 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4869&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2018-11-07+17:13&entry.1917517419=2018-11-07+19:41&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by OmarIthawi** [comment]
@macdiesel thank you for the review! Can't we add the devstack CI as part of the configuration repo?

**Pull request merged**
