### PR TITLE
SOL-2037: Make sure ssh private keys are not leaked

### PR DESCRIPTION
**Pull request by saleem-latif**
## Configuration Pull Request

Hi @mattdrayer , @feanil , @jibsheet 
Kindly take a look at the changes, I have verified alton build passing. I will update the PR when I complete [ansible testing checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist). 
Who would be the best person to review HipChat plugin changes ?

Make sure that the following steps are done before merging
- [x] @devops team member has commented with :+1:
- [ ] are you adding any new default values that need to be overriden when this goes live?  
  - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
  - [ ] Add an entry to the CHANGELOG.

### CODE REVIEW

**Comment by jibsheet** [comment]
I think this is fine 👍  Asking @feanil to take a second look if he has time.
@saleem-latif do me a favor and hold on merging until Cambridge is back in the office next week?
Thanks.
Also not sure if we should block on the merge until we resolve the sandbox theming issues also in flight.

**Comment by feanil** [comment]
This seems fine to me.

**Comment by mattdrayer** [comment]
@saleem-latif I think we are clear to merge this PR now

**Comment by saleem-latif** [comment]
I have just completed [Ops ansible testing checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist), so going ahead with the merge.

**Pull request merged**
