### PR TITLE
Fix the team mention in the PR template

### PR DESCRIPTION
**Pull request by nedbat**
Configuration Pull Request
---

Make sure that the following steps are done before merging

  - [ ] @edx/devops team member has commented with :+1:
  - [ ] are you adding any new default values that need to be overridden when this goes live?  
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

### CODE REVIEW

**Comment by maxrothman** [comment]
I'm 👎 on this. This kills our ability to choose when to get notified for new PRs.

**Comment by nedbat** [comment]
My goal here is to be clear about how to get the attention of devops on pull requests.  The existing template is misleading: it looks like it pings you guys, but it does not.  This would ping you.  If you prefer, I can change the first bullet to:
```
[ ] A devops team member has approved the changes. Be sure to ping them to get their attention.
```
or some other suggestion :)

**Comment by maxrothman** [comment]
I would suggest:

[ ] A devops team member has approved the changes.

Then at the bottom:

You can ping the whole devops team using @ devops (no space).

**Comment by feanil** [comment]
@maxrothman updated.

**Comment by nedbat** [comment]
@maxrothman One of the reasons for this change was that `@devops` doesn't ping you, it pings the GitHub user named devops.

**Review by maxrothman — APPROVED** [review]

**Pull request merged**
