### PR TITLE
Add oscar_populate_countries to ecommerce playbook.

### PR DESCRIPTION
**Pull request by jimabramson**
XCOM-284

@feanil @clintonb @rlucioni 

see also: https://github.com/django-oscar/django-oscar/pull/1841/

### CODE REVIEW

**Comment by jimabramson** [comment]
also note that I had to use https://github.com/edx/configuration/pull/2227 to provision things correctly in order to test this command (on my sandbox).

**Comment by rlucioni** [comment]
:+1:

**Comment by clintonb** [comment]
:+1:

**Comment by feanil** [comment]
:+1:

**Pull request merged**
