### PR TITLE
Convert active gunicorn services to use configuration file

### PR DESCRIPTION
**Pull request by carsongee**
Per the mailing list discussion (https://groups.google.com/d/msg/openedx-ops/kHTfBuVr6ko/1XKWaFyh50gJ), here is the conversion of xqueue to using a conf file.  It ends up looking a bit cleaner.  Should I just submit a PR for each service I convert, or would you prefer I just do them all in one? @feanil

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @carsongee! I've created [OSPR-227](https://openedx.atlassian.net/browse/OSPR-227) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams. 

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ('this must be merged by XX date', and why that is)
- partner information ('this is a course on edx.org')
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the Github pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by carsongee** [comment]
I went ahead and wrote this for all the gunicorn services that are currently used (as far as I know).  I skipped discern, analytics, and analytics-server, but I could port those if wanted but I couldn't get analytics or analytics-server tested since they are still using `/opt/wwc`

**Comment by e0d** [comment]
Generally seems reasonable to me, needs a change log update.

**Comment by carsongee** [comment]
I've added a change log entry.

**Comment by feanil** [comment]
:+1:  after squash.

**Comment by carsongee** [comment]
Do you want me to squash all of them?  I did each role as a commit so it might be easier to revert if it say broke ora1, but if you want it all in one, I'm happy to oblige.

**Comment by feanil** [comment]
Ah, I see, merging as is sounds good then. :+1:

**Comment by carsongee** [comment]
Cool, thanks for the reviews guys

**Pull request merged**
