### PR TITLE
Feanil/change ppas

### PR DESCRIPTION
**Pull request by feanil**
@edx/devops 
I am the captain now

### CODE REVIEW

**Comment by FremanZhang** [comment]
Hi @feanil 
I built use python 2.7.11-0 and failed again. Please advise.

TASK: [common | add edx ppa apt key] ****************************************** 
<10.1.100.219> ESTABLISH CONNECTION FOR USER: root
<10.1.100.219> REMOTE_MODULE apt_key keyserver=http://pgp.mit.edu id=69464050 state=present
<10.1.100.219> EXEC ssh -C -tt -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 10.1.100.219 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1450315649.76-123561749557076 && echo $HOME/.ansible/tmp/ansible-tmp-1450315649.76-123561749557076'
<10.1.100.219> PUT /tmp/tmpiB5srL TO /home/ubuntu/.ansible/tmp/ansible-tmp-1450315649.76-123561749557076/apt_key
<10.1.100.219> EXEC ssh -C -tt -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 10.1.100.219 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=djaiwwnmxrpbvpjytfeuqyjdzjgvpggg] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-djaiwwnmxrpbvpjytfeuqyjdzjgvpggg; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1450315649.76-123561749557076/apt_key; rm -rf /home/ubuntu/.ansible/tmp/ansible-tmp-1450315649.76-123561749557076/ >/dev/null 2>&1'"'"''
failed: [10.1.100.219] => {"cmd": "apt-key adv --keyserver http://pgp.mit.edu --recv 69464050", "failed": true, "rc": 2}
stderr: gpg: requesting key 69464050 from http server pgp.mit.edu
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0

stdout: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.FH5VYWqvi8 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver http://pgp.mit.edu --recv 69464050
gpgkeys: no key data found for http://pgp.mit.edu/

msg: gpg: requesting key 69464050 from http server pgp.mit.edu
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0

**Comment by FremanZhang** [comment]
Hi @feanil
Sorry for the previous disturbing, it is work for me for PPA issue.
But after this I came across a new issue as below:

TASK: [supervisor | update supervisor configuration] *************************\* 
<10.1.100.219> ESTABLISH CONNECTION FOR USER: root
<10.1.100.219> REMOTE_MODULE command /edx/app/supervisor/venvs/supervisor/bin/supervisorctl -c /edx/app/supervisor/supervisord.conf update #USE_SHELL
<10.1.100.219> EXEC ssh -C -tt -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 10.1.100.219 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1450316463.26-33451110789448 && echo $HOME/.ansible/tmp/ansible-tmp-1450316463.26-33451110789448'
<10.1.100.219> PUT /tmp/tmpeMxHKW TO /home/ubuntu/.ansible/tmp/ansible-tmp-1450316463.26-33451110789448/command
<10.1.100.219> EXEC ssh -C -tt -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/root/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 10.1.100.219 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=pgcxdyjlhcqzgsjtleuagvvgehwspodv] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-pgcxdyjlhcqzgsjtleuagvvgehwspodv; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1450316463.26-33451110789448/command; rm -rf /home/ubuntu/.ansible/tmp/ansible-tmp-1450316463.26-33451110789448/ >/dev/null 2>&1'"'"''
failed: [10.1.100.219] => {"changed": true, "cmd": "/edx/app/supervisor/venvs/supervisor/bin/supervisorctl -c /edx/app/supervisor/supervisord.conf update", "delta": "0:00:00.073594", "end": "2015-12-17 01:41:05.407375", "rc": 2, "start": "2015-12-17 01:41:05.333781", "stdout_lines": ["error: <class 'socket.error'>, [Errno 2] No such file or directory: file: /usr/lib/python2.7/socket.py line: 228"], "warnings": []}
stdout: error: <class 'socket.error'>, [Errno 2] No such file or directory: file: /usr/lib/python2.7/socket.py line: 228

**Comment by feanil** [comment]
@fremanzhang are you seeing this with python 2.7.10 or python 2.7.11?  We know 2.7.11 will cause issues, the PPA provides python 2.7.10

**Comment by e0d** [comment]
:+1:

**Comment by FremanZhang** [comment]
@feanil in python 2.7.11
Refer to the following link I resolve it temporarily by kill supervisor process and restart it manually.
https://github.com/edx/configuration/issues/2065

**Comment by e0d** [comment]
@mtyaka @smarnach can we get a review from one of you?

**Comment by e0d** [comment]
@tusbar @stvstnfrd @devalih FYI

**Comment by nedbat** [comment]
FWIW, I'm building a base box with the branch now.  (It's going very slowly.. :( )

**Comment by e0d** [comment]
@nedbat the python installation specifically or the process in general?

**Comment by nedbat** [comment]
@e0d the process overall.  I'm on "TASK: browsers | download ChromeDriver".

**Comment by nedbat** [comment]
@e0d it finished successfully! base/devstack

**Comment by nedbat** [comment]
:+1:

**Comment by feanil** [comment]
I've verified that it hasn't broken running on top of existing sandboxes, and I'm testing a build from scratch with sandboxes now.  It has gotten well past the error on my build from scratch on sandboxes.  I'm going to merge this but if people have issues, I'll make follow-on updates.

**Comment by FremanZhang** [comment]
@feanil I back to use python2.7.10 and it works well for me.

Thanks a lot.

**Comment by mtyaka** [comment]
Thanks for doing this so quickly :+1:

**Comment by stvstnfrd** [comment]
Thanks for the ping @e0d

**Comment by tusbar** [comment]
:+1:

**Pull request merged**
