### PR TITLE
Adding force option for installing mongo

### PR DESCRIPTION
**Pull request by hkim823**

### CODE REVIEW

**Comment by hkim823** [comment]
Based on https://github.com/edx/configuration/issues/1381

**Comment by feanil** [comment]
So this is only needed if we want to force downgrades, is that something we want to do.  Seems like it is good to maintain the version we had in configuration but I just wanted to hear your thoughts on this as well.

**Comment by hkim823** [comment]
I think if someone were to type sudo apt-get upgrade -y on a server for whatever reason then run sudo /edx/bin/update edx-platfor master, this is needed or the script is going to bomb out.

**Comment by feanil** [comment]
:+1:

**Comment by carsongee** [comment]
I know it is a little late, but I think a better way would be to hold the package instead of forcing the downgrade, so adding a task that does `apt-mark hold mongodb-10gen` so update will work normally since going back and forth can be problematic for mongodb and is why we forced a version to start with.

**Comment by feanil** [comment]
I like that as well, @hkim823 thoughts?

**Pull request merged**
