### PR TITLE
Switch to mongo_4_0 role in openedx_native.yml

### PR DESCRIPTION
**Pull request by mtyaka**
**Description**

MongoDB 3.6 reached end of life on April 30, 2021 and is no longer receiving security updates. We want to use Mongo 4 by default for new Open edX installations.

This PR updates local MongoDB version installed by the `openedx_native.yml` playbook from 3.6 to 4.0.

Also see discussion at https://github.com/openedx/build-test-release-wg/issues/47.

**Testing instructions**

Run the `openedx_native.yml` playbook from this branch and verify that MongoDB 4 gets installed successfully and that the Open edX instance works correctly.

**Sandbox URL**

- LMS: https://mongo-4-master.opencraft.hosting/
- Studio: https://studio.mongo-4-master.opencraft.hosting/

**Reviewers**

- [ ] @shimulch 
- [ ] edX

---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mtyaka! I've created [OSPR-5792](https://openedx.atlassian.net/browse/OSPR-5792) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@mtyaka Thank you for your contribution. Please let me know once it is ready for our review.

**Review by shimulch — APPROVED** [review]
@mtyaka  LGTM :+1:

- [x] I tested this: checked on the OCIM instance, verified if Mongo v4 is running and services works as expected.
- [x] I read through the code
- [N/A] I checked for accessibility issues
- [N/A] Includes documentation
- [N/A] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.

**Comment by mtyaka** [comment]
@natabene This is now ready for review.

**Comment by mtyaka** [comment]
I opened a second PR to cherry-pick these changes into the open-release/lilac.master branch at https://github.com/edx/configuration/pull/6420. /cc @nedbat

**Comment by natabene** [comment]
@mtyaka Could you please provide a user centric/business feature description  for this PR?

**Comment by mtyaka** [comment]
@natabene I updated the description. Basically mongo 3.6 has reached end of life and is no longer receiving security updates. We want new Open edX installations to use mongo 4.0 instead of the outdated 3.6 version.

This update does not result in any changes visible to end users.

This is also being discussed on https://github.com/openedx/build-test-release-wg/issues/47.

**Comment by natabene** [comment]
@mtyaka thank you for more information. @adzuci FYI

**Review by pomegranited — APPROVED** [review]
:+1:

- [x] I tested this:
   Shelled into the sandbox instance provisioned with this change to check:
   * The modulestore/contentstore databases use localhost
   * The forum database uses localhost
   * The `db.version()` of the mongo database running on localhost is `4.0.22`
   
   Also ran some basic functionality tests on the sandbox Open edX service:
   * Logged into https://mongo-4-master.opencraft.hosting as `staff@example.com` / `edx`
   * Viewed Demo course content
   * Posted to the discussion forum
   * Added a new unit to the Demo course in Studio and Published it.
- [x] I read through the code
- [x] <strike>I checked for accessibility issues</strike> N/A
- [x] <strike>Includes documentation</strike> N/A

**Comment by pomegranited** [comment]
Hi @adzuci @christopappas,

This change tested out fine and is non-controversial, so I'll merge it before the end of the day on Monday if there's no objections from you all.

CC @natabene

**Comment by natabene** [comment]
@pomegranited We are off on Monday, so maybe Tuesday is better? Just in case.

**Review by syed-awais-ali — APPROVED** [review]
I have checked this on a sandbox, and after sandbox was made I verified that the mongo was running on version 4 and tested some of the related functionality to see things are working fine.
LGTM

**Comment by pomegranited** [comment]
Thank you @syed-awais-ali ! I'll merge this now. CC @natabene

**Comment by openedx-webhooks** [comment]
@mtyaka 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6416&entry.1484655318=https://github.com/mtyaka&entry.752974735=2021-05-20+05:57&entry.1917517419=2021-06-02+03:08&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
