### PR TITLE
Update common_pip_pkgs versions

### PR DESCRIPTION
**Pull request by singingwolfboy**
Related to https://github.com/edx/edx-platform/pull/7465 @feanil

### CODE REVIEW

**Comment by feanil** [comment]
Cool, we'll have to run through the tests defined here for this to make sure we don't break anything with this change: https://openedx.atlassian.net/wiki/display/EdxOps/Ansible+testing+checklist

You should be able to do most of them, let me know if you have any questions.

**Comment by maxrothman** [comment]
@singingwolfboy is this PR still relevant?

**Comment by singingwolfboy** [comment]
@maxrothman. Absolutely. We should be running Ansible with updated versions of pip, setuptools, etc. Fortunately, this PR is not tied to https://github.com/edx/edx-platform/pull/8934 -- they can be considered and merged separately, and neither should affect the other.

**Comment by singingwolfboy** [comment]
@edx/devops just a reminder that this PR is still here

**Comment by feanil** [comment]
@singingwolfboy the testing checklist has been much improved, please go through it if this is important: https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Testing+Checklist

**Comment by singingwolfboy** [comment]
@feanil: thanks for the pointer -- I took a look at the checklist previously, and didn't know how to follow the steps. Now it's much more accessible, and I've successfully gone through the entire checklist. (I discovered that I had to remove the `--use-mirrors` argument to `pip`, so it was definitely a useful test!)

What's the next step, here? If I've gone through the checklist successfully, is this ready to merge, or is there further review work to be done?

**Comment by feanil** [comment]
If you've gone through the checklist then we're good.  :+1:

**Pull request merged**
