### PR TITLE
Configuration Pull Request ---

### PR DESCRIPTION
**Pull request by bderusha**
Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Review by coryleeio — APPROVED** [review]

**Comment by nedbat** [comment]
@bderusha with these changes cherry-picked onto master, I still get a failure when running the Native installation:
```
TASK [edx_service : Create edx_service log dir] ********************************
changed: [localhost] => (item=/edx/var/log/ecommerce) => {"changed": true, "gid": 108, "group": "syslog", "item": "/edx/var/log/ecommerce", "mode": "0755", "ow
ner": "syslog", "path": "/edx/var/log/ecommerce", "size": 4096, "state": "directory", "uid": 104}

TASK [edx_service : Write out app config file] *********************************
fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
        to retry, use: --limit @/var/tmp/configuration/playbooks/openedx_native.retry

PLAY RECAP *********************************************************************
localhost                  : ok=304  changed=185  unreachable=0    failed=1
```

**Comment by bderusha** [comment]
Thanks @nedbat I am looking at it

**Comment by bderusha** [comment]
@nedbat can you provide more details as to how to ran the command that resulted in those errors?  I want to make sure that I can recreate appropriately

**Comment by nedbat** [comment]
@bderusha I use these instructions to test the installation: https://openedx.atlassian.net/wiki/spaces/OpenOPS/pages/146440579/Native+Open+edX+platform+Ubuntu+16.04+64+bit+Installation  In this case, I used the nedbat/test/j.a3 branch, which already has your first commits cherry-picked onto it.

**Comment by nedbat** [comment]
BTW, I have the complete Ansible log from the failed installation, if that would help.

**Comment by nedbat** [comment]
@bderusha Should I try the installation again?

**Comment by lgp171188** [comment]
@bderusha, as a part of [this Trello card](https://trello.com/c/hfREYuf2/39-test-pr-reverting-breaking-changes-to-the-configuration-repo), I am currently testing the changes in this PR and hope to finish testing and report issues, if any in a couple of days of time.

Based on my testing done till now in a setup without discovery and ecommerce (which is likely affected by the bug that @nedbat has reported) and just LMS + Studio, I can confirm, that there weren't any issues during the provisioning or on the instance.

**Comment by bderusha** [comment]
> @bderusha, as a part of [this Trello card](https://trello.com/c/hfREYuf2/39-test-pr-reverting-breaking-changes-to-the-configuration-repo), I am currently testing the changes in this PR and hope to finish testing and report issues, if any in a couple of days of time.
> 
> Based on my testing done till now in a setup without discovery and ecommerce (which is likely affected by the bug that @nedbat has reported) and just LMS + Studio, I can confirm, that there weren't any issues during the provisioning or on the instance.

Excellent!  Let me know if you run into any issues.  I've been trying to test, but it's a workflow I am personally unfamiliar with so I've been hitting issues unrelated to this code.

**Comment by bderusha** [comment]
@nedbat @lgp171188 I am going to go ahead and merge this and we can fix forward if there are still issues deploying. This will at least unblock folks for a good chunk of apps

**Pull request merged**
