### PR TITLE
sandboxes now run mongo4 and no longer run mongo 3.6

### PR DESCRIPTION
**Pull request by syedimranhassan**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Review by syed-awais-ali — APPROVED** [review]

**Comment by amitvadhel** [comment]
@nedbat Can we cherry pick MySQL commits from master to koa.master? 

Recently I tried to install native Koa in Ubuntu 20.04 and it's failing due to `5.7.32-1ubuntu18.04 was replaced by 5.7.33-1ubuntu18.04`. Not sure about MongoDB.

What do you think guys? @syed-awais-ali, @syedimranhassan 

Discuss thread: https://discuss.openedx.org/t/failed-to-install-koa-in-aws-ubuntu-20-04-mysql-client-error/4132

**Comment by eugenechabanov** [comment]
Same error here. Couldn't install Koa Native on local machine. 
TASK[mysql :  install mysql-5.7-client] FAILED
Changed my Ansible files according to these three commits and installation succeeded.

**Comment by vmathurpaytm** [comment]
These commits will be pushed to "koa.master"  (currently merged to master) as well ?? as installation is giving error for koa.master

**Comment by nedbat** [comment]
Hi sorry I missed getting this onto Koa.

We'll have to work on our build/test/release processes.
For the future, the pull request description should include more detail, and the title should have mentioned MySQL.

**Comment by nedbat** [comment]
I have cherry-picked the two MySQL commits onto Koa.

**Comment by vmathurpaytm** [comment]
@nedbat  Thank you for checking this
I think there was one more change in this issue,  Can you include this as well in koa ??  
Change :     mongo_3_6  ->  mongo_4_0

Reference : https://github.com/edx/configuration/pull/6248/commits/a5cc58939e5ab2d11be90336369f20d5b730a428

**Comment by nedbat** [comment]
@vmathurpaytm That seems like a much larger change, the kind we would not do after creating the release-master branch.  Is there a problem with Mongo 3.6?

**Comment by vmathurpaytm** [comment]
@nedbat  I did not got any specific error with mongo, but i saw this changes were part of same issue , so i was curious if same will be included in koa

**Comment by nedbat** [comment]
To be honest, I don't know the specifics of the mongo changes. @syedimranhassan: this is a reason to provide more detail in pull request descriptions :) 

We're updating the MySQL version, but only to a new micro version, and even then, only because the older version no longer installs.  Changes on release branches like Koa are made very very conservatively.

**Pull request merged**
