### PR TITLE
update symlink to mongo_3_2

### PR DESCRIPTION
**Pull request by icarrr**
MongoDB 2.6 reached End of Life (EOL)

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @icarrr! I've created [OSPR-3854](https://openedx.atlassian.net/browse/OSPR-3854) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@icarrr Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions. Thanks

**Comment by icarrr** [comment]
@natabene Okay, the document has been sent to email legal@edx.org. Thanks

**Comment by natabene** [comment]
@icarrr Thank you for joining the Open edX community! We have added your user to our records and can now review your code going forward.

**Comment by natabene** [comment]
@edx/devops This is ready for you to review.

**Comment by nedbat** [comment]
@icarrr I didn't realize you'd made two similar pull requests for different branches.  It will help our review if you can point out helpful tips like that.

**Comment by icarrr** [comment]
@nedbat This is a request to solve the problem that will install Open edX ginkgo version in the mongoDB section. I tried and it worked.
[discus](https://discuss.openedx.org/t/ginkgo-install-ansible-failed/696)

**Comment by nedbat** [comment]
I'm sorry, but we cannot do maintenance on unsupported versions.  We need as a community to come up with a better way to keep old releases working.  I started a thread here to discuss possibilities: https://discuss.openedx.org/t/how-to-keep-old-releases-installable/341

**Comment by openedx-webhooks** [comment]
@icarrr Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/5419&entry.1484655318=https://github.com/icarrr&entry.752974735=2019-09-25+06:26&entry.1917517419=2019-10-24+15:07&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
