### PR TITLE
Builds are failling because ffi.h is not installed

### PR DESCRIPTION
**Pull request by jibsheet**
We're not yet sure what changed, but something between Friday morning's
patchset release and this afternoon's rc cut.

@ormsbee
@edx/devops

### CODE REVIEW

**Comment by maxrothman** [comment]
👍

**Comment by feanil** [comment]
This should go in this file: https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp_common/defaults/main.yml  so that jenkins workers can also pick it up.  @benpatterson  how did tests pass without the jenkins workers having this requirement?

**Comment by jibsheet** [comment]
@feanil jenkins_workers/defaults/main.yml declares libffi-dev
Oh, I wonder when that was added....

**Comment by feanil** [comment]
yea, whoever did that, did it wrong...

**Comment by jibsheet** [comment]
@feanil so, long story short, it's for a new set of accessibility tests, so it was added to workers and devstacks, but not platform.  However, obviously we need it to build the platform.  We're going to rejigger this to be in edxapp_common and then devstack/jenkins_worker and edxapp will be covered.

just talked to @clytwynec

**Comment by benpatterson** [comment]
What needs libffi on platform?

We put it into jenkins_worker and devstack because it was used for validation only. AFAIK it was not needed for running the edxapp itself. That's why we took that approach FWIW.

**Comment by clytwynec** [comment]
Yea, sorry for this!  The thinking was that the dependency was actually only needed for testing, so I was avoiding adding a new dependency to production that wasn't needed.

**Comment by jibsheet** [comment]
@benpatterson platform now installs scrapy, which needs libffi-dev and there's no difference between what's installed for testing and what is installed during platform builds.  This was causing the platform to fail to build.

**Comment by benpatterson** [comment]
ahhh and perhaps this is chalked up to: the need to separate test requirements from prod?

**Comment by benpatterson** [comment]
I'm sorry I didn't think of that either :(

**Comment by jibsheet** [comment]
@benpatterson I feel like that's a long conversation, but yes.

@ormsbee Here's the root cause of the build failures.  It's clear I need to move some deps around to correct final destination on Monday.

**Comment by jibsheet** [comment]
@benpatterson @clytwynec Feanil pointed out requirements/edx/development.txt exists and is not installed everywhere.  It may be time for testing.txt that only gets pulled in on devstacks and jenkins workers.  I'll be making a new PR for now to collect the 3 libffi-dev requirements into the one common place for them.

**Comment by benpatterson** [comment]
Ok @jibsheet . Yeah we have put in cycles to figure out what could be pulled out of base.txt and put into a new file, and it always ends up having a scope balloon. Getting started with a known quantity and at least putting that into a separate file sounds great to me. We'll want to be sure that we run development.txt as part of builds though, before we merge the change in ansible, or else we'll have the opposite problem (i.e., not in production, and not in builds, either).

**Comment by jibsheet** [comment]
Yeah @benpatterson - we'll need edx-local or other similar scaffolding for devstack and jenkins workers.  I think development.txt is explicitly not installed, it's only if you want extreme development techniques provided by John Eskew.

I think a specific testing.txt that starts with known quantities that we can add to over time is the medium term goal.

**Pull request merged**
