### PR TITLE
Update name.

### PR DESCRIPTION
**Pull request by feanil**
@edx/devops

### CODE REVIEW

**Comment by maxrothman** [comment]
:+1:

**Comment by maxrothman** [comment]
Might be worth it to go re-prefix all the variables in the role.

**Comment by feanil** [comment]
Already done.  This is a straggler.

**Comment by maxrothman** [comment]
@feanil all of the variables [here](https://github.com/edx/configuration/blob/master/playbooks/roles/ecomworker/defaults/main.yml) still have the old name prefix.

**Pull request merged**
