### PR TITLE
Remove rendering of obsolete json files

### PR DESCRIPTION
**Pull request by jdmulloy**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Review by adzuci — APPROVED** [review]
There were some notes in OPS-3772 about a ticket being created that may have involved cleaning this up, but I think it can be removed.  If it turns out it was in use elsewhere we can likely fix forward.

**Comment by adzuci** [comment]
@jdmulloy, I un-reviewed since I see @coryleeio found https://github.com/edx/configuration/pull/5414#issuecomment-588398918 which has more context that I don't entirely understand.  Could be worth asking someone from @bradenmacdonald's team to take a look.

**Comment by jdmulloy** [comment]
@coryleeio @adzuci @bradenmacdonald 

I changed it so that it can be turned back on with a flag in case anyone needs it. Is this ok? Edxapp shouldn't even be reading these files any more, but it could be used if for some reason someone is using master of configuration with an older relase or edxapp.

**Review by adzuci — APPROVED** [review]
I like the flag idea.  Ship it.

**Review by coryleeio — APPROVED** [review]

**Comment by bradenmacdonald** [comment]
@adzuci @jdmulloy Thanks for the ping. From looking at https://github.com/edx/configuration/blob/b36e34c0d9a4156c990b12167c668efcbb251353/playbooks/roles/edxapp/tasks/service_variant_config.yml#L20-L48 it seems that this code is still rendering the .yml files, but not the old .json files right? If so it should be totally fine with us, flag or not. As mentioned, edxapp doesn't even read the JSON.

Having the configuration end up only in a `.yml` file is fine with us, we just didn't want to remove from edx/configuration the code that creates the application [yml or json] config file(s) from ansible vars.

**Pull request merged**
