### PR TITLE
Include ORGANIZATIONS_API_URL_ROOT in programs defaults

### PR DESCRIPTION
**Pull request by rlucioni**
This setting is used when requesting data from the LMS Organizations API. This shouldn't require any additional overrides if PROGRAMS_LMS_URL_ROOT is already overridden.

@maxrothman you appear to be on-call this week. Would you mind taking a quick look at this?

### CODE REVIEW

**Comment by fredsmith** [comment]
@rlucioni  - since this variable is part of a hash, typically we would reference a globally scoped variable in the hash (eg. PROGRAMS_ORGANIZATIONS_API_URL_ROOT) and then set the default in the global variable.  Ansible's hash merging is problematic, and there is otherwise no other way to override a single component of a default hash.

**Comment by rlucioni** [comment]
@fredsmith does that mean that if we were to merge this as-is, we'd have no way to override ORGANIZATIONS_API_URL_ROOT?

**Comment by fredsmith** [comment]
That's correct.

**Comment by fredsmith** [comment]
:+1:

**Comment by rlucioni** [comment]
@fredsmith understood, thanks for the explanation. I've updated this PR to use globally-scoped variables in the hash.

**Pull request merged**
