### PR TITLE
Upgrade to pip 6.1.0.

### PR DESCRIPTION
**Pull request by alawibaba**
…version mismatch.

### CODE REVIEW

**Comment by alawibaba** [comment]
@maxrothman PTAL

**Comment by alawibaba** [comment]
@feanil and @maxrothman had comments they gave me in person: I need to check to make sure that the 1.5.6 version of pip is not used in other places and to go through the devops testing procedures for this repo, which are described in the wiki.

**Comment by alawibaba** [comment]
Completed the test procedure, PTAL!

**Comment by maxrothman** [comment]
:+1:

**Comment by feanil** [comment]
:+1:

**Comment by feanil** [comment]
:sheep: :it:

**Pull request merged**
