### PR TITLE
Updated Vagrantfile

### PR DESCRIPTION
**Pull request by valera-rozuvan**
**Description**

Make the configuration versions of the Vagrantfile more explicit. Require specific versions of Vagrant. [The docs state that Vagrant should be >= 1.3.4](https://github.com/edx/configuration/wiki/edX-Developer-Stack).

**Reviewers**
- @jarv

### CODE REVIEW

**Comment by jarv** [comment]
looks good, can you make the change in all of them? 

```
./base/devstack/Vagrantfile
./base/fullstack/Vagrantfile
./release/devstack/Vagrantfile
./release/fullstack/Vagrantfile
```

**Comment by valera-rozuvan** [comment]
@jarv Done.

**Comment by valera-rozuvan** [comment]
@jarv Am I good to merge?

**Comment by hkim823** [comment]
I'm getting an issue testing this, I get this error, still testing right now 

https://gist.github.com/hkim823/9218941

**Comment by hkim823** [comment]
Tested this AM looking good, :+1:

**Pull request merged**
