### PR TITLE
Adds INSIGHTS_LEARNER_API_LIST_DOWNLOAD_FIELDS

### PR DESCRIPTION
**Pull request by pomegranited**
This variable is used by the Learner List view's "Download CSV" button to determine the fields to include in the downloaded report, and their sort order.

The default value shows all fields, in the order they're defined in the Learner Roster Record.

**Discussions**: Part of the Learner Profile reports to be downloadable from Insights.  Architecture discussed extensively with @mulby and the analytics team.

**Dependencies**: Used by [edx-analytics-dashboard PR #533](https://github.com/edx/edx-analytics-dashboard/pull/533)

**Partner information**: 3rd party-hosted open edX instance
1. See [edx-analytics-dashboard PR #533](https://github.com/edx/edx-analytics-dashboard/pull/533) for testing setup instructions.
2. Checkout this PR branch on your vagrant instance under `/edx/app/edx_ansible`
3. Create an extra-vars.yml file containing some overrides for the variables in this PR, and any others you want to preserve, e.g.
   
   ``` yaml
   INSIGHTS_LEARNER_API_LIST_DOWNLOAD_FIELDS: username,name,email,cohort,language,year_of_birth,gender,level_of_education,mailing_address,goals,city,country,first_enrollment_date,last_updated
   
   INSIGHTS_DATA_API_AUTH_TOKEN: token
   ```
4. Re-run the updated `insights` role:
   
   ```
   ssh vagrant
   source /edx/app/edx_ansible/venvs/edx_ansible/bin/activate
   cd /edx/app/edx_ansible/edx_ansible/playbooks
   ansible-playbook -i localhost, -c local run_role.yml -e role=insights --extra-vars=@/path/to/extra-vars.yml
   ```
5. Note changes written to `/edx/etc/insights.yml`.
6. Confirm changes by restarting Insights, and checking the downloaded the Learner List CSV.

**Author Notes & Concerns:**
1. The example field list uses the full list of fields available once [edx-analytics-data-api#129](https://github.com/edx/edx-analytics-data-api/pull/129) is merged.  Until then, only these fields will be returned: `username,name,email,cohort,first_enrollment_date,last_updated`.  However, it will not cause an error.

**Reviewers**
- [x] @bradenmacdonald 
- [x] @feanil 
- [x] @fredsmith

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pomegranited! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?number=3305&repo=edx%2Fconfiguration

**Comment by bradenmacdonald** [comment]
@pomegranited 
1. Why does this need to be configurable at all?
2. The default null value means "include all fields", right? If so, it would be nice to explain that in a comment.

**Comment by pomegranited** [comment]
@bradenmacdonald 
1. The client had a specific list of fields they wanted in their report, and I thought this might be a common use case.  People can be fussy about their reports :)
2. Done!

**Comment by pomegranited** [comment]
Rebased [76b49a6](https://github.com/open-craft/configuration/commit/76b49a6a61a496eea532ef807e8e36e4653bc9e1) from [master](https://github.com/edx/configuration/commit/af01848b91a0b228a33da667f284c3dfacd66aba) and squashed commits into [168d245](https://github.com/open-craft/configuration/commit/168d245e0c4b05fd4119af6852a92fcd384fa3aa).

**Comment by bradenmacdonald** [comment]
:+1:

Though it might also be nice to have a comment showing an example value of `INSIGHTS_LEARNER_API_LIST_DOWNLOAD_FIELDS`. For example, it's not necessarily obvious that it should be a comma-separated string and not a YAML list.
- [x] I tested this: Followed testing instructions
- [x] I read through the code
- [x] Includes documentation: has a comment to explain the default; other issue mentioned above.

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pomegranited! I've created [OSPR-1405](https://openedx.atlassian.net/browse/OSPR-1405) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by pomegranited** [comment]
Hi @feanil, sorry to bother you directly about this issue, but it seems to be stuck in "awaiting prioritization".  Is there anything I can do to move it along?  Thanks!

**Comment by feanil** [comment]
:+1:   @fredsmith second look.

**Comment by fredsmith** [comment]
LGTM 👍

**Comment by feanil** [comment]
@pomegranited feel free to merge.  I see that the analytics-dashboard PR is still open, but assuming the name of the var is not going to change. I think this is good to go.

**Comment by pomegranited** [comment]
Thank you @feanil , @fredsmith !

**Pull request merged**
