### PR TITLE
credentials: correct AWS_S3_CUSTOM_DOMAIN setting

### PR DESCRIPTION
**Pull request by jimabramson**
@maxrothman @zubair-arbi @rlucioni @clintonb FYI.

### CODE REVIEW

**Comment by clintonb** [comment]
:+1:

**Comment by zubair-arbi** [comment]
Great find. @jimabramson I now recall your warnings about custom domain.

> we did see this before with profile images, but it went away when we switched to custom domain
> 
> @max lessons learned from last time about aws custom domain https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml#L487-L500

:+1:

**Comment by maxrothman** [comment]
:+1: :shipit:

**Comment by rlucioni** [comment]
Nice. :+1:

**Pull request merged**
