### PR TITLE
Add port support for kibana configuration

### PR DESCRIPTION
**Pull request by carsongee**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @carsongee! I've created [OSPR-131](https://openedx.atlassian.net/browse/OSPR-131) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams. Supporting information that is good to add there is anything that can help Product understand the context for the PR - supporting documentation, edx-code email threads, timeline information ('this must be merged by XX date', and why that is), partner information (this is for a course on edx.org, for example), etc. 

All technical communication about the code itself will still be done via the Github pull request interface. As a reminder, [our process documentation is here](http://edx.readthedocs.org/projects/userdocs/en/latest/process/overview.html).

**Comment by e0d** [comment]
:+1: 

Already defined in defaults.

**Comment by carsongee** [comment]
Forgot to switch the port for when SSL is enabled.

**Comment by e0d** [comment]
Impatiently awaiting my reading glasses, :+1:

**Comment by carsongee** [comment]
lol, thanks for the quick review.

**Pull request merged**
