### PR TITLE
Presupervisor check is failing because the service name for workers is X-worker, but the user is just X. Setting it to the play name instead.

### PR DESCRIPTION
**Pull request by coryleeio**

### CODE REVIEW

**Comment by jdmulloy** [comment]
@coryleeio which app(s) is this failing for?

**Comment by coryleeio** [comment]
@jdmulloy you can see the failure on stage registrar

**Comment by coryleeio** [comment]
if you check the status of supervisor it is failing bc of the presupervisor check

**Comment by coryleeio** [comment]
it is failing bc there is no registrar_worker user

**Comment by coryleeio** [comment]
app code owner is named 'registrar'

**Review by jdmulloy — APPROVED** [review]

**Pull request merged**
