### PR TITLE
SE-333 Allow arbitrary cron jobs to be added via configuration

### PR DESCRIPTION
**Pull request by pomegranited**
Adds `EDXAPP_ADDITIONAL_CRON_JOBS`, which provides a fully configurable list of cron jobs to be added.

Default is an empty list, so no additional cron jobs are added.

**JIRA tickets**: SE-126, [OSPR-3007](https://openedx.atlassian.net/browse/OSPR-3007)

**Discussions**: See https://github.com/edx/edx-platform/pull/19047

**Sandbox URL**:  Sandbox being provisioned.

* LMS: https://pr19047.sandbox.opencraft.hosting/
* Studio: https://studio-pr19047.sandbox.opencraft.hosting/

Running [edx-platform/master](https://github.com/edx/edx-platform/commit/33fab4b1e4a5f7d3b388bc8105c6b60abd1d93e0), configured using this branch and the extra configuration below.  Has 2 active VMs (`vm1.pr19047.sandbox.opencraft.hosting`, and `vm2.pr19047.sandbox.opencraft.hosting`)

**Merge deadline**: Would like to get this merged before Ironwood if possible.

**Testing instructions**:

1. On the sandbox, register and activate an account.
1. Enrol in the [Weekly Course Updates test course](https://pr19047.sandbox.opencraft.hosting/courses/course-v1:OpenCraft+Highlights+2018_1/about)
1. With the current configuration, you'll get a scheduled course update in your inbox in a week.

To trigger the email earlier:
1. Login to the sandbox as the `staff` user (it's been elevated to superuser).
1. Visit the [Django Admin Schedules › Schedules ](https://pr19047.sandbox.opencraft.hosting/admin/schedules/schedule) and locate the schedule created for your newly-registered user above.
   Adjust the Start date to backdate it by 1 week.  You should get a single email for Week 1 in your inbox within 24 hours.

**Reviewers**
- [x] @clemente 
- [ ] edX DevOps reviewer[s] TBD

**Settings**
```yaml
EDXAPP_ADDITIONAL_CRON_JOBS:
- name: "Send weekly course highlight emails"
  user: "{{ edxapp_user }}"
  job: "VM1=$(dig vm1.{{ COMMON_DEPLOYMENT }} +short -4); /sbin/ifconfig | grep \"inet addr:${VM1} \" && . {{ edxapp_app_dir }}/edxapp_env && {{ edxapp_venv_bin }}/python {{ edxapp_code_dir }}/manage.py lms send_course_update --settings={{ edxapp_settings }} {{ EDXAPP_SITE_NAME }} >/dev/null 2>&1"
  hour: "0"
  minute: "0"
  day: "*"

configuration_repo_url: https://github.com/open-craft/configuration
configuration_version: jill/addl-crons

## Use default django mailer for scheduled course highlight messages
EDXAPP_ACE_CHANNEL_DEFAULT_EMAIL: "django_email"
EDXAPP_ACE_CHANNEL_SAILTHRU_DEBUG: false
EDXAPP_ACE_CHANNEL_SAILTHRU_TEMPLATE_NAME: "template"
EDXAPP_ACE_CHANNEL_TRANSACTIONAL_EMAIL: "django_email"
EDXAPP_ACE_ENABLED_CHANNELS: ["django_email"]
EDXAPP_ACE_ENABLED_POLICIES: ["bulk_email_optout"]
EDXAPP_DEFAULT_FROM_EMAIL: “jill+highlights@opencraft.com” 
```

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [x] Are you adding any new default values that need to be overridden when this change goes live? No
    - [ ] <strike>Update the appropriate internal repo (be sure to update for all our environments)</strike>
    - [ ] <strike>If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.</strike>
    - [ ] <strike>Add an entry to the CHANGELOG.</strike>
  - [x] Are making a complicated change?  No

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pomegranited! I've created [OSPR-3007](https://openedx.atlassian.net/browse/OSPR-3007) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@pomegranited  Thank you for your contribution. @edx/devops  Can you  have a look?

**Comment by nedbat** [comment]
The ironwood branches have been created, but this seems simple enough if it gets to master.

**Comment by natabene** [comment]
@feanil Do you think we can get it in? See @nedbat comment above.

**Comment by clemente** [comment]
:+1:

  - [X] I tested this: checked that the cronjobs are installed
  - [X] I read through the code: name is ok, it includes default, the default doesn't have side effects, the same cron syntax from ansible is used
  - [] I checked for accessibility issues
  - [X] Includes documentation

The other test instructions in this PR are for a particular case we're testing about weekly course highlights. But the code in this PR is fine and be merged when approved.

**Comment by pomegranited** [comment]
Thanks @natabene  and @nedbat !  This is ready for devops review, and it would be great if we could get it into Ironwood.

**Comment by natabene** [comment]
@pomegranited Thanks for letting me know. @edx/devops  Can you give this a look? We want to get it into Ironwood.

**Review by feanil — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@pomegranited 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4963&entry.1484655318=https://github.com/pomegranited&entry.752974735=2019-01-22+06:40&entry.1917517419=2019-02-04+19:10&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by natabene** [comment]
@nedbat Can we take this into Ironwood?

**Comment by pomegranited** [comment]
Thank you so much, @feanil @natabene @nedbat !

**Comment by nedbat** [comment]
This has been cherry-picked onto open-release/ironwood.master.

**Pull request merged**
