### PR TITLE
Pinning XQUEUE_VERSION

### PR DESCRIPTION
**Pull request by juniorojha**
In commit https://github.com/edx/xqueue/commit/352d102a7e3badcb987e59b76d704eb41228d543 xqueue has removed gunicorn so this isn't compatible anymore with open-release/ironwood.master branch. Therefore, we need to pin the XQUEUE_VERSION in this to prevent installation issues.

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [x] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @juniorojha! I've created [OSPR-4051](https://openedx.atlassian.net/browse/OSPR-4051) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://open.edx.org/wp-content/uploads/2019/01/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@juniorojha Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions. Thanks

**Comment by nedbat** [comment]
@juniorojha Help me understand where this falls apart.  In native.sh, we set "xqueue_version", is that not serving to set the version of xqueue that gets installed?

**Comment by juniorojha** [comment]
Hi @nedbat, even though we have xqueue_version in native.sh which is overridable in config.yml and the comment https://github.com/edx/configuration/blob/e16ed3ddc378b95ef693f5b668fcef52bcb6af85/util/install/native.sh#L111 says it is also overridable via OPENEDX_RELEASE, the script still ends up cloning the xqueue repository's master branch.

**Comment by nedbat** [comment]
Can you try fixing native.sh instead? That fix could be on master, and would work for all future releases also.

**Comment by juniorojha** [comment]
Okay, thanks for the suggestion. I will attempt that and get back on this.

**Comment by regisb** [comment]
Can I suggest replacing all instances of `XQUEUE_VERSION` by `xqueue_version`? I didn't test this, but it seems to me that the bug comes from the fact that the `XQUEUE_REPOS` should include the version given by `xqueue_version`, and not `XQUEUE_VERSION`.

**Comment by juniorojha** [comment]
Hi @regisb, you're right. Ultimately, the branch to be checked out after cloning is defined here https://github.com/edx/configuration/blob/fe1fa0e2a6182bac346249646e9cfbf46f070952/playbooks/roles/xqueue/defaults/main.yml#L131 
Ansible variables must be case-sensitive.

**Comment by juniorojha** [comment]
It would actually make sense to replace xqueue_version and other lowercase variables collected in https://github.com/edx/configuration/blob/fe1fa0e2a6182bac346249646e9cfbf46f070952/util/install/native.sh#L111 to their uppercase versions. Inside the playbooks, I can hardly see any lowercase variables expected to be overridden.

**Comment by regisb** [comment]
@juniorojha are you able to make the fix and test it?

**Comment by juniorojha** [comment]
I am going to test it in today. Will update on this thread soon, thanks a lot for your very helpful inputs!

**Comment by nedbat** [comment]
@juniorojha I'm not sure all the variables should be upper-cased.  Looking at the repos cloned on an Ironwood installation, only xqueue looks wrong:
```
$ /edx/bin/show-repo-heads
With status...
---- /edx/app/analytics_api/analytics_api ----
 2019-12-19 14:48:02 -0500 (074dc17) Ned Batchelder: Upgrade Django to 1.11.27  (grafted, HEAD -> open-release/ironwood.master, origin/open-release/ironwood.master)
---- /edx/app/demo/edx-demo-course ----
 2019-06-05 14:49:06 -0400 (1dcf2d8) Ned Batchelder: Remove trademarks  (HEAD -> open-release/ironwood.master, tag: open-release/ironwood.2, origin/open-release/ironwood.master)
---- /edx/app/discovery/discovery ----
 2019-12-19 14:48:01 -0500 (242f05e) Ned Batchelder: Upgrade Django to 1.11.27  (grafted, HEAD -> open-release/ironwood.master, origin/open-release/ironwood.master)
---- /edx/app/ecommerce/ecommerce ----
 2019-12-19 14:48:00 -0500 (6d9d756) Ned Batchelder: Upgrade Django to 1.11.27  (grafted, HEAD -> open-release/ironwood.master, origin/open-release/ironwood.master)
---- /edx/app/ecomworker/ecomworker ----
 2019-01-10 15:06:20 +0500 (33ee006) Uzair Rasheed: Update newrelic-agent for distributed tracing  (grafted, HEAD -> open-release/ironwood.master, tag: open-release/ironwood.2, tag: o pen-release/ironwood.1rc4, tag: open-release/ironwood.1rc3, tag: open-release/ironwood.1rc2, tag: open-release/ironwood.1rc1, tag: open-release/ironwood.1, tag: 0.7.2, origin/open-re lease/ironwood.master)
---- /edx/app/edx_ansible/edx_ansible ----
 2020-01-23 14:00:55 -0500 (9bfdea2) Ned Batchelder: Just like #5617  (HEAD -> nedbat/test-5617, origin/nedbat/test-5617)
---- /edx/app/edxapp/edx-platform ----
 2019-12-19 14:48:01 -0500 (9490d8e) Ned Batchelder: Upgrade Django to 1.11.27  (HEAD -> open-release/ironwood.master, origin/open-release/ironwood.master)
---- /edx/app/forum/cs_comments_service ----
 2019-05-21 13:19:19 -0400 (df507c6) Alan Zarembok: Upgrade unicorn version to include GC issue fix.  (HEAD -> open-release/ironwood.master, tag: open-release/ironwood.2, origin/open- release/ironwood.master)
---- /edx/app/insights/edx_analytics_dashboard ----
 2019-12-19 14:48:02 -0500 (6992d5c) Ned Batchelder: Upgrade Django to 1.11.27  (grafted, HEAD -> open-release/ironwood.master, origin/open-release/ironwood.master)
---- /edx/app/notifier/src ----
 2019-01-08 14:14:13 -0500 (17a308f) GitHub: Merge pull request #70 from edx/mikix/drop-datadog  (HEAD -> open-release/ironwood.master, tag: open-release/ironwood.2, tag: open-release /ironwood.1rc4, tag: open-release/ironwood.1rc3, tag: open-release/ironwood.1rc2, tag: open-release/ironwood.1rc1, tag: open-release/ironwood.1, origin/open-release/ironwood.master)
?? notifier/settings_local.py
---- /edx/app/xqueue/xqueue ----
 2020-01-21 12:34:41 +0500 (45c2e69) GitHub: Merge pull request #670 from edx/jenkins/upgrade-python-requirements-826f610  (grafted, HEAD -> master, origin/master, origin/HEAD)
```

**Comment by juniorojha** [comment]
> @juniorojha Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions. Thanks

Hi @natabene ma'am, where or in what form shall I send in the mentioned signed agreement?

**Comment by juniorojha** [comment]
Hi @nedbat, thanks for the clarification. This goes in accordance with what @regisb had suggested earlier. The better choice seems to be to go for changing the XQUEUE_VERSION to xqueue_version. I've made this change to the current patch.

**Comment by nedbat** [comment]
Thanks.  I've made a more extensive correction in https://github.com/edx/configuration/pull/5618.

**Comment by openedx-webhooks** [comment]
@juniorojha Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/5615&entry.1484655318=https://github.com/juniorojha&entry.752974735=2020-01-21+11:49&entry.1917517419=2020-01-24+15:29&entry.2133058324=No) so we can improve your experience in the future.

**Comment by juniorojha** [comment]
> Thanks. I've made a more extensive correction in #5618.

Thank you. However, #5618 changes 6 files whereas #5615 changes only one. But still, if that sounds good we can go ahead with it!

**Comment by nedbat** [comment]
Yes, thanks for looking.  The convention is that this should have been an uppercase variable, and I know it is inconsistent throughout the repo, but #5618 moves us in the desired direction.

**Comment by juniorojha** [comment]
Okay, that's good. I'll keep this in mind if I spot any inconsistency in future. Thank you!

**Comment by natabene** [comment]
@juniorojha Thank you for joining the Open edX community! We have added your user to our records and can now review your code going forward.

**Pull request closed without merging**
