### PR TITLE
Update protobuf url in playbooks/roles/hadoop_common/defaults/main.yml

### PR DESCRIPTION
**Pull request by jjmiranda**
## Configuration Pull Request

Make sure that the following steps are done before merging
- [ ] @devops team member has commented with :+1:
- [ ] are you adding any new default values that need to be overriden when this goes live?  
  - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
  - [ ] Add an entry to the CHANGELOG.

Protobuf does not exits anymore in Google Code, today exists in GitHub.
Updating url for protobuf.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @jjmiranda! I've created [OSPR-1417](https://openedx.atlassian.net/browse/OSPR-1417) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by gsong** [comment]
@jjmiranda Thank you for your PR. We appreciate you taking the time to make the contribution.

Please submit a [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf) to us so we can review this pull request. We realize it's additional work for a simple change in this case, but we're hoping you would make future contributions as well.

**Comment by jjmiranda** [comment]
Hi @gsong , the signed document :)!
image

**Comment by gsong** [comment]
@jjmiranda I've submitted your contributor agreement to legal, they'll reach out if they have any questions.

**Comment by mulby** [comment]
@edx/devops this is blocking a bunch of stuff for me, are you OK with me merging this PR?

**Comment by mulby** [comment]
@jjmiranda - thanks for this contribution! This was very broken.

**Review by maxrothman — APPROVED** [review]

**Review by mulby — APPROVED** [review]

**Pull request merged**
