### PR TITLE
Add variable NOTIFIER_POLLING_INTERVAL

### PR DESCRIPTION
**Pull request by clemente**
Configuration Pull Request
---

This adds the possibility of changing the interval at which the celery worker in notifier refreshes the connection to the database.
- Before this change, it was using [the default defined by kombu](https://github.com/celery/kombu/blob/249e56525c17ece5791ebb283fa2679d6155986f/kombu/transport/django/__init__.py#L28) which is 5 seconds, which we found too fast.
- After this change, there's a new ansible variable `NOTIFIER_POLLING_INTERVAL` (default 5) to specify this interval; this ends up in a Django setting `KOMBU_POLLING_INTERVAL` and then in kombu's `POLLING_INTERVAL`.
- To do this change, notifier now uses the [settings_local.py](https://github.com/edx/configuration/blob/master/playbooks/roles/notifier/templates/settings_local.py.j2) settings file (which extends `settings.py`). Before this change, this settings file was used only when there was a notifier theme; now it's always used.  

**JIRA tickets**: None
**Discussions**: None
**Dependencies**: None
**Screenshots**: None
**Sandbox URL**: None
**Merge deadline**: None

**Testing instructions**:

1. Deploy a server with this playbook and a variable `NOTIFIER_POLLING_INTERVAL = "60"`
2. It should deploy
3. Connect to the database server (logins at `/edx/app/notifier/notifier_env`), and run a command like `show full processlist` (MySQL). In the `time` column it shows the connection age. Before this change, you never saw values greater 5. After this change, they go until the number of seconds you chose (60).
4. Everything else should work. In particular, what notifier does (daily digests of new content to subscribed forums users). If you subscribe to forum digests, then you can either wait for some days to see if you receive digests, or (this is a bit tricky) from inside the notifier virtualenv and after you define the variables found in the supervisor conf, you can run a command like `cd /edx/app/notifier/src$ /edx/app/notifier/virtualenvs/notifier/bin/python manage.py forums_digest --minutes 1 --show-users  -v 3` and see that the notifier code is running and finding users  
5. Verify the modified files: `/edx/app/supervisor/conf.d/notifier-celery-workers.conf`, `/edx/app/notifier/src/notifier/settings_local.py`

**Reviewers**
- [ ] @tomaszgy 
- [ ] edX reviewer

**Author concerns**: None
**Settings**: None

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @clemente! I've created [OSPR-2522](https://openedx.atlassian.net/browse/OSPR-2522) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by tomaszgy** [comment]
:+1:

- [x] I tested this:
I've followed the testing instructions using the sandbox from a sister PR (https://github.com/open-craft/configuration/pull/49). I've seen `forums_digest` command work and I've observed with @clemente forum digest e-mail arrive after the changes have been applied.
- [x] I read through the code
~- [ ] I checked for accessibility issues~
~- [ ] Includes documentation~

**Comment by mduboseedx** [comment]
@edx/devops Could you take a look at this?

**Comment by clemente** [comment]
@mduboseedx Any news about this review? (awaiting priorization) Thanks

**Comment by mduboseedx** [comment]
@clemente I apologize for the delay as I was out of the office this past week. I'm checking with our DevOps team about this PR.

**Review by feanil — COMMENTED** [review]
`settings_local.py` adds vars for themes related directories which won't have been checked out the way you're doing this right now.  Won't this cause failures in rendering templates that look for themes files?

**Comment by clemente** [comment]
@feanil I didn't find a sample notifier theme to test this, but the logic is maintained:

- `settings_local.py` was only created when there's a theme name (note the `when: NOTIFIER_THEME_NAME != ''` in the original).
- In the new system, the variables are set only when there's a theme name (note the `{% if NOTIFIER_THEME_NAME != "" %}`).

So while the file is now always created, the variables are set with the same logic as before.

It seems the logic is correct: *only* when there's a theme name, the theme is downloaded ([there's a `when: NOTIFIER_THEME_NAME != ''`](https://github.com/edx/configuration/blob/9f573abf35b69f7ba4bc1a22f0c7fc5d7fbfcb61/playbooks/roles/notifier/tasks/deploy.yml#L55)) and `TEMPLATE_DIRS` is expanded.

**Comment by clemente** [comment]
@mduboseedx Friendly ping about what's the next step for this review (awaiting prioritization).

**Comment by mduboseedx** [comment]
@feanil Do you think that @clemente has addressed your concerns with this PR?

**Comment by clemente** [comment]
@feanil Are you fine with this PR as it is? (see previous comment)

(Note: I'll be off the next two weeks but can address new comments about it later).

**Review by feanil — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@clemente 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4689&entry.1484655318=https://github.com/clemente&entry.752974735=2018-07-14+23:19&entry.1917517419=2018-12-04+16:27&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
