### PR TITLE
Add lifecycle tags for ansible-role-django-ida role.

### PR DESCRIPTION
**Pull request by mrgnr**
Add lifecycle tags for ansible-role-django-ida role. Lifecycle tags allow users to run specific sets of related tasks within a role. See the [proposal](https://openedx.atlassian.net/wiki/display/OpenOPS/Role+Life-cycle) for details.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @emrob! I've created [OSPR-902](https://openedx.atlassian.net/browse/OSPR-902) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).
We can't start reviewing your pull request until you've   submitted a [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)   or indicated your institutional affiliation   and   added yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS) file . Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst) file for more information.

**Comment by sarina** [comment]
@emrob Are you covered under Appsembler's agreement? Can you work with @natea to get us a list of who is covered under this agreement ASAP?

**Comment by sarina** [comment]
@emrob is covered under Appsembler's agreement, thanks Nate.

@emrob can you provide a description on this PR?

**Comment by feanil** [comment]
@emrob can you rebase this PR?

**Comment by feanil** [comment]
@emrob NM, I cherry-picked this into master: https://github.com/edx/configuration/pull/2473

**Pull request closed without merging**
