### PR TITLE
Update scipy, lxml, boto

### PR DESCRIPTION
**Pull request by singingwolfboy**
Companion PR to https://github.com/edx/edx-platform/pull/4697

### CODE REVIEW

**Comment by e0d** [comment]
@singingwolfboy : @jzoldak needs to weigh in on this.

**Comment by jzoldak** [comment]
@benpatterson do we need to get these changes into the configuration repo?

**Comment by feanil** [comment]
@singingwolfboy can you post the change log for the requirements update.  also, it looks like this needs a rebase.

@benpatterson can you verify that this doesn't break the jenkins workers?

**Comment by singingwolfboy** [comment]
@feanil this is not a simple PR to rebase: [playbooks/roles/jenkins_worker/defaults/main.yml](https://github.com/edx/configuration/blob/master/playbooks/roles/jenkins_worker/defaults/main.yml) has changed dramatically on master since this pull request was made. Can someone give me some guidance on where these changes need to go?

**Comment by benpatterson** [comment]
@singingwolfboy @feanil We are no longer using the wheels configuration, so all the changes under playbooks/roles/jenkins_worker/defaults/main.yml are no longer relevant.

If you git checkout that file, the merge will probably look much better. Can't comment on the requirements.txt....that obviously will have a broader impact on ansible runs, but it shouldn't impact our workers, which are provisioned without boto (and when they use boto it will be according to whatever's in the edx-platform requirements files.)

CC @jzoldak

**Comment by singingwolfboy** [comment]
@benpatterson In that case, I'm closing this pull request in favor of #1572.

**Pull request closed without merging**
