### PR TITLE
mattdrayer/add-default-theme-setting: Update ecommerce playbook

### PR DESCRIPTION
**Pull request by mattdrayer**
@clintonb @jibsheet -- I think this is where the plumbing needs to be, actually, versus in ecommerce/settings/base.py

### CODE REVIEW

**Comment by jibsheet** [comment]
You need to set ECOMMERCE_DEFAULT_SITE_THEME to something as a sane default 
Further up in the same file with the other initial defaults.

**Comment by clintonb** [comment]
If the application defaults to `None`, why do we need this at all?

**Comment by jibsheet** [comment]
@clintonb He asked us to override it in the secure config, which needs pluming in configuration to copy the value

**Comment by clintonb** [comment]
Got it.

**Comment by clintonb** [comment]
👍

**Comment by mattdrayer** [comment]
Added default value for the setting

**Comment by jibsheet** [comment]
👍

**Comment by mattdrayer** [comment]
Failing checks are due to timeouts and an insights npm failure -- unrelated to the change introduced by this PR -- going ahead with the merge now.

**Pull request merged**
