### PR TITLE
enable decrypt and copy config sandbox (OPS-4261)

### PR DESCRIPTION
**Pull request by nadeemshahzad**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Review by coryleeio — APPROVED** [review]
This should be fine to go ahead and merge - before closing this though, can you make it so that the jenkins job can be parameterized with which yml file to decrypt from the internal repo?  I think it is safe to assume the key is the same for now.

The reason for this is that some of our long lived sandboxes are essentially working around having to use the main config.yml and could do a lot less if they just used a different config.yml so I feel like it might be worth enabling them to do this for the future.

**Comment by coryleeio** [comment]
Feel free to do the above as a separate PR

**Comment by nadeemshahzad** [comment]
Thanks @coryleeio I have made PR (https://github.com/edx/jenkins-job-dsl/pull/784) to add parameters  in sandbox job and made relevant changes in this PR to enable decrypt and copy config for apps.

**Comment by coryleeio** [comment]
@nadeemshahzad Can you make it possible for the sandbox job to change their yaml file that they upload from internal?

For instance, instead of sandbox-internal/sandbox-remote-config/notes.yml someone might want to do the following to test a new feature:
sandbox-internal/sandbox-remote-config/sally-notes.yml

**Comment by coryleeio** [comment]
The default should be set to the normal .yml in sandbox-internal though

**Pull request merged**
