### PR TITLE
lilac backport: add Elasticsearch variable overrides

### PR DESCRIPTION
**Pull request by Agrendalath**
This backports #6646 to Lilac.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Agrendalath! I've created [OSPR-6385](https://openedx.atlassian.net/browse/OSPR-6385) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@Agrendalath Thank you for your contribution. @pomegranited Would you be able to review and merge this one as well?

**Review by pomegranited — APPROVED** [review]
:+1:

- [x] I tested this by checking the updated variable names against lilac.master's [course_discovery.settings.production](https://github.com/openedx/course-discovery/blob/open-release/lilac.master/course_discovery/settings/production.py#L69) and [notesserver.settings.common](https://github.com/openedx/edx-notes-api/blob/open-release/lilac.master/notesserver/settings/common.py#L22). 
- [x] I checked the code against the original PR#
- [x] <strike>I made sure any change in configuration variables is reflected in the corresponding
    client's `configuration-secure` repository.</strike> N/A

**Comment by openedx-webhooks** [comment]
@Agrendalath 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/configuration&entry.867055334=https://github.com/openedx/configuration/pull/6659&entry.1484655318=https://github.com/Agrendalath&entry.752974735=2022-01-13+16:59&entry.1917517419=2022-01-16+23:11&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
