### PR TITLE
added edx-event-routing-backends in PRIVATE_REQUIREMENTS

### PR DESCRIPTION
**Pull request by ziafazal**
edx-event-routing-backends library transforms edX events according to caliper and xAPI specifications and route them to specifies LRS.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @ziafazal! I've created [OSPR-6086](https://openedx.atlassian.net/browse/OSPR-6086) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@ziafazal Thank you for your contribution. Is this ready for our review?

**Review by feanil — APPROVED** [review]

**Comment by feanil** [comment]
@ziafazal FYI, this will not automatically install it for edx.org.  If you need that to happen let me know, edX keeps a separate override of this list for edx.org.

**Comment by openedx-webhooks** [comment]
@ziafazal 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6565&entry.1484655318=https://github.com/ziafazal&entry.752974735=2021-09-30+07:04&entry.1917517419=2021-09-30+21:01&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
