### PR TITLE
Add ECOMMERCE_SECURE_PROXY_SSL_HEADER

### PR DESCRIPTION
**Pull request by viadanna**
Description
---
This PR adds `ECOMMERCE_SECURE_PROXY_SSL_HEADER` ansible variable and the `SECURE_PROXY_SSL_HEADER` configuration on `ecommerce.yml`

Testing
---

1. Provision a VM for testing (Vagrant is recommended).
2. Run the Ecommerce playbook without any variables to make sure there's a sane default:
```
$ ansible-playbook -vvv --user=ubuntu -i hosts playbooks/ecommerce.yml
```
3. Make sure the defaults produce a sane `/edx/etc/ecommerce.yml`:
```
(...)
SECURE_PROXY_SSL_HEADER: null
(...)
```
4. Run the playbook setting a value for the added config:
```
$ ansible-playbook -vvv --user=ubuntu -i hosts playbooks/ecommerce.yml -e '{"ECOMMERCE_SECURE_PROXY_SSL_HEADER":["HTTP_X_FORWARDED_PROTO","https"]}'
```
5. Make sure the resulting configuration is correct:
```
(...)
SECURE_PROXY_SSL_HEADER:
- HTTP_X_FORWARDED_PROTO
- https
(...)
```

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [x] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @viadanna! I've created [OSPR-3805](https://openedx.atlassian.net/browse/OSPR-3805) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@viadanna Thank you for your contribution. Please let me know once it is ready for our review.

**Comment by viadanna** [comment]
Thanks @natabene 
This is good for review

**Comment by natabene** [comment]
@edx/devops This is ready for your review.

**Comment by viadanna** [comment]
@edx/devops any news here?

**Comment by natabene** [comment]
@nedbat Can you help us out here? @fredsmith said these defaults have all been pulled out of config, but not sure where it used to be.

**Comment by nedbat** [comment]
@fredsmith Where should this go?

**Comment by fredsmith** [comment]
this should go into https://github.com/edx/ecommerce/tree/master/ecommerce/settings

**Comment by openedx-webhooks** [comment]
@viadanna Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/5374&entry.1484655318=https://github.com/viadanna&entry.752974735=2019-08-26+11:23&entry.1917517419=2020-02-20+17:05&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
