### PR TITLE
Add ability to specify custom python requirements.

### PR DESCRIPTION
**Pull request by mtyaka**
This lets you specify additional python packages to be installed
into the edxapp virtual environment.

The `EDXAPP_EXTRA_REQUIREMENTS` should be a list of dict objects
with `name`, `version` (optional) and `extra_args` (optional) keys,
that correspond to the options of ansible's pip module.

Example:

```
EDXAPP_EXTRA_REQUIREMENTS:
  - name: mypackage
    version: 1.0.1
  - name: git+https://git.myproject.org/MyProject#egg=MyProject
```

### CODE REVIEW

**Comment by e0d** [comment]
There are a couple competing ways of doing something similar at the moment, while this looks good, we need to discuss the different approaches internally and decide how best to provide this feature.

Can you clarify your use case?  Is this targeted for development or production?

Also, have you signed a contributor agreement?

**Comment by mtyaka** [comment]
@e0d The main use case is to be able to easily deploy custom XBlocks to production servers. I did sign the contributor agreement.

Sorry it took me so long to reply, for some reason github didn't notify me about your questions.

**Comment by tusbar** [comment]
I do something similar for custom XBlocks deployment.

```
- name: install blocks
  pip: >-
    name={{ item.repo }}@{{ item.version }}#egg={{ item.name }}
    virtualenv={{ edxapp_venv_dir }}
    state=present
    extra_args="-i {{ COMMON_PYPI_MIRROR_URL }}"
  with_items: edx_xblocks_blocks
  sudo_user: "{{ edxapp_user }}"
  environment: "{{ edxapp_environment }}"
  notify:
    - "restart edxapp"
    - "restart edxapp_workers"
  tags:
    - deploy
```

It’s a little different than what @mtyaka proposes, but it allows specifying git versions/tags/commits in a more _user-friendly_ way.

```
edx_xblocks_blocks:
  - name: 'xblock-taggedtext'
    repo: 'git+https://github.com/IONISx/xblock-taggedtext.git'
    version: 'v0.1.0'
```

But :+1: on implementing something that does this.

**Comment by antoviaque** [comment]
@e0d Is there a good way to do this now? Or would this be mergeable if it was rebased? It would be useful to have a mechanism for this in the repo in any case, to avoid having to keep this type of changes in the edx-platform repo forks.

**Comment by sarina** [comment]
Hi @e0d - could you please advise on this PR?

**Comment by sarina** [comment]
@mtyaka I don't think you can see this, but you'll need to rebase this PR atop master to resolve merge conflicts.

**Comment by mtyaka** [comment]
@sarina Thanks for the warning, I rebased the patch.

**Comment by Mihara** [comment]
> There are a couple competing ways of doing something similar at the moment

Pardon me for interrupting. While the PR is still a ways off from being merged, could anyone please describe what those are? Because that 'deploy XBlocks' is exactly what I need to do right now. :)

**Comment by e0d** [comment]
@Mihara see:

https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/tasks/deploy.yml#L236 and
https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml#L225

**Comment by e0d** [comment]
@mtyaka does the feature referenced above meet your needs as well?  Sorry for the delay in a useful response from me.

**Comment by sarina** [comment]
Thanks for the pull request, @mtyaka! I've created https://openedx.atlassian.net/browse/OSPR-64 to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams. Supporting information that is good to add there is anything that can help Product understand the context for the PR - supporting documentation, edx-code email threads, timeline information ('this must be merged by XX date', and why that is), partner information (this is for a course on edx.org, for example), etc.

All technical communication about the code itself will still be done via the Github pull request interface.

**Pull request merged**
