### PR TITLE
Hotfix - Fix Insights YML file 

### PR DESCRIPTION
**Pull request by lock9**
I'm unable to build the latest version, and this is one of the reasons.
This YAML file is invalid, this PR fixes it. Thanks

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A SRE team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a SRE ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/spaces/SRE/pages/28967861/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

This should work out of the box. Also, YML lint can be used to ensure it's correct. This problem was preventing me from building the project. I'm facing other issues, but I'll solve them eventually

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @lock9!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

**Comment by natabene** [comment]
@lock9 Thank you for your contribution. Once you've submitted a [signed contributor agreement](https://openedx.org/cla) and it has been processed, I will update here, and we will be able to review your code.

**Comment by lock9** [comment]
Hi @natabene , I've just done it.
Thanks

**Comment by openedx-webhooks** [comment]
@lock9 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/configuration&entry.867055334=https://github.com/openedx/configuration/pull/6799&entry.1484655318=https://github.com/lock9&entry.752974735=2022-08-31+19:50&entry.1917517419=2022-08-31+22:11&entry.2133058324=No) so we can improve your experience in the future.

**Comment by natabene** [comment]
@lock9 Thanks for submitting the forms. It may take a day or two for them to be processed. Did you intentionally close this PR?

**Comment by lock9** [comment]
Hi @natabene , yes, I closed it.
The YML file is broken, however, there are many other YAML files that are not working properly. That made me think if the problem wasn't between the keyboard and the chair. 
I'll try a new fresh install, to see if the problem was already there, or if it was something I've broken myself.

The problem lies in the PyYAML dependency. Depending on the version you have, the parsing may be more 'friendly'. I'll do more tests today. It's worth mentioning that those files were updated on the Master branch, however, they don't have to, if you use the correct version of PyYAML.  Some parts of the file were not updated to match the new format

Thanks!

**Comment by natabene** [comment]
Got it, @lock9, thanks for the explanation.

**Pull request closed without merging**
