### PR TITLE
[SE-3111] Update labxchange-xblocks audio xBlock

### PR DESCRIPTION
**Pull request by toxinu**
See https://github.com/open-craft/labxchange-xblocks/pull/11 - this pull request adds transcripts support for audio xBlock.

**Dependencies**: None
**Merge deadline**: None
**Testing instructions**:

- Verify that the updated hash/revision of the labxchange-xblocks dependency is valid and matches the commit that merged open-craft/labxchange-xblocks#11
- Provision the platform with this configuration
- Verify that labxchange-xblocks is installed successfully in the environment.

**Reviewers**

 - @s0b0lev
 - edX reviewer[s] TBD

**Settings**
```
```

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @toxinu! I've created [OSPR-4901](https://openedx.atlassian.net/browse/OSPR-4901) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@toxinu Thank you for your contribution. Please let me know once it is ready for edX review.

**Comment by s0b0lev** [comment]
@toxinu  LGTM :+1: 

- [x] I tested this: checked manually. (Instance provision is in progress)
- [x] I read through the code (match commit version)

**Review by s0b0lev — APPROVED** [review]

**Comment by toxinu** [comment]
@natabene This is ready to be reviewed by edX. Thanks!

**Comment by natabene** [comment]
@fredsmith Could you give this a look when you have a chance?

**Comment by toxinu** [comment]
@natabene Friendly ping.

**Review by fredsmith — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@toxinu 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/5942&entry.1484655318=https://github.com/toxinu&entry.752974735=2020-08-18+07:01&entry.1917517419=2020-09-08+16:46&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
