### PR TITLE
Add the forums migration for teams discussion filtering

### PR DESCRIPTION
**Pull request by nedbat**
Based on https://openedx.atlassian.net/wiki/display/TNL/Migrating+the+Discussion+Forums+to+Support+Teams+Discussion+Filtering

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
# PR Cover Letter
- [ ] A detailed description of the changes in the body of the PR
- [ ] If available, a link to the relevant JIRA ticket in the body of the PR
  - `[PROJ-XXXX](https://openedx.atlassian.net/browse/PROJ-XXXX)`

# Reviewers

If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [ ] Code review #1
- [ ] Code review #2

# DevOps assistance

If it's needed, or even if you suspect it might be needed, do any/all these things as early as possible. Don't surprise devops right before merging! For example, touching envs/aws.py or or envs/common.py are dead giveaways that you'll need assistance when pushing your changes out. Things that require devops attention include, but are not limited to:
- configuration changes
- feature flags
- migrations
  Ways to get devops attention, pick-and-choose whichever is most appropriate for your specific PR:
- [ ] Tag devops on your PR (`@edx/devops`), either for review (more specific to devops = better) or just a general FYI

**Comment by nedbat** [comment]
@dianakhuang @feanil ?

**Comment by dianakhuang** [comment]
This looks correct to me. :+1:

**Comment by nedbat** [comment]
@feanil I'm going to merge to test an update.  If you have concerns, we can address them.

**Pull request merged**
