### PR TITLE
Only run dependencies conditionally.

### PR DESCRIPTION
**Pull request by feanil**

### CODE REVIEW

**Comment by e0d** [comment]
Why not have deps lists per OS family as we have stubbed out elsewhere?

**Comment by feanil** [comment]
I didn't see anything like that, can you point me to an example?

**Comment by fredsmith** [comment]
@feanil like https://github.com/edx/configuration/blob/2129abc370abf13ce221c87764a32266d44a74f4/playbooks/roles/edx_service/tasks/main.yml#L69 ?

I don't really see anything functionally different from what you're doing vs. that, though. 

I also don't really understand why we include specific roles based on the distro.

**Comment by feanil** [comment]
The reason is that those roles are not distribution agnostic and assume debian variants(apt), which prenvents us from running the newrelic role on non debian boxes(ec2-linux).

**Comment by e0d** [comment]
The PR seems to me to violate the principal of least astonishment.  I realize we don't support RH variants in any useful way, but shouldn't we move the check to the roles that are being included rather than in the meta include?  Minimally, I'd like comments and a TODO.

**Pull request closed without merging**
