### PR TITLE
use the YAML style parameter passing

### PR DESCRIPTION
**Pull request by arbabnazar**
@edx/devops kindly review. Thanks

Jenkins build to verify this branch (7542)

### CODE REVIEW

**Comment by feanil** [comment]
The 14.04 style blas and lapack linking should work with newer versions of ubuntu as well including xenial.  I think we should remove the conditionals that check the distribution and just think of it as two possible places where blas and lapack could be installed.  Everything else looks good so if you want to make that change, let's pull it out into a separate PR.

**Comment by arbabnazar** [comment]
@feanil kindly review, is it ok I have removed the condition to check the distribution. Thanks

**Comment by feanil** [comment]
👍   @arbabnazar please build an AMI off of this branch to make sure that the tagging of AMIs still works since that part of the code is being refactored and it's pretty crucial to our workflow.

**Comment by arbabnazar** [comment]
@feanil I have verified the tagging part and it's working. I am merging this branch. Thanks for the review and suggestions.

**Pull request merged**
