### PR TITLE
parameterize machine names in edx-west playbooks -- to edx-west/release

### PR DESCRIPTION
**Pull request by sefk**
@jbau and @jrbl -- this is the new way I recommend running ansible plays, using the "-e machine=foo" option.  this is a pull request to our release branch.  If it lands then I'll do the same to master just for cleanliness sake (I've already put our README up there).

### CODE REVIEW

**Comment by jbau** [comment]
this makes sense.  how about carnegie and cme?

**Comment by sefk** [comment]
oh of course forgot those.  I'll do.

**Comment by jrbl** [comment]
Yeah, makes sense to me.

**Comment by sefk** [comment]
I decided that this is unsafe as it currently stands.  Before, it was hard to run a "util" play on an "app" machine, this makes it much easier to make that mistake, and who knows what that would do.  Before submitting I want to add some validation.

**Comment by sefk** [comment]
Validation added, this is how it will fail.  Note this is calling the stage-worker play with machine=app1:

```
ANSIBLE_EC2_INI=stage-ec2.ini ANSIBLE_CONFIG=stage-ansible.cfg ansible-playbook -e "machine=app1" -c ssh -u ubuntu -i ec2.py stage-worker.yml  

PLAY [Basic util setup on all hosts] ****************************************** 

GATHERING FACTS *************************************************************** 
ok: [ip-10-0-10-76.us-west-1.compute.internal]

TASK: [fail msg="This playbook only runnable on 'util' machines"] ************* 
failed: [ip-10-0-10-76.us-west-1.compute.internal] => {"failed": true}
msg: This playbook only runnable on 'util' machines

FATAL: all hosts have already failed -- aborting
```

**Comment by sefk** [comment]
@jbau and @jrbl please look again.  These are the playbooks I installed with this time.  See commit msg on ddd57c4da0603f64fc648261babeac2f157da968 for more info.

**Comment by jrbl** [comment]
ok, lgtm

**Comment by sefk** [comment]
thanks for the review @jrbl.  I'll go head and pull based on that, and do a PR to master for good measure.

**Pull request merged**
