### PR TITLE
Add libffi-dev to discovery

### PR DESCRIPTION
**Pull request by bderusha**
FYI @clintonb @jibsheet

### CODE REVIEW

**Comment by jibsheet** [comment]
What changed to add the dep?

**Comment by clintonb** [comment]
👍

**Comment by clintonb** [comment]
@bderusha this is needed for all IDAs, and the template.

**Comment by bderusha** [comment]
@jibsheet required by the `cryptography` package, which is required by `pyJWT` to use asymmetric key signing for JWTs

**Comment by bderusha** [comment]
@clintonb it will be for them to start using asymmetric keys, but I think we should wait until we validate this with course discovery before we add the dependency to all IDAs

**Comment by clintonb** [comment]
LMS is being updated to issue JWTs as access tokens. Those tokens won't be able to be validated without updating the IDAs.

**Comment by jibsheet** [comment]
I'll let you folks decide which IDAs get it, but I'd like to request that the commit be amended to explain why libffi-dev is installed (either in the commit message or in a comment).
After that I'll thumb, I'd like to get at least this merged since it's causing Travis to fail for all Pull Requests against configuration right now.

**Comment by clintonb** [comment]
@bderusha is sick today. I'll add the comment and get this out of the way. We'll follow-up with changes to the other IDAs later.

**Comment by clintonb** [comment]
@jibsheet comment added.

**Comment by jibsheet** [comment]
👍

**Pull request merged**
