### PR TITLE
Download JSCover from S3

### PR DESCRIPTION
**Pull request by wedaly**
Use an S3 URL for JSCover instead of downloading from a SourceForge mirror.  This should be more reliable, as SourceForge download URLs can change.

@feanil

### CODE REVIEW

**Comment by jarv** [comment]
can we use files.edx.org instead?

**Comment by wedaly** [comment]
@jarv Sure.  I don't think I have permissions to upload to that bucket, though.

**Comment by feanil** [comment]
@wedaly uploaded it, can you use this url instead: 'http://files.edx.org/testeng/JSCover-1.0.2.zip'

Thanks.

**Comment by wedaly** [comment]
sure thing

**Comment by feanil** [comment]
looks good.

**Pull request merged**
