### PR TITLE
sync the locust role with edx-load-tests

### PR DESCRIPTION
**Pull request by pwnage101**
## Configuration Pull Request

Make sure that the following steps are done before merging
- [ ] @devops team member has commented with :+1:
- [ ] are you adding any new default values that need to be overriden when this goes live?  
  - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
  - [ ] Add an entry to the CHANGELOG.

Required changes to the ansible-provision-locust-master project's "Build with
Parameters" page:
- remove the "locust_loadtest_dir" field
- add a "locust_loadtest_name" text field and hook it into the ansible
  var LOCUST_LOADTEST_NAME.
- add a "locust_is_master" boolean field and hook it into the ansible var
  LOCUST_IS_MASTER.

Required changes to the ansible-provision-locust-slave project's "Build with
Parameters" page:
- remove the "locust_loadtest_dir" field
- add a "locust_loadtest_name" text field and hook it into the ansible
  var LOCUST_LOADTEST_NAME.

These changes certainly don't work with the old load-tests repo, so don't even
suggest that it will work---convert the locust_loadtest_repo field from
drop-down options to text field.

---

What's the easiest way for me to test this?

This PR depends on edx/edx-load-tests#68

### CODE REVIEW

**Comment by feanil** [comment]
@pwnage101 I would suggest cloning the locust jenkins job and updating the paramaters and pointing to your branch.  Once that's working, we can merge this and delete the old job and make the new job the canonical job.

**Comment by feanil** [comment]
Changes generally look good and we should merge once we have a working locust-machine jenkins job.

**Comment by pwnage101** [comment]
@feanil I'm going to make an attempt to try to do this soon.  How can I get the appropriate permissions to clone a job on http://jenkins.edx.org:8080/ ?

**Comment by feanil** [comment]
@pwnage101 The ground has shifted since I last advised you.  I think that this job should be written in Jenkins Job DSL.  Maybe setup a 30min meeting and I can give you a lay of the land?

**Comment by pwnage101** [comment]
I'm just going to recreate this PR for clarity.

**Pull request closed without merging**
