### PR TITLE
Use utf8mb4 encoding for mysql databases

### PR DESCRIPTION
**Pull request by omarkhan**
Allows full 4-byte UTF-8 characters (e.g. 😜) to be written to mysql.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @omarkhan! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?number=2823&repo=edx%2Fconfiguration

**Comment by jibsheet** [comment]
@omarkhan Thanks for the utf8mb4 change, it looks great, however mixing it in with a mysql 5.7 upgrade  is a much larger change.

Can you split these apart?  We're still running RDS 5.6 so we will want to continue to do so, so will need to figure out a 5.7 change.

**Comment by brianhw** [comment]
Also just wondering about the effect (if any) on indexing.  It used to be that we had varchar(255) values because these could be indexed within the 768-byte limit that Mysql supported.  If Mysql has the same limit, and we move from 3-byte to 4-byte characters, then not all 255-char values will be indexed.

**Comment by smarnach** [comment]
@jibsheet @brianhw We are still reviewing and testing this change on our side.  Currently, it isn't easily possible to make utf8mb4 work without upgrading to version 5.7 due to the indexing issue Brian mentions, so we might drop the plan.

I'll close this PR for now.  We might reopen it in case we figure out a better way to make this work.

**Pull request closed without merging**
