### PR TITLE
WIP: Install Stanford's PDF Certificates

### PR DESCRIPTION
**Pull request by stvstnfrd**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @stvstnfrd! I've created [OSPR-3616](https://openedx.atlassian.net/browse/OSPR-3616) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by stvstnfrd** [comment]
CC: @feanil 

I hope to have this polished up this week, but wanted to show movement.

In tandem, @caesar2164 has reconciled the few recent changes from edx's fork into ours.

**Comment by natabene** [comment]
@stvstnfrd Thank you for your contribution. @feanil Does this need to be run by product first?

**Comment by feanil** [comment]
@natabene no, this does not need to go through product review.

**Comment by natabene** [comment]
@stvstnfrd Do you expect anything from us at this point or does this PR wait on you?

**Comment by natabene** [comment]
@stvstnfrd We have not heard from you in a while, so I am closing this PR for now. Please feel free to re-open if you decide to work on it again.

**Comment by openedx-webhooks** [comment]
@stvstnfrd Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/5160&entry.1484655318=https://github.com/stvstnfrd&entry.752974735=2019-05-30+05:36&entry.1917517419=2020-01-24+20:31&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
