### PR TITLE
edx-west prod: don't install notifiers yet

### PR DESCRIPTION
**Pull request by sefk**
The notifier isn't ready yet, needs theming to be done before it can be installed.  Affects the edx-west machines only.

@jrbl -- make sure you pull this in before this week's install.

### CODE REVIEW

**Comment by jrbl** [comment]
Do we not need the workers for anything but notification? I thought @jbau had stuff that ran on the workers.  I mean, I'm happy to have one less machine to install - but I want to make sure that I really do. @jbau?

**Comment by jbau** [comment]
no. nothing else runs on the workers
but again, we should install workers whenever we update the prod machines, to keep edx-platform consistent between app and worker

**Comment by jrbl** [comment]
ok, understood, thanks.

**Comment by jrbl** [comment]
lgtm @sefk

**Comment by jrbl** [comment]
merged, you can delete your branch whenever you'd like.

**Pull request merged**
