### PR TITLE
Previously, this was hammered on in aws.py for all DBs

### PR DESCRIPTION
**Pull request by jibsheet**
Instead, turn it on for the databases where it makes sense.

https://github.com/edx/edx-platform/pull/11722

### CODE REVIEW

**Comment by jibsheet** [comment]
@edx/devops See also the referenced platform PR for the why.

**Comment by feanil** [comment]
What is the reason for not having atomic requests on the `read_replica`?

**Comment by jibsheet** [comment]
@feanil Is there a win there?  I figured it's read only, so unlike the default db where someone might take a transaction and update while someone is reading, all the read-replica access should be reads and are outside the transaction boundaries anyway.

**Comment by feanil** [comment]
:+1:

**Comment by jibsheet** [comment]
This was cherry picked into https://github.com/edx/configuration/pull/2815 and merged

**Pull request closed without merging**
