### PR TITLE
Run xqueue on python3

### PR DESCRIPTION
**Pull request by zainab-amir**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Review by feanil — CHANGES_REQUESTED** [review]
You should not make this change in the edx_service role, which is meant to be a role that is shared by services that might not be python.  You should instead add this to the xqueue role and conditionally create a python3 xqueue venv on a python 2 xqueue venv.

I would look to making your change here: https://github.com/edx/configuration/blob/master/playbooks/roles/xqueue/tasks/main.yml

Ideally long term, xqueue would be using the edx_django_service role as its base instead of just the edx_service role but I think that doing that is too much work to get this over the line.

**Review by feanil — APPROVED** [review]

**Comment by bderusha** [comment]
@zainab-amir based on an issue we ran into in another service you may also need to make the `install pip requirements` also switch between `pip` and `pip3` conditionally by adding the line `executable=pip3` to the requirements install

https://github.com/edx/configuration/pull/5415/files#diff-49cfef58ebeac4f9f324b8fdf8aee7afL66-L88

**Comment by bderusha** [comment]
```
  name: install python3 requirements
  pip: >
    requirements="{{ item }}"
    virtualenv="{{ venv_dir }}"
    state=present
    executable=pip3
  sudo_user: "{{ user }}"
  when: use_python3
  with_items:
    - "{{ prerequirements_file }}"
    - "{{ requirements_file }}"
```

**Comment by syed-awais-ali** [comment]
> ```
>   name: install python3 requirements
>   pip: >
>     requirements="{{ item }}"
>     virtualenv="{{ venv_dir }}"
>     state=present
>     executable=pip3
>   sudo_user: "{{ user }}"
>   when: use_python3
>   with_items:
>     - "{{ prerequirements_file }}"
>     - "{{ requirements_file }}"
> ```

It would lead to an error stating
`"msg": "parameters are mutually exclusive: ['executable', 'virtualenv']"`

The correct way is to remove the `executable` bit from this and add

`virtualenv_python="python{{ VENV_PYTHON_VERSION }}"`

where `VENV_PYTHON_VERSION` can be defined in the defaults.

```
- name: install python requirements
  pip: >
    requirements="{{ item }}"
    virtualenv="{{ venv_dir }}"
    virtualenv_python="python{{ VENV_PYTHON_VERSION }}"
    state=present
  sudo_user: "{{ user }}"
  with_items:
    - "{{ requirements_file }}"
```

OR an alternate way could be of what we have done in `edx_django_service` by removing the pip bit and adding the command and giving it the requirements file as the item (if there are multiple files to loop over)

**Review by feanil — APPROVED** [review]

**Pull request merged**
