### PR TITLE
discovery play fixes

### PR DESCRIPTION
**Pull request by fredsmith**

### CODE REVIEW

**Comment by fredsmith** [comment]
FYI, newrelic gevent bug is at https://discuss.newrelic.com/t/python-agent-and-gevent-on-python-3/30707/5

**Comment by feanil** [comment]
:+1:

**Comment by e0d** [comment]
@fredsmith is the Analytics team synched up on this change?

**Comment by fredsmith** [comment]
@clintonb can you review this?

**Comment by clintonb** [comment]
:+1:

**Pull request merged**
