### PR TITLE
Install vault on DE jenkins (old+new)

### PR DESCRIPTION
**Pull request by pwnage101**
I should be able to just run the `jenkins` tag to effect this change.

DENG-382

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Review by estute — APPROVED** [review]
I can't recall off the top of my head. Does anything else use the `jenkins` tag (aside from these files)? I wouldn't want you to accidentally blow away the Jenkins installation. It doesn't seem to be related to what you are doing here and might be confusing

**Comment by estute** [comment]
Just to clarify, this role calls out to jenkins_common (https://github.com/edx/configuration/blob/master/playbooks/roles/jenkins_data_engineering/meta/main.yml#L4). I would recommend making sure that nothing in that role also uses the `jenkins` tag.

**Comment by pwnage101** [comment]
I just went ahead and made a more specific tag called `jenkins-vault`.

**Review by estute — APPROVED** [review]

**Comment by pwnage101** [comment]
Ran the play with `--tags jenkins-vault` and it worked.

**Pull request merged**
