### PR TITLE
Ansible fails in looking up keys inside the dictionary when the top leve...

### PR DESCRIPTION
**Pull request by feanil**
...l var does not exist.

### CODE REVIEW

**Comment by maxrothman** [comment]
Are there other motivations for pulling the DB name out of that dict, or is it just to get this part functional?

**Comment by feanil** [comment]
It is necessary for this to be functional.

**Comment by maxrothman** [comment]
Is there a way this could be accomplished with an "is defined" conditional instead?

**Comment by feanil** [comment]
Not that I know of.  That is the whole reason we use the pattern with defaults.

**Comment by maxrothman** [comment]
:+1:

**Pull request merged**
