### PR TITLE
Update main.yml

### PR DESCRIPTION
**Pull request by wwj718**
As of Node.js v0.10.0, the nodejs package includes npm

### CODE REVIEW

**Comment by dhpollack** [comment]
already working on this in pull #1285

**Comment by wwj718** [comment]
OK

**Comment by nedbat** [comment]
@wwj718 @dhpollack if this pull request isn't needed anymore, please close it.

**Comment by nedbat** [comment]
If you still need this open, feel free to re-open it.

**Comment by wwj718** [comment]
@nedbat thank you

**Pull request closed without merging**
