### PR TITLE
adding symlink pointing to 2.6

### PR DESCRIPTION
**Pull request by e0d**
## Configuration Pull Request

Simple indirection for the mongo version specific roles for the sake of clarity and making future upgrades easier.

Make sure that the following steps are done before merging
- [ ] @devops team member has commented with :+1:
- [ ] are you adding any new default values that need to be overriden when this goes live?  
  - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
  - [ ] Add an entry to the CHANGELOG.

### CODE REVIEW

**Comment by e0d** [comment]
@jibsheet as discussed.

**Comment by jibsheet** [comment]
@e0d Looks like it's missing the symlink back from mongo to mongo_2.6?

**Review by jibsheet — APPROVED** [review]
Build a sandbox to test and we're good to go.

**Comment by e0d** [comment]
Incremental:  http://jenkins.edx.org:8080/job/ansible-provision/9645/

From scratch: http://jenkins.edx.org:8080/job/ansible-provision/9652/

**Comment by jibsheet** [comment]
:shipit:

**Pull request merged**
