### PR TITLE
Removed ECOMMERCE_ORDER_NUMBER_PREFIX

### PR DESCRIPTION
**Pull request by clintonb**
This value is no longer used/needed.

ECOM-2618

### CODE REVIEW

**Comment by clintonb** [comment]
@fredsmith @rlucioni please review

edx/ecommerce#423 must be merged first.

**Comment by rlucioni** [comment]
:+1:

**Comment by feanil** [comment]
@clintonb @rlucioni have either of you filed a ticket to remove the config from our secure settings?  If not can you please do that? Also please add an entry to the CHANGELOG.  This is good practice when removing top level variables.

**Comment by clintonb** [comment]
@feanil https://openedx.atlassian.net/browse/DEVOPS-3197

**Pull request merged**
