### PR TITLE
Use common packages between edxlocal and edxapp.

### PR DESCRIPTION
**Pull request by benpatterson**
@feanil @singingwolfboy @clytwynec 

As per discussion for getting libjpeg onto jenkins_workers with some refactoring. 

To be tested once you give it a look.

### CODE REVIEW

**Comment by benpatterson** [comment]
Intended as an alternative solution to #1655.

**Comment by feanil** [comment]
@benpatterson  I thought from the e-mail that we would not be pursuing this now.  Did something change or is this just a kickstart of the future work?

**Comment by benpatterson** [comment]
Just a kickstart, @feanil 

I don't think we could implement this right now as it is, because of the testing cost. But I would like to have some discussion on the right overall approach. Let's move discussion to the Jira ticket.

I'll leave this PR open in case we go in this direction, but let's chat first.

**Comment by feanil** [comment]
Cool got it.

**Comment by e0d** [comment]
@benpatterson I think that ultimately, I prefer a convention for specifying OS level requirements in the repo for each project rather than having them managed in ansible because the project is a complete thing without any dependencies on ansible if someone chooses a different configuration management tool.

This does add some additional risk, because dependencies can be added without devops knowing.  Dependencies may conflict between services and we won't know that until later than ideal.  Despite this, I still think I prefer defining them in our projects.  Thoughts?

**Comment by benpatterson** [comment]
@e0d my goal here was to reduce upkeep and duplication. 

I think what you're suggesting merits a longer conversation. This PR can wait for that conversation at this point, before proceeding.

**Comment by benpatterson** [comment]
@e0d could we discuss with @feanil ? 

I'll shoot you guys an e-mail.

**Comment by benpatterson** [comment]
@e0d @feanil @clytwynec after yesterday's discussion I believe we are GTG on this. 

I'll plan to merge later today unless you'd like me to hold back on it.

**Pull request merged**
