### PR TITLE
Support the Ubuntu 14.04 release

### PR DESCRIPTION
**Pull request by stem**
As seen with Feanil, this switches the support from Ubuntu 12.04 to Ubuntu 14.04.

There might be an issue with MITx 6.341x course but I can't pull the course so
I'm not able to test it.
In order to not forget about this course, I've left the ansible commands that
where necessary on Ubuntu 12.04.

Let me know if I can do something else for this PR.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @stem! I've created [OSPR-218](https://openedx.atlassian.net/browse/OSPR-218) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams. 

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ('this must be merged by XX date', and why that is)
- partner information ('this is a course on edx.org')
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the Github pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

We can't start reviewing your pull request until you've submitted a [signed contributor agreement](http://code.edx.org/individual-contributor-agreement.pdf) or indicated your institutional affiliation and added yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS) file. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst) file for more information.

**Comment by sarina** [comment]
Hi @stem -  I'm so sorry for the late attention to your PR. The Open Source team has been super busy planning and hosing last week's [Open edX Con](http://con.openedx.org/). We definitely appreciate your patience with us!

We now have your contributor's agreement, thanks for that!

**Comment by sarina** [comment]
This PR is something we really would like to support though it is not a high priority right now. 

The work you've done is useful as a reference of what changes need to be made though probably not sufficient to just be able to merge it in without further investigation. Given that our DevOps team is short staffed right now, this isn't a change we're going to be able to help you push through and merge at this point in time.

I encourage you to continue to develop this solution in your own fork, and share your work (and perhaps collaborate with others) on the openedx-ops mailing list. If this work gets into a definitely working state and is supporting many users, please feel free open a new PR at a later point in time. Thanks!

**Comment by OmarIthawi** [comment]
I didn't see this PR earlier. We have faced the problem before and solved it (#2517) using feature detection instead of version-based solution. Hopefully this would be more future-proof.

**Pull request closed without merging**
