### PR TITLE
Fix typo from EDXAPP_COURSE_* to EDXAPP_COURSES_*

### PR DESCRIPTION
**Pull request by smaeda-ks**
Because see below.
https://github.com/edx/configuration/blob/master/playbooks/roles/nginx/templates/edx/app/nginx/sites-available/lms.j2#L16

Using "EDXAPP_COURSES_REQUEST_RATE" but it is not defined below.
https://github.com/edx/configuration/blob/master/playbooks/roles/edxapp/defaults/main.yml#L229-L230

```
EDXAPP_COURSE_REQUEST_RATE: '5r/s'
EDXAPP_COURSE_REQUEST_BURST_RATE: 10
```

I think it is typo.
And "EDXAPP_COURSES_*" is better than "EDXAPP_COURSE_*" as a variable name of this case.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @smaeda-ks! I've created [OSPR-1221](https://openedx.atlassian.net/browse/OSPR-1221) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by nedbat** [comment]
@edx/devops this seems like a quick one.

**Comment by feanil** [comment]
:+1:   @edx/devops I verified that this is not being overridden by us anywhere so no corresponding change is needed in our secure config. 

@smaeda-ks can you please add an entry to the CHANGELOG as well so people can see that this is a backwards incompatible change.

**Comment by nedbat** [comment]
We now have @smaeda-ks's contributor agreement.

**Comment by jibsheet** [comment]
:+1: now that I've looked in the secure config also.

**Comment by smaeda-ks** [comment]
@feanil Thanks. I will add entry.

**Pull request merged**
