### PR TITLE
[Ansible 2.x ] use the get_url and unarchive module instead of curl and tar

### PR DESCRIPTION
**Pull request by arbabnazar**
@edx/devops @e0d please review and will be merged once we'll migrate to Ansible 2.x. Thanks

### CODE REVIEW

**Comment by arbabnazar** [comment]
@edx/devops is it OK to merge as you have migrated to `Ansible 2.x`. Thanks

**Comment by jibsheet** [comment]
@arbabnazar I'd like to build a devstack and test ecom before we merge.
@gsong How do we trigger the OSPR bot for this change?  I'd like to schedule a little time to review and merge this, since the download fails often enough that having a retry would be nice.

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @arbabnazar! I've created [OSPR-1773](https://openedx.atlassian.net/browse/OSPR-1773) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by gsong** [comment]
@jibsheet Any updates on this PR?

**Review by coryleeio — APPROVED** [review]

**Comment by coryleeio** [comment]
I was able to run this locally in a docker container and verified that the role ran successfully and that the JVM was installed.

**Comment by feanil** [comment]
@coryleeio you confirm that  the new JVM was set as the default jvm as well?

**Comment by coryleeio** [comment]
It does appear to be set, yes.

**Comment by coryleeio** [comment]
update-alternatives --config java
There is 1 choice for the alternative java (providing /usr/bin/java).

     Selection    Path                                Priority   Status
      0            /usr/lib/jvm/jdk1.8.0_131/bin/java   50        auto mode
    * 1            /usr/lib/jvm/jdk1.8.0_131/bin/java   50        manual mode

cat /etc/profile.d/java.sh
export JAVA_HOME="/usr/lib/jvm/java-8-oracle"
export PATH=$JAVA_HOME/bin:$PATH
 
java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Review by feanil — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@arbabnazar 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/3237&entry.1484655318=https://github.com/arbabnazar&entry.752974735=2016-07-08+20:25&entry.1917517419=2017-11-02+13:20&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
