### PR TITLE
Adds ANALYTICS_API_AGGREGATE_PAGE_SIZE, default value 10

### PR DESCRIPTION
**Pull request by pomegranited**
Adds a new `ANALYTICS_API_AGGREGATE_PAGE_SIZE` variable, with default value `10`.

**JIRA tickets**: [OSPR-1695](https://openedx.atlassian.net/browse/OSPR-1695)

**Discussions**: Please see https://github.com/edx/edx-analytics-data-api/pull/162#issuecomment-284547729

**Partner information**: 3rd party-hosted open edX instance

**Deployment targets**: insights.edx.org and insights.edge.edx.org

**Merge deadline**: 31 Mar 2017 if possible.  We'd like to deploy this change when upgrading our clients to Ficus.

**Testing instructions**:

1. Create an [analytics devstack](http://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/installation/analytics/install_analytics.html), using this branch as your `configuration_version`
1. Ensure that the new `ANALYTICS_API_AGGREGATE_PAGE_SIZE: 10` shows up in your `/edx/etc/analytics_api.yml` file.

**Author notes and concerns**:

1. The [elasticsearch_dsl aggregate search results defaults to 10](https://github.com/elastic/elasticsearch-dsl-py/blob/1a9092429ac582c0cf33f8d6287a20266be063cd/elasticsearch_dsl/search.py#L261), so that's why we're using `10` as the default.  But would be fine with anything you think is reasonable.

**Reviewers**
- [x] @bdero 
- [x] @edx/devops reviewers

Configuration Pull Request
---

Make sure that the following steps are done before merging

  - [x] A devops team member has commented with :+1:
  - [-] are you adding any new default values that need to be overridden when this goes live? No.
    - [-] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [x] Add an entry to the CHANGELOG.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pomegranited! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fconfiguration&number=3738"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Comment by pomegranited** [comment]
@gsong This is the configuration PR related to https://github.com/edx/edx-analytics-data-api/pull/162#issuecomment-284547729.

Is it ok if I piggyback on that issue's [OSPR-1695](https://openedx.atlassian.net/browse/OSPR-1695)?

**Comment by bdero** [comment]
This looks good! Only one thing: Can you please add an entry to the top of the [changelog](https://github.com/edx/configuration/blob/master/CHANGELOG.md) for the new setting?

:+1:

Here's what I did in a nutshell:
```
# Prepare the configuration repo
sudo -Hu edx-ansible bash
cd /edx/app/edx_ansible/edx_ansible/playbooks
export PYTHONUNBUFFERED=1
source /edx/app/edx_ansible/venvs/edx_ansible/bin/activate
git remote set-url origin https://github.com/open-craft/configuration.git
git checkout jill/analytics_api_aggregate_page_size
pip install -r ../requirements.txt
exit

# Run the analytics_api role as the vagrant user
cd /edx/app/edx_ansible/edx_ansible/playbooks
export PYTHONUNBUFFERED=1
source /edx/app/edx_ansible/venvs/edx_ansible/bin/activate
ansible-playbook -i localhost, -c local run_role.yml -e role=analytics_api -e configuration_version=jill/analytics_api_aggregate_page_size
```

Result:
```
$ grep AGGREGATE /edx/etc/analytics_api.yml
AGGREGATE_PAGE_SIZE: 10
```

- [x] I tested this: I ran the `analytics_api` role with this PR's configuration branch, and I confirmed that `AGGREGATE_PAGE_SIZE` is being set in `/edx/etc/analytics_api.yml`.
- [x] I read through the code
- [ ] ~I checked for accessibility issues~ N/A.
- [ ] Includes documentation (awaiting changelog entry)

**Comment by pomegranited** [comment]
Thanks, @bdero !  Added a [CHANGELOG entry](https://github.com/open-craft/configuration/blob/90357ea305aa233691ae0caa8b838fb1ee4895e0/CHANGELOG.md).

@edx/devops This is now ready for your review.

**Review by feanil — APPROVED** [review]
@edx/devops second review.

**Review by jibsheet — APPROVED** [review]
Found the PR, looks fine.

**Comment by pomegranited** [comment]
Thanks @feanil and @jibsheet !  Merging now.

**Pull request merged**
