### PR TITLE
turn off logging for ec2 facts

### PR DESCRIPTION
**Pull request by estute**
## Configuration Pull Request

Make sure that the following steps are done before merging
- [ ] @devops team member has commented with :+1:
- [ ] are you adding any new default values that need to be overriden when this goes live?  
  - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
  - [ ] Add an entry to the CHANGELOG.

### CODE REVIEW

**Review by jibsheet — APPROVED** [review]
Just curious which fact was too hot for the logs?
But is totally fine (although you will loathe this some day when debugging).

**Comment by estute** [comment]
@jzoldak @benpatterson

**Comment by jzoldak** [comment]
👍

**Comment by estute** [comment]
For posterity's sake, the ec2_facts action logs aws credentials and such, which is not a good idea.

**Pull request merged**
