### PR TITLE
SE-126 Adds optional lms celery beat supervisor process

### PR DESCRIPTION
**Pull request by pomegranited**
Enabled when EDXAPP_ENABLE_CELERY_BEAT is set (off by default).

**JIRA tickets**: SE-126, [OSPR-2980](https://openedx.atlassian.net/browse/OSPR-2980)

**Discussions**: See https://github.com/edx/edx-platform/pull/19047

**Dependencies**: Related to https://github.com/edx/edx-platform/pull/19047

**Sandbox URL**: See https://github.com/edx/edx-platform/pull/19047

This sandbox was configured with this PR's branch.

**Merge deadline**: Would like to get this merged before Ironwood if possible.

**Testing instructions**:

See https://github.com/edx/edx-platform/pull/19047

**Author Notes & Concerns**:

1. I chose to run the celery beat process only on the `lms` service, to ensure that there aren't multiple processes pulling periodic tasks out of the database and stepping on each other.
   Note sure if this was correct.

**Reviewers**

- [ ] @clemente 
- [ ] edX DevOps ?

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pomegranited! I've created [OSPR-2980](https://openedx.atlassian.net/browse/OSPR-2980) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@pomegranited Thank you for your contribution. Please let me know once it is ready to be looked at.

**Comment by pomegranited** [comment]
This approach does not work if there are two identically-configured VMs, which is a critical part of our use case.  So I'm closing this PR.

**Comment by openedx-webhooks** [comment]
@pomegranited Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4946&entry.1484655318=https://github.com/pomegranited&entry.752974735=2019-01-15+04:46&entry.1917517419=2019-01-22+06:23&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
