### PR TITLE
add DEFAULT_COURSE_VISIBILITY_IN_CATALOG

### PR DESCRIPTION
**Pull request by jagonzalr**
[OSPR-1952](https://openedx.atlassian.net/browse/OSPR-1952)

Configuration Pull Request
---

Adds the default value for course visibility in catalog using this var ```EDXAPP_DEFAULT_COURSE_VISIBILITY_IN_CATALOG```

This PR is related to this [PR](https://github.com/edx/edx-platform/pull/16191)

Reviewers
- Code review: ¯_(ツ)_/¯

cc @gsong @nedbat

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @jagonzalr! I've created [OSPR-1952](https://openedx.atlassian.net/browse/OSPR-1952) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Review by pomegranited — APPROVED** [review]
@jagonzalr  :+1: once added to [CHANGELOG.md](https://github.com/edx/configuration/blob/master/CHANGELOG.md)

- [x] I tested this by spinning up a sandbox instance with `EDXAPP_DEFAULT_COURSE_VISIBILITY_IN_CATALOG: "none"`, and verifying that this setting was propagated through to the `/edx/app/edxapp/*.env.json` files.
- [x] I read through the code
- [x] I checked for accessibility issues
- [ ] Includes documentation - Need to add this new setting to the [CHANGELOG.md](https://github.com/edx/configuration/blob/master/CHANGELOG.md)

**Comment by jagonzalr** [comment]
@pomegranited fixed the conflicts and updated the CHANGELOG.md

**Comment by pomegranited** [comment]
Thanks @jagonzalr !  Looks good 👍

**Comment by pomegranited** [comment]
@edx/devops  This is ready for edX review cc @nedbat

**Comment by pomegranited** [comment]
@nedbat  Could you please ping devops for us?  Looks like I can't do that anymore 😦

**Comment by jagonzalr** [comment]
@nedbat the related [PR](https://github.com/edx/edx-platform/pull/16191) has been merged. Can anyone review this one?

**Comment by nedbat** [comment]
@edx/devops This is ready for review, and should be uncontroversial.

**Review by feanil — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@jagonzalr 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4138&entry.1484655318=https://github.com/jagonzalr&entry.752974735=2017-10-09+10:01&entry.1917517419=2018-03-20+20:54&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by pomegranited** [comment]
Thank you @feanil !

**Pull request merged**
