### PR TITLE
Use ansible core module ec2_ami

### PR DESCRIPTION
**Pull request by nadeemshahzad**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

### CODE REVIEW

**Comment by nadeemshahzad** [comment]
@edx/devops Please review. After upgrade boto to latest version build_ami job completed with success.

**Comment by feanil** [comment]
@nadeemshahzad can you link to the GoCD job that you ran the test on?

**Comment by nadeemshahzad** [comment]
@feanil https://gocd.tools.edx.org/go/pipelines/value_stream_map/loadtest-ecommerce/21

**Comment by feanil** [comment]
@nadeemshahzad I'm looking at the materials for that pipeline and it looks like it did not run with your changes on it.  Did you push your changes to the `loadtest-ecommerce` branch before you kicked off the pipeline?

**Comment by nadeemshahzad** [comment]
@feanil I run pipline with my branch 'nadeem/Upgrade-ec2_ami' and changed back to 'loadtest-ecommerce' after job done. Please let me know if I need to test pushing changes to loadtest-ecommerce.

**Comment by feanil** [comment]
Right but I don't think that worked correctly, because the version of Configuration for the run you pointed me to seems to be incorrect.  Just force push your changes onto the 'loadtest-ecommerce' branch of configuration and re-run that pipeline.

**Comment by nadeemshahzad** [comment]
@feanil Can you please look the job now https://gocd.tools.edx.org/go/pipelines/value_stream_map/loadtest-ecommerce/23. I have trigger the pipeline after pushing my changes to ```loadtest-ecommerce``` branch.

**Review by feanil — APPROVED** [review]
Confirmed that this was run in GoCD.  @nadeemshahzad please squash your commits and then I think this is good to go.

**Pull request merged**
