### PR TITLE
Added resolvconf

### PR DESCRIPTION
**Pull request by bdero**
Configuration Pull Request
---

Related to #3872: This PR adds resolvconf to the common package lists separately.

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @bdero! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?number=4116&repo=edx%2Fconfiguration"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @bdero! I've created [OSPR-1932](https://openedx.atlassian.net/browse/OSPR-1932) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Review by feanil — APPROVED** [review]

**Comment by feanil** [comment]
It looks like this is failing for the same reason as the other PR is that right @bdero ?

**Comment by bdero** [comment]
@feanil Yup, it's [the bug](https://github.com/edx/configuration/pull/3872#issuecomment-332042123). Should I wait until a new image is pushed, or will that happen after merging automatically?

**Comment by feanil** [comment]
I'll build a new image from this PR and push it up than we should be able to re-run the tests.

**Comment by bdero** [comment]
@feanil  :+1:

**Comment by feanil** [comment]
I pushed up a new image and have restarted the tests.

**Comment by feanil** [comment]
Hmm, still failing.  There is a newer version of ansible since the last time we had an issue internally.  I'm gonna try to see if that fixes the bug in our image building.  If it does we can just go with that.

**Comment by bdero** [comment]
@feanil Hmm that's too bad. Let me know how it goes, or if there's any way I can help on my side.

**Comment by nedbat** [comment]
What's the latest status on this PR?

**Comment by feanil** [comment]
@nedbat it's on hold right now as we try to get some of our internal ducks in a row.  We're trying to move away from the last tool that is preventing us from moving forward with the ansible upgarde.  Once the ansible upgrade goes through, we can move forward on this again.

**Comment by nedbat** [comment]
@feanil @bdero Any news on this? (sorry for the duplicate ping)

**Comment by mduboseedx** [comment]
@feanil @bdero Any update on this PR?

**Comment by smarnach** [comment]
@mduboseedx Brandon has left OpenCraft, and I will be taking care of this PR.  However, as far as I can tell, there is nothing we can do on our end at the moment.

**Comment by openedx-webhooks** [comment]
@bdero Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4116&entry.1484655318=https://github.com/bdero&entry.752974735=2017-09-28+17:20&entry.1917517419=2018-04-23+15:03&entry.2133058324=No) so we can improve your experience in the future.

**Comment by mduboseedx** [comment]
@feanil Have you had a chance to take another look at this?

**Comment by smarnach** [comment]
@mduboseedx Do you have any suggestion how to move this forward?  I can't think of many things we can do on our end, but we would appreciate if we could get this merged at some point.  This PR blocks #3872.

**Comment by antoviaque** [comment]
@mduboseedx @feanil This PR and https://github.com/edx/configuration/pull/3872 have been open for more than a year now (actually 1.5 year for https://github.com/edx/configuration/pull/3872 ) - can we figure out a way to complete the work here? What is blocking, and can we help unblocking it?

**Comment by mduboseedx** [comment]
@antoviaque I believe we are still unable to do the ansible upgrade which is required in order to merge this change. @edx/devops @feanil Is there anything we or OpenCraft can do to help push this along?

**Comment by natabene** [comment]
@feanil  is fine with this change, just waiting for the ansible upgrade. I will update once things start moving.

**Comment by smarnach** [comment]
@natabene Thanks for letting us know! If there is anything we can do to help, just ping us!

**Comment by antoviaque** [comment]
@mduboseedx @natabene @feanil Thank you for the update : )

**Comment by SSPJ** [comment]
@mduboseedx @natabene I have taken over this ticket from Sven, is there any update on the Ansible issue?

**Comment by natabene** [comment]
@SSPJ I don't think so, but let me check and post here in a couple of days.

**Comment by SSPJ** [comment]
@natabene Thanks for checking!

**Comment by natabene** [comment]
@sspj Not done yet, but don't lose hope.

**Comment by SSPJ** [comment]
@natabene Can I get another status update on this one?

**Comment by natabene** [comment]
@SSPJ I checked, and we have not competed ansible upgrade yet.

**Comment by SSPJ** [comment]
@natabene Thanks for checking. I'll ping again later.

**Comment by natabene** [comment]
@SSPJ Great news, ansible upgrade is finished. Can you rebase to master, kick off test again, and look into the Travis CI if it fails, before we review again and merge this?

**Comment by SSPJ** [comment]
@natabene Absolutely, thanks for letting me know! I'll aim to get this ready for review in the next three weeks.

**Comment by edx-webhook** [comment]
Thanks for the pull request, @bdero! I've created [OSPR-3502](https://openedx.atlassian.net/browse/OSPR-3502) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@SSPJ Are you still interested in this or should we close this PR?

**Comment by SSPJ** [comment]
@natabene Thanks for checking in! I have been trying, unsuccessfully, to find time for this for the past several months. I would like to get this merged, so I will ask around OpenCraft if we can find another assignee. If you don't hear anything in the next two weeks, I would say safe to close it, yes.

Thanks for pushing this forward on your end; I appreciated it.

**Review by fredsmith — APPROVED** [review]

**Comment by samuelallan72** [comment]
Note: this breaks devstack provisioning. See https://discuss.openedx.org/t/ironwood-master-devstack-installation-fails/924/2

The [travis tests](https://github.com/edx/configuration/runs/321497386) were alse failing, so I'm not sure why this was merged. :thinking: 

CC @fredsmith

**Comment by samuelallan72** [comment]
@fredsmith #5543 opened to revert this.

**Pull request merged**
