### PR TITLE
fix: add CELERY_RESULT_BACKEND with default django-cache

### PR DESCRIPTION
**Pull request by navinkarkera**
Configuration Pull Request
---

**Cherry pick of** https://github.com/openedx/configuration/pull/6720

Note: This PR has a corresponding edx-platform PR https://github.com/openedx/edx-platform/pull/30245

## Description

At Opencraft, we want to run multiple instances of celery workers in separate servers. The celery workers need to be able to share task results. Currently, the `CELERY_RESULT_BACKEND` is hard coded to use `django-cache`.

So this PR allows to setup `CELERY_RESULT_BACKEND` via configuration.

To use django ORM as celery backend, one can set `CELERY_RESULT_BACKEND` to `django-db` as described in [docs](https://docs.celeryq.dev/en/stable/django/first-steps-with-django.html#django-celery-results-using-the-django-orm-cache-as-a-result-backend).

## Supporting information

- Task: https://tasks.opencraft.com/browse/BB-6077

## Deadline

"None"

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @navinkarkera! I've created [OSPR-6622](https://openedx.atlassian.net/browse/OSPR-6622) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@navinkarkera Thank you for the contribution. Is this ready for our review?

**Comment by kaustavb12** [comment]
Hi @natabene !

This is not  ready for your review yet. I'll ping you here once ready.

**Comment by natabene** [comment]
@navinkarkera Just checking if this is ready.

**Comment by kaustavb12** [comment]
@natabene We have scheduled to review and test this internally in the ongoing sprint. Will ping here once ready. Perhaps early next week.

**Comment by kaustavb12** [comment]
:+1:

Looks good to go from my end.

- [X] I tested this: Changes tested in the PR sandbox
- [X] I read through the code
- [X] Includes documentation

**Comment by navinkarkera** [comment]
@natabene This is ready for your review.

**Comment by natabene** [comment]
@navinkarkera Thanks, I am lining this up for our review.

**Comment by natabene** [comment]
@BbrSofiane This is ready for your review.

**Review by OmarIthawi — APPROVED** [review]

**Comment by OmarIthawi** [comment]
@navinkarkera This is on `lilac` but the [other PR](https://github.com/openedx/edx-platform/pull/30572) is on `nutmeg` did I miss anything?

**Comment by navinkarkera** [comment]
> @navinkarkera This is on `lilac` but the [other PR](https://github.com/openedx/edx-platform/pull/30572) is on `nutmeg` did I miss anything?

@OmarIthawi We also have one for [lilac](https://github.com/openedx/edx-platform/pull/30245)

**Review by jfavellar90 — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@navinkarkera 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/configuration&entry.867055334=https://github.com/openedx/configuration/pull/6721&entry.1484655318=https://github.com/navinkarkera&entry.752974735=2022-04-14+09:15&entry.1917517419=2022-07-28+15:35&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
