### PR TITLE
enable insights to be deployed via ansible-provision

### PR DESCRIPTION
**Pull request by fredsmith**

### CODE REVIEW

**Comment by clintonb** [comment]
:+1:

**Comment by feanil** [comment]
:+1:   Is this sufficient to run insights on sandbox?

**Comment by fredsmith** [comment]
@feanil I have another PR against sandbox-secure that I'm working on.  any other concerns?

**Comment by feanil** [comment]
If we don't update the base sandbox play, the default sandbox won't have insights by default.

https://github.com/edx/configuration/blob/master/playbooks/edx_sandbox.yml

**Comment by fredsmith** [comment]
ah, I thought https://github.com/edx/configuration/blob/master/util/jenkins/ansible-provision.sh#L244 would deploy it, but that's only if $reconfigure != "true".

**Pull request closed without merging**
