### PR TITLE
Revert "Merge pull request #4023 from edx/revert-4022-revert-3974-asa…

### PR DESCRIPTION
**Pull request by cpennington**
…diqbal08/ENT-322"

This reverts commit 889073f6fa7cefe0082c93c41d5e304b6a762205, reversing
changes made to 9730dd345e2b5b6918feb3fb0b7b8db3b35e9da6.

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

### CODE REVIEW

**Comment by cpennington** [comment]
@douglashall: FYI. This broke my hotfix

**Review by jibsheet — APPROVED** [review]

**Comment by jibsheet** [comment]
@douglashall it sounded like you made manual changes to these users to make them match.  I wonder if app-permissions is also in play here?  You should check what is changing the user to make them mismatch and fail.

**Comment by douglashall** [comment]
@cpennington @jibsheet Can you hold off on merging this? I have updated the enterprise_worker email address on stage and I am crafting an app-permissions PR now.

**Comment by douglashall** [comment]
app-permissions PR for adding enterprise_worker user: https://github.com/edx/app-permissions/pull/423

**Comment by feanil** [comment]
@douglashall if you are adding it there, it means that it wasn't there already, so app-permissions couldn't have caused the breakage.  This might suggest that something else is in play causing your code to fail.

**Comment by douglashall** [comment]
@feanil The issue is that during my debugging of the first revert, I manually changed the enterprise_worker email address using Django admin on stage, and I forgot to change it back. I have again manually updated the email address in stage Django admin to be the correct `enterprise+enterprise_worker@edx.org` email address and filed the app-permission PR above to keep that email in place.

**Comment by feanil** [comment]
app-permission uses the same management command that you use here so that PR doesn't help.  I think the important thing here is that you stop manually making changes to this user, it is now a part of production, if you need to test, use different users.

**Comment by douglashall** [comment]
@feanil Cool. Should I close that app-permissions PR then?

**Comment by feanil** [comment]
@douglashall  Yes.

@cpennington if the user has been corrected, you should be able to re-run the pipeline and it should go through.  If that works, we can close this PR as well.

**Comment by cpennington** [comment]
Ok, we'll see what happens when I re-start the regular release process.

**Pull request closed without merging**
