### PR TITLE
fixing perm issue with npm registry

### PR DESCRIPTION
**Pull request by jarv**

### CODE REVIEW

**Comment by feanil** [comment]
:+1:

**Comment by benpatterson** [comment]
@jarv @feanil @hkim823 I don't suppose this was tested on devstack? (or, for that matter, #1285 ?)

I'm having issues provisioning a functional jenkins_worker play...running into the same npm chown issue.

CC @jzoldak

**Comment by hkim823** [comment]
No these were testing to make sure edx-platform can be built basically, which is where we were seeing the errors.  Can you show us the error you are running into?  Try update your configuration branch to master before running the jenkins_worker play

**Comment by benpatterson** [comment]
@hkim823 You can see some info on this over on this PR: https://github.com/edx/edx-platform/pull/4828; however we're considering other options for fixing the issue since that solution is still going to have errors the user sees.

**Pull request merged**
