### PR TITLE
[BB-6458] Fix tasks that create django users for IDAs; nutmeg backport

### PR DESCRIPTION
**Pull request by Cup0fCoffee**
Nutmeg backport of #6783

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Cup0fCoffee!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by kaustavb12 — APPROVED** [review]
:+1:

- [X] I tested this: Verified sandbox instances successfully deployed
- [X] I read through the code

**Comment by natabene** [comment]
@Cup0fCoffee Thank you for your contribution. Is this ready for a review?

**Comment by Cup0fCoffee** [comment]
> @Cup0fCoffee Thank you for your contribution. Is this ready for a review?

@natabene Yes, this PR is ready for the review. I hope it's ok that this PR's description is just referencing another PR, since it's exactly the same, just the target branch/version is different.
Let me know if I should change it.

**Comment by natabene** [comment]
@Cup0fCoffee Thank you for letting me know, it is fine.

**Review by nadeemshahzad — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@Cup0fCoffee 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/configuration&entry.867055334=https://github.com/openedx/configuration/pull/6784&entry.1484655318=https://github.com/Cup0fCoffee&entry.752974735=2022-07-11+22:21&entry.1917517419=2022-08-01+10:19&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
