### PR TITLE
use debian s3cmd package everywhere

### PR DESCRIPTION
**Pull request by fredsmith**

### CODE REVIEW

**Comment by nedbat** [comment]
@fredsmith Thanks.  We think this fixes the same problem as https://github.com/edx/configuration/pull/5652 ?

**Comment by fredsmith** [comment]
@nedbat both are useful independently and together.  I want to keep both changes, although I think either of them would have fixed the problem.

**Comment by nedbat** [comment]
@fredsmith help me out: here's the state I want to get to: 1) we think the problem is fixed, and 2) the problem is fixed the same way on both master and open-release/juniper.alpha1.

We have three options:
1. Merge this PR onto master, cherry-pick it onto juniper.alpha1, and revert #5652.
2. Merge this PR onto master, cherry-pick it onto juniper.alpha1, and also cherry-pick #5652 onto master.
3. Close this PR, and cherry-pick #5652 onto master.

Which do you recommend?

**Review by jdmulloy — APPROVED** [review]

**Comment by nedbat** [comment]
@fredsmith Do you have a recommendation?

**Comment by fredsmith** [comment]
@nedbat I would cherry pick both fixes.

**Comment by nedbat** [comment]
I've cherry-picked this PR onto open-release/juniper.alpha1

**Pull request merged**
