### PR TITLE
WIP: Make EDXAPP_ENV_EXTRA and EDXAPP_AUTH_EXTRA be included in LMS and CMS env files together with the specific settings

### PR DESCRIPTION
**Pull request by clemente**
**Work in progress**. Do not merge yet. We'll ping when it goes through our internal review.

We found that when passing `EDXAPP_ENV_EXTRA` and `EDXAPP_LMS_ENV_EXTRA` together, settings from `EDXAPP_ENV_EXTRA` were discarded and only the ones from `EDXAPP_LMS_ENV_EXTRA` entered into `lms.env.json`.

We find it more useful if `EDXAPP_ENV_EXTRA` holds the common settings (LMS+CMS), and `EDXAPP_LMS_ENV_EXTRA` the LMS-specific ones, and then they are combined when creating `lms.env.json`.
This PR does that, and does the same for `EDXAPP_CMS_ENV_EXTRA`, and for the `….auth.json` files: `EDXAPP_AUTH_EXTRA`, `EDXAPP_LMS_AUTH_EXTRA`, `EDXAPP_CMS_AUTH_EXTRA`.

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

**Testing instructions**

TODO provide clearer steps and exact syntax.

Roughly:
1. Run the playbook with these variables: `EDXAPP_ENV_EXTRA` set to `{A: 1, B: 2}`, and `EDXAPP_LMS_ENV_EXTRA` to `{B: 22, C: 3}`.
2. The resulting `lms.env.json` should hold: `A: 1, B: 22, C: 3`. Before this patch, it would have been `B: 22, C: 3`.

**Reviewers**
- [ ] @pomegranited 
- [ ] edX

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @clemente! I've created [OSPR-2798](https://openedx.atlassian.net/browse/OSPR-2798) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by pomegranited** [comment]
@clemente As mentioned on the ticket, I don't think this PR is necessary, we just need to use the existing variables as they were intended.  Ok to close this.

**Comment by natabene** [comment]
@clemente  @pomegranited  Please let me know if you change your mind and want us to look at it.

**Comment by clemente** [comment]
@clemente @pomegranited 
Right, in the end we went for the simple solution: passing only one variable, instead of both at the same time. We can close this PR and reopen if we ever need the more complex approach.

**Comment by openedx-webhooks** [comment]
@clemente Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4874&entry.1484655318=https://github.com/clemente&entry.752974735=2018-11-14+03:26&entry.1917517419=2018-11-15+16:24&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
