### PR TITLE
ENH: performance enhancements

### PR DESCRIPTION
**Pull request by nicovanniekerk**
This PR contains the following changes:
Moving lms and cms from communicating over ports to web sockets.
OS tweaks to allow for more concurrent connections as well as allows the www-data web user to be able to open a large limit of files, to allow for 1000s of connections over the web sockets.
Minor changes to the Gunicorn processes, adding the jitter setting to stagger restart of idle processes, as well as preloading the application to allow for a master slave process spawning.
Some minor vars added to make number of processes configurable for nginX.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @nicovanniekerk! I've created [OSPR-2537](https://openedx.atlassian.net/browse/OSPR-2537) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by mduboseedx** [comment]
@edx/devops Could you give this a look?

**Comment by feanil** [comment]
Hello,  thanks for the contribution but this is a lot of different changes to performance that we don't have time to test and not sure about the full benefits of the changes.  At this point, we're not going to be accepting the change.

**Comment by openedx-webhooks** [comment]
@nicovanniekerk Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4711&entry.1484655318=https://github.com/nicovanniekerk&entry.752974735=2018-07-27+09:02&entry.1917517419=2018-12-10+15:42&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
