### PR TITLE
Add task to store OAuth credentials

### PR DESCRIPTION
**Pull request by mrgnr**
This PR adds a task to add OAuth credentials to the database. Previously, credentials had to be [added manually](https://openedx.atlassian.net/wiki/pages/viewpage.action?spaceKey=AN&title=Configuring+Insights+for+Open+ID+Connect+SSO+with+LMS) for services like Insights.

This adds the `EDXAPP_OAUTH_CREDENTIALS` variable, which is a list of hashes where each hash represents a set of OAuth credentials. The keys in each hash correspond to parameters passed to the `create_oauth2_client` management command.

Example to add credentials for Insights:
```
EDXAPP_OAUTH_CREDENTIALS:
  - url: "{{ INSIGHTS_BASE_URL }}"
    redirect_uri: "{{ INSIGHTS_BASE_URL }}/complete/edx-oid/"
    client_type: "confidential"
    client_name: "insights"
    client_id: "{{ INSIGHTS_OAUTH2_KEY }}"
    client_secret: "{{ INSIGHTS_OAUTH2_SECRET }}"
```

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mrgnr! I've created [OSPR-1726](https://openedx.atlassian.net/browse/OSPR-1726) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by gsong** [comment]
@edx/devops Ping. @mrgnr You might want to consider documenting the param, it's not clear what the format of the list is unless you look at the role.

**Comment by feanil** [comment]
@clintonb thoughts on this? I think you have some common oauth stuff you have been adding via the IDAs and I want to make sure we're not repeating things or doing things in multiple different ways.  Can you please take a look.

**Comment by clintonb** [comment]
We have a role for this: https://github.com/edx/configuration/blob/2094cef01817b54315f95323dffd1da4a8ec5dc9/playbooks/roles/oauth_client_setup/tasks/main.yml. We use it in playbooks for CI (and Vagrant, I think): https://github.com/edx/configuration/blob/2cda75a61d567cb307d71c786cbd87e0c3e78132/playbooks/edx-east/edx_continuous_integration.yml#L41.

I'm not opposed to this addition, but I think a custom playbook is a potentially better solution.

**Comment by gsong** [comment]
@feanil and @clintonb Are we saying no to this PR? Should I close it out?

**Comment by clintonb** [comment]
@gsong I'm not saying no, but wondering if this is needed because our existing role is lacking in some manner.

**Comment by gsong** [comment]
@mrgnr Are you still interested in this PR given the comments above?

**Comment by gsong** [comment]
@mrgnr I'm going to close this PR for now. Feel free to re-open or open a new PR if/when you're ready to pick this back up.

**Pull request closed without merging**
