### PR TITLE
Upgrade tools jenkins and plugins

### PR DESCRIPTION
**Pull request by jibsheet**
Remove plugins I don't believe are in use, or planned to be in use.
We can add back as needed.

### CODE REVIEW

**Comment by feanil** [comment]
Generally looks good, One question, Is the jobdsl plugin not installed via this mechanism?

**Comment by jibsheet** [comment]
Fascinating question - I wonder what else was set up manually.  I'll investigate.

**Comment by feanil** [comment]
:+1:

**Comment by jibsheet** [comment]
@fredsmith @feanil Updates based on running (and re-running) the job.

**Comment by fredsmith** [comment]
👍

**Pull request merged**
