### PR TITLE
check before installing rabbit

### PR DESCRIPTION
**Pull request by jarv**

### CODE REVIEW

**Comment by feanil** [comment]
won't this break our ability to do upgrades?

**Comment by feanil** [comment]
How about doing the install when there is a change to the get_url task to download the deb file?

**Comment by jarv** [comment]
I don't this it's really safe to upgrade in a cluster scenario without some thought put into it since upgrading will prevent the node from joining the cluster

**Comment by jarv** [comment]
> How about doing the install when there is a change to the get_url task to download the deb file?

Will break the base AMI unfortunately since rabbit is installed but doesn't have the deb file on disk yet

**Comment by feanil** [comment]
I thought we were always using base ubuntu for the common cluster?

**Comment by jarv** [comment]
we are, the breakage is happening in the single instance sandbox case that uses the release AMI

**Comment by feanil** [comment]
:+1:

**Pull request merged**
