### PR TITLE
fix mismatch between retirement service worker username configs

### PR DESCRIPTION
**Pull request by fredsmith**

### CODE REVIEW

**Comment by samuelallan72** [comment]
@fredsmith If you're going to rename the vars this way, then you'll probably want to rename this one too:

https://github.com/edx/configuration/blob/4020a8bfa09efc1a51c556f5c74044bc22c26bd2/playbooks/roles/edxapp/defaults/main.yml#L1432

And also check the usages of `RETIREMENT_SERVICE_WORKER_USERNAME` elsewhere across the codebases:

```
edx-documentation/en_us/install_operations/source/configuration/user_retire/service_setup.rst:   * - RETIREMENT_SERVICE_WORKER_USERNAME
edx-documentation/en_us/install_operations/source/configuration/user_retire/service_setup.rst:   RETIREMENT_SERVICE_WORKER_USERNAME = 'retirement_service_worker'
edx-documentation/en_us/install_operations/source/configuration/user_retire/service_setup.rst:that is done by specifying the ``RETIREMENT_SERVICE_WORKER_USERNAME`` variable
edx-platform/cms/envs/common.py:RETIREMENT_SERVICE_WORKER_USERNAME = 'RETIREMENT_SERVICE_USER'
edx-platform/cms/envs/production.py:    'RETIREMENT_SERVICE_WORKER_USERNAME',
edx-platform/cms/envs/production.py:    RETIREMENT_SERVICE_WORKER_USERNAME
edx-platform/cms/envs/production.py:RETIREMENT_SERVICE_WORKER_USERNAME = ENV_TOKENS.get(
edx-platform/cms/envs/studio.yml:RETIREMENT_SERVICE_WORKER_USERNAME: retirement_worker
edx-platform/lms/djangoapps/discussion/rest_api/views.py:        A superuser or the user with the settings.RETIREMENT_SERVICE_WORKER_USERNAME
edx-platform/lms/djangoapps/edxnotes/views.py:        A superuser or the user with the username specified by settings.RETIREMENT_SERVICE_WORKER_USERNAME can "retire"
edx-platform/lms/envs/common.py:RETIREMENT_SERVICE_WORKER_USERNAME = 'RETIREMENT_SERVICE_USER'
edx-platform/lms/envs/lms.yml:RETIREMENT_SERVICE_WORKER_USERNAME: retirement_worker
edx-platform/lms/envs/production.py:    'RETIREMENT_SERVICE_WORKER_USERNAME',
edx-platform/lms/envs/production.py:    RETIREMENT_SERVICE_WORKER_USERNAME
edx-platform/lms/envs/production.py:RETIREMENT_SERVICE_WORKER_USERNAME = ENV_TOKENS.get(
edx-platform/openedx/core/djangoapps/user_api/accounts/tests/test_permissions.py:        with self.settings(RETIREMENT_SERVICE_WORKER_USERNAME=user.username):
edx-platform/openedx/core/djangoapps/user_api/rules.py:        user.username == settings.RETIREMENT_SERVICE_WORKER_USERNAME or
edx-platform/openedx/tests/settings.py:RETIREMENT_SERVICE_WORKER_USERNAME = 'RETIREMENT_SERVICE_USER'
```

...

Alternatively, we may just have to accept that we have two different variables for the same thing, ensure they keep in sync, and update the docs accordingly...?

**Review by jdmulloy — APPROVED** [review]

**Comment by fredsmith** [comment]
@swalladge one is the edx-platform/python variable, one is the ansible variable.  This is how almost all our ansible config works - one variable for sysadmins to tweak, ansible then sets the python variable that the app reads.  They're not usually consistently named because the two projects have different developers and naming conventions.

**Comment by samuelallan72** [comment]
@fredsmith Ok, that's fair. So it's `EDXAPP_RETIREMENT_SERVICE_USER_NAME` in configuration, and `RETIREMENT_SERVICE_WORKER_USERNAME` is the django setting in edx-platform.

These should be deleted from edx-platform then to avoid confusion:

```
edx-platform/cms/envs/common.py
1635:RETIREMENT_SERVICE_USER_NAME = "retirement_worker"

edx-platform/lms/envs/common.py
3715:RETIREMENT_SERVICE_USER_NAME = "retirement_worker"
```

(These are defaults set in edx-platform, which are not used anywhere else (yet)).

**Comment by nedbat** [comment]
I have cherry-picked this onto open-release/juniper.alpha1

**Pull request merged**
