### PR TITLE
[BTR-35] Update ecommerce BROKER_URL default value

### PR DESCRIPTION
**Pull request by 0x29a**
This PR updates Ansible variables for ecommerce and ecommerce worker services.

During testing Koa native installation, we've noticed that values in `BROKER_HOST` value in `/edx/etc/ecommerce.yml` and `/edx/etc/ecomworker.yml` files is invalid and still contains URL for RabbitMQ.

In `/edx/var/log/ecomworker/edx.log` I found log records like following:
```
Dec  3 13:47:13 ubuntu-focal [service_variant=ecomworker][celery.worker.consumer.consumer][env:no_env] ERROR [ubuntu-focal  28069] [consumer.py:428] - consumer: Cannot connect to amqp://celery:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)
```

After changing `BROKER_HOST` to the correct value and restarting worker, `/edx/var/log/ecomworker/edx.log`:
```
Dec  3 14:06:45 ubuntu-focal [service_variant=ecomworker][celery.worker.consumer.connection][env:no_env] INFO [ubuntu-focal  30780] [connection.py:24] - Connected to redis://:**@localhost:6379//
```

**JIRA tickets**:
- [BTR-35](https://openedx.atlassian.net/browse/BTR-35)

**Dependencies**:
- https://github.com/edx/ecommerce/pull/3271
- https://github.com/edx/ecommerce-worker/pull/112

**Testing instructions**:

Follow official [Native installation guide](https://openedx.atlassian.net/wiki/spaces/OpenOPS/pages/1969455764/Koa+Native+Open+edX+platform+Ubuntu+20.04+64+bit+Installation), but in `config.yml` add the following:
```
ECOMMERCE_BROKER_USERNAME: ''
ECOMMERCE_BROKER_PORT: 6379
ECOMMERCE_BROKER_TRANSPORT: 'redis'

ECOMMERCE_WORKER_BROKER_USERNAME: ''
ECOMMERCE_WORKER_BROKER_PORT: 6379
ECOMMERCE_WORKER_BROKER_TRANSPORT: 'redis'
```

After installation is finished, you should see `Connected to redis://:**@localhost:6379/` line in `/edx/var/log/ecomworker/edx.log`.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @0x29a! I've created [OSPR-5281](https://openedx.atlassian.net/browse/OSPR-5281) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by nedbat — APPROVED** [review]

**Comment by nedbat** [comment]
These are the same values as set in edx-internal, so are safe for edX. Thanks!

**Comment by openedx-webhooks** [comment]
@0x29a 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6189&entry.1484655318=https://github.com/0x29a&entry.752974735=2020-12-03+15:32&entry.1917517419=2020-12-04+18:58&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by nedbat** [comment]
I have cherry-picked this change to Koa.

**Pull request merged**
