### PR TITLE
Add empty default for EDXAPP_PASSWORD_COMPLEXITY

### PR DESCRIPTION
**Pull request by mikix**
This adds an overridable empty default for EDXAPP_PASSWORD_COMPLEXITY.

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [x] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [x] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [x] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

### CODE REVIEW

**Comment by feanil** [comment]
@mikix since we're changing the defaults for the whole community, can you also add an entry to the CHANGELOG and I assume you already added a note on the hawthorne wiki page?

**Comment by mikix** [comment]
@feanil I did add a note to the Hawthorn page that we've added new config options for PASSWORD_COMPLEXITY, but why would I add a comment there about a change to the edx.org site config?

But good point about the CHANGELOG.md file. Will add a note there.

**Comment by mikix** [comment]
@feanil I've been testing this a bit on https://mikix-mobile.sandbox.edx.org. Feeling confident that it doesn't blow stuff up.

I am not super familiar with our set of config repos, but I'm expecting this change would just affect sites we host, right?

**Comment by bderusha** [comment]
@feanil are we good to move ahead with this?

@mikix if so can you resolve the changelog merge conflict

**Comment by mikix** [comment]
Fixed the changelog conflict.

**Comment by mikix** [comment]
(FYI, I've also given White Label and Support heads up that this is coming.)

**Comment by feanil** [comment]
@mikix this is the set of defaults that all OpenEdx uses, so it will impact the defaluts for other sites.  Hence the changelog entry.  What we're doing is changing the default for all Open Edx.  I think it's the right thing to do but worth a big note.

**Comment by mikix** [comment]
@feanil oh. I'm not so sure I want to enforce these rules on OpenEdx then. I'm seeing now that maybe I should change edx-internal instead of this.

**Comment by mikix** [comment]
@feanil I've updated this branch to merely set an empty default for PASSWORD_COMPLEXITY and pass it on to the lms vars. The override is in https://github.com/edx/edx-internal/pull/334

**Review by feanil — APPROVED** [review]

**Pull request merged**
