### PR TITLE
[ENT-628] Add `ENTERPRISE_TAGLINE` and `PLATFORM_DESCRIPTION` to edxapp.

### PR DESCRIPTION
**Pull request by UmanShahzad**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

This adds a tagline var we need for [ENT-628](https://openedx.atlassian.net/browse/ENT-628), as well as a configurable platform description. The corresponding edx-platform PR is https://github.com/edx/edx-platform/pull/16094

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @UmanShahzad! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

<a   href="https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fconfiguration&number=4083"   rel="nofollow" >Create an OSPR issue for this pull request</a>.

**Review by feanil — APPROVED** [review]

**Comment by UmanShahzad** [comment]
@feanil Btw, you seemed to have approved this while I had `EDXAPP_ENTERPRISE_TAGLINE: "{{ EDXAPP_ENTERPRISE_TAGLINE }}"`, setting itself to itself :P Fixed now, though.

**Comment by UmanShahzad** [comment]
I've updated this to include `PLATFORM_DESCRIPTION`, which is something we'll need for the overall goal here. The corresponding edx-platform PR is also updated.

Will get back to this when we're ready to update `edx-enterprise`.

**Comment by UmanShahzad** [comment]
@douglashall @haikuginger This is now relevant for merge. See https://github.com/edx/edx-platform/pull/16094

**Comment by UmanShahzad** [comment]
Nevermind the above, I'm making a new PR.

**Comment by itsjeyd** [comment]
@UmanShahzad Could you link to this PR from relevant OC-* tickets? I don't see it listed on any of the ones that relate to the second part of the programs landing page work.

**Comment by UmanShahzad** [comment]
@itsjeyd Thanks for the reminder! There were so many different open PRs/tickets up at the time, and I had this bookmarked, so I got the false impression that I had already done it.

**Review by haikuginger — APPROVED** [review]
:+1:

- [x] I tested this: Validated the variables in the relevant `edx-platform` PR; verified that the code should fill them into the relevant spots in `lms.env.json` and `cms.env.json`.
- [x] I read through the code
- [x] ~~I checked for accessibility issues~~
- [x] Includes documentation

**Pull request merged**
