### PR TITLE
add open-ended-message to XQUEUE_QUEUES

### PR DESCRIPTION
**Pull request by fmyzjs**
due to [openendedchild.py#L79](https://github.com/edx/edx-platform/blob/master/common/lib/xmodule/xmodule/open_ended_grading_classes/openendedchild.py#L79)

I add  open-ended-message to XQUEUE_QUEUES

### CODE REVIEW

**Comment by fmyzjs** [comment]
@feanil  @jarv  Please review

**Comment by feanil** [comment]
looks good to me. @jarv ?

**Comment by fredsmith** [comment]
:+1:

**Comment by jarv** [comment]
:+1:

**Pull request merged**
