### PR TITLE
New playbook and role for go-server

### PR DESCRIPTION
**Pull request by macdiesel**
@feanil @doctoryes PTAL.

### CODE REVIEW

**Comment by doctoryes** [comment]
LGTM - so at the end of this install, GitHub OAuth login will be functional? Or is there further configuration to do?

**Comment by macdiesel** [comment]
The OAuth agent will be installed. 
you can override GO_SERVER_ADMIN_USERS to set the admin users who will then be able to log in to the system.

The unfortunate part is that the plugin does not currently allow you to limit login to only users with an edx account or via group membership. So for the time being we will need to manually add users to the system.

**Comment by doctoryes** [comment]
Unfortunate indeed. @feanil Should we capture items like this inability to limit login to users in a GitHub group as tickets representing work on an external open-source package? Guess it depends on the situation.

:+1:

**Comment by feanil** [comment]
:+1:   Story is on the un-groomed backlog.

**Pull request merged**
