### PR TITLE
Make changes need for matplotlib to work in the code sandbox.

### PR DESCRIPTION
**Pull request by feanil**

### CODE REVIEW

**Comment by carsongee** [comment]
:+1:

**Comment by carsongee** [comment]
Any reason we haven't merged this yet?

**Comment by feanil** [comment]
I wanted to spend a little bit more time trying to figure out why matplotlib was not respecting the temp directory environment variable and needs to write the font and tex caches to the virtualenv directory.

**Comment by carsongee** [comment]
Cool.  I've tried running this on a sandbox with matplot code, and I'm getting errors about not being able to allocate memory.

```
ImportError: /edx/app/edxapp/venvs/edxapp-sandbox/local/lib/python2.7/site-packages/matplotlib/backends/_backend_agg.so: failed to map segment from shared object: Cannot allocate memory
```

Is there anything else extra that needs to be done to allow shared memory maps in the code jail that isn't here?

**Comment by feanil** [comment]
Not that I've run into so far.  Haven't seen that error before. Perhaps I
didn't run a problem that needs that?

**Comment by carsongee** [comment]
Ugh, figured it out.  Looks like our default VMEM value isn't big enough for a lot of those problems and I had to increase it.

**Comment by feanil** [comment]
What was your default vmem?

**Comment by carsongee** [comment]
It was the repo default 128MiB.  Bumping it to 220MiB solved it for me, but I'll try and find a closer value

**Comment by hkim823** [comment]
@feanil what  the status of this?

**Comment by feanil** [comment]
@jarv @e0d More updates to make the 6.341x class work this fall.  I think this is now ready for a final review.

**Comment by carsongee** [comment]
Ouch on the new limits, but lgtm

**Comment by jarv** [comment]
after squash :+1:

**Pull request merged**
