### PR TITLE
Update to Ruby 2.3.0 for forums.

### PR DESCRIPTION
**Pull request by tobz**
Subject says it all: there's a PR for the forums to move to Ruby 2.3 (edx/cs_comments_service#196) and this is the corresponding configuration change to make it work.

### CODE REVIEW

**Comment by tobz** [comment]
Note the lack of a patch version, because there's no actual patches out for version 2.3.0.  I've tested installing the naked version (i.e. sans patch version) with `rbenv install` and it works as intended.

**Comment by jibsheet** [comment]
@edx/devops since more of you will have opinions

**Comment by jibsheet** [comment]
@tobz you're failing legit tests https://travis-ci.org/edx/configuration/jobs/151257098 is there a Forums PR we need to coordinate with?

**Comment by tobz** [comment]
Yeah, I guess if this is installing master, there would need to be coordination.  Hrmph..

**Comment by tobz** [comment]
I've created edx/configuration#3301 as a stepping stone towards building confidence that this works.  It takes this branch, and simply changes the version of the forums that gets installed to be the corresponding forums PR, which should fix the current bug encountered in the tests for _this_ PR.

**Comment by tobz** [comment]
Tests done to show that this works, despite failing tests:
- overrode the forums branch to make it work in a dummy PR (#3301)
- created a sandbox w/ the updated forums branch and updated configuration branch
- created a sandbox w/ the updated branches, but from scratch
- created a stage forums AMI w/ the updated branches, from scratch

**Comment by jibsheet** [comment]
I assume you mean #3301 not #3001?
This looks good, including the forums dockerfile cleanup.

Please coordinate with @fredsmith for the Sandbox/Devstack image updates.

👍

**Comment by tobz** [comment]
Yes, correct: #3301.  Updated my comment above.

**Pull request merged**
