### PR TITLE
Change boxname on fullstack, and remove ansible play from devstack

### PR DESCRIPTION
**Pull request by carsongee**
I wasn't sure on the devstack "fix", but don't know why you would need to run ansible again on a prebuilt box. The fullstack box isn't downloading a new box if you already have the previous release installed, so I changed the name.

### CODE REVIEW

**Comment by jarv** [comment]
I think the idea at the time was that you would re-run ansible so that you would be caught up with any configuration updates (specifically json updates) on the master branch.
@wedaly  may have more input.

**Comment by wedaly** [comment]
We need to re-run the deploy scripts during provisioning to checkout repos into the shared folders, which don't exist on the VM.  There are some other set-up steps that need to occur as well (such as creating binstubs for the rake command in edx-platform).

We might be able to get away with running just the steps tagged --deploy instead of every step to speed things up.

**Comment by carsongee** [comment]
I'll test it out with --tags deploy and if it works I'll update it or remove my change.

**Comment by carsongee** [comment]
Switching to deploy tag worked for me, and was quite a bit quicker

**Comment by carsongee** [comment]
ping this came up on the code list and reminded me about it.

**Comment by jarv** [comment]
:+1:

**Pull request merged**
