### PR TITLE
adding helper scripts in /edx/bin

### PR DESCRIPTION
**Pull request by jarv**
This adds some helper scripts for managing the edx server.

### CODE REVIEW

**Comment by feanil** [comment]
Can you also update the configuration to use these scripts instead of calling migrate directly?

**Comment by fredsmith** [comment]
:+1:  I think these would be useful to have merged in.  is /edx/bin/ added to $PATH automatically?

**Comment by jarv** [comment]
@fredsmith not yet but we could do that pretty easily

**Comment by feanil** [comment]
:+1:

**Pull request merged**
