### PR TITLE
Remove play made unnecessary by nodeenv 1.1.1

### PR DESCRIPTION
**Pull request by bjacobel**
These four PRs should merge first (and be incorporated into the ficus.master tag):

- [x] https://github.com/edx/credentials/pull/165
- [x] https://github.com/edx/edx-analytics-dashboard/pull/618
- [x]  https://github.com/edx/ecommerce/pull/1125
- [x] https://github.com/edx/edx-platform/pull/14454

### CODE REVIEW

**Comment by jibsheet** [comment]
This change (and the upstream changes) seem fine, but
https://travis-ci.org/edx/configuration/jobs/197666887#L2119-L2121
I'm seeing that failure on another branch, so it's something that's wrong on master I think.

**Review by gsong — APPROVED** [review]

**Comment by gsong** [comment]
@bjacobel and @jibsheet I'm looking into the Travis failure now.

**Comment by gsong** [comment]
Travis failure fixed via #3668.

**Review by jibsheet — APPROVED** [review]
Once you rebase on top of master and tests pass

**Comment by gsong** [comment]
@bjacobel I went ahead and rebased.

**Pull request merged**
