### PR TITLE
Enabling SSL for insights

### PR DESCRIPTION
**Pull request by e-kolpakov**
**Description:** Enables SSL in insights nginx insights config.
**JIRA:** [OSPR-1229](https://openedx.atlassian.net/browse/OSPR-1229)
**Partner information**: 3rd party-hosted open edX instance
**Merge deadline:** Apr 22th - issue addressed in branch, so no hard deadline.

**Testing instructions:**
1. Provision insights sanbox with the following vars:
1. NGINX_SSL_ENABLED - true
2. NGINX_SSL_KEY, NGINX_SSL_CERTIFICATE - SSL cert and key
3. (Optional) NGINX_REDIRECT_TO_HTTPS - true
   1. Access insights with HTTPS protocol (https://insights.sandbox.url:18110). _Expected result:_ Should open Insights main page.

**Author concerns:**
This PR reuses `NGINX_ENABLE_SSL` and `NGINX_SSL_*` variables for simplicity reasons, but it might be more robust and maintainable to have dedicated configuration variables (i.e. `INSIGHTS_NGINX_ENABLE_SSL`). However, adding such dedicated variables will break role isolation - nginx role will host/be aware/depend on variables, logically belonging to other roles.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @e-kolpakov! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fconfiguration&number=2947

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @e-kolpakov! I've created [OSPR-1229](https://openedx.atlassian.net/browse/OSPR-1229) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by mtyaka** [comment]
LGTM :+1:

**Comment by e-kolpakov** [comment]
@mulby this PR needs your (or someone else from your team) review.

**Comment by mulby** [comment]
@edx/devops - can one of you review this? I don't know enough about nginx to be an effective reviewer here.

**Comment by e-kolpakov** [comment]
@edx/devops Friendly reminder - this PR still needs your review (or redirection to someone else to review)

**Comment by e-kolpakov** [comment]
@edx/devops friendly reminder number two - please review this PR.

**Comment by feanil** [comment]
:+1:  LGTM  @edx/devops second review?

**Comment by jibsheet** [comment]
👍

**Pull request merged**
