### PR TITLE
allow overriding of nginx max_body_size and proxy_read_timeout

### PR DESCRIPTION
**Pull request by thraxil**
This introduces ansible variables to allow for overriding the `max_body_size` and `proxy_read_timeout` nginx settings for the lms, cms, and forum nginx configs.

This is necessary in certain situations, particularly when dealing with large file upload requirements.

The `max_body_size` variables' default values are set to the values previously hard-coded in the config file templates.

The `read_proxy_timeout` variables' default values are set to 60s, which is just the nginx default value if that variable is not set (http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout).

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @thraxil! I've created [OSPR-5154](https://openedx.atlassian.net/browse/OSPR-5154) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@thraxil Thank you for your contribution. We will review it soon.

**Review by fredsmith — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@thraxil 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6153&entry.1484655318=https://github.com/thraxil&entry.752974735=2020-11-17+15:58&entry.1917517419=2020-11-19+16:18&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by nedbat** [comment]
It looks like this is breaking sandbox builds:
```
19:20:59 TASK [nginx : Test nginx configs] **********************************************
19:20:59 fatal: [54.234.225.147]: FAILED! => {"changed": true, "cmd": ["nginx", "-t"], "delta": "0:00:00.022309", "end": "2020-11-19 19:20:59.434263", "msg": "non-zero return code", "rc": 1, "start": "2020-11-19 19:20:59.411954", "stderr": "nginx: [emerg] invalid number of arguments in \"proxy_read_timeout\" directive in /etc/nginx/sites-enabled/cms:112\nnginx: configuration file /etc/nginx/nginx.conf test failed", "stderr_lines": ["nginx: [emerg] invalid number of arguments in \"proxy_read_timeout\" directive in /etc/nginx/sites-enabled/cms:112", "nginx: configuration file /etc/nginx/nginx.conf test failed"], "stdout": "", "stdout_lines": []}
```

**Comment by nedbat** [comment]
Fixing forward in #6158

**Pull request merged**
