### PR TITLE
fix: tubular should be installed at particular version

### LINKED ISSUE #41: Should edx/tubular be tagged for releases?
[From Slack](https://openedx.slack.com/archives/C01AGTSB1LL/p1617983602084400?thread_ts=1617977408.083100&cid=C01AGTSB1LL)

> Guruprasad
> the edx/tubular repository is used by the Retirement service but it is not tagged for any named releases. Due to this, if there is breaking change that is backwards-incompatible, it will break older installations. This happened with the periodic build Juniper sandbox.

### PR DESCRIPTION
**Pull request by nedbat**
Installations of Juniper were failing because tubular was always
installing master, rather than the Juniper branch.  This change will
check out a particular version, to keep everything working.

This change will be cherry-picked back to Juniper and Koa, as well as Lilac.

Fixes https://github.com/openedx/build-test-release-wg/issues/41

### CODE REVIEW

**Comment by nedbat** [comment]
@giovannicimolin can you review?

**Comment by nedbat** [comment]
@lgp171188 you might also have relevant expertise.

**Comment by giovannicimolin** [comment]
@nedbat Nice catch, it's surprising that it worked for so long.

I'm provisioning a sandbox to test this playbook version and can review the code tomorrow.

**Review by giovannicimolin — APPROVED** [review]
:+1:

- [x] I tested this:
1. Set up a sandbox (internal - https://manage.opencraft.com/instance/27280/edx-appserver/19118/) with this branch.
2. Set `RETIREMENT_SERVICE_VERSION: "dbdce060d5c3caf908ece0ae9bce9f14f807ec39"`
3. After provisioning, checked that the tubular repo was checked out in the commit I've set above. 
```
root@edxapp-tubular-version-testope-appserver-1:/edx/app/retirement_service/tubular# git status
HEAD detached at dbdce06
nothing to commit, working tree clean
```
- [x] I read through the code
- [ ] ~~I checked for accessibility issues~~ NA
- [x] Includes documentation

@nedbat Good to go. I'm not a core committer here, so my approval doesn't mark this PR as green. 

@pomegranited (since you are core committer for this repo) do you have some spare minutes to check this out?

**Review by giovannicimolin — APPROVED** [review]

**Comment by nedbat** [comment]
@edx/site-reliability-engineering any opinions?

**Comment by nedbat** [comment]
I've cherry-picked this onto Lilac, Koa, and Juniper.

**Pull request merged**
