### PR TITLE
feature: Allow installing extra requirements when using the `credentials` role

### PR DESCRIPTION
**Pull request by kewne**
This makes the `credentials` role support the use of `edx_django_service_extra_requirements`
as done originally in [!6400](https://github.com/edx/configuration/pull/6400)

The end-goal of this is to support theming of the credentials service as described [here](https://edx-credentials.readthedocs.io/en/latest/theming.html#installing-a-theme)

Related tickets:
* [BB-4342](https://tasks.opencraft.com/browse/BB-4342)

# Testing

1. Launch devstack with credentials service: `make dev.up.credentials`
2. In the `configuration` repo, create a `docker_inventory.ini` file containing just
```ini
credentials ansible_connection=docker ansible_host=edx.devstack.credentials
```
3. Create a playbook `credentials_test.yml`:
```yml
- name: Deploy edX Credentials Service
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_DATADOG: False
    ENABLE_NEWRELIC: False
    CLUSTER_NAME: 'credentials'
  roles:
    - credentials
```
4. Run the playbook from the `playbooks` directory (to ensure ansible.cfg is picked up): `ansible-playbook credentials_test.yml -i docker_inventory.ini --skip-tags install:code -e '{ disable_edx_services: true, CREDENTIALS_EXTRA_REQUIREMENTS: [{name: 'lolcat'}], edx_django_service_is_devstack: true}'`
5. Assert `lolcat` is now installed in the credentials virtualenv:
```sh
make dev.shell.credentials
source /edx/app/credentials/venvs/credentials/bin/activate
echo test | lolcat 
```

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @kewne! I've created [OSPR-5867](https://openedx.atlassian.net/browse/OSPR-5867) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@kewne Thank you for your contribution. Please let me know once it is ready for our review.

**Review by lgp171188 — APPROVED** [review]
@kewne, :+1:. Before the edX/core committer review, can you edit the description of this PR to mention that this is going to be used to install a theme in the `credentials` service as documented [here](https://edx-credentials.readthedocs.io/en/latest/theming.html#installing-a-theme)? 
- [x] I tested this change and verified that it works as expected. It is similar to the changes done in https://github.com/edx/configuration/pull/6400
- [x] I read through the code
- [x] ~~I checked for accessibility issues~~ NA
- [x] ~~Includes documentation~~ NA

**Comment by lgp171188** [comment]
@natabene, this is now ready for edX/core committer review. The workflows configured for PRs in this repository haven't run for this PR, and there is a message that says `First-time contributors need a maintainer to approve running workflows.`. So can you approve running the workflows for this PR?

@pomegranited, will you be able to review this PR as a core committer since you reviewed the very similar https://github.com/edx/configuration/pull/6400? Thanks!

**Comment by kewne** [comment]
@lgp171188 
> can you edit the description of this PR

Done, thanks!

**Comment by pomegranited** [comment]
:+1: Works perfectly, thank you @kewne !

- [x] I tested this using the beautiful PR test instructions, which made it quick and easy to verify.
- [x] I read through the code
- [x] <strike>I checked for accessibility issues</strike> N/A
- [x] Includes documentation -- and thanks for updating the PR description with the purpose of this change!
- [x] Commit structure follows [OEP-0051](https://github.com/edx/open-edx-proposals/pull/189) -- close enough 😄 
   @kewne Technically, you should have used the prefix `feat:`, not `feature:` cf [OEP-0051: Conventional Commits#Type](https://github.com/edx/open-edx-proposals/blob/master/oeps/oep-0051-bp-conventional-commits.rst#type).

I'll merge this in 2 days if there are no objections from @edx/devops .

**Comment by kewne** [comment]
@pomegranited oops! I can amend this to match the expected format, it's not too much trouble.

**Comment by pomegranited** [comment]
Sure if you want to @kewne  :)

**Review by pomegranited — APPROVED** [review]
Approved, see [previous comment](https://github.com/edx/configuration/pull/6449#issuecomment-871140012) 👍

**Comment by openedx-webhooks** [comment]
@kewne 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6449&entry.1484655318=https://github.com/kewne&entry.752974735=2021-06-17+16:03&entry.1917517419=2021-07-05+00:31&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
