### PR TITLE
Revert AMI due to failures.

### PR DESCRIPTION
**Pull request by adzuci**

### CODE REVIEW

**Review by jdmulloy — APPROVED** [review]

**Comment by adzuci** [comment]
The nightly build from last night did pass, so I may not need to revert, update pending: https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#Images:visibility=owned-by-me;search=ami-01f65220538bf9b3a;sort=name

**Comment by adzuci** [comment]
Will close if sandbox build pointing at `adzuci/devops-88886-newer-sandbox-ami` succedes: https://github.com/edx/configuration/pull/5246
https://tools-edx-jenkins.edx.org/job/Sandboxes/job/CreateSandbox/21572/console (built with registrar, disco, and credentials)

**Comment by adzuci** [comment]
Giving up for now, so many fun new errors though:

```
15:30:15 TASK [edxapp : code sandbox | put sandbox apparmor profile in complain mode] ***
15:30:15 fatal: [adzuci-new-ami.sandbox.edx.org]: FAILED! => {"msg": "the connection plugin 'ssh' was not found"}
15:30:15 	to retry, use: --limit @/edx/var/jenkins/jobs/Sandboxes/jobs/CreateSandbox/workspace@2/configuration/playbooks/edxapp.retry
```

https://tools-edx-jenkins.edx.org/job/Sandboxes/job/CreateSandbox/21574/console

**Comment by adzuci** [comment]
https://github.com/edx/configuration/pull/5237/files

**Pull request merged**
