### PR TITLE
Rationalize custom modules

### PR DESCRIPTION
**Pull request by maxrothman**

### CODE REVIEW

**Comment by maxrothman** [comment]
@carsongee @antoviaque @natea @stvstnfrd

**Comment by maxrothman** [comment]
test me please

**Comment by antoviaque** [comment]
@maxrothman Thanks for the ping! I don't see any custom module that we would be depending on among the ones you removed, so LGTM. @mtyaka can you have a quick look too?

**Comment by mtyaka** [comment]
:+1:

**Comment by maxrothman** [comment]
Testing complete. Ready for final review.

**Comment by feanil** [comment]
@max can you link to the wiki page of tests you ran here so people know what you tested.

**Comment by maxrothman** [comment]
https://openedx.atlassian.net/wiki/display/EdxOps/Ansible+testing+checklist

**Comment by feanil** [comment]
:+1: :shipit:

**Comment by stvstnfrd** [comment]
Late to the party, but thanks for the mention @maxrothman ; lgtm.

**Pull request merged**
