### PR TITLE
Changing stop/start back to restart now that things work for stanford

### PR DESCRIPTION
**Pull request by jbau**
I was noticing that a full run of the playbook edx-west/edxapp_prod.yml left edxapp stopped.  So this should fix it and get rid of the distinct stop and start 

@jarv @feanil

### CODE REVIEW

**Comment by jarv** [comment]
looks good

**Comment by jbau** [comment]
hmm. notice that http://jenkins.edx.org:8080/job/ansible-tests/56/console failed because edxapp upstart didn't come back up on restart.  I guess this possibly replicates what I was seeing on the Stanford servers.
Maybe it only succeeds in certain machine states, which would be scary.  I wonder if the upstart script itself needs some attention?

**Comment by jbau** [comment]
I'll manually do another run to see.

**Comment by jbau** [comment]
and http://jenkins.edx.org:8080/job/ansible-tests/57/console fails b/c it can't stop edxapp services.

**Comment by jbau** [comment]
I'm going to merge b/c it has worked several times on our release.

**Pull request merged**
