### PR TITLE
make backup of previous server-vars.yml

### PR DESCRIPTION
**Pull request by dhpollack**
Added some code so the previous server-vars.yml is backed up when /edx/bin/update is run.  Previously only the variables in all caps were preserved.

### CODE REVIEW

**Comment by hkim823** [comment]
this makes sense to me @e0d @feanil @jarv or @feanil thoughts?

**Comment by e0d** [comment]
Well the idea was that all caps vars would be the ones changing or subject to customization per environment.  Still, I think that it's wishful thinking that we could predict all var that would need customization, etc.  So I'm fine with this.

@dhpollack Have you signed a contributor agreement?

**Comment by dhpollack** [comment]
@e0d Yes, I've signed the agreement and added myself to the AUTHORS from a previous pull request.

**Comment by dhpollack** [comment]
@e0d anything else that I need to do for this?

**Pull request merged**
