### PR TITLE
Remove vestiges of obsolete USE_CUSTOM_THEME setting

### PR DESCRIPTION
**Pull request by nedbat**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

### CODE REVIEW

**Review by jibsheet — APPROVED** [review]
I'm assuming you'll do some test builds.  We also define one of these vars in edx-internal, so please remove it there.

**Comment by nedbat** [comment]
@jibsheet I can build some sandboxes if that is what you mean, though I need help understanding precisely which builds you want to see.

**Comment by jibsheet** [comment]
@nedbat I think if you build a sandbox and use alton to cut an AMI and it doesn't blow up, we can ship this.  Actually testing themes requires configuration that the WL team has only really set up stage (you can tag one of them in, but I'm not sure who is most knowledgeable).

**Comment by nedbat** [comment]
Sandbox build completed successfully with configure_secure_version set to jibsheet/remove-obsolete-theme-vars: https://tools-edx-jenkins.edx.org/job/sandboxes/job/CreateSandbox/1914/

**Comment by nedbat** [comment]
AMI also built successfully.  @jibsheet are we good to merge?

**Comment by jibsheet** [comment]
@nedbat ship it

**Pull request merged**
