### PR TITLE
Add missing scripts to connect ro to prod dbs

### PR DESCRIPTION
**Pull request by maxrothman**
Blocked by https://github.com/edx/configuration/pull/2091
Relates to https://github.com/edx-ops/edx-secure/pull/493

### CODE REVIEW

**Comment by feanil** [comment]
:+1:  Has this been run already?  Did you already created the actual replica scripts?

**Comment by maxrothman** [comment]
@feanil No, I have not run it yet.

**Comment by maxrothman** [comment]
@feanil I've run it now and it works!

**Comment by feanil** [comment]
:+1:   :sheep: :it:

**Pull request merged**
