### PR TITLE
Add vagrant tests for devstack.

### PR DESCRIPTION
**Pull request by benpatterson**
@jzoldak @cgoldberg 

Currently these would live alongside the Vagrantfile. We can move it to another dir as a follow-up improvement.

### CODE REVIEW

**Comment by benpatterson** [comment]
@feanil @e0d care to look/comment?

**Comment by jzoldak** [comment]
@benpatterson I'm getting errors when running this against a devstack that has already been up and running. Couple issues:
1. `pip install -q --exists-action w -r requirements/edx/github.txt` gives

```
Exception:
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/req.py", line 1153, in prepare_files
    location = req_to_install.build_location(self.build_dir, not self.is_download)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/req.py", line 218, in build_location
    _make_build_dir(build_dir)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pip/req.py", line 1527, in _make_build_dir
    os.makedirs(build_dir)
  File "/edx/app/edxapp/venvs/edxapp/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/edx/app/edxapp/venvs/edxapp/build'
```
1. `rm -rf /tmp/mako_[cl]ms` from `paver test_js_run -s xmodule` gives a whole bunch of these errors. This is because I've already run stuff on that devstack. Not sure if this is a supported use case.

```
rm: cannot remove `/tmp/mako_lms/foo.pyc': Permission denied
```

**Comment by benpatterson** [comment]
@jzoldak FWIW I ran into that this morning just running some paver tasks (not testing vagrant, but actually using devstack). Could it be related to this change? https://github.com/edx/edx-platform/commit/61cf1d6edb4609094ba6b84c87a29ff5bec4ee2c#diff-9280d61660044201fa35456d5ae4ee74

**Comment by jzoldak** [comment]
@benpatterson Not sure. I know I've updated requirements since that change to github.txt and not seen the error while working in devstack itself. As an aside, if it is because of that we should keep an eye on the channels to see if anyone else is having trouble with paver commands in devstack, as I just merged in that change recently. (yesterday maybe?)

**Comment by benpatterson** [comment]
CC @maxrothman 

some paver commands you can run to test a new devstack. not exhaustive, but useful smoketest.

**Comment by feanil** [comment]
@benpatterson what's up with this PR, it seems like this just tests the edx-platform but not really any of the other apps on the vagrant box.  Can we merge it or close it?

**Comment by benpatterson** [comment]
@feanil we never got it 100% working, and there's a lot of bending of fabric to do the things we want. So, sadly, we should close this.

**Pull request closed without merging**
