### PR TITLE
XCOM-539: Added Platform Name and Theme SCSS settings to E-Commerce config

### PR DESCRIPTION
**Pull request by Nickersoft**
@clintonb @rlucioni @jimabramson @feanil

### CODE REVIEW

**Comment by rlucioni** [comment]
:+1: 

Please open a support ticket asking DevOps to configure the proper overrides in configuration-secure, and update the [Service Settings](https://openedx.atlassian.net/wiki/display/XCOM/Service+Settings) wiki page.

**Comment by clintonb** [comment]
@feanil

**Comment by clintonb** [comment]
:+1: (wait for DevOps review before merging)

**Comment by feanil** [comment]
:+1:

**Pull request merged**
