### PR TITLE
Add a migration script for Birch

### PR DESCRIPTION
**Pull request by singingwolfboy**
@maxrothman, @feanil, can you two take a look at this? Both the contents of the script, and the general idea of having this script here in this repo.

### CODE REVIEW

**Comment by feanil** [comment]
Can we move this under 'util/devstack' instead of creating a new top level directory?

**Comment by singingwolfboy** [comment]
@feanil: So, you want me to make a `devstack` directory under the `util` directory, and put this `migrate.sh` script there? It's designed to work with fullstack, too, so I'm not sure that a directory named `devstack` is a good choice. Maybe `util/vagrant`?

**Comment by feanil** [comment]
`util/vagrant` sounds good to me.

**Comment by singingwolfboy** [comment]
@feanil I've updated the path to the script. Better?

**Comment by feanil** [comment]
:+1:

**Comment by feanil** [comment]
nit: maybe rename it to 'migrate-aspen-to-birch.sh'?  As we'll have more in the future?

**Comment by singingwolfboy** [comment]
@feanil I wrote the script with support for specifying the migration target, so that (in theory) you'll be able to reuse the same migration script to get to a future named release.

**Pull request merged**
