### PR TITLE
Harprofiler repo is now under edx. Disable test cruft.

### PR DESCRIPTION
**Pull request by benpatterson**
The test was under dev and shouldn't have been merged. (This
approach is incompatible with ansible's design.)

cc @cgoldberg

### CODE REVIEW

**Comment by clytwynec** [comment]
Why don't we want the test?

**Comment by benpatterson** [comment]
The test never worked, and ansible does not currently support sourcing in the context of a shell command (which is what we would need to use for a venv --- ansible uses a session-less user). I can't find the perfect link to describe this, but here's a concise one: https://groups.google.com/forum/#!searchin/ansible-project/bashrc/ansible-project/44Lb72cPMmg/Acton7JTJbcJ

**Comment by clytwynec** [comment]
Ahh ok. Thanks.  I was just curious what the reason was.  

Changes look good. :+1:

**Comment by cgoldberg** [comment]
FWIW, you must be in a bash shell to use 'source'.  you can't source in a
dash/bourne/etc shell.
can ansible run things under bash explicitly?

**Comment by benpatterson** [comment]
Best, recent example of accomplishing this is using the rbenv on the new relic plugin. That was done with separate shell scripts (basically, one for each command that would need to be independently run under a given sourced environment).

https://github.com/edx/configuration/blob/master/playbooks/roles/newrelic/tasks/s3-watcher.yml#L34

**Pull request merged**
