### PR TITLE
Merge rbenv change to rc.

### PR DESCRIPTION
**Pull request by feanil**
@singingwolfboy FYI

### CODE REVIEW

**Comment by singingwolfboy** [comment]
Can you remove the extra merge commit from this PR, and make sure it's reflected on https://openedx.atlassian.net/wiki/display/OPEN/Cypress+Bugfixes ?

**Comment by feanil** [comment]
@singingwolfboy FYI,  I'm happy to remove the merge commits but why?  They show which PRs actually made the changes that got merged into the RC.

**Comment by singingwolfboy** [comment]
I had assumed they were useless noise, but you're right, they do have valuable info. It looks like some more commits have crept into your PR though, which I'm not sure are intentional. Can you double-check?

**Comment by feanil** [comment]
They are a fix for testeng, it doesn't effect the deployment of other parts of configuration, so I saw no reason to keep it out.

**Pull request merged**
