### PR TITLE
Revert "Use DraftMongoModuleStore."

### PR DESCRIPTION
**Pull request by feanil**
This reverts commit bd33e9a34ab63047fd56c52a1d5ba09f3267cd45.

This is to maintain backwards compatibility with older versions
of edx-platform.

### CODE REVIEW

**Comment by jarv** [comment]
:+1:

**Comment by jarv** [comment]
don't we want to revert this from release, not master?

**Comment by feanil** [comment]
good point will close this and open a PR against release.

**Comment by jbau** [comment]
hmm.  this is one case where maintaining configuration forward / backward compatibility seems tricky.  I wonder if there should be some state support period for edx-platform versions.

**Comment by feanil** [comment]
Yea, we need to figure that out,  right now I'm reverting this so that we can unbreak solutions.

**Comment by feanil** [comment]
Made https://github.com/edx/configuration/pull/1338 to revert this on release.

**Pull request closed without merging**
