### PR TITLE
Upgrade edxapp node version to 6.9 LTS

### PR DESCRIPTION
**Pull request by bjacobel**
## Description:
[TNL-5521](https://openedx.atlassian.net/browse/TNL-5521). Upgrade to Node 6.

## Testing:

- [x] **Created a devstack**: I've been using it for the past few days without issue (update: Ari is now on Node 6 as well)
```
$> CONFIGURATION_VERSION=bjacobel/node6 vagrant up
[...]
$> vagrant ssh
[...]
vagrant@precise64:~$ sudo su edxapp
edxapp@precise64:~/edx-platform$ node --version
v6.9.1
edxapp@precise64:~/edx-platform$ npm --version
3.10.8
```
- [x] **Created a "normal" sandbox**: https://peerdeps-npm3.sandbox.edx.org
- [x] **Built an AMI**: succeeded (Job number 5766, build token kevin-prod-edx-edxapp-1480954987)
- [x] **Create a "from scratch" sandbox**: https://scratch-node-lts.sandbox.edx.org, [job](http://jenkins.edx.org:8080/view/Ansible/job/ansible-provision/10313/)
- [x] **Build Jenkins worker AMI**: [success](https://build.testeng.edx.org/view/packer/job/build-packer-ami/4246/)
- [x] **Jenkins worker AMI smoketests**: running [javascript](https://build.testeng.edx.org/view/All/job/edx-platform-pr-tests-special-worker/2/) and [bokchoy](https://build.testeng.edx.org/view/All/job/edx-platform-pr-tests-special-worker/3/)

## Reviewers;
- [x] @jibsheet 
- [ ] @benpatterson

### CODE REVIEW

**Review by jibsheet — APPROVED** [review]

**Comment by jibsheet** [comment]
@bjacobel Should we land this now that your change is on master?

**Comment by bjacobel** [comment]
@jibsheet I just updated the PR description, let me know what you think about the testing I've done already and if it obviates the other two testing items I haven't done yet.

**Comment by jibsheet** [comment]
@bjacobel You should kick off the from-scratch sandbox build.  It'll take a few hours, so just run it and let it go and check on it.  I'll let @benpatterson speak to what testing he'd like for Jenkins workers.

I was happy to see
```
23:07:01 TASK: [edxapp | create nodeenv] *********************************************** 
23:07:04 changed: [peerdeps-npm3.sandbox.edx.org]
```
in http://jenkins.edx.org:8080/job/ansible-provision/10277/consoleFull since it answers one of my questions about "will nodeenv wipe out and recreate itself with the newer version" which appears to be true from that output (and is great).

**Comment by bjacobel** [comment]
From-scratch sandbox build finished successfully!

**Comment by bjacobel** [comment]
Jenkins worker AMI/smoketests job completed successfully. 

FYI @estute

**Review by jibsheet — APPROVED** [review]
Not sure what's up with the Version Eye failure here, any ideas @e0d?

**Comment by benpatterson** [comment]
:+1:

**Comment by bjacobel** [comment]
Just checking to make sure I'm good to merge this without VersionEye, the failure looks like it's on their end.

(compare [the first build on this PR](https://www.versioneye.com/pullrequests/584f1378b5d54c001687d325) to the [most recent](https://www.versioneye.com/pullrequests/58500b2dd8d0b60016f60f2a))

**Comment by jibsheet** [comment]
@bjacobel Go ahead an merge, I expect an upstream change in license parsing that we need to address.

**Pull request merged**
