### PR TITLE
Reorder edxapp modulestores

### PR DESCRIPTION
**Pull request by maxrothman**
as per [DEVOPS-1079](https://openedx.atlassian.net/browse/DEVOPS-1079)
@cahrens is this what you were looking for?

### CODE REVIEW

**Comment by cahrens** [comment]
@maxrothman Certainly this change needs to be made, but I don't know how many other changes.

In general, wherever "stores" are defined for MODULESTORE, DraftVersioningModuleStore needs to be listed before DraftMongoModuleStore.

In addition, if DEFAULT_STORE_FOR_NEW_COURSE is defined anywhere, it needs to be removed. The default store for a new course is now just based on the ordering within "stores".

**Comment by maxrothman** [comment]
Once the referenced PR is merged, does this one look good to merge?

**Comment by cahrens** [comment]
Are there really no occurrences of DEFAULT_STORE_FOR_NEW_COURSE? There is something that is currently making split the default for new courses on staging and prod (though not on devstack and sandbox). I don't know the configuration files outside of edx-platform, so I don't know how to tell what configuration is set for staging and prod.

Does this main.yml file control what appears in cms.auth.json and lms.auth.json on devstack? On my devstack, those files have the split modulestore listed at the end instead of first.

Definitely have someone from devops review this PR, as I don't know much about the edx configuration repo.

**Comment by cahrens** [comment]
FYI, the change to make split the default modulestore for newly created courses on prod/staging was fairly recent (within the last month). So there should be a devops ticket/PR/knowledge about what was done.

**Comment by maxrothman** [comment]
There were occurrences of DEFAULT_STORE_FOR_NEW_COURSE in the linked PR (which you might not be able to see).

The lms/cms.auth.json files are generated from information in this main.yml file.

**Comment by carsongee** [comment]
I was messing around with this and ran into a bug, but it is probably more relevant to the edx-platform PR, just an FYI. https://openedx.atlassian.net/browse/TNL-1362

**Comment by cahrens** [comment]
@maxrothman no, I don't see a linked PR.

@carsongee what will be the impact on your team if we merge these PRs with TNL-1362 outstanding? Is this a bug you are able to help investigate?

**Comment by carsongee** [comment]
Currently it means all of our residential and MOOC course development environments would have to forgo this change until it is resolved as command line imports are a key factor for our course development automations/CI, but as long as we can continue to override the settings and make draft the default we can be ok with this total change until the issue is resolved.  I'm happy to help investigate the bug as time allows. It is very easy to reproduce, and I'm trying to do all my vetting of the birch RC before it goes gold so I'm a bit strapped on time since I've been finding quite a few things so far.

**Comment by cahrens** [comment]
@carsongee Yes, you could continue to override the setting by listing DraftMongoModuleStore before DraftVersioningModuleStore in the "stores" variable.

**Comment by cahrens** [comment]
@maxrothman I have a fix for the issue that @carsongee reported (though it still needs to be reviewed). Have your 2 configuration PRs been reviewed? I think we need to coordinate merging with respect to this week's release.

**Comment by feanil** [comment]
:+1:

**Comment by maxrothman** [comment]
@cahrens I've merged the PR you can't see, and this one looks like it's ready to merge from our end. Let me know when this one should be merged.

**Comment by cahrens** [comment]
@maxrothman This one is good to go-- I just merged my PR to edx-platform. Thanks!

**Pull request merged**
