### PR TITLE
Add course catalog visibility feature

### PR DESCRIPTION
**Pull request by panessa**
Add course catalog visibility feature

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @panessa! I've created [OSPR-1706](https://openedx.atlassian.net/browse/OSPR-1706) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by feanil** [comment]
Looks good to me but someone from @edx/ecommerce  should also review.

**Review by clintonb — APPROVED** [review]

**Comment by clintonb** [comment]
This is not the same as the Catalog Service. I'm not entirely what this feature is, but all this commit does is expose the default value set in edx/edx-platform here in configuration. That's fine as it makes life easier for maintainers.

**Comment by feanil** [comment]
@clintonb good to know.

@gsong I think this is good to go but not sure about contributor's agreement.

**Comment by gsong** [comment]
@feanil 👍 from the contributor standpoint.

**Pull request merged**
