### PR TITLE
add jwt config

### PR DESCRIPTION
**Pull request by muhammad-ammar**
EDUCATOR-1644

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

### CODE REVIEW

**Comment by muhammad-ammar** [comment]
@feanil This is a small change. Please have a look.

**Comment by feanil** [comment]
@muhammad-ammar per our previous conversations, I thought we weren't gonig to add the JWT settings until the library was ready to have asymmetric keys.  Right now you shouldn't need this I think.  @muzaffaryousaf correct me if I'm wrong here.

**Comment by muhammad-ammar** [comment]
@feanil muzaffar is on annual leaves. I was not part of that discussion so I am not completely sure but as for the ansible work, my understanding is that we need to setup/configure JWT like other services.

**Comment by feanil** [comment]
@nasthagiri can you help provide guidance here?  I believe we said we weren't going to do this correct?

**Comment by nasthagiri** [comment]
Yes, that is correct.  We decided not to use JWT-based authentication at this time for VEDA - not until Asymmetric JWT keys are supported.
For now, we should continue to use vanilla OAuth, with the Client-ID and Client-Secret that must have already been established.

**Pull request closed without merging**
