### PR TITLE
Use COMMON_GIT_MIRROR

### PR DESCRIPTION
**Pull request by fmyzjs**
**Ticket:** [OSPR-297](https://openedx.atlassian.net/browse/OSPR-297)

**Background:**
Some times ,because of the GFW or worse network,people in China can not use github services.

 I open this pull  to make sure we can switch our local edx  repo mirrors.

**Studio Updates:**  None.

**LMS Updates:** None

**Test:** [travis](https://travis-ci.org/eduStack/configuration/builds/43984602)

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @fmyzjs! I've created [OSPR-297](https://openedx.atlassian.net/browse/OSPR-297) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams. 

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ('this must be merged by XX date', and why that is)
- partner information ('this is a course on edx.org')
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the Github pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by sarina** [comment]
@fmyzjs - don't you need to set the value of `COMMON_GIT_MIRROR` somewhere in these files?

Also, a better variable name might be `GITHUB_URL`. `COMMON_GIT_MIRROR` doesn't make a ton of sense to me.

**Comment by fmyzjs** [comment]
@sarina COMMON_GIT_MIRROR has been set in [common/defaults/main.yml#L34](https://github.com/edx/configuration/blob/master/playbooks/roles/common/defaults/main.yml#L34)

**Comment by sarina** [comment]
OK, cool, thanks for clarifying. I have put this in the Dev Ops team
backlog to review. Please note that review may take longer than normal, due
to the upcoming holiday time in America (Christmas and New Year's).

**Comment by fmyzjs** [comment]
Thanks

**Comment by e0d** [comment]
Looks reasonable to me.

@maxrothman second set of eyes?

**Comment by maxrothman** [comment]
Looks good to me, but before merging, we should look at [all of the places github.com is still referenced explicitly](https://gist.github.com/maxrothman/eb638c093459de15db29) and make sure we don't have to change any others.

**Comment by sarina** [comment]
@e0d @maxrothman could you guys finish up reviewing this pull request? It's very close.

**Comment by sarina** [comment]
@fmyzjs could you please rebase atop of master?

**Comment by e0d** [comment]
@sarina This PR is effectively blocked by another PR.  Could we add a label for that?  @fmyzjs please hold off on rebasing until we land another PR that touches similar code paths.

**Comment by sarina** [comment]
@e0d will think about best way to do that. Process is extremely confusing to most already.

**Comment by sarina** [comment]
@e0d what is this blocked by? Linking to the other PR will link them both on github.

**Comment by feanil** [comment]
@sarina this is blocked by work related to https://github.com/edx/configuration/pull/1784 which is refactoring the service role, as a part of that work we are making changes to the 'edx-service' role that will change how we do checkouts generally for many of the roles.  This work is going to conflict with that but that work should land in master tomorrow.

**Comment by fmyzjs** [comment]
sorry for late response,i am busying in making preparations for theend-of-term exams...

**Comment by sarina** [comment]
@fmyzjs no worry. This PR will need to be rebased once #1784 lands, then it can be re-reviewed.

**Comment by feanil** [comment]
@fmyzjs This work makes sense but needs to be rebased on top of the refactor work that @maxrothman recently did.

**Comment by sarina** [comment]
@fmyzjs If you are unable to spend time to rebase this pull request, please close it. Thanks!

**Comment by maxrothman** [comment]
@fmyzjs Thank you! This looks good. Before merging, would you have time to also refactor out the `/edx/` part of the path to `COMMON_GIT_PATH`? It's a new variable introduced in the aforementioned refactor.

**Comment by sarina** [comment]
@fmyzjs are you still working on this issue? If you don't have time right now, it would be better to close the pull request. You can open a new one when you have time to finish it up.

**Comment by feanil** [comment]
@fmyzjs Closing this for now.  Please re-open when you have updates and we can re-review.

**Pull request closed without merging**
