### PR TITLE
Add Enterprise Service worker username and API URL

### PR DESCRIPTION
**Pull request by mattdrayer**
Configuration Pull Request
---

@fredsmith here is the configuration update for communicating with the Enterprise service.

Make sure that the following steps are done before merging

  - [x] A devops team member has commented with :+1:
  - [ ] are you adding any new default values that need to be overridden when this goes live?
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

### CODE REVIEW

**Review by fredsmith — APPROVED** [review]

**Comment by mattdrayer** [comment]
@fredsmith before I merge this PR, just want to confirm that we have the relevant setting(s) defined in our internal configuration spec (assuming it is required)

**Comment by fredsmith** [comment]
@mattdrayer I don't think we need to override these settings, do we?

**Review by fredsmith — CHANGES_REQUESTED** [review]
We should use the edxapp API base URL variable instead of localhost

**Comment by fredsmith** [comment]
https://github.com/edx/edge-internal/pull/10 and https://github.com/edx/edx-internal/pull/34 @jibsheet FYI

**Review by fredsmith — APPROVED** [review]

**Review by jibsheet — APPROVED** [review]

**Comment by mattdrayer** [comment]
Awesome -- yeah when I looked again at the `localhost:8000` URL I had the same thought and that is why I asked.  The change LGTM -- I'm assuming we'll want to squash the commits into one before merging, yes?  Happy to do that after the checks are complete.

**Pull request merged**
