### PR TITLE
BOM-2128 : Upgrade XQueue to Ubuntu 20.04

### PR DESCRIPTION
**Pull request by mzulqarnain1**
Relevant JIRA : https://openedx.atlassian.net/browse/BOM-2128

### CODE REVIEW

**Comment by mzulqarnain1** [comment]
I've created a sandbox here: https://tools-edx-jenkins.edx.org/job/sandboxes/job/CreateSandbox/34803/, build looks fine.

**Comment by mzulqarnain1** [comment]
I've filed an SRE ticket here: https://openedx.atlassian.net/browse/PSRE-466, for the SRE team to review the configuration changes.

**Review by mraarif — APPROVED** [review]

**Review by jmbowman — APPROVED** [review]

**Review by nadeemshahzad — APPROVED** [review]

**Comment by mzulqarnain1** [comment]
Image pushed to dockerhub successfully.

**Comment by jmbowman** [comment]
@nedbat We may want to cherrypick this one into Koa to get xqueue on Ubuntu 20.04 in devstack.

**Comment by nedbat** [comment]
I've cherry picked this to Koa.

**Pull request merged**
