### PR TITLE
Don't install or build ruby dependencies for edxapp

### PR DESCRIPTION
**Pull request by feanil**

### CODE REVIEW

**Comment by jibsheet** [comment]
:+1: assuming sandbox goes cleanly

**Comment by feanil** [comment]
Sandbox is here: https://feanil.sandbox.edx.org/

Both studio and LMS look good.

FYI:  @ormsbee @andy-armstrong

**Comment by ormsbee** [comment]
:sunglasses:

**Comment by ormsbee** [comment]
FYI @benpatterson

**Comment by benpatterson** [comment]
Damn I guess I need to submit a new PR against master now; my previous PR had been against Feanil's branch. Pls give me a heads up when you do this kinds

**Pull request merged**
