### PR TITLE
WIP: Feanil/small deployments

### PR DESCRIPTION
**Pull request by feanil**

### CODE REVIEW

**Comment by feanil** [comment]
@bradenmacdonald FYI, I'm not going to have time to work on this in the near future.  The current state is that the two machines come up and ansible runs cleanly but some services can't reach from the stateless machine to the stateful machine.

**Comment by bradenmacdonald** [comment]
@feanil Too bad. Thanks for the update. Between this and #3118, I'll see what we can do to get a working playbook.

**Comment by danielmcquillen** [comment]
@bradenmacdonald @feanil I was able to use these playbooks with good success on aws. A quick manual change to /etc/memcached.conf on datastores resolved the inaccessibility issue there. I found that by enabling the following ports between the security groups for stateless and datastore things seemed to work ok:  11211 memcached, 5672 for rabbitmq, 27017 for mongo db and 9200 for elasticsearch. @feanil was there something else that you thought needed resolving in terms of access between layers?
(I hope these playbooks get pushed forward as they're really useful for small sites like the one I'm working on...I hope I can contribute at some point. I added some other observations/questions [on the wiki](https://openedx.atlassian.net/wiki/display/OpenOPS/Hosting+edX+in+Production).)

**Comment by danielmcquillen** [comment]
@bradenmacdonald just curious, do you plan on expanding on Feanil's work?

**Comment by bradenmacdonald** [comment]
We have a need for this, so we will eventually help out in some way, whether that's finishing this, testing it, or converting our similar WIP PR.

@feanil are you planning to revisit this any time soon?

**Comment by feanil** [comment]
Unforutnately, I have not been able to get back to this and I think that will stay the case for a little while.  I'm about to head of on paternity leave so I don't think I'll be able to make progress on this.

**Comment by bradenmacdonald** [comment]
@feanil Ok, we will try to finish it up then. Thanks for the update.

**Comment by danielmcquillen** [comment]
Congrats @feanil !

**Comment by feanil** [comment]
Gonna close this as it is out of date and most of the useful things have landed I believe.

**Pull request closed without merging**
