### PR TITLE
Add box files for eucalyptus.2

### PR DESCRIPTION
**Pull request by nedbat**

### CODE REVIEW

**Comment by nedbat** [comment]
@gsong @edx/devops Let's get eucalyptus.2 out the door!

**Comment by gsong** [comment]
Looks good, let's merge and test. 👍

**Comment by jibsheet** [comment]
You can test using the Vagrantfile from the branch, no need to merge first.

The change looks fine 👍

**Comment by nedbat** [comment]
@jibsheet the new install_stack.sh script doesn't provide a way to use your own Vagrantfile, we need to add that to it.

**Comment by gsong** [comment]
@nedbat I suppose I could have just edited the shell script manually.

**Pull request merged**
