### PR TITLE
700 doesn't seem to match what Jenkins does.

### PR DESCRIPTION
**Pull request by e0d**
@jzoldak @benpatterson @arbabnazar

### CODE REVIEW

**Comment by arbabnazar** [comment]
:+1:

**Comment by benpatterson** [comment]
I'm looking at our Jenkins instance, and it appears to me that it will depend on whether or not it's a .jpi or a .hpi:

``` bash
$ stat -c "%a %n" ldap.jpi
644 ldap.jpi
$ stat -c "%a %n" ant
755 ant
$ stat -c "%a %n" ant.jpi
644 ant.jpi
$ stat -c "%a %n" thinBackup.hpi
700 thinBackup.hpi
$ stat -c "%a %n" subversion.jpi
644 subversion.jpi
$ stat -c "%a %n" ssh-agent.hpi
700 ssh-agent.hpi
```

**Comment by jzoldak** [comment]
oh snaps! :+1:

**Comment by e0d** [comment]
@benpatterson I think that's because our scripts add them hki and jenkins adds them as jki, but, from what I understand, the formats don't differ other than in name -- not an expert here though.  I made this to address a bug we were seeing rebuilding Jenkins which ultimately required another change too.  So, this may not be strictly needed, though still seems like an improvement.

**Comment by benpatterson** [comment]
Hmm FWIW I looked at plugins we manually added after Jenkins was built out, and saw the differences in permissions settings. I'd just encourage you to test the 700s and ensure those plugins can still do their jobs.

**Comment by arbabnazar** [comment]
@e0d @benpatterson @jzoldak this change worked for me. I was setting up the new jenkins and got these errors while this change fixed that:

```
java.io.IOException: Failed to expand /var/lib/jenkins/plugins/translation.jpi
        at hudson.ClassicPluginStrategy.explode(ClassicPluginStrategy.java:531)
        at hudson.ClassicPluginStrategy.createPluginWrapper(ClassicPluginStrategy.java:166)
        at hudson.PluginManager$1$3$1.run(PluginManager.java:267)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
        at jenkins.model.Jenkins$8.runTask(Jenkins.java:913)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: src '/var/lib/jenkins/plugins/translation.jpi' cannot be read.
        at org.apache.tools.ant.taskdefs.Expand.execute(Expand.java:130)
        at hudson.ClassicPluginStrategy.unzipExceptClasses(ClassicPluginStrategy.java:603)
        at hudson.ClassicPluginStrategy.explode(ClassicPluginStrategy.java:528)
        ... 10 more

Jan 19, 2016 11:23:56 AM jenkins.InitReactorRunner$1 onTaskFailed
SEVERE: Failed Inspecting plugin /var/lib/jenkins/plugins/build-pipeline-plugin.hpi
java.io.IOException: Failed to expand /var/lib/jenkins/plugins/build-pipeline-plugin.hpi
        at hudson.ClassicPluginStrategy.explode(ClassicPluginStrategy.java:531)
        at hudson.ClassicPluginStrategy.createPluginWrapper(ClassicPluginStrategy.java:166)
        at hudson.PluginManager$1$3$1.run(PluginManager.java:267)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
        at jenkins.model.Jenkins$8.runTask(Jenkins.java:913)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
```

**Comment by e0d** [comment]
@benpatterson we're merging.

**Comment by benpatterson** [comment]
Yep, @e0d, understood. Move the ball forward sir. If we encounter a problem related to this, we can tackle it at that time.

**Comment by e0d** [comment]
@benpatterson just to be clear, @arbabnazar tested this in a new Jenkins environment and it worked, also resolving a plugin loading issue we were seeing.

**Comment by benpatterson** [comment]
Yes...also understood @e0d. Glad @arbabnazar gave it a closer look...

**Pull request merged**
