### PR TITLE
using hosts all for commoncluster

### PR DESCRIPTION
**Pull request by jarv**

### CODE REVIEW

**Comment by feanil** [comment]
This will break how we build the clustering templates:
https://github.com/edx/configuration/blob/master/playbooks/roles/rabbitmq/templates/etc/rabbitmq/rabbitmq.config.j2

**Comment by jarv** [comment]
Tested and it looks like this will work fine with `--limit`

**Comment by jarv** [comment]
ran on stage from jenkins, config looks ok:

```
% Ansible managed: /edx/var/jenkins/jobs/run-ansible-stage/workspace/configuration/playbooks/edx-east/roles/rabbitmq/templates/etc/rabbitmq/rabbitmq.config.j2 modified on 2014-04-02 15:29:58 by jenkins on ip-10-0-100-98


[{rabbit,
  [{cluster_nodes, {['rabbit@ip-10-3-48-188','rabbit@ip-10-3-46-205','rabbit@ip-10-3-47-249'], disc}}]}].
```

**Comment by feanil** [comment]
:+1:

**Pull request merged**
