### PR TITLE
Remove ruby from jenkins-workers.

### PR DESCRIPTION
**Pull request by benpatterson**
@feanil @ormsbee @jibsheet @cpennington 

Also planning to run a packer build once I get stuff wired into edx-platform.

Note this change includes an improvement to allow us to build the venv based on a specific edx-platform branch. That'll help with testing this and similar kinds of changes.

### CODE REVIEW

**Comment by benpatterson** [comment]
Also note there are no builds running for this PR b/c I'm not doing this against the master branch.

**Comment by cpennington** [comment]
:+1:

**Comment by ormsbee** [comment]
:+1:

**Comment by feanil** [comment]
:+1:

**Comment by benpatterson** [comment]
Upstream branch was merged. I will re-submit this change against master.

**Pull request closed without merging**
