### PR TITLE
Enable Mongo auth

### PR DESCRIPTION
**Pull request by mrgnr**
Authentication for Mongo is [disabled by default](https://docs.mongodb.com/manual/tutorial/enable-authentication/). This PR adds the `MONGO_AUTH` variable, which is used to enable/disable auth in the config file. Auth is now enabled by default.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mrgnr! I've created [OSPR-1655](https://openedx.atlassian.net/browse/OSPR-1655) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by gsong** [comment]
@mrgnr Thank you for your PR. We appreciate you taking the time to make the contribution.

Please submit a [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf) to us so we can review this pull request. We realize it's additional work for a simple change in this case, but you only have to do this *once* and we're hoping you would make future contributions as well.

**Comment by mrgnr** [comment]
@gsong I work at Appsembler and have contributed to this repo before, so I believe that I'm covered by the contributor agreement. Could you check please?

**Comment by gsong** [comment]
@natea Vouch for @mrgnr?

**Comment by natea** [comment]
@gsong yes, we have a company-wide contributor's agreement, so this PR should be good to merge.

**Review by e0d — APPROVED** [review]
@jibsheet second look, but SGTM

**Comment by jibsheet** [comment]
There's no Travis test for these plays unfortunately.  I'd like to cut a sandbox and may need to run it against another type of machine also.  There's some bizarreness in how you cluster mongo, auth needs to be off, then later on, and timing/ordering need to match.  I'll try to look tomorrow, but may have to wait until next week.

@mrgnr Can you tell me which scenarios you've used the plays in with this change?
BTW - this also needs a Changelog entry I think.

**Comment by gsong** [comment]
@mrgnr I need your email address to add you to our contributor list.

**Comment by mrgnr** [comment]
@jibsheet We deployed these changes to all of our production deployments a few weeks ago. To my knowledge, every edX service that talks to Mongo presents credentials already, so enabling auth by default shouldn't cause any connection failures. We haven't observed any issues since deploying this. How should I go about updating the Changelog? Just push another commit with this PR?

@gsong My email address is morgan@appsembler.com.

**Comment by gsong** [comment]
@mrgnr You're all set from a contributor agreement perspective.

**Comment by jibsheet** [comment]
@mrgnr Yes - just push an additional commit with an addition to CHANGELOG.md
I'll try to get to this before the end of the week, between illness and snow days things have been crunched her.

**Comment by mrgnr** [comment]
@jibsheet Thanks, I updated the changelog (and rebased). Let me know if it looks alright :)

**Review by jibsheet — APPROVED** [review]

**Pull request merged**
