### PR TITLE
refactor: remove obsolete setting ENABLE_INSTRUCTOR_ANALYTICS

### PR DESCRIPTION
**Pull request by pdpinch**
ENABLE_INSTRUCTOR_ANALYTICS was removed from edx-platform in 2015.

Hopefully it won't come back again. 

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [x] ~~Are you adding any new default values that need to be overridden when this change goes live? If so:~~
    - [x] ~~Update the appropriate internal repo (be sure to update for all our environments)~~
    - [x] ~~If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.~~
    - [x] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [x] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

I thought about open edX operators. Since this setting was removed years ago, I don't think its removal here needs to be included in release notes

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pdpinch! I've created [OSPR-5808](https://openedx.atlassian.net/browse/OSPR-5808) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by pdpinch** [comment]
Clean-up PR in edx-platform at https://github.com/edx/edx-platform/pull/27720

**Review by sarina — APPROVED** [review]
Agree this doesn't need to make it into release notes.

**Comment by pdpinch** [comment]
Should this go in the Changelog? There is a mention the last time it was added at https://github.com/edx/configuration/blame/master/CHANGELOG.md#L160

**Comment by natabene** [comment]
@pdpinch Thank you for your contribution. Is this ready for our review?

**Comment by sarina** [comment]
Ah, @pdpinch in that case yeah let's add it

**Comment by sarina** [comment]
@natabene I'm reviewing this one

**Comment by sarina** [comment]
Hey @pdpinch let's add this to the CHANGELOG as you suggested and then I'll merge

**Comment by pdpinch** [comment]
Thanks @sarina this should be good to go now.

**Comment by openedx-webhooks** [comment]
@pdpinch 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6423&entry.1484655318=https://github.com/pdpinch&entry.752974735=2021-05-26+12:27&entry.1917517419=2021-06-05+19:54&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
