### PR TITLE
Update requirements installation commands for course discovery.

### PR DESCRIPTION
**Pull request by peter-fogg**
See edx/course-discovery@7482d0e49645476a260588d21a78a8e53d2b4cc6.

@clintonb

### CODE REVIEW

**Comment by edx-webhook** [comment]
# PR Cover Letter
- [ ] A detailed description of the changes in the body of the PR
- [ ] If available, a link to the relevant JIRA ticket in the body of the PR
  - `[PROJ-XXXX](https://openedx.atlassian.net/browse/PROJ-XXXX)`

# Sandbox
- [ ] Build a sandbox for your branch and add a link here

# Testing
- [ ] i18n
- [ ] RTL
- [ ] Unit, integration, acceptance tests as appropriate
- [ ] Analytics
- [ ] Performance
- [ ] Database migrations are backwards-compatible

# Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [ ] Code review #1
- [ ] Code review #2
- [ ] UI strings/error msgs review
- [ ] UX review
- [ ] Accessibility review
- [ ] Product review

# DevOps assistance
If it's needed, or even if you suspect it might be needed, do any/all these things as early as possible. Don't surprise devops right before merging! For example, touching envs/aws.py or or envs/common.py are dead giveaways that you'll need assistance when pushing your changes out. Things that require devops attention include, but are not limited to:
- configuration changes
- feature flags
- migrations
Ways to get devops attention, pick-and-choose whichever is most appropriate for your specific PR:
- [ ] Tag devops on your PR (`@edx/devops`), either for review (more specific to devops = better) or just a general FYI
- [ ] File a support ticket

FYI: Tag anyone who might be interested in this PR here.

# Post-review
- [ ] Squash commits

**Comment by clintonb** [comment]
:+1:

**Comment by feanil** [comment]
What's the rationale for this?  I'd rather the make targets across all our IDAs are the same for consistency.

**Comment by clintonb** [comment]
This is making them the same. The IDA template needs to be updated; but, until course discovery, `make requirements` always installed local requirements.

**Comment by feanil** [comment]
:+1:

**Pull request merged**
