### PR TITLE
Add a toggle for the bulk enrollment view

### PR DESCRIPTION
**Pull request by fghaas**
This feature enables Staff users to bulk-enroll learners into one or multiple courses, via the REST API.

It is defined in the bulk_enroll LMS Django app, and is toggled on and off in the LMS' master urls.py:

https://github.com/edx/edx-platform/tree/master/lms/djangoapps/bulk_enroll
https://github.com/edx/edx-platform/blob/master/lms/urls.py

Settings reference:
https://openedx.atlassian.net/browse/OSPR-1835

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @fghaas! I've created [OSPR-4857](https://openedx.atlassian.net/browse/OSPR-4857) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@fghaas Thank you for your contribution. @marcotuts Would you like to review this first?

**Comment by fghaas** [comment]
@natabene @marcotuts Taking the liberty to follow up on this — I try to do this once a week, just so you know I haven't lost interest in getting this landed. 🙂

**Comment by natabene** [comment]
@fghaas Thanks for letting me know. Please note that we have very little bandwidth right now, unfortunately, so we won't be able to review this very soon.

**Comment by fghaas** [comment]
Weekly follow-up on this one, courtesy tag for @natabene and @marcotuts.

**Comment by fghaas** [comment]
@natabene @marcotuts Checking in on this one again, after a month.

**Comment by fghaas** [comment]
Same consideration here as on #5886: if there's no interest in adding this toggle, then operators can also set it via overriding all of `EDXAPP_FEATURES`, and including `ENABLE_BULK_ENROLLMENT_VIEW: True` in it. So if there is no bandwidth available to review this patch in the foreseeable future, maybe it's a better idea to close this PR and recommend that approach instead?

**Review by fredsmith — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@fghaas 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/5887&entry.1484655318=https://github.com/fghaas&entry.752974735=2020-07-24+06:41&entry.1917517419=2020-09-17+13:32&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by fredsmith** [comment]
@fghaas sorry I've been so slow in merging these.  We (edx.org) are no longer managing feature toggles with ansible, as we use edx/hermes to pull a simplified config out of git.

**Pull request merged**
