### PR TITLE
Fix xqwatcher sudoers

### PR DESCRIPTION
**Pull request by carsongee**
@e0d and @itsbenweeks I created jails for course numbers and those have dots.  It turns out sudoers.d ignores any file with a dot in it and doesn't give a warning of any kind so it wasn't an apparmor problem.  I also removed the sudoers files for the jail users since they don't need a password to execute any command as themselves.  I am also fairly certain we don't want xqwatcher or the codejail users to be able to execute kill and pkill as root.

### CODE REVIEW

**Comment by e0d** [comment]
:+1:

**Comment by nedbat** [comment]
@e0d @carsongee is it clear who will merge this?

**Comment by e0d** [comment]
Carson can merge, it's his PR and he has the bits.

**Comment by carsongee** [comment]
yummy yummy merge bits

**Pull request merged**
