### PR TITLE
Updated Insights Code Location

### PR DESCRIPTION
**Pull request by clintonb**
The repo is been restructured.

Depends on edx/edx-analytics-dashboard#243.

### CODE REVIEW

**Comment by clintonb** [comment]
Might help to notify someone! @e0d @maxrothman @feanil @fredsmith

**Comment by fredsmith** [comment]
:+1:

**Comment by maxrothman** [comment]
FYI: we'll have to remember this when [this pr](https://github.com/edx/configuration/pull/1835) lands on master.

**Comment by clintonb** [comment]
Changed the structure of the restructure. This is no longer needed.

**Pull request closed without merging**
