### PR TITLE
[BD-6] Use pip3 in the Makefile

### PR DESCRIPTION
**Pull request by morenol**
Use pip3 in the Makefile in order to force the usage of python3

## Reviewers
- [ ] @awais786 
- [ ] @ericfab179

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @morenol! I've created [BLENDED-450](https://openedx.atlassian.net/browse/BLENDED-450) to keep track of it in Jira.  More details are on the [BD-06](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1594000004/BD-06+Python+3.8+Upgrade) project page.

When this pull request is ready, tag your edX technical lead.

**Review by awais786 — APPROVED** [review]

**Comment by nedbat** [comment]
I think i see the problem in the native instructions that get some stuff from master ("sudo bash" should be "sudo -E bash").

What problem was this originally solving? We should be able to make changes on master.

**Comment by morenol** [comment]
> What problem was this originally solving?

Not a problem in specific, I am just trying to remove the usage of python2.7

**Comment by nedbat** [comment]
These commands should all be running in a virtualenv, so "pip" does refer to Python 3, no?

**Comment by morenol** [comment]
> These commands should all be running in a virtualenv, so "pip" does refer to Python 3, no?

Yes, if the virtualenv is created with python3. Currently it is being created with python2.7 

https://github.com/edx/configuration/blob/4c8a5e98370270cb231339aebc3d7bca2e3a8763/util/install/ansible-bootstrap.sh#L144

**Comment by nedbat** [comment]
That is something to fix!

**Pull request merged**
