### PR TITLE
DEVOPS-3094 - Require HTTPS access to insights.edx.org

### PR DESCRIPTION
**Pull request by arbabnazar**
@feanil can you please review it. Thanks

### CODE REVIEW

**Comment by feanil** [comment]
@arbabnazar can you please make the same change for programs as well.

FYI: @mulby @clintonb @jimabramson @rlucioni

**Comment by arbabnazar** [comment]
@feanil please review.

**Comment by feanil** [comment]
:+1:

**Comment by clintonb** [comment]
Can you update the ansible-role-django-ida role as well? It generates the nginx config for future IDAs.

:+1:

**Comment by clintonb** [comment]
FYI @mattdrayer

**Comment by feanil** [comment]
@clintonb it looks like the ansible-role-django-ida role doesn't generate the NGINX template at all right now... this makes sense since it is not part of the role but a new template that is added to the existing NGINX role.

**Pull request merged**
