### PR TITLE
datajam: remove dependency on hostsupdater

### PR DESCRIPTION
**Pull request by mulby**
Note that now users will have to manually include the following line in their /etc/hosts file:

192.168.33.10  preview.localhost

We will have to update the readme accordingly.

@brianhw, @rocha

### CODE REVIEW

**Comment by jtauber** [comment]
why was the dependency removed? was it causing problems?

**Comment by mulby** [comment]
Yup.  It has failed for me, Brian and Carlos intermittently.  One user has also reported it failing for her quite consistently.

See this thread: https://github.com/cogitatio/vagrant-hostsupdater/issues/16

**Comment by mulby** [comment]
@wedaly - any thoughts on this?

**Comment by brianhw** [comment]
Looks good to me.  (This matters if people are using preview, and for the Xblock development we hope they will be creating some kind of course in studio.)

**Comment by wedaly** [comment]
Weird, I haven't had an issue with it.  I wonder if it's a Linux/Mac OS X thing?  Definitely makes sense to remove from the datajam Vagrant image, but I'd like to get it working in devstack so preview works out of the box.

**Pull request merged**
