### PR TITLE
[SE-3613] Python2.7 deprecation means htpasswd now requires python3-passlib

### PR DESCRIPTION
**Pull request by pomegranited**
Native deployments on `xenial` which require basic authentication are failing with the following error:

```
TASK [nginx : Write out htpasswd file] *********************************************
2020-11-11 05:20:33+1030 INFO
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named 'passlib'
2020-11-11 05:20:33+1030 ERROR
failed: [213.32.72.33] (item={u'state': u'present', u'password': u'9449ecc70b8ee44c', u'name': u'397bf39ead3d3751'}) => {"ansible_loop_var": "item", "changed": false, "item": {"name": "397bf39ead3d3751", "password": "9449ecc70b8ee44c", "state": "present"}, "msg": "Failed to import the required Python library (passlib) on edxapp-periodic-buil-appserver-1039's Python /usr/bin/python3. Please read module documentation and install in the appropriate location"}
```

**JIRA tickets**: [OSPR-5124](https://openedx.atlassian.net/browse/OSPR-5124)

**Discussions**: [Periodic master build failure report](https://groups.google.com/g/open-edx-btr-notifications/c/Qy68eTORzto/m/eynvc_SMAwAJ)

**Sandbox URL**: TBD - sandbox is being provisioned.

* LMS: https://configpr6143.sandbox.opencraft.hosting/
* Studio: https://studio.configpr6143.sandbox.opencraft.hosting/

**Merge deadline**: ASAP, as this is breaking master deployments.

**Testing instructions**:

No independent testing instructions -- core review and the successful deployment of the sandbox is sufficient.

**Reviewers**
- [ ] @mtyaka 

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [x] <strike>Are you adding any new default values that need to be overridden when this change goes live?</strike> N/A If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [x] <strike>If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)</strike>? N/A
  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [x] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release? N/A

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pomegranited! I've created [OSPR-5124](https://openedx.atlassian.net/browse/OSPR-5124) to keep track of it in JIRA.

As a core committer in this repo, you can merge this once the pull request is approved per the [core committer reviewer requirements](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529675973/Open+edX+Core+Committers#Reviews-and-Ownership) and according to the agreement with your edX Champion.

**Comment by mtyaka** [comment]
Thanks for the fix @pomegranited :+1:

- [x] I tested this: I verified that the sandbox built successfully and that the htpasswd file was written.
- [x] I read through the code
- [ ] I checked for accessibility issues
- [ ] Includes documentation

**Comment by pomegranited** [comment]
FYI @nedbat @feanil  This is a fix for a periodic master build failure. I can't merge it as core committer because I created it. Can we get it reviewed soon?

**Review by nedbat — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@pomegranited 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6143&entry.1484655318=https://github.com/pomegranited&entry.752974735=2020-11-11+03:39&entry.1917517419=2020-11-16+15:54&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by openedx-webhooks** [comment]
@nedbat, @feanil: thought you might like to know that pomegranited merged this pull request.

**Comment by natabene** [comment]
@pomegranited Thank you all for merging this quickly.

**Comment by nedbat** [comment]
This broke sandbox builds here at edX, so I'm reverting it in #6148

**Comment by pomegranited** [comment]
@nedbat @fredsmith Ach bummer! 
Could you provide more details about what broke on the sandboxes?
Perhaps the sandbox image has an older version of `htpasswd`?

**Comment by nedbat** [comment]
It failed on this task: https://github.com/edx/configuration/blob/7c7bd4778fd4257e7c9b73e908b51d8197839305/playbooks/roles/nginx/tasks/main.yml#L278

```
ImportError: No module named passlib.apache
```
```
Failed to import the required Python library (passlib) on ip-10-3-147-5's Python /usr/bin/python.
```

**Comment by pomegranited** [comment]
@nedbat Ok, I have a theory..  11 days ago, https://github.com/edx/configuration/pull/6132 removed python2.7 from the standard `openedx_native.yml` playbook. However, I assume edX are still running ansible-bootstrap.sh to provision sandboxes, and since these are still xenial, [they're still getting python2.7 installed on them](https://github.com/edx/configuration/blob/master/util/install/ansible-bootstrap.sh#L141-L142).

My theory is that ansible's `htpasswd` module is using python2.7 if it's available, which requires `python-passlib`. If python2.7 isn't available, then it uses python3.x, which requires `python3-passlib`.

I can see a few ways to handle this:

1. Install both `python3-passlib` and `python-passlib` on xenial.
1. Remove python2.7 from [ansible-bootstrap.sh](https://github.com/edx/configuration/blob/master/util/install/ansible-bootstrap.sh#L141-L142) xenial installations, along with the `python3-passlib` change in this PR.
   I don't know what flow-on effects this could cause with your sandboxes or other installations that use this script, and I'd need your help to set up a sandbox using this change to make sure nothing else breaks.
1. Revert https://github.com/edx/configuration/pull/6132 so that native installations that are not running ansible-bootstrap.sh still get python2.7 installed.
  This is moving backwards, so doesn't feel right.

Which would be most acceptable to you?

**Pull request merged**
