### PR TITLE
Update Vagrantfiles for dogwood.2

### PR DESCRIPTION
**Pull request by nedbat**

### CODE REVIEW

**Comment by nedbat** [comment]
@edx/devops very simple, right?

**Comment by jibsheet** [comment]
👍  This was another "Changes only in the configuration repo" release, right?

**Comment by nedbat** [comment]
@jibsheet there are changes in edx-platform also: https://github.com/edx/edx-platform/compare/named-release/dogwood.1...named-release/dogwood.rc

**Comment by jibsheet** [comment]
Ok, but nothing worth a new base box over I take it

**Comment by nedbat** [comment]
Right, there's no reason for a new base box.

**Pull request merged**
