### PR TITLE
feat: Add IPv6 support to MFE's

### PR DESCRIPTION
**Pull request by mrtmm**
This is a follow-up change to https://github.com/edx/configuration/pull/6557 which added an option to make
nginx listen on both, IPv4 and IPv6 wildcard addresses.

This change adds that option for MFE's as well.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mrtmm! I've created [OSPR-6159](https://openedx.atlassian.net/browse/OSPR-6159) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by fghaas — COMMENTED** [review]
This change looks good to me. The fact that it uses an `NGINX_` variable despite not having a dependency on the `nginx` role should not be a road block, since this role already does use other `NGINX_` variables (namely, `NGINX_ENABLE_SSL` and `NGINX_REDIRECT_TO_HTTPS`).

**Comment by mrtmm** [comment]
@natabene, would you mind running the tests? Otherwise, this is ready for review, thanks!

**Comment by natabene** [comment]
@mrtmm Thank you for your contribution. I kicked off the tests.

**Comment by mrtmm** [comment]
Thanks @natabene, the tests passed now, this is ready for review.

**Review by arbabkhalil — CHANGES_REQUESTED** [review]
Please also listen following ports on ipv6 as well
```
listen {{ MFE_SSL_NGINX_PORT }} ssl;
```
and 
```
listen {{ MFE_DEPLOY_SSL_NGINX_PORT }} ssl;
```

**Comment by mrtmm** [comment]
Thanks @arbabkhalil! I've made the changes, please review at your convenience.

**Review by arbabkhalil — APPROVED** [review]
Looks good to me.

**Comment by openedx-webhooks** [comment]
@mrtmm 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6589&entry.1484655318=https://github.com/mrtmm&entry.752974735=2021-10-22+09:21&entry.1917517419=2021-10-27+09:44&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
