### PR TITLE
Merge Dogwood changes (so far) into master.

### PR DESCRIPTION
**Pull request by nedbat**

### CODE REVIEW

**Comment by nedbat** [comment]
@feanil look ok? Would you like it squashed?

**Comment by feanil** [comment]
:+1:   let's leave the commits as they are to reduce conflicts in future merges of dogwood into master.

**Comment by nedbat** [comment]
@feanil @jibsheet you said you were testing this? Is it good to merge?

**Comment by feanil** [comment]
@nedbat bring the :train: into the :station: :+1:

**Pull request merged**
