### PR TITLE
Fix typo on $vagrant_mount_location

### PR DESCRIPTION
**Pull request by agriffis**
## Configuration Pull Request

Make sure that the following steps are done before merging
- [ ] @devops team member has commented with :+1:
- [ ] are you adding any new default values that need to be overriden when this goes live?  
  - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
  - [ ] Add an entry to the CHANGELOG.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @agriffis! I've created [OSPR-1453](https://openedx.atlassian.net/browse/OSPR-1453) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Review by jibsheet — APPROVED** [review]
@nedbat This seems obviously correct, but as this is your team's script, I'll leave merging for you.

**Comment by gsong** [comment]
@agriffis Thank you for your PR. We appreciate you taking the time to make the contribution.

Please submit a [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf) to us so we can review this pull request. We realize it's additional work for a simple change in this case, but we're hoping you would make future contributions as well.

**Comment by agriffis** [comment]
@gsong I sent in the CLA yesterday. Let me know if I need to resend, thanks.

**Comment by nedbat** [comment]
@agriffis Thanks, and welcome to the Open edX family! :)

**Pull request merged**
