### PR TITLE
Facilitate enabling course export to Git

### PR DESCRIPTION
**Pull request by fghaas**
The `edxapp` role defines both `EDXAPP_GIT_REPO_DIR` (the directory where courses being imported from a Git repo are staged) and `EDXAPP_GIT_REPO_EXPORT_DIR` (the reverse, for export to a Git repo).

It also populates the LMS/CMS variables `GIT_REPO_DIR` and `GIT_REPO_EXPORT_DIR`, but only creates the directory for the former.

Fix the `edxapp` role so that it creates both directories.

In addition, Studio export to Git relies on the `ENABLE_EXPORT_GIT` feature being set, which previously could only be toggled by defining (overriding) `EDXAPP_FEATURES` altogether. Add a separate toggle named `EDXAPP_ENABLE_EXPORT_GIT`, defaulting to `false`.

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @fghaas! I've created [OSPR-4865](https://openedx.atlassian.net/browse/OSPR-4865) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

Please let us know once your PR is ready for our review and all tests are green.

**Comment by natabene** [comment]
@fghaas Thank you for your contribution. Is this ready for edX review?

**Comment by fghaas** [comment]
@natabene Yes, I believe it is. 

There's one additional thing I did run into: if the Git repository does not allow pushing via HTTPS, then the working alternative is to push via SSH. That, in turn, requires that a `.ssh/id_rsa` file be placed into the home directory of `common_web_user` (typically `www-data`). 

It's not feasible to include that in the `edxapp` role, though, since it would clash with https://github.com/edx/configuration/blob/8adaf01fd73e7bf428107343f65a8862b48a3c5e/playbooks/roles/gitreload/tasks/deploy.yml#L8-L13 — so if I were to add a similar task to `edxapp`, then anyone using both `edxapp` and `gitreload` _with different Git identities_ would inevitably break either Git export, or Git reload. So I suggest not to introduce that potential source of a notoriously difficult-to-debug configuration problem.

My suggestion for someone needing to support Git export via SSH would thus be to also deploy the `gitreload` role (in addition to `edxapp`), and then just not enabling any webhooks on their Git repo.

**Comment by natabene** [comment]
@fghaas Thanks for letting me know.  I am lining this up for engineering review.

**Comment by fghaas** [comment]
Weekly follow-up on this one, courtesy tag for @natabene.

**Comment by fghaas** [comment]
If anyone is interested in getting this fixed, I would much appreciate any feedback on this one.

**Review by pdpinch — APPROVED** [review]
Thanks @fghaas -- I didn't know anyone else cared! 

We're currently managing this outside of ansible in our deploys, but this would give us more flexibility.

**Comment by fghaas** [comment]
@pdpinch 

> Thanks @fghaas -- I didn't know anyone else cared!

I can make the identical statement. 😉

I actually have a couple of other thoughts on the Git export functionality — are you OK with me taking this to Discourse and tagging you in the discussion?

**Comment by fghaas** [comment]
@natabene, following up on this one. Can you give me an idea on when this might see a review?

**Comment by pdpinch** [comment]
@fghaas sorry I missed your follow up from 9/2. I would love to discuss export to git on Discourse and/or Slack.

**Comment by natabene** [comment]
@fghaas Sorry, I am not sure, I will check with the team. Do you have a deadline to meet?

**Comment by fghaas** [comment]
@natabene No I don't, I just wouldn't mind having one less local patch to carry, considering the fix is rather trivial. :) 

And if @pdpinch's comment is any indication, other people would like to use this too.

**Review by fredsmith — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@fghaas 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/5891&entry.1484655318=https://github.com/fghaas&entry.752974735=2020-07-27+12:52&entry.1917517419=2020-09-17+13:26&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
