### PR TITLE
Jarv/ansible

### PR DESCRIPTION
**Pull request by jarv**

### CODE REVIEW

**Comment by carsongee** [comment]
Ah the ouroboros role ;)

**Comment by feanil** [comment]
Why do we need an ansible role instead of a configuration role?  Shouldn't we install ansible from pip but download the configuration repo?

**Comment by jarv** [comment]
after discussing this with fenail I'm going to rename it to edx_ansible

**Comment by jarv** [comment]
@feanil @e0d @carsongee @jrbl @wedaly 
In this pull I am cleaning up the playbooks/ dir, removing old plays that we shouldn't need at that level.

**Comment by feanil** [comment]
:+1:

**Pull request merged**
