### PR TITLE
Fixed Docker issues for discovery service

### PR DESCRIPTION
**Pull request by clintonb**
- Corrected WSGI package path
- Using a single database user

### CODE REVIEW

**Comment by clintonb** [comment]
@cpennington @fredsmith please review

**Comment by cpennington** [comment]
Ah, nice. So, when running docker, this just uses the db user setup in the mysql container for all of the migration steps?

**Comment by clintonb** [comment]
Yep. One user for (allthethings).

**Comment by cpennington** [comment]
Awesome. :+1:

**Pull request merged**
