### PR TITLE
AN-7716 Update grading policy api url to new api

### PR DESCRIPTION
**Pull request by thallada**
## Configuration Pull Request

The grading policy api moved from the deprecated course_structure api to it's own grades api. [Insights has a PR](https://github.com/edx/edx-analytics-dashboard/pull/572) to deal with this new API, but this variable needs to be updated for production.

Make sure that the following steps are done before merging
- [ ] @devops team member has commented with :+1:
- [ ] are you adding any new default values that need to be overriden when this goes live?  
  - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
  - [ ] Add an entry to the CHANGELOG.

Can devops ensure that this variable will not be overwritten by anything in the secure vars repo?

### CODE REVIEW

**Review by dsjen — APPROVED** [review]
👍

**Comment by thallada** [comment]
@edx/devops could I get a review on this?

**Review by jibsheet — APPROVED** [review]
I assume you know where this URL should point.

There's no secure override, not sure what else to review.

**Comment by thallada** [comment]
Thanks! The new API endpoint was created in a recent release of edx-platform.

I'll go ahead and merge then.

**Pull request merged**
