### PR TITLE
Specify mongo replica set protocolVersion

### LINKED ISSUE #87: [edx/configuration] Mongo 4.0 plays are not idempotent
### Description

This is a follow-up to #47.  When running the native playbook a second time, the user will run into the following:

```
TASK [mongo_4_0 : configure replica set] ***************************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/root/.ansible/tmp/ansible-tmp-1624872124.1895957-19738-170392710700769/AnsiballZ_mongodb_replica_set:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\n  import imp\nTraceback (most recent call last):\n  File \"/tmp/ansible_mongodb_replica_set_payload_bozb8srj/__main__.py\", line 121, in reconfig_replset\n  File \"/usr/local/lib/python3.8/dist-packages/pymongo/database.py\", line 738, in command\n    return self._command(sock_info, command, slave_ok, value,\n  File \"/usr/local/lib/python3.8/dist-packages/pymongo/database.py\", line 626, in _command\n    return sock_info.command(\n  File \"/usr/local/lib/python3.8/dist-packages/pymongo/pool.py\", line 683, in command\n    return command(self, dbname, spec, slave_ok,\n  File \"/usr/local/lib/python3.8/dist-packages/pymongo/network.py\", line 159, in command\n    helpers._check_command_response(\n  File \"/usr/local/lib/python3.8/dist-packages/pymongo/helpers.py\", line 160, in _check_command_response\n    raise OperationFailure(errmsg, code, response, max_wire_version)\npymongo.errors.OperationFailure: Support for replication protocol version 0 was removed in MongoDB 4.0. Downgrade to MongoDB version 3.6 and upgrade your protocol version to 1 before upgrading your MongoDB version, full error: {'operationTime': Timestamp(1624872122, 2), 'ok': 0.0, 'errmsg': 'Support for replication protocol version 0 was removed in MongoDB 4.0. Downgrade to MongoDB version 3.6 and upgrade your protocol version to 1 before upgrading your MongoDB version', 'code': 103, 'codeName': 'NewReplicaSetConfigurationIncompatible', '$clusterTime': {'clusterTime': Timestamp(1624872122, 2), 'signature': {'hash': b'\\xaf*\\x8d\\xc2\\x9d\\xc4R>\\xdf\\x1an?\\xe8No\\xbe\\x8b\\x02ho', 'keyId': 6977701412083859460}}}\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1624872124.1895957-19738-170392710700769/AnsiballZ_mongodb_replica_set\", line 114, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1624872124.1895957-19738-170392710700769/AnsiballZ_mongodb_replica_set\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1624872124.1895957-19738-170392710700769/AnsiballZ_mongodb_replica_set\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/usr/lib/python3.8/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/lib/python3.8/imp.py\", line 169, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 604, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 783, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_mongodb_replica_set_payload_bozb8srj/__main__.py\", line 385, in <module>\n  File \"/tmp/ansible_mongodb_replica_set_payload_bozb8srj/__main__.py\", line 269, in update_replset\n  File \"/tmp/ansible_mongodb_replica_set_payload_bozb8srj/__main__.py\", line 123, in reconfig_replset\nAttributeError: 'OperationFailure' object has no attribute 'message'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

Originally reported on #ops, [here](https://openedx.slack.com/archives/C08B4LZEZ/p1624873238025800) and [here](https://openedx.slack.com/archives/C08B4LZEZ/p1625104718027800).

### Acceptance criteria

* Running the native playbook a second time does not cause the above failure and does not have any other detectably harmful side effects.

### Estimated effort

4 hours of work by a developer versed in Ansible and Mongo

### Bounties offered

None, yet.

### PR DESCRIPTION
**Pull request by mtyaka**
The `mongo_4_0.yml` playbook is not idempotent. If run twice on the same mongo server, it will fail with the following error the second time:

```
pymongo.errors.OperationFailure: Support for replication protocol version 0 was removed in MongoDB 4.0.
Downgrade to MongoDB version 3.6 and upgrade your protocol version to 1 before upgrading your MongoDB version
```

Mongo 4 no longer supports `protocolVersion: 0`. While creating a new replica set in Mongo 4 automatically defaults to `protocolVersion: 1`, we need to explicitly specify `protocolVersion: 1` when reconfiguring an existing replica set, even if the existing replica set is already on `protocolVersion: 1`.

This fixes https://github.com/openedx/build-test-release-wg/issues/87.

**Test instructions**:

1. Run the `mongo_4_0.yml` playbook on a fresh server using default values.
2. Re-run the playbook using the same ansible variables.
3. Verify that the playbook completes successfully when run the second time.

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mtyaka! I've created [OSPR-5902](https://openedx.atlassian.net/browse/OSPR-5902) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by clemente** [comment]
@mtyaka thanks; a few questions:
- what Ubuntu version should be used when running the playbook? I'm running it against Ubuntu 20.04 and found a few errors in packages (e.g. it wants `python-minimal`, but `apt` provides `python2-minimal`). I solved them but I found more, like a `systemd` one: `fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service disable-transparent-hugepages: "}`, though the playbooks have correctly installed `/etc/systemd/system/disable-transparent-hugepages.service`. I can fix the small errors but I'd prefer to use the right versions.
- you applied the change to 4.0, but there are also 4.2 and 4.4 playbooks which also wouldn't support version 0. Do we need the change there too?
- is it enough to test this in a single server or should the testing procedure include deploying 3 servers in a replica set? (Please include commands if so)
- I guess that this playbook won't be run to upgrade a cluster from a procotol-version-0 (e.g. running Mongo 3.6) to a protocol-version-1 (e.g. running Mongo 4). That step [requires extra steps](https://docs.mongodb.com/manual/reference/replica-set-protocol-versions/#modify-replica-set-protocol-version). I assume the playbook will be run against MongoDB 4 with protocol-version-1 each time

For reference I'm using `ansible-playbook mongo_4_0.yml --connection=local -i localhost, -e COMMON_ENABLE_AWS_ROLE=false`, with no extra variables.

**Comment by mtyaka** [comment]
Thanks for looking at this @clemente!

> * what Ubuntu version should be used when running the playbook? I'm running it against Ubuntu 20.04 and found a few errors in packages (e.g. it wants `python-minimal`, but `apt` provides `python2-minimal`). I solved them but I found more, like a `systemd` one: `fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service disable-transparent-hugepages: "}`, though the playbooks have correctly installed `/etc/systemd/system/disable-transparent-hugepages.service`. I can fix the small errors but I'd prefer to use the right versions.

Hmm... I was running it on Ubuntu 20.04, but I wasn't running the `mongo_4_0.yml` playbook in isolation - I actually ran the full `opened_native.yml` playbook to be able check that the LMS works fine after re-running the playbook. I was trying to shorten the testing instructions, but it looks like that wasn't the best idea. Sorry about that :( If the errors aren't easy to solve, you might have to run the full `openedx_native.yml` as well. You could also use Ocim to build your instance, check [this instance](https://manage.opencraft.com/instance/27350/edx-appserver/19685/) for how to configure it so that it deploys mongo to localhost. After the first VM is successfully built, you'd manually have to re-run the `mongo_4_0.yml` playbook on it using the configuration repository configured in `/edx/app/edx_ansible` and copying ansible vars from Ocim.

> * you applied the change to 4.0, but there are also 4.2 and 4.4 playbooks which also wouldn't support version 0. Do we need the change there too?

The main goal of this PR is to fix the native installation of lilac. 4.0 is the version used in lilac, which is why I only looked at 4.0. 4.2 and 4.4 might also require the same change, but I don't have time to look into those.

> * is it enough to test this in a single server or should the testing procedure include deploying 3 servers in a replica set? 

The `openedx_native.yml` playbook only uses the mongo_4_0 role [when using mongo on localhost](https://github.com/edx/configuration/blob/8e2c77b2fa41a12ff359a1baa0136b0ced40a2f1/playbooks/openedx_native.yml#L89). The main goal of this PR is to fix the native installation of lilac, which is why I don't think we need to test this a on 3 server replica set.

> * I guess that this playbook won't be run to upgrade a cluster from a procotol-version-0 (e.g. running Mongo 3.6) to a protocol-version-1 (e.g. running Mongo 4). That step [requires extra steps](https://docs.mongodb.com/manual/reference/replica-set-protocol-versions/#modify-replica-set-protocol-version). I assume the playbook will be run against MongoDB 4 with protocol-version-1 each time

Yes, I think we can assume this will be run on Mongo 4. If for any reason you try to run it on a protocol version 0 replica set, the command will fail with an error explaining that you need to manually upgrade your replica set on Mongo 3.6 first, so while running on a protocol version 0 replica set won't work, it will fail with a clear error message and won't harm your existing replica set.

**Comment by clemente** [comment]
Thanks @mtyaka, then it makes sense. I asked in our JIRA whether we need to test it still once more in Ocim.

**Comment by arbrandes** [comment]
This has been confirmed to work by @cmltaWt0 [on Slack](https://openedx.slack.com/archives/C01AGTSB1LL/p1625725752151600?thread_ts=1625666089.151000&cid=C01AGTSB1LL).

@pomegranited, tagging you as core committer: this is looking good.  @nedbat, @regisb, objections to merging it?

**Review by regisb — APPROVED** [review]
LGTM go-go merge!

**Comment by natabene** [comment]
Thank you all. Let me know if you need any help or input from the SRE team.

**Comment by pomegranited** [comment]
This is working fine, thanks @mtyaka :+1: 

Could you please ensure that future commits follow the format laid out in [OEP-0051](https://github.com/edx/open-edx-proposals/pull/189) ?

- [x] I tested this using the PR test instructions on the new fal-2100.opencraft.hosting sandbox server, which had mongo installed locally.
- [x] I read through the code
- [x] <strike>I checked for accessibility issues</strike> N/A
- [x] Includes documentation</strike> N/A
- [ ] Commit structure follows [OEP-0051](https://github.com/edx/open-edx-proposals/pull/189) -- noted.

**Review by pomegranited — APPROVED** [review]
Approved this as core committer, will merge in 2 days if no objection from @edx/devops .

**Comment by natabene** [comment]
@pomegranited I just verified that SRE doesn't actively monitor notifications, sent by this Github handle, so it is best to call out your CC champions.

**Review by jdmulloy — APPROVED** [review]

**Comment by jdmulloy** [comment]
Seems fine to me.

**Comment by pomegranited** [comment]
@natabene Ah, good to know! I'll ping my champions directly next time.

Thank you @jdmulloy for approving this! Merging now.

**Comment by openedx-webhooks** [comment]
@mtyaka 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/6468&entry.1484655318=https://github.com/mtyaka&entry.752974735=2021-07-06+08:15&entry.1917517419=2021-07-15+07:49&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
