### PR TITLE
using YAML syntax for ansible tasks

### PR DESCRIPTION
**Pull request by arbabnazar**
@edx/devops kindly review. Thanks

### CODE REVIEW

**Comment by arbabnazar** [comment]
@e0d  @feanil kindly review. Thanks

CC: @edx/devops

**Comment by feanil** [comment]
:+1:

**Comment by dianakhuang** [comment]
This seems to be causing problems with sandbox builds. The error message we're seeing is:

```
19:39:40 TASK: [git_clone | Validate git protocol] ************************************* 
19:39:40 fatal: [ora2.sandbox.edx.org] => with_items expects a list or a set
19:39:40 
19:39:40 FATAL: all hosts have already failed -- aborting
```

You can see it in this build: http://jenkins.edx.org:8080/job/ansible-provision/8020/

**Comment by feanil** [comment]
Investigating where it's from this PR now, Test sandbox here: http://jenkins.edx.org:8080/job/ansible-provision/8021/console  

If that fixes it, I'll revert this.

**Comment by arbabnazar** [comment]
@feanil @dianakhuang fixed here https://github.com/edx/configuration/pull/3194

**Pull request merged**
