### PR TITLE
Make AMQP vhost and TLS configurable for xqueue/celery

### PR DESCRIPTION
**Pull request by bdero**
This PR adds in an easily overrideable default for [RABBIT_VHOST](https://github.com/edx/xqueue/blob/0ad917c714d5797becf2b8a2c7e6b4b5de934809/xqueue/aws_settings.py#L38) in xqueue.
The celery broker configuration [similarly allows](https://github.com/edx/configuration/blob/0934017d942f991dcf59fd8d63affb81311aa3f5/playbooks/roles/edxapp/defaults/main.yml#L816) for overriding the vhost like this.

It also adds in config overrides necessary for supporting TLS connections between xqueue/celery and an external RabbitMQ provider.

See also: https://github.com/edx/xqueue/pull/118 and https://github.com/edx/edx-platform/pull/13958

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @bdero! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?number=3447&repo=edx%2Fconfiguration

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @bdero! I've created [OSPR-1561](https://openedx.atlassian.net/browse/OSPR-1561) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Review by feanil — APPROVED** [review]
@edx/devops second review.

**Review by jibsheet — APPROVED** [review]

**Comment by feanil** [comment]
@bdero since we are adding a bunch of new vars, would you mind adding a changelog entry as well.  Merge at your convenience when that's done.

**Comment by haikuginger** [comment]
:+1:

- [x] I tested this as part of a separate PR
- [x] I read through the code
- [x] ~~I checked for accessibility issues~~ N/A
- [x] Includes documentation

**Comment by bdero** [comment]
Thanks for the reviews! I added the changelog entries before merging.

**Pull request merged**
