### PR TITLE
Decouple applications that do not have remote config from edx_service's ansible config render

### PR DESCRIPTION
**Pull request by syedimranhassan**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by syedimranhassan** [comment]
@coryleeio FYI

- There is one role (veda_web_frontend) that had dependencies on edx_django_service and don't have remote config enabled. So, I have moved edx_django_service (variables, dependencies, tasks and templates) to veda_web_frontend role to remove it's dependencies on edx_django_service role.

- For edx_service role there were multiple roles that had dependencies on edx_service role. So, I made a separate role (edx_rendering_service) to remove their dependencies on edx_service.

**I have set new role name edx_renering_service. You may suggest any other if it doesn't sounds good.**

**Review by coryleeio — CHANGES_REQUESTED** [review]
This seems reasonable - is it possible add edx_service as a meta role of  from edx_rendering_service to avoid the duplication?

Could you also rename edx_rendering_service to edx_service_with_rendered_config?

I don't want someone to think this service is actually doing any rendering.

**Comment by coryleeio** [comment]
I am wondering if we could avoid duplicating all of the edx_django_service role specific stuff into the veda_frontend role by creating a  edx_django_service_role_with_rendered_config role which calls edx_django_service and appends the render.

Then we wouldn't need to decouple veda from edx_django_service to edx_service, as that is a much larger change.

**Comment by syedimranhassan** [comment]
@coryleeio I have added new role **edx_django_service_with_rendered_config** which calls **edx_service_with_rendered_config** and this calls **edx_service**
The flow will be this
**edx_django_service_with_rendered_config** (contains edx_django logic) --> **edx_service_with_rendered_config** (contains rendering logic only and calls edx_service) --> **edx_service** (perform further actions)

**Review by coryleeio — APPROVED** [review]

**Comment by coryleeio** [comment]
This looks right thanks!

**Pull request merged**
