### PR TITLE
Show alert when using unsupported browser

### PR DESCRIPTION
**Pull request by jagonzalr**
[OSPR-2148](https://openedx.atlassian.net/browse/OSPR-2148)

Configuration Pull Request
---

Adds the default value for showing an alert when using an unsupported browser ```EDXAPP_ENABLE_UNSUPPORTED_BROWSER_ALERT```
```EDXAPP_UNSUPPORTED_BROWSER_ALERT_VERSIONS```

This PR is related to this [PR](https://github.com/edx/edx-platform/pull/17216)

Reviewers
- Code review: ¯_(ツ)_/¯

cc @pomegranited

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @jagonzalr! I've created [OSPR-2148](https://openedx.atlassian.net/browse/OSPR-2148) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by pomegranited** [comment]
@jagonzalr Since these settings are just added to `EDXAPP_FEATURES`, we can get away without a configuration change, and so it's ok to close this PR.

**Comment by jagonzalr** [comment]
Cool @pomegranited will close.

**Comment by openedx-webhooks** [comment]
@jagonzalr Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4286&entry.1484655318=https://github.com/jagonzalr&entry.752974735=2018-01-17+10:24&entry.1917517419=2018-01-25+07:54&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
