### PR TITLE
upgrade GoCD

### PR DESCRIPTION
**Pull request by nadeemshahzad**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

### CODE REVIEW

**Comment by nadeemshahzad** [comment]
@edx/devops Please review

**Comment by feanil** [comment]
@nadeemshahzad if the go-server now relies on openjdk then we don't need to install oraclejdk as a dependency anymore correct?

**Comment by feanil** [comment]
@nadeemshahzad I think that's the opposite of the change that I was suggesting.  I think the thing to do is remove the oraclejdk dependency because the gocd package depends on openjdk-8

**Comment by nadeemshahzad** [comment]
@feanil Oraclejdk and openjdk are both needed for go-server. Openjdk is installed with go-server, previous versions till 17.1.0 relies on  'openjdk-7-jre-headless' . Upgrade to next release depends on  openjdk-8-jre-headless missing from14.04 repo. Setting openjdk repository resolved the dependencies and upgrade works, explicit installation of package is not needed so it is removed

**Comment by nadeemshahzad** [comment]
@feanil Yes, we can remove the oraclejdk dependency as GoCD doc says it depends on openjdk. I was testing the change on a new sandbox instance but openjdk repository is stop working for openjdk-8 package even go-agent docker containers 'https://github.com/gocd/docker-gocd-agent-ubuntu-14.04/blob/master/Dockerfile' depends on this repo. are failing. I am digging this issue as it was all good since this morning. I think we can block this PR until we resolve this issue.

**Comment by nadeemshahzad** [comment]
@feanil Repository is updated for 14.04 https://launchpad.net/~openjdk-r/+archive/ubuntu/ppa
and dependency 'ca-certificate-java' required a change reported as bug 
https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/1706442

**Comment by nadeemshahzad** [comment]
@feanil Changes are rolled back in Openjdk repo. things are working now. I have removed oraclejdk dependency from role.

**Review by feanil — APPROVED** [review]

**Pull request merged**
