### PR TITLE
Fix forums looking for unicorn in the wrong place

### PR DESCRIPTION
**Pull request by maxrothman**
@edx/devops 

FYI @clintonb

### CODE REVIEW

**Comment by feanil** [comment]
:+1:

**Comment by clintonb** [comment]
What's the issue here? The binstub executable should be no different than that installed by rbenv.

**Comment by maxrothman** [comment]
@clintonb I think I see the issue. I deployed a new version of configuration without updating forums. Is forums ready to release?

**Comment by clintonb** [comment]
@maxrothman maybe. All of my changes have been to tests and rake tasks. @e0d updated `nokogiri`. I'm unsure of any actual functionality that has been changed since the last release.

**Comment by maxrothman** [comment]
Are you planning to deploy it soon?

**Comment by clintonb** [comment]
I have no plans to deploy anytime soon. My changes were all in preparation for upgrading to Elasticsearch 1.x. That work was unscheduled, and has been set aside while I deal with other tasks.

**Comment by maxrothman** [comment]
@clintonb and I discussed deploying new forums in-person.

**Pull request closed without merging**
