### PR TITLE
Add script to graph Ansible playbook role dependencies

### PR DESCRIPTION
**Pull request by gsong**
Add a script to parse Ansible playbook YAML and generate a role dependency graph.

Make sure that the following steps are done before merging

  - [ ] @devops team member has commented with :+1:

/cc @edx/devops  @edx/ospr

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @gsong! I've created [OSPR-2091](https://openedx.atlassian.net/browse/OSPR-2091) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by nedbat** [comment]
Sorry for the bot noise!

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @gsong! I've created [OSPR-2356](https://openedx.atlassian.net/browse/OSPR-2356) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by openedx-webhooks** [comment]
@gsong Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/3475&entry.1484655318=https://github.com/gsong&entry.752974735=2016-11-16+17:37&entry.1917517419=2018-04-19+20:19&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
