### PR TITLE
Jibsheet/multiple worker cluster detection

### PR DESCRIPTION
**Pull request by jibsheet**
Improve active_instances_in_asg.py to handle multiple worker ASGs, detecting when Asgard is deleting a cluster.  https://openedx.atlassian.net/browse/OPS-2035

@edx/devops please review, I'm going to inject this into the sprint and close because it's causing too many disruptions

@clintonb @rlucioni @jcdyer I believe you've all run into this obstacle (long running worker process keeps 2 ASGs alive, preventing jenkins from running management commands).  This should resolve that.

### CODE REVIEW

**Comment by rlucioni** [comment]
Thank you @jibsheet!

**Review by clintonb — APPROVED** [review]
Thanks!

Nit: squash your commits

**Review by fredsmith — APPROVED** [review]
:shipit:

**Comment by fredsmith** [comment]
@brittneyexline @mattdrayer, @jibsheet fixed your bug on tuesday, but I hadn't reviewed it.  Should be all set as soon as this merges.

**Pull request merged**
