### PR TITLE
Remove unused SUBDOMAIN_BRANDING setting from edxapp config

### PR DESCRIPTION
**Pull request by rlucioni**
@cpennington @edx/devops please review. Corresponding edx-platform PR is at https://github.com/edx/edx-platform/pull/11000.

### CODE REVIEW

**Comment by jibsheet** [comment]
@rlucioni You should add these vars to your DEVOPS ticket, I remember seeing them when grepping for the other subdomain thing this morning.

**Comment by rlucioni** [comment]
@jibsheet done.

**Comment by feanil** [comment]
can you also add a change log item since others in the community might be using these vars.

**Comment by rlucioni** [comment]
@feanil change logged.

**Comment by feanil** [comment]
:+1:

**Pull request merged**
