### PR TITLE
switches the security task file to a role that is included by common

### PR DESCRIPTION
**Pull request by jarv**

### CODE REVIEW

**Comment by jarv** [comment]
@carsongee @feanil @e0d This moves the security task file into a separate role so it is easier to apply by itself. thoughts?

**Comment by feanil** [comment]
Why not just a security tag?

**Comment by jarv** [comment]
Having it in its own role does a couple things

1) gives us the ability to run it from a play without using tags
2) allows us to run it outside of common

**Comment by e0d** [comment]
Makes sense ot me, :+1:

**Comment by carsongee** [comment]
:+1: from me

**Pull request merged**
