### PR TITLE
Fix broken sqoop mirror

### PR DESCRIPTION
**Pull request by dominicfollett**
Carfab service is unavailable. Rather use official Apache Mirror for Sqoop.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @dominicfollett! I've created [OSPR-1315](https://openedx.atlassian.net/browse/OSPR-1315) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation.     If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by nedbat** [comment]
@dominicfollett thanks for taking care of this detail.  I know it seems like a lot for such a small change, but can you send in a signed contributor agreement? We're hopeful you'll be making more contributions in the future :)

**Comment by gsong** [comment]
@dominicfollett Couple things we need from you:
1. Please submit a [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf) to us so we can review this pull request. We realize it's additional work, but you only have to do this _once_ and we're hoping you would make future contributions as well.
2. Please rebase your changes on top of `master`, looks like you've merged in changes from another branch, which makes this PR impossible to review.

**Comment by gsong** [comment]
Closing due to lack of response from contributor.

**Pull request closed without merging**
