### PR TITLE
Make notifier user service request page size configurable

### PR DESCRIPTION
**Pull request by kluo**
This setting was bottlenecking our notifier digest job performance. This will allow us to configure it. Works with https://github.com/edx/notifier/pull/75
@iloveagent57

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @kluo! I've created [OSPR-3016](https://openedx.atlassian.net/browse/OSPR-3016) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@kluo Thank you for your contribution. Please let us know once it is ready for review.

**Comment by kluo** [comment]
@natabene It is ready for review

**Review by iloveagent57 — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@kluo 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/4972&entry.1484655318=https://github.com/kluo&entry.752974735=2019-01-26+01:32&entry.1917517419=2019-01-28+20:49&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
