### PR TITLE
configure global tools script for build jenkins

### PR DESCRIPTION
**Pull request by estute**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
-------------------------------------------------
This configures the script introduced in https://github.com/edx/jenkins-configuration/pull/99

### CODE REVIEW

**Comment by estute** [comment]
I am temporarily using my branch of jenkins-configuration until that has been merged into master

**Review by jmbowman — APPROVED** [review]

**Comment by estute** [comment]
CI trigger is just from me switching the branch back to master

**Comment by estute** [comment]
This PR has been updated according to the work in https://github.com/edx/jenkins-configuration/pull/102

**Comment by jmbowman** [comment]
👍

**Pull request merged**
