### PR TITLE
The ownership of the theme folder needs to be changed as well

### PR DESCRIPTION
**Pull request by pdehaye**
Before the patch, the {{app_base_dir}}/themes/{{edxapp_theme_name}} folder ends up in the /opt/wwc folder but the owner of that folder is still root. This is now changed to www-data

### CODE REVIEW

**Comment by feanil** [comment]
This seems like a good fix.  @jtauber has pdehaye signed the release?

**Comment by pdehaye** [comment]
I haven't

**Comment by pdehaye** [comment]
@feanil : Would appreciate a reply on my question on the edx-code mailing list if you know the answer...

**Comment by jarv** [comment]
closing this pull, please re-open on an updated branch after you have signed a contributor agreement https://github.com/edx/edx-platform/wiki/How-To-Contribute

**Pull request closed without merging**
