### PR TITLE
Capture both kinds of node bin dirs

### PR DESCRIPTION
**Pull request by jibsheet**
Nodeenv contains npm
node_modules is where npm installs things which are used
say paver test_js and friends

Caused by 7ca232dc83e5d6570b5aec42d3b33a5e25c95e5f

It's possible a better solution is to ensure that nodeenvs/edxapp/bin/activate is sourced in bashrc instead

### CODE REVIEW

**Comment by jibsheet** [comment]
I'd be interested in @bjacobel and @arizzitano 's thoughts on sourcing bin/activate vs jamming the path into PATH

FYI @edx/devops I wrote https://openedx.atlassian.net/browse/OPS-1917 which we should groom in the morning and I'll need someone to help unbreak js testing on new devstacks.

**Comment by jibsheet** [comment]
Oh, nevermind, sourcing nodeenv doesn't get your npm's destination directory.
All packaging is terrible.
I suspect this is the correct solution but someone will need to assist in testing and reading commit messages and explanations.

**Comment by jibsheet** [comment]
paver test_js works on a devstack provisioned with this

**Comment by bjacobel** [comment]
This looks good to me, I'll have my laptop spin up a devstack using this during demos to check it out.

**Comment by bjacobel** [comment]
Actually... I might not know how to have two devstacks at once.

**Comment by jibsheet** [comment]
@bjacobel  What I do is 
```
cd devstack
vagrant halt
mkdir ../devstack2
cd ../devstack2
Maybe copy all the git repos from ../devstack to ../devstack2
curl down Vagrantfile from https://raw.githubusercontent.com/edx/configuration/master/vagrant/release/devstack/Vagrantfile
Add CONFIG_VER="jibsheet/node-devstacks" on line 38 after CONFIG_VER is defined to master and before ansible-playbook is called
```

I can help configure / debug in person if needed, I'm in the office today.

**Review by feanil — APPROVED** [review]

**Pull request merged**
