### PR TITLE
Fixup config version in vagrant devstack

### PR DESCRIPTION
**Pull request by singingwolfboy**
@stephensanchez does this work for you?

### CODE REVIEW

**Comment by stephensanchez** [comment]
:+1: yup! Is release what we used to do, or master? Release makes sense, just was curious.

**Comment by singingwolfboy** [comment]
@stephensanchez it used to be release. The `${OPENEDX_RELEASE-release}` syntax in bash _should_ mean "Use the contents of the `$OPENEDX_RELEASE` variable, or if its unset, use the string `release`", but I guess something was getting confused. This syntax, while more verbose, should also be clearer.

**Comment by stephensanchez** [comment]
oh, I get ya. OK well looks good to me then!

**Comment by fredsmith** [comment]
I agree the old syntax should have worked.  This is clearer, though.  Looks good to me. :+1:

**Pull request merged**
