### PR TITLE
By deafult, nginx looks for ELB headers to forward

### PR DESCRIPTION
**Pull request by jibsheet**
In the case of sandboxes, nginx listens on 443/80 and needs to pass
along the scheme of the request so that django knows if the client is
connecting over HTTP or HTTPS
DEVOPS-2074

### CODE REVIEW

**Comment by maxrothman** [comment]
Ticket # should be in the commit msg

**Comment by feanil** [comment]
That name is misleading but you know this.  :+1:

**Comment by jibsheet** [comment]
@maxrothman ticket # is in the commit message

**Comment by maxrothman** [comment]
Ah, I think we're trying to do msgs like "DEVOPS-####: this is some stuff"

**Comment by maxrothman** [comment]
Otherwise, :+1:

**Comment by jibsheet** [comment]
Putting DEVOPS-####: in the subject of the git commit eats a lot of valuable space, but since I needed to fix a typo in the message, I moved it.

I have generally included it in the body of the commit message in recent work.

We should discuss this and write a policy, but not in this PR.

**Pull request merged**
