### PR TITLE
Update AUTHORS

### PR DESCRIPTION
**Pull request by riccardomurri**
Add myself to the AUTHORS list, as per "contributing" instructions.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @riccardomurri! I've created [OSPR-406](https://openedx.atlassian.net/browse/OSPR-406) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams. 

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ('this must be merged by XX date', and why that is)
- partner information ('this is a course on edx.org')
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the Github pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

We can't start reviewing your pull request until you've submitted a [signed contributor agreement](http://code.edx.org/individual-contributor-agreement.pdf) or indicated your institutional affiliation and added yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS) file. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst) file for more information.

**Comment by riccardomurri** [comment]
Needed in PR #1843  and #1844

**Comment by sarina** [comment]
@riccardomurri - for this and all PRs, you'll need to [rebase your pull request](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request). If you look at your commit history in all your PRs, they contain commits that aren't yours.

**Comment by sarina** [comment]
@riccardomurri now that we have the agreement we can merge this, but this has to be rebased.

**Comment by riccardomurri** [comment]
@sarina Rebased against `master`

**Comment by sarina** [comment]
thanks!

**Pull request merged**
