### PR TITLE
fix: remove JWT_DECODE_HANDLER override

### PR DESCRIPTION
**Pull request by robrap**
Remove the override of JWT_DECODE_HANDLER in the settings files, because it already matches the default set in base.py, and when we wish to remove this custom
jwt_decode_handler, it is possible that this setting will unnecessarily cause an error in the future. See
https://github.com/openedx/ecommerce/blob/b5fa2e55e3d4f5f8224d381317177cf4086b35a6/ecommerce/settings/base.py#L449

The JWT_AUTH dictionary should not be replaced as a whole, but should only replace keys that are declared, according to this:
https://github.com/openedx/ecommerce/blob/b5fa2e55e3d4f5f8224d381317177cf4086b35a6/ecommerce/settings/production.py#L51-L53

Note: This change is very similar to https://github.com/edx/edx-internal/pull/8163 which already landed.

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A SRE team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a SRE ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/spaces/SRE/pages/28967861/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Review by pshiu — APPROVED** [review]
Thanks, @robrap!

**Comment by pshiu** [comment]
Note: We are having a temporary issue with the Jenkins job that builds the ecommerce Docker image for devstack.

Until this PR can be incorporated into devstack via that Jenkins job, developers experiencing issues like:

```
ImportError: Could not import 'ecommerce.extensions.api.handlers.jwt_decode_handler' for API setting 'JWT_DECODE_HANDLER'. ModuleNotFoundError: No module named 'ecommerce.extensions.api.handlers'.
```

after bringing up a new container of the ecommerce devstack can make it work by temporarily adding:

```
'JWT_DECODE_HANDLER': 'edx_rest_framework_extensions.auth.jwt.decoder.jwt_decode_handler',
```
to [this dictionary](https://github.com/openedx/ecommerce/blob/43b7e87b68882bf7c4d74bd9503a83e822a99ed3/ecommerce/settings/devstack.py#L34-L48) on their local. (Apologies for the inconvenience.)

**Comment by robrap** [comment]
@pshiu: Will this PR temporarily fix the issue for everyone without special instructions? https://github.com/openedx/ecommerce/pull/3958. I did not test.

**Comment by pshiu** [comment]
Great idea, thanks @robrap! Just gave a thumb and added an AC to https://github.com/edx/upgrades/issues/109.

**Comment by robrap** [comment]
Great @pshiu. As I noted, this is **untested**, so just make sure it resolves your issue. Thanks.

**Comment by pshiu** [comment]
@robrap, yep, @jsnwesson and I had tested an almost identical patch right before I saw your comment.

**Pull request merged**
