### PR TITLE
use COMMON_HTPASSWD_USER and COMMON_HTPASSWD_PASS 

### PR DESCRIPTION
**Pull request by fmyzjs**
use COMMON_HTPASSWD_USER and COMMON_HTPASSWD_PASS 
based on: 
XQUEUE_BASIC_AUTH_USER: "{{ COMMON_HTPASSWD_USER }}"
XQUEUE_BASIC_AUTH_PASSWORD: "{{ COMMON_HTPASSWD_PASS }}"
defined on roles/xqueue/defaults/main.yml

### CODE REVIEW

**Comment by sarina** [comment]
@feanil heads up

**Comment by jarv** [comment]
lgtm, @fmyzjs  have you signed a contributor agreement?

**Comment by fmyzjs** [comment]
@jarv Of course

**Comment by jarv** [comment]
@fmyzjs thanks! and sorry for the delay. In the future if you can mention that you have signed the CLA in the description it will help us move faster for those of us with short memories :) thanks again!

**Comment by sarina** [comment]
@jarv we keep track of this in the https://github.com/edx/repo-tools/blob/master/people.yaml file.

Also, you can view the PR page http://dash.openedx.org/age.html - users without a contributor's agreement have a red exclamation point next to their names. When the OS team triages an OS pull request, we will mention the contributor's agreement and get that process started if we notice the red mark.

**Comment by jarv** [comment]
@sarina thanks that's helpful.

**Comment by fmyzjs** [comment]
@jarv you are welcome

**Pull request merged**
