### PR TITLE
xserver sandbox apparmor

### PR DESCRIPTION
**Pull request by fredsmith**
Make sure that xserver is running code under apparmor.

### CODE REVIEW

**Review by feanil — APPROVED** [review]

**Comment by nedbat** [comment]
@fredsmith @feanil This should work on Hawthorn, right?  The file renaming threw me off a bit, but the key fix here is to use `xserver_venv_sandbox_dir` in the paths in the apparmor config, right?

**Comment by nedbat** [comment]
("work" meaning, once we cherry-pick it to Hawthorn, the fix will work there too.)

**Comment by feanil** [comment]
@nedbat yes, this should get ported to hawthorn and yes, the change in the path for the app-armor profile is the key change.

**Comment by nedbat** [comment]
This has been cherry-picked onto Hawthorn.

**Pull request merged**
