### PR TITLE
Update mongo role link from 2.6 to 3.0

### PR DESCRIPTION
**Pull request by feanil**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

### CODE REVIEW

**Review by fredsmith — APPROVED** [review]

**Comment by nedbat** [comment]
I believe this PR is because Felipe Montoya said that mongo 3.2 is required, but 2.6 is still the default.

I'm confused: why can i install Hawthorn and make courses without this pr? In what way is 3.2 required, or in what way is 2.6 the default?

My Hawthorn.1 rc3 installation has:
```
[@ip-172-31-39-15:~] $ mongo
MongoDB shell version: 3.2.16
connecting to: test
Welcome to the MongoDB shell.
For interactive help, type "help".
For more comprehensive documentation, see
	http://docs.mongodb.org/
Questions? Try the support group
	http://groups.google.com/group/mongodb-user
rs0:PRIMARY>
bye
```

**Comment by feanil** [comment]
Most of our playbooks were already updated to use 3.2 directly however the base role symlink is still used in the mongo.yml playbook and a few other standalone playbooks that are used is larger installations.  It's for those installations that this update is needed.

**Comment by nedbat** [comment]
OK, so cherry-pick onto Hawthorn, right?

**Comment by feanil** [comment]
yes, please cherry-pick this to hawthorn @nedbat

**Comment by nedbat** [comment]
This has been cherry-picked onto Hawthorn.

**Pull request merged**
