### PR TITLE
Fix failover issue in forum service

### PR DESCRIPTION
**Pull request by viadanna**
Description
=========

This PR adds a watchdog for the forum service that restarts it every time it fails to recover from a MongoDB failover when using replica sets.

Testing
----------

1. Checkout this branch and deploy the forum playbook `forum.yml` to the devstack:
```
$ ansible-playbook -vvv -i hosts playbooks/forum.yml -e "disable_edx_services=true"
```

2. Check the forum-watchdog files have been installed correcly:
```
/edx/app/forum/forum-watchdog.sh
/edx/app/supervisor/conf.available.d/forum-watchdog.conf
```

3. Watch the forum-watchdog log file to make sure it has been started:
```
$ tail -f /edx/var/log/supervisor/forum-watchdog-stdout.log
```

4. Trigger the watchdog:
```
$ echo "Mongo::Error::OperationFailure - not master and slaveOk=false (13435)" >> /edx/var/log/supervisor/forum-stderr.log
```

5. Make sure the watchdog restarts the forum service:
```
[28/08/2019 20:02:56] Forum WatchDog service started
[28/08/2019 20:35:19] Forum Failure detected - Restarting forum service...
forum: stopped
forum: started
```

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @viadanna! I've created [OSPR-3818](https://openedx.atlassian.net/browse/OSPR-3818) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@viadanna Thank you for your contribution. Please let me know once this is ready for our review.

**Review by giovannicimolin — APPROVED** [review]
:+1:

- [x] I tested this: 
1. I followed the testing instructions on local Vagrant server.
2. I checked that the forum service is reset when the failover issue happens :heavy_check_mark: 
3. I spawned a master sandbox with this configuration branch.
4. I checked that the watchdog script was correctly deployed and restarted the forum service when the issue was triggered :heavy_check_mark: 
- [x] I read through the code
- [ ] ~~I checked for accessibility issues~~ NA
- [ ] ~~Includes documentation~~ NA

@viadanna Thanks for upstreaming this.

For edX reviewer: this might be hard to reproduce, as the server recovers sometimes when a failover is performed. Using a 3 server MongoDB configuration, performing a failover enough times to rotate between all the servers makes the issue happen. 

The version of the mongodriver used on the comments service is likely the main cause of this issue, and can't be easily updated because there are too many ruby gems that don't support any newer version.

**Comment by viadanna** [comment]
@natabene this is good for edX review.

**Comment by natabene** [comment]
@edx/devops Please review this when you have a chance.

**Comment by fredsmith** [comment]
this isn't the appropriate place for this functionality.  if this failure is unrecoverable, the service should shut down and supervisor will restart it.

**Comment by openedx-webhooks** [comment]
@viadanna Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/configuration&entry.867055334=https://github.com/edx/configuration/pull/5389&entry.1484655318=https://github.com/viadanna&entry.752974735=2019-09-02+13:54&entry.1917517419=2020-01-24+20:10&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
