### PR TITLE
fix: change default mongodb replica set to null

### PR DESCRIPTION
**Pull request by kaustavb12**
(cherry picked from commit 1ad3ecf3e73f28f8077b5aa8577ddc64b34dcbf6)
Cherry-pick from master PR #6831
This PR changes the default value of EDXAPP_MONGO_REPLICA_SET from empty string ("") to null.

This is required due to unpinnig of pymongo via https://github.com/openedx/edx-platform/pull/30569
As mentioned in that PR, pymongo >= 3.11 only accepts None as replica set if standalone MongoDB instance is used.
Empty string is not accepted as a valid value for replica set.

Other information
---
Private Ref: [BB-6773](https://tasks.opencraft.com/browse/BB-6773)

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A SRE team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a SRE ticket with details.
    - [x] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/spaces/SRE/pages/28967861/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @kaustavb12!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by navinkarkera** [comment]
:+1:
- [x] I tested this: checked deployment of nutmeg instance
- [x] I read through the code
- [ ] I checked for accessibility issues
- [ ] Includes documentation
- [ ] I made sure any change in configuration variables is reflected in the corresponding client's `configuration-secure` repository.

**Comment by mphilbrick211** [comment]
Hi @kaustavb12 and @navinkarkera - thank you for this submission! Is this ready for review?

**Comment by kaustavb12** [comment]
@mphilbrick211 Yes, this is ready for review.

**Comment by mphilbrick211** [comment]
Hi @adzuci! Flagging this for your review/merge.

**Comment by mphilbrick211** [comment]
Hi @adzuci! Friendly ping on this :)

**Comment by mphilbrick211** [comment]
Hi @adzuci! Do you have an ETA on when you'll be able to review/merge?

**Comment by mphilbrick211** [comment]
Hi @adzuci - just checking for an update on this.

**Review by adzuci — APPROVED** [review]

**Comment by mphilbrick211** [comment]
Hi @adzuci! Would you mind merging this? Thanks!

**Comment by openedx-webhooks** [comment]
@kaustavb12 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/configuration&entry.867055334=https://github.com/openedx/configuration/pull/6832&entry.1484655318=https://github.com/kaustavb12&entry.752974735=2022-11-11+02:48&entry.1917517419=2023-04-10+08:42&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
