### PR TITLE
Add flag to disable/enable New Relic

### PR DESCRIPTION
**Pull request by tusbar**
Set to `'false'` to disable.

### CODE REVIEW

**Comment by feanil** [comment]
@tusbar is there a corresponding PR on the comment_service to honor this?

**Comment by tusbar** [comment]
@feanil there’s not need, newrelic uses the environment variable to determine whether the agent should start or not.

**Comment by feanil** [comment]
@e0d this looks good to me.

**Comment by hkim823** [comment]
@feanil or @e0d you guys can decide to merge this in or not.

**Comment by feanil** [comment]
@hkim823 perhaps you can review this?

**Comment by hkim823** [comment]
:+1:

**Comment by tusbar** [comment]
Thank you. :+1:

**Pull request merged**
