### PR TITLE
Pin things installed by devstack and fullstack

### PR DESCRIPTION
**Pull request by nedbat**
Trying to prevent future version slippage from breaking installations.

### CODE REVIEW

**Comment by nedbat** [comment]
@edx/devops are we ok with specific version pinning of things like supervisor?

**Comment by maxrothman** [comment]
Are those all the latest versions? 👍

**Comment by nedbat** [comment]
Those are the latest versions, as pypi reports them.

**Comment by maxrothman** [comment]
:shipit:

**Pull request merged**
