### PR TITLE
WIP: OPS-3164 NGINX maintenance page

### PR DESCRIPTION
**Pull request by jdmulloy**
This won't be merged, I just need feedback on my changes.

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).

### CODE REVIEW

**Comment by feanil** [comment]
Why do you need to move it into each location block?

**Comment by feanil** [comment]
Since this is a jinja template, should we just do a jinja include of a single shared block?

**Comment by jdmulloy** [comment]
I moved the maintenance page if to the location that proxies to edxapp, so that static assets will still be served normally. This is to prevent the CDN from caching the maintenance page.

In all the locations that have "api" in them I added an if to serve a 503 if the maintenance page exists. Right now it's the standard nginx error page, I can do some work to make it serve empty content, or perhaps an empty json object which would be ```{}```

**Comment by jdmulloy** [comment]
@feanil I can do a shared block.

**Comment by feanil** [comment]
Empty page with the right response code is fine for API endpoints I think.  Can we serve the maintenance page from s3 like we have in the past?

**Comment by feanil** [comment]
@jdmulloy how does this reconcile with https://github.com/edx/configuration/blob/master/playbooks/roles/nginx/templates/edx/app/nginx/sites-available/s3_maintenance.j2

**Comment by jdmulloy** [comment]
@feanil we might be able to serve a page from s3, there is some code in here for it, but I don't yet know how it works. It looks like it requires rerunning ansible to reconfigure nginx, whereas the OSPR solution just requires puting a file in place, which could be done by ansible. I'll try figuring out the s3 solution.

**Pull request closed without merging**
