### PR TITLE
E0d/sec 90

### PR DESCRIPTION
**Pull request by e0d**
Configuration Pull Request
---

Make sure that the following steps are done before merging

  - [ ] @devops team member has commented with :+1:
  - [ ] are you adding any new default values that need to be overriden when this goes live?  
    - [ ] Open a ticket (DEVOPS) to make sure that they have been added to secure vars.
    - [ ] Add an entry to the CHANGELOG.

### CODE REVIEW

**Comment by feanil** [comment]
:+1:

**Comment by feanil** [comment]
@e0d looks like this one already has the changes from https://github.com/edx/configuration/pull/3495

**Comment by e0d** [comment]
Yeah, this PR needed conflict resolution in the fork as it touches the same lines as #3495 Will merge this to bring both changes to master.

**Comment by feanil** [comment]
Sounds good.

**Review by jibsheet — APPROVED** [review]

**Pull request merged**
