### PR TITLE
Update node version for learner_portal.

### PR DESCRIPTION
**Pull request by dianakhuang**
Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Comment by dianakhuang** [comment]
@Tj-Tracy Is this role even used anymore? The repo it references does not seem to exist any longer.

**Comment by Tj-Tracy** [comment]
This repo does still exist, its just been split into 2: https://github.com/edx/frontend-app-learner-portal-programs, and an enterprise version.

As far as I know, this setting is still used by both.

**Review by brittneyexline — COMMENTED** [review]
seems ok but i don't fully understand the impact of these changes firsthand, and at this point the impact is more important for masters because enterprise isn't live with the learner portal. @adamstankiewicz may be able to shed more light?

**Comment by adamstankiewicz** [comment]
The upgrade to Node 12 should be fine; I've been running the code locally on 12 for a bit now.

That said, I'm not exactly sure if/how this role is being used. @Tj-Tracy do you mind shedding some light on that? According to the commit message, it was related to enabling the learner portal in sandbox builds.

I'm guessing we should probably update the referenced repo to https://github.com/edx/frontend-app-learner-portal-programs, though.

**Comment by Tj-Tracy** [comment]
Correct, this is strictly used in the tasks needed to build the sandbox for a `learner_portal`. It's only being used to install node on the sandbox: https://github.com/edx/configuration/blob/539e8da2740c0a14c96427097690955663a0575a/playbooks/roles/learner_portal/tasks/main.yml#L38 Since this doesn't really have anything to do with the repo itself, the upgrade is fine.

The only difference splitting the repo should have made is you can't build a sandbox for the enterprise version of `learner_portal`. I can talk about that more sometime if you ever need a sandbox. @adamstankiewicz

**Review by fredsmith — APPROVED** [review]

**Comment by matthugs** [comment]
This has been being tested in edX developers' devstacks for the month of November. See https://github.com/edx/frontend-app-learner-portal-programs/pull/159

**Pull request merged**
