### PR TITLE
Populate ENABLE_OAUTH2_PROVIDER in [cl]ms.env.yaml.

### PR DESCRIPTION
**Pull request by agaylard**
**Description**: This change adds a variable: `EDXAPP_ENABLE_OAUTH2_PROVIDER`.

This allows the `FEATURES` list to be populated with `ENABLE_OAUTH2_PROVIDER` set to the value of `EDXAPP_ENABLE_OAUTH2_PROVIDER`.

Previously, it was necessary to edit `/edx/etc/edxapp/[cl]ms.env.yaml` and add/set `ENABLE_OAUTH2_PROVIDER` manually. 

Ansible users needing to control `ENABLE_OAUTH2_PROVIDER` can now set `EDXAPP_ENABLE_OAUTH2_PROVIDER` to "true" to override the default, which is "false".

**Dependencies**: None

**Screenshots**: Not applicable.

**Sandbox URL**: Not applicable.

**Partner information**: Not applicable.

**Testing instructions**:
1. Run `sudo /edx/bin/ansible-playbook -c local -i "localhost," edx_sandbox.yml` and confirm successfule completion.
2. Run `grep OAUTH2 /edx/etc/edxapp/*yaml`; the result should be

`/edx/etc/edxapp/cms.env.yaml:    ENABLE_OAUTH2_PROVIDER: false`
`/edx/etc/edxapp/lms.env.yaml:    ENABLE_OAUTH2_PROVIDER: false`
(Prior to this change, grep would return no output.)

**Reviewers**
@omarkhan, TBD

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @agaylard! It looks like you're a member of a company that does contract work for edX. If you're doing this work as part of a paid contract with edX, you should talk to edX about who will review this pull request. If this work is not part of a paid contract with edX, then you should ensure that there is an OSPR issue to track this work in [JIRA](https://openedx.atlassian.net), so that we don't lose track of your pull request.

To automatically create an OSPR issue for this pull request, just visit this link: https://openedx-webhooks.herokuapp.com/github/process_pr?repo=edx%2Fconfiguration&number=2774

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @agaylard! I've created [OSPR-1147](https://openedx.atlassian.net/browse/OSPR-1147) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

If you like, you can add yourself to the [AUTHORS](https://github.com/edx/configuration/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by omarkhan** [comment]
@agaylard might be worth checking why the travis test failed. It's probably just a flaky test but worth investigating nonetheless.

Apart from that, :+1: (please squash the commits for upstream review)

**Comment by agaylard** [comment]
@omarkhan , this is the error from Travis:

Gem::RemoteFetcher::FetchError: Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/gems/listen-0.5.0.gem)

An error occurred while installing listen (0.5.0), and Bundler cannot continue.
Make sure that `gem install listen -v '0.5.0'` succeeds before bundling.
FATAL: all hosts have already failed -- aborting

So I think we can discount this.

**Comment by omarkhan** [comment]
Yes, sounds good.

**Comment by agaylard** [comment]
Squashed commits.

**Comment by jibsheet** [comment]
@agaylard Can you rebase to resolve the conflicts?  But generally looks fine.  We will need to sanity check against what ansible-provision passes in.

**Comment by jbzdak** [comment]
@jibsheet I'm OpenCraft member reassigned to this task. I have rebased this PR on top of master branch, the TravisCi build fails, but it seems all PR's suffer from this problem right now.

**Comment by jibsheet** [comment]
@jbzdak Thanks for rebasing - the failed nodeenv creation in travis is known, trying to get the responsible devs to supply a fix.  I will try to look at this today, need to check on how we're doing our sandbox oauth setups before thumbing.

**Comment by jibsheet** [comment]
:+1: 
@edx/devops second thumb?
Also - there's a PR up now to fix the travis errors

**Comment by jbzdak** [comment]
@jibsheet Thanks for the review. I'll wait for before mentioned PR to merge (it's this one: https://github.com/edx/configuration/pull/2826 , right?) and then rebase once again to get a green build.

**Comment by jibsheet** [comment]
@jbzdak Yep, that's the one

**Comment by feanil** [comment]
:+1:

**Comment by jbzdak** [comment]
@feanil @jibsheet Thanks for the review once again. Since I got two thumbs up, I'm merging this now.

**Pull request merged**
