### PR TITLE
Starting supervisor+nginx when running Docker

### PR DESCRIPTION
**Pull request by clintonb**
In addition to validating our nginx configurations, using nginx ensures we can serve static files locally as we would in production.

### CODE REVIEW

**Comment by clintonb** [comment]
FYI @edx/devops @edx/ecommerce @cpennington

**Comment by rlucioni** [comment]
👍

**Comment by schenedx** [comment]
👍

**Comment by cpennington** [comment]
@zubair-arbi did something similar, but at the ansible task level, by using `manage:start` (see https://github.com/edx/configuration/blob/master/playbooks/roles/credentials/templates/edx/app/credentials/devstack.sh.j2#L15)

**Comment by clintonb** [comment]
Great! Update to use `manage:start` tag.

**Comment by clintonb** [comment]
This results in an error at startup; however, the system still behaves as expected. I'd prefer to eliminate the error before merging this to avoid confusing other developers, including future me. Thoughts, @cpennington or @edx/devops?

```
course-discovery    | PLAY [Deploy Discovery] ******************************************************* 
course-discovery    | 
course-discovery    | GATHERING FACTS *************************************************************** 
course-discovery    | ok: [127.0.0.1]
course-discovery    | 
course-discovery    | TASK: [nginx | make sure nginx has started] *********************************** 
course-discovery    | changed: [127.0.0.1]
course-discovery    | 
course-discovery    | TASK: [supervisor | wait for web port to be available] ************************ 
course-discovery    | fatal: [127.0.0.1] => error while evaluating conditional: start_supervisor.changed
course-discovery    | 
course-discovery    | FATAL: all hosts have already failed -- aborting
course-discovery    | 
course-discovery    | PLAY RECAP ******************************************************************** 
course-discovery    |            to retry, use: --limit @/root/discovery.retry
course-discovery    | 
course-discovery    | 127.0.0.1                  : ok=2    changed=1    unreachable=1    failed=0
```

**Comment by cpennington** [comment]
@clintonb: hrm... Not sure what that error is.

**Comment by clintonb** [comment]
For reference, here is the Ansible being executed: https://github.com/edx/configuration/blob/master/playbooks/roles/supervisor/tasks/main.yml#L211-L241.

**Comment by jibsheet** [comment]
@clintonb Can you get it to run with -vv or something, because that's a bizarre error to me

**Comment by cpennington** [comment]
FYI: https://github.com/ansible/ansible/issues/5356

**Comment by clintonb** [comment]
@jibsheet here is the result of a run with `-vvvv`:

```
root@f921971cbd78:/edx/app/edx_ansible/edx_ansible/docker/plays# sudo ansible-playbook -vvvv discovery.yml -c local -i '127.0.0.1,' -t 'install:app-requirements,assets:gather,devstack,migrate,manage:start' --extra-vars="migrate_db=yes" --extra-vars="@/ansible_overrides.yml"

PLAY [Deploy Discovery] ******************************************************* 

GATHERING FACTS *************************************************************** 
<127.0.0.1> REMOTE_MODULE setup
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1462546823.56-235316217348300 && echo $HOME/.ansible/tmp/ansible-tmp-1462546823.56-235316217348300']
<127.0.0.1> PUT /tmp/tmpqWliqn TO /root/.ansible/tmp/ansible-tmp-1462546823.56-235316217348300/setup
<127.0.0.1> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=mcgaytboxjnpxwdnnzjqpzvgnmlqelxq] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-mcgaytboxjnpxwdnnzjqpzvgnmlqelxq; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1462546823.56-235316217348300/setup; rm -rf /root/.ansible/tmp/ansible-tmp-1462546823.56-235316217348300/ >/dev/null 2>&1'"'"''
ok: [127.0.0.1]

TASK: [nginx | make sure nginx has started] *********************************** 
<127.0.0.1> REMOTE_MODULE service name=nginx state=started
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1462546825.7-138073671599522 && echo $HOME/.ansible/tmp/ansible-tmp-1462546825.7-138073671599522']
<127.0.0.1> PUT /tmp/tmpbMA9zF TO /root/.ansible/tmp/ansible-tmp-1462546825.7-138073671599522/service
<127.0.0.1> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=wznmjrdpiytzqxzhfaznplvopujddojs] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-wznmjrdpiytzqxzhfaznplvopujddojs; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1462546825.7-138073671599522/service; rm -rf /root/.ansible/tmp/ansible-tmp-1462546825.7-138073671599522/ >/dev/null 2>&1'"'"''
ok: [127.0.0.1] => {"changed": false, "name": "nginx", "state": "started"}

TASK: [supervisor | wait for web port to be available] ************************ 
fatal: [127.0.0.1] => error while evaluating conditional: start_supervisor.changed

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/discovery.retry

127.0.0.1                  : ok=2    changed=0    unreachable=1    failed=0  
```

**Comment by jibsheet** [comment]
@clintonb got it
- name: start supervisor
  isn't running because it's tagged
- manager:start

I think if you remove that r, then the start_supervisor will be registered and the task won't fail

**Comment by clintonb** [comment]
@jibsheet Nice catch. Thanks!

**Comment by clintonb** [comment]
@jibsheet new failure:

```
course-discovery    | 
course-discovery    | PLAY [Deploy Discovery] ******************************************************* 
course-discovery    | 
course-discovery    | GATHERING FACTS *************************************************************** 
course-discovery    | ok: [127.0.0.1]
course-discovery    | 
course-discovery    | TASK: [nginx | make sure nginx has started] *********************************** 
course-discovery    | changed: [127.0.0.1]
course-discovery    | 
course-discovery    | TASK: [supervisor | start supervisor] ***************************************** 
course-discovery    | ok: [127.0.0.1]
course-discovery    | 
course-discovery    | TASK: [supervisor | wait for web port to be available] ************************ 
course-discovery    | skipping: [127.0.0.1]
course-discovery    | 
course-discovery    | TASK: [supervisor | update supervisor configuration] ************************** 
course-discovery    | failed: [127.0.0.1] => {"changed": true, "cmd": "/edx/app/supervisor/venvs/supervisor/bin/supervisorctl -c /edx/app/supervisor/supervisord.conf update", "delta": "0:00:00.272902", "end": "2016-05-06 15:23:38.407462", "rc": 2, "start": "2016-05-06 15:23:38.134560", "stdout_lines": ["error: <class 'socket.error'>, [Errno 2] No such file or directory: file: /usr/lib/python2.7/socket.py line: 224"], "warnings": []}
course-discovery    | stdout: error: <class 'socket.error'>, [Errno 2] No such file or directory: file: /usr/lib/python2.7/socket.py line: 224
course-discovery    | 
course-discovery    | FATAL: all hosts have already failed -- aborting
course-discovery    | 
course-discovery    | PLAY RECAP ******************************************************************** 
course-discovery    |            to retry, use: --limit @/root/discovery.retry
course-discovery    | 
course-discovery    | 127.0.0.1                  : ok=3    changed=1    unreachable=0    failed=1   
course-discovery    | 
course-discovery    | [2016-05-06 15:23:38 +0000] [120] [INFO] Starting gunicorn 19.4.5
course-discovery    | [2016-05-06 15:23:38 +0000] [120] [INFO] Listening at: http://0.0.0.0:8381 (120)
course-discovery    | [2016-05-06 15:23:38 +0000] [120] [INFO] Using worker: sync
course-discovery    | [2016-05-06 15:23:38 +0000] [123] [INFO] Booting worker with pid: 123
course-discovery    | [2016-05-06 15:23:38 +0000] [124] [INFO] Booting worker with pid: 124
```

**Comment by jibsheet** [comment]
@clintonb bah.  I assume something else is missing a tag, but can't look right now.  Will try to come back this afternoon.

**Comment by clintonb** [comment]
[This SO post](http://stackoverflow.com/questions/18859063/supervisor-socket-error-issue) lead me to attempt to start `supervisord`. I added call in devstack.sh, just before the Ansible call to no avail:

```
/edx/app/supervisor/venvs/supervisor/bin/supervisord --configuration /edx/app/supervisor/supervisord.conf
```

```
course-discovery    | 
course-discovery    | PLAY [Deploy Discovery] ******************************************************* 
course-discovery    | 
course-discovery    | GATHERING FACTS *************************************************************** 
course-discovery    | ok: [127.0.0.1]
course-discovery    | 
course-discovery    | TASK: [nginx | make sure nginx has started] *********************************** 
course-discovery    | changed: [127.0.0.1]
course-discovery    | 
course-discovery    | TASK: [supervisor | start supervisor] ***************************************** 
course-discovery    | ok: [127.0.0.1]
course-discovery    | 
course-discovery    | TASK: [supervisor | wait for web port to be available] ************************ 
course-discovery    | skipping: [127.0.0.1]
course-discovery    | 
course-discovery    | TASK: [supervisor | update supervisor configuration] ************************** 
course-discovery    | ok: [127.0.0.1]
course-discovery    | 
course-discovery    | TASK: [discovery | install application requirements] ************************** 
course-discovery    | changed: [127.0.0.1]
course-discovery    | 
course-discovery    | TASK: [discovery | install development requirements] ************************** 
course-discovery    | changed: [127.0.0.1]
course-discovery    | 
course-discovery    | TASK: [discovery | migrate database] ****************************************** 
course-discovery    | changed: [127.0.0.1]
course-discovery    | 
course-discovery    | TASK: [discovery | write devstack script] ************************************* 
course-discovery    | changed: [127.0.0.1]
course-discovery    | 
course-discovery    | TASK: [discovery | update supervisor configuration] *************************** 
course-discovery    | changed: [127.0.0.1]
course-discovery    | 
course-discovery    | TASK: [discovery | create symlinks from the venv bin dir] ********************* 
course-discovery    | ok: [127.0.0.1] => (item=python)
course-discovery    | ok: [127.0.0.1] => (item=pip)
course-discovery    | ok: [127.0.0.1] => (item=django-admin.py)
course-discovery    | 
course-discovery    | TASK: [discovery | create symlinks from the repo dir] ************************* 
course-discovery    | ok: [127.0.0.1] => (item=manage.py)
course-discovery    | 
course-discovery    | TASK: [discovery | run collectstatic] ***************************************** 
course-discovery    | changed: [127.0.0.1]
course-discovery    | 
course-discovery    | TASK: [discovery | restart the application] *********************************** 
course-discovery    | ok: [127.0.0.1]
course-discovery    | 
course-discovery    | PLAY RECAP ******************************************************************** 
course-discovery    | 127.0.0.1                  : ok=13   changed=7    unreachable=0    failed=0   
course-discovery    | 
course-discovery    | [2016-05-06 21:24:00 +0000] [291] [INFO] Starting gunicorn 19.4.5
course-discovery    | [2016-05-06 21:24:00 +0000] [291] [ERROR] Connection in use: ('0.0.0.0', 8381)
course-discovery    | [2016-05-06 21:24:00 +0000] [291] [ERROR] Retrying in 1 second.
course-discovery    | [2016-05-06 21:24:01 +0000] [291] [ERROR] Connection in use: ('0.0.0.0', 8381)
course-discovery    | [2016-05-06 21:24:01 +0000] [291] [ERROR] Retrying in 1 second.
course-discovery    | [2016-05-06 21:24:02 +0000] [291] [ERROR] Connection in use: ('0.0.0.0', 8381)
course-discovery    | [2016-05-06 21:24:02 +0000] [291] [ERROR] Retrying in 1 second.
course-discovery    | [2016-05-06 21:24:03 +0000] [291] [ERROR] Connection in use: ('0.0.0.0', 8381)
course-discovery    | [2016-05-06 21:24:03 +0000] [291] [ERROR] Retrying in 1 second.
course-discovery    | [2016-05-06 21:24:04 +0000] [291] [ERROR] Connection in use: ('0.0.0.0', 8381)
course-discovery    | [2016-05-06 21:24:04 +0000] [291] [ERROR] Retrying in 1 second.
course-discovery    | [2016-05-06 21:24:05 +0000] [291] [ERROR] Can't connect to ('0.0.0.0', 8381)
course-discovery exited with code 1
```

**Comment by clintonb** [comment]
I dug into this further. The port reuse error was due to the fact that `supervisor` started `gunicorn`, leading to a port conflict with the second call to `gunicorn` from devstack.sh. Getting rid of supervisor, which isn't really necessary for docker is a bit more difficult than tailing the logs to ensure Docker doesn't close the container.

**Comment by clintonb** [comment]
@jibsheet please review.

**Comment by jibsheet** [comment]
@clintonb As mentioned in person, the ansible parts look fine, but I'm not familiar enough with devstack.sh in the docker context to review that part.

**Comment by clintonb** [comment]
@cpennington please review the docker changes.

**Pull request merged**
