### PR TITLE
Move credentials and discovery to edxlocal for database setup

### PR DESCRIPTION
**Pull request by cpennington**
N.B. This may break docker-based devstacks. Fix TBD.

@maxrothman, @jimabramson, @zubair-arbi: I think this will fix the current credentials issues.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
## PR Cover Letter
- [ ] A detailed description of the changes in the body of the PR
- [ ] If available, a link to the relevant JIRA ticket in the body of the PR
  - `[PROJ-XXXX](https://openedx.atlassian.net/browse/PROJ-XXXX)`

## Sandbox
- [ ] Build a sandbox for your branch and add a link here

## Testing
- [ ] i18n
- [ ] RTL
- [ ] Unit, integration, acceptance tests as appropriate
- [ ] Analytics
- [ ] Performance
- [ ] Database migrations are backwards-compatible

## Reviewers

If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [ ] Code review #1
- [ ] Code review #2
- [ ] Docs review (required for UI strings/error messages)
- [ ] UX review
- [ ] Accessibility review
- [ ] Product review

## Documentation considerations
- [ ] Are there user visible changes? If so, list who is affected, and include a pointer to the relevant code.
- [ ] Should this be mentioned in the release notes? If so, make sure that you included a description.

## DevOps assistance

If it's needed, or even if you suspect it might be needed, do any/all these things as early as possible. Don't surprise devops right before merging! For example, touching envs/aws.py or or envs/common.py are dead giveaways that you'll need assistance when pushing your changes out. Things that require devops attention include, but are not limited to:
- configuration changes
- feature flags
- migrations
  Ways to get devops attention, pick-and-choose whichever is most appropriate for your specific PR:
- [ ] Tag devops on your PR (`@edx/devops`), either for review (more specific to devops = better) or just a general FYI
- [ ] File a support ticket

FYI: Tag anyone who might be interested in this PR here.

## Post-review
- [ ] Squash commits

**Comment by maxrothman** [comment]
This should also remove `CREDENTIALS_MYSQL_MATCHER`, `CREDENTIALS_DB_ADMIN_PASSWORD`, `CREDENTIALS_DB_ADMIN_USER`, and any similar vars from `credentials/defaults/main.yml` (and maybe discovery too?)

**Comment by cpennington** [comment]
We're likely to need them for making docker work, but I can remove them as well, to keep the changes in a single commit.

**Comment by maxrothman** [comment]
:+1:

**Comment by maxrothman** [comment]
@zubair-arbi you should rebase your branch on top of this one. (alternatively @jimabramson)

**Comment by cpennington** [comment]
@maxrothman or we can merge it to master, or to @zubair-arbi's branch.

**Comment by cpennington** [comment]
I'm going to squash this

**Comment by jimabramson** [comment]
@cpennington thanks for this.  :+1:   @maxrothman would it make sense to merge this to master and then rebase #2781 ?

**Comment by maxrothman** [comment]
@jimabramson you can rebase on this branch, and when it eventually makes it to master it'll effectively be the same thing.

**Comment by jimabramson** [comment]
@maxrothman ok.

**Comment by jimabramson** [comment]
these commits got merged directly into #2781

**Pull request closed without merging**
