### PR TITLE
Fix zombie workers

### PR DESCRIPTION
**Pull request by jdmulloy**
Having this set to 5 days is causing us a lot of pain with workers not shutting down. Looking at the history it was put in place to prevent grading tasks from getting killed. I suspect the issue might not exist any more.

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR if it is code shared across multiple services and you don't own all of the services.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] If you are making a complicated change, have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?  Adding a new variable does not require the full list (although testing on a sandbox is a great idea to ensure it links with your downstream code changes).
  - [ ] Think about how this change will affect Open edX operators.  Have you updated the wiki page for the next Open edX release?

### CODE REVIEW

**Review by adzuci — APPROVED** [review]
:shipit: 1 hour sounds good, maybe we can make the Jenkins job not fail for an hour to sync these things up too?  cc @feanil 

Context: https://github.com/edx/configuration/pull/1410/files

**Comment by kdmccormick** [comment]
@jdmulloy what does this setting control? is it how long a task is allowed to run before getting killed?

If so, that's fine for Registrar, because none of its tasks should take longer than a minute.

I don't know about grading tasks, though; @iloveagent57 might know more.

**Comment by jdmulloy** [comment]
@kdmccormick This only comes into play when shutting down a server. When we shutdown supervisro sends the celery worker process a sigterm and if it still hasn't shut down after ```stopwiatsecs``` it sends a sigkill. We should check how long your tasks run. edx-platform actually has some processes that can run for 19+ hours. I figured this setting was just copied when the registrar workers were created and it may not be the setting you want.

**Comment by kdmccormick** [comment]
@jdmulloy got it. yeah, Registrar tasks shouldn't last longer than a minute, and also they will not corrupt anything if they are killed (they are just aggregating the results of several individually-safe LMS API calls), so definitely feel free to lower Registrar's `stopwaitsec`.

It's just that I can't say anything about grading tasks, as they aren't related to Registrar.

**Review by fredsmith — CHANGES_REQUESTED** [review]
I think this will cause issues with long running grading tasks.  I think we've resolved the failure we were seeing in monitoring without having to do this.

**Comment by kdmccormick** [comment]
@fredsmith @jdmulloy is this safe to close?

**Comment by fredsmith** [comment]
Closing this as we're no longer being impacted by long running tasks

**Pull request closed without merging**
