### PR TITLE
Include common for jenkins_worker role.

### PR DESCRIPTION
**Pull request by benpatterson**
@hkim823 @jzoldak @clytwynec 

Running the jenkins_worker role via vagrant results in errors because the common_web_user is not set. This takes care of it.

### CODE REVIEW

**Comment by jzoldak** [comment]
:thumbsup: 

Did this break due to some other merge? And if so, how do we prevent this from happening in the future?

**Comment by hkim823** [comment]
:+1:

**Comment by benpatterson** [comment]
@jzoldak @hkim823 

This was missed because the jenkins_worker was never run as a role in & of itself, but always part of the jenkins_worker.yml play. So in part this is more about setting dependencies in the correct place (a role vs a play).

See updated commit.

This update will make the worker role something that can be run on vagrant, assuming the github oauth token is provided in a separate yml file.

**Comment by clytwynec** [comment]
:+1:

**Comment by jzoldak** [comment]
oh, good one @benpatterson I get what you're doing - setting it up to be able to be provisioned and tested in an automated way. I like it. :)

**Comment by benpatterson** [comment]
Bingo @jzoldak !

**Pull request merged**
