### PR TITLE
Expose CORS_ORIGIN_ALLOW_ALL for testing in sandboxes

### PR DESCRIPTION
**Pull request by wedaly**
Companion PR to https://github.com/edx/edx-platform/pull/7090.

### CODE REVIEW

**Comment by wedaly** [comment]
@feanil please review when you have a moment.

**Comment by feanil** [comment]
@wedaly is there a corresponding change in aws.py on edx-platform?  Or is this just exposing something that is already in aws.py.

**Comment by wedaly** [comment]
@feanil The corresponding change is in this PR: https://github.com/edx/edx-platform/pull/7090

**Comment by feanil** [comment]
:+1:

**Pull request merged**
