### PR TITLE
upgrade node version to 6.11.1

### PR DESCRIPTION
**Pull request by arizzitano**
Addresses a recently discovered [security vulnerability](https://github.com/edx/edx-platform/pull/15537). See also https://github.com/edx/edx-platform/pull/15537

Sandbox: https://ari-node-6-11.sandbox.edx.org/
Sandbox from scratch: https://ari-node-6-11-from-scratch.sandbox.edx.org/
Sandbox with manual update: https://manual-update-ari-node-6-11-take-2.sandbox.edx.org
Packer AMI build: https://build.testeng.edx.org/view/packer/job/build-packer-ami/6655/

Configuration Pull Request
---

Make sure that the following steps are done before merging:

  - [ ] A DevOps team member has approved the PR.
  - [ ] Are you adding any new default values that need to be overridden when this change goes live? If so:
    - [ ] Update the appropriate internal repo (be sure to update for all our environments)
    - [ ] If you are updating a secure value rather than an internal one, file a DEVOPS ticket with details.
    - [ ] Add an entry to the CHANGELOG.
  - [ ] Have you performed the proper testing specified on the [Ops Ansible Testing Checklist](https://openedx.atlassian.net/wiki/display/EdxOps/Ops+Ansible+Testing+Checklist)?

### CODE REVIEW

**Review by jibsheet — APPROVED** [review]

**Comment by jibsheet** [comment]
FYI @edx/learner and @edx/educator-dahlia this will roll up the version on your IDAs too for this security fix

**Review by clintonb — APPROVED** [review]

**Comment by andy-armstrong** [comment]
@nedbat do you think this warrants getting into Ginkgo?

**Comment by nedbat** [comment]
This sounds like it should be in Ginkgo.  I'll cherry-pick it once it's merged.

**Comment by nedbat** [comment]
Is there something I can do to help get this merged?

**Comment by clintonb** [comment]
I believe all that's needed is for @arizzitano to click the merge button.

**Comment by arizzitano** [comment]
Currently blocked on validating AMI creation -- will update here when resolved.

**Comment by jibsheet** [comment]
There is an issue in build-ami preventing full testing of this, but I've done manual testing as part of an AMI build and we're going to go ahead and merge this. https://openedx.atlassian.net/browse/OPS-2296

**Comment by nedbat** [comment]
This has been cherry-picked to Ginkgo.

**Pull request merged**
